### ISSUE TITLE
License

### ISSUE THREAD

**Issue by burningtree** [liberland/constitution#1]
Which license to choose for the Constitution?

I think it would be best to choose the least restrictive, so we can choose from these:
- **CC0 1.0** - https://creativecommons.org/publicdomain/zero/1.0/
- **MIT** / **BSD**

I recommend CC0 1.0 because has no requirements.

Good overview of available licenses is here: http://choosealicense.com/licenses/

**Comment by ohadcn** [comment]
From MIT license:
'The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.'
We are not dealing with software, but we do not want to force anyone copying the document to include the copyright in it.

**Comment by l29ah** [comment]
WTFPL: keeping it simple and stupid.

**Comment by Zephram-C** [comment]
Other Licenses would mean always including *License and copyright notice* in Constitution. Therefore I am for CC0 1.0 too.

**Comment by joshmh** [comment]
+1
