### ISSUE TITLE
Socialized Legal Services?

### ISSUE THREAD

**Issue by liberlandcitizen** [liberland/constitution#102]
"§III.14. In criminal proceedings, the defendant shall have the right to the following:
§III.14(5) to the assistance of legal counsel free of charge where appropriate;
§III.14(8) to be provided without expense with the services of an interpreter if he or she does not speak the language of proceedings."

Why have socialized legal services? Much like medical and retirement services, I believe the market, without regulation, will keep prices for legal services low. I believe charity will take care of the rest.

**Comment by Jean-LouisMesic** [comment]
This existed long before Marx. It's not exactly socialist.

I also find it necessary. There are many circumstances that arise after being detained that render you unable to compensate an advocate and/or interpreter. Additionally, if a defendant has no interpreter, than how is a jury to ascertain guilt? Are they to dismiss his case and release a potential murderer? Or convict him just to be safe?

**Comment by Jean-LouisMesic** [comment]
@liberlandcitizen Perhaps a compromise would be to incur a debt to the government after winning a case. This debt would have to be paid in full in some time frame. After losing a case, your debt can be paid through prison labor.

**Comment by KacperZajc** [comment]
it guarantees there will be no abuse of process because of language or lack of resources; it was accepted by the Founding Fathers as such

**Comment by liberlandcitizen** [comment]
Well "free" education "guarantees" that all children will be educated....but in many places they are not.  "Free" healthcare "guarantees" that all people will receive quality medical care...but is government care quality?

I would argue the quality of legal counsel would be lower if government run than what people would be able to find in a truly free, unregulated legal market.  

Do we believe in the market or not?  Is it right to force other uninvolved people to pay for something through theft (taxes), or is it not?  I would guess if the founding fathers were offered these arguments, they just might change their mind.

**Comment by KacperZajc** [comment]
I leave this issue open to discussion :)

**Comment by Jean-LouisMesic** [comment]
It is not controlling the entire market of legal representatives, unlike fully-socialized healthcare and education. When everyone is placed on the system, undoubtedly quality falls. But this is, or rather, should be different.

It should be done on the provision that payment could not be rendered at the time of need. This makes all those able to pay for legal counsel pay for legal counsel, lowering the state's control on that market. The current wording does not stipulate this, so perhaps this is something that should be discussed. Free legal counsel would only be provided in absolute need. Naturally, we will have to determine how absolute need is determined.

On the topic of healthcare, believe it or not, before we had "socialized" healthcare, we had a de facto system like this. If you were a hobo bleeding to death, you could receive treatment without question in an E.R. You would simply incur a debt and go on with your life. If you refused to pay, the hospital would eventually sue. And it worked like this for many years, making our health system the best in the world for a very long time. Dr. Ron Paul often references this time as a counterpoint to the need for fully-socialized healthcare.

Finally, I ask that you read Harper Lee's To Kill a Mockingbird, as contained within is a blatant example of the system I describe. Many in town are so poor that the town could not function without service-debt transactions. Atticus Finch even himself accepts bags of potatoes and other favors from one of his former clients as compensation for services rendered long ago. As long as both parties, the client and the advocate, or the patient and the doctor, agree to a method and period of compensation in the event of successful legal or medical process, I see no problem with this system. And if said legal process fails, and the client is convicted, than the state will compensate the lawyer using value produced by the convicted's labor in prison.

**Comment by jsenko** [comment]
If we simply omit the "without expense" part and leave the "to be provided with the services", than IMHO implies that the services must be provided in any case (even if the accused refuses to pay) but leaves the possibility of charging him/her for the services at any time after the trial.
One problem that I see are recursive trials where the next trial will be about paying for the services for the previous trial:)

**Comment by Jean-LouisMesic** [comment]
@jsenko That makes it possible for an advocate to post-facto charge a client, where no consent or plan to pay was made before service. It's better to require that a consensus be reached on compensation method and period before any service is rendered, to protect clients from this form of fraud. You can still require that services be rendered, but an agreement must be reached by both parties. If the client refuses to reach an agreement, then they could be held in contempt or court.

The recursive trials problem isn't really a recursive trial, just a trial, service, then subsequent civil case in the event of refusal of payment.

**Comment by liberlandcitizen** [comment]
@Jean-LouisMesic - you don't have to control an entire market to mess it up.  In the US, the government pays for the healthcare of 1/3 of the population and the system garbage because of it.

**Comment by jsenko** [comment]
@Jean-LouisMesic you may need a service of an interpreter in the civil case of the refusal of the payment:)

**Comment by Jean-LouisMesic** [comment]
That is not a part of criminal proceedings, so the interpreter would not be provided by the government anyway. 

Jusden K. Messick 
Washington College 
Class of 2018 
Chemistry Major 


----- Original Message -----

**Comment by Jean-LouisMesic** [comment]
That is not a part of criminal proceedings, and thus the government would not be in a position to provide an interpreter.

**Comment by Jean-LouisMesic** [comment]
@jsenko Honestly, I'm waiting for someone else to chime in on my side. I'm the first to admit that I am not good at extended debates.

**Comment by terrorist96** [comment]
My state offers free legal representation (for crimes which the punishment includes the possibility of prison time) to those who can't afford it. However, if you are found guilty, you are required to pay for your representation after the fact. The theory being that an innocent person who can't afford an attorney shouldn't have their liberty stripped from them (by denying them representation, thus tipping the scales of justice against them) because of their economic status.

**Comment by KacperZajc** [comment]
I think for now, I would like to leave the free services. It says 'where appropriate' so there might be further rules on paying back etc.
