### ISSUE TITLE
II.13 - 'All Parties Involved' Includes Whom?

### ISSUE THREAD

**Issue by liberlandcitizen** [liberland/constitution#103]
"§II.13. No law shall regulate the rules concerning uploading and/or transmitting any materials through the Internet and/or any other medium of exchange, where all parties of age involved consent; nor shall it regulate the rules concerning displaying and/or accessing such material."

What constitutes involvement?  Does one need the author’s consent to link to an article? To paste parts of an article somewhere? To use an image that they did not create? To broadcast a film they did not create?

What about a newspaper?  Does it need to ask permission to publish a photo of somebody?  A celebrity?  A politician?  

In my opinion the transmission of anything via the internet or other exchanges should be allowed, consent or not.  If we need to put in protections for child porn, let's find another way of doing it that doesn't limit possibly everything else.

**Comment by Jean-LouisMesic** [comment]
All that needs to be done here is to revise that small part. Let's think about what is intended:

*The uploader and all parties of age involved in the production of the material to be uploaded/transmitted are aware and consenting to the upload/transmission.
*The uploader and all parties of age involved in the production of the material to be uploaded/transmitted are aware and consenting to any and all uses of the uploaded/transmitted material.

Needs to be worded better.

"In my opinion the transmission of anything via the internet or other exchanges should be allowed, consent or not. If we need to put in protections for child porn, let's find another way of doing it that doesn't limit possibly everything else."

Careful with that. Am I allowed to scan personal letters of someone else to the internet under that definition?

**Comment by liberlandcitizen** [comment]
I urge zero regulation of the internet in Liberland, protected in the bill of rights.  If somebody steals letters from your home, it's already theft and they can be prosecuted.  

Transmitting zeros and ones should never be a crime though, no matter what the material may be.

**Comment by Jean-LouisMesic** [comment]
What if my neighbor acquire those letters through a consensual association, like I wanted their counsel on something contained within? Do they then have the right to make thousands of Xerox copies and ship them around the globe through snail mail? That could be defamation. The same goes for the Internet. At the very least, it should be possible for the defamed to take a civil case up with the defamer for broadcasting those emails, or any other data acquired similarly.

It does not seem right to leave the door wide open. The door has never been wide open, even before the internet existed, and for good reason.

I understand your concerns that this could lead to abuse of internet regulation, but, if worded correctly, it will not allow for regulation of any kind. It would entail the non-consenting party to sue the party which wrongfully spread the information. It should be determined on a case-by-case basis, rather than with the government bottlenecking emails, making sure that every email was sent with express consent by all involved parties.

**Comment by liberlandcitizen** [comment]
Defamation?  That's a slippery slope.  Maybe people should be careful about who they associate with and give their personal letters to?  Perhaps have somebody sign a contract to keep the letters private?  

Wikileaks didn't have consent from the US government when it leaked classified info.  Illegal in Liberland?

**Comment by KacperZajc** [comment]
we could just change from 'all parties involved' to 'sending and receiving parties'

**Comment by liberlandcitizen** [comment]
That could lead to things like online ads becoming illegal.  I truly favor free transmission of all material.  

We would do well to only have:  "§II.13. No law shall regulate the rules concerning uploading and/or transmitting any materials through the Internet and/or any other medium of exchange; nor shall it regulate the rules concerning displaying and/or accessing such material."

**Comment by KacperZajc** [comment]
I already considered it.
It would allow paedophilia.
We cant.

**Comment by liberlandcitizen** [comment]
Raping/molesting/taking photos of children will be illegal because they cannot consent.  If people are doing that, they can and should be prosecuted.  However I wouldn't regulate the internet simply because people may transmit photos/videos of their crimes.  Why not just prosecute the actual crime itself and leave the internet out of it?

**Comment by KacperZajc** [comment]
this is designed to prevent the government from regulating the Internet; we just want to make one small exception

**Comment by liberlandcitizen** [comment]
As much as I hate child pornography - I believe it is better dealt with offline.  Still, since I probably won't win that argument.....may I make this suggestion....

Make child pornography/molestation/rape a very clear and well defined illegal act elsewhere in the constitution.  And then refer to that part of the constitution here in this section about the internet....and note that the child rape/porn stuff S.XX still applies.  "nothing in this article shall be construed" etc.  Does that work?  

Sorry but I fear the heavy hand of government in the name of "saving the children"  If we aren't careful, websites will have to be registered, content will be monitored by the government, websites will be shut down etc.  We must have one place on earth with a truly free internet.  

So again I would suggest being extremely clear about the protections of minors somewhere else, and refer back to it here and otherwise leave the internet alone :)

**Comment by Jean-LouisMesic** [comment]
I've suggested adding a separate "Persons Not Of Age" Bill of Rights elsewhere, and I still find it to be relevant. This could be included in there somewhere.

**Comment by jsenko** [comment]
Doesn't the "No law shall regulate" without the consent part prevent laws concerning "secrecy of correspondence" for example? In that case hacking would be completely legal and you won't be able to pass a law preventing it. A possible solution may be to explicitly state  a distinction between transmitting the information and acting on it. There can also be an exception for transmitting unlawfuly obtained information.

**Comment by Jean-LouisMesic** [comment]
@jsenko The sending party did not consent to the receipt of the letter by anyone other than to whom they sent it, thus this does not block secrecy of correspondence regulation, nor hacking.

**Comment by liberlandcitizen** [comment]
Hacking will be legal?  I don't know if that's true but people ought to secure their own data and protect themselves from being hacked in the first place.  

Please - let's not regulate the internet, and kill off things like wikileaks in the name of protecting the people who....poor them....aren't "smart enough" to figure out how to protect their servers/computers/data.

**Comment by saintego** [comment]
I prefer also free Internet. Hacking should be covered by violating private property and paedophilia by some definition of rights of kids

**Comment by KacperZajc** [comment]
see #111 for further debate on the subject

**Comment by KacperZajc** [comment]
see #118
