### ISSUE TITLE
List of immediate changes

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#106]
Points I want to introduce at the moment unless there is a strong objection:

1.	Remove any qualification as to whom the Bill of Rights apply and add that it applies to everyone unless stated otherwise.
2.	Require unanimity for the declaration of constitutionality by the Supreme Court.
3.	Change 'Public Authority' to 'Public Administration' and '3 functions' to '3 powers' in the Political Institutions preamble (just a mistake).
4.	Remove the word ‘indenture’ from II.4 because as someone pointed out there were forms of voluntary indenture and the involuntary ones are already covered by the article.
5.	Add a possibility to issue a warrant where there is a risk the accused will flee or interfere with the investigation (not only pose a threat to others) in III.4.
6.	Add a ban on being a judge and an Assembly Representative at the same time.
7.	Qualify the term for the Chief Public Prosecutor is 6 years.
8.	Clarify that all public areas shall constitute free speech zones and that no permits will be needed in order to protest in II.9.
9.	 Add a ‘persons of age’ qualification to II.3 (ban on victimless crimes).
10.	Clarify that agents of the Public Administration can be required to be adequately educated and qualified (in II.12).
11.	Clarify that ban on regulation of marriage does not preclude the Assembly from regulating inheritance rules where there is no will.
12.	Add ‘consensual’ to II.6 
13.	Clarify that the right to issue anything as commodity does not apply to ‘things’ which are illegal (e.g.: add "unless either party of transaction is legally prohibited to possess such item or commodity" to II.10).
14.	Add protection ‘of others’ to the right of self-defence and defence (in addition to the right to defend ‘the close ones’) as well as add 'in direct threat' in II.11.
16.   Raise the threshold for constitutional amendment to 3/4 in a (mandatory) referendum.
17.	Change ‘where all parties of age involved consent’ to ‘where the sending and receiving parties of age consent’ in II.13
18.	Add ‘unless such order would render a person stateless’ in III.10
19.	Restate the right to bear arms.
20.   Introduce ban on requiring identification.
21.   Qualify the 1 year period for prosecution.

Proposed wording:

(7) The Chef Public Prosecutor is appointed by the Chancellor for the term of six years.

(19) "No person of age shall be deprived of the right to own, manufacture, sell, transport, and bear any small arms, be they now historic, contemporary and/or experimental and regardless of their condition, unless decided otherwise by a decision of the court where law allows it as punishment for crime, or on medical grounds where a person would constitute a threat to others; licensing shall not be used to infringe upon this right, nor restrictions as to the purchase and/or use of ammunition and/or the firearms accessories.”

(20) “No law shall allow any body of any branch of the Public Administration to assign a number to any citizen, nor shall he or she be required to procure, carry, or otherwise maintain identification materials of any form without his or her consent unless upon the conviction in a court of law and for the duration of the sentence only; no person shall be compelled to identify themselves to any agent of the Public Administration, otherwise than upon arrest with probable cause or pursuant to a warrant issued by a judge of the Criminal Court; all data collected by any body of any branch of the Public Administration shall be used only for the direct and necessary purposes for which it was originally collected, and shall be kept confidential and shared only with the consent of the rightful owner or pursuant to a court order or otherwise in accordance with the provisions of this Constitution.”

(21) "No person shall be tried for any criminal offence any later than a year since the warrant for custody of said person was executed and the person was taken into custody; the deadline shall be renewed for any and all subsequent warrants for custody in the event of escape and/or subsequent offence.”

Points I want us to debate on:

1.	Abolishing the free of charge service of an interpreter and legal counselling in III.14.
2.	Oblige the Cabinet to consider a bill proposal put forward by 5 Assembly Representatives (no obligation to actually submit such a bill) .
3.	Make the Justices of the Supreme Court who are to replace the ones removed in a referendum directly elected.

**Comment by Jean-LouisMesic** [comment]
Yea to 1., 2., 3., 4., 5., 7., 10., 12., 13., 14., 15., and 17.

No opposition to 6. and 8.

Still questioning but unable to debate 9., and 11.

(16) this precludes the consent of any parties referenced in or involved in gathering/manufacturing said data. Including non-consenting persons of age pictured therein. This doesn't fully cover your special case; peeping tom's with toilet cameras and their consumers could get away with trafficking candid non-consensual adult pornography under this definition. I'm beginning to err on the side of @liberlandcitizen on this, perhaps these special cases should be outlined in a separate, supercedeing section (i.e. SII.13(1) The provisions outlined in SII.13 does not extend to the trafficking of pornography depicting persons not consenting or unable to consent to the manufacturing and/or transaction involved.)

**Comment by terrorist96** [comment]
(19) "No person of age shall be deprived of the right to own, manufacture, sell, transport, and bear any small arms, be they now historic, contemporary and/or experimental and regardless of their condition, unless decided otherwise by a decision of the court where law allows it as punishment for crime, or on medical grounds where a person would constitute a threat to others; licensing shall not be used to infringe upon this right, nor restrictions as to the purchase and/or use of ammunition and/or the **accessories to arms**.”

We're talking about arms in general, not just firearms. 

I'm in favor of keeping the free interpreter/lawyer; fair justice is more important.

**Comment by KacperZajc** [comment]
@Jean-LouisMesic you're right about 16, I'll leave it for now and think it over
