### ISSUE TITLE
Convicted criminals' liberty

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#109]
This was in the first draft:

§26. Convicted criminals shall not have their liberty restricted except so far as is necessary for the protection of others, nor their property seized except so far as it is necessary to make restitution to the victim and/or to pay the costs of the criminal's capture and trial.

Why was it removed in version 2.0?

**Comment by terrorist96** [comment]
Also, these sections were removed too:

§6. No law shall abridge the right of each person to do as he or she chooses with his or her own person and property, so long as he or she does not interfere, by force or fraud, or the threat thereof, with the equal right of others to do as they choose with their own persons and property.
§15. No law shall restrict or hamper the free and peaceful movement of persons, goods, or capital within or across the borders of the Free Republic of Liberland.
§19. No law shall regulate the use of any chemical substance so long as the use is not designed to intentionally harm any person without his or her consent.

Why?

**Comment by KacperZajc** [comment]
6 is restated
15 and 19 were removed because of PR issues as requested by the President

**Comment by terrorist96** [comment]
26 was removed because of PR too?

**Comment by Jean-LouisMesic** [comment]
26 is removed because they wanted to leave the ability to take away gun rights from convicted felons.

**Comment by terrorist96** [comment]
"except so far as is necessary for the protection of others"

I feel like that allows for the option to disarm violent felons.

**Comment by Jean-LouisMesic** [comment]
I don't know. You can look for the pull request that deleted this provision. I'll check myself later.

**Comment by terrorist96** [comment]
I couldn't find a reference to it when doing a search.

**Comment by Jean-LouisMesic** [comment]
Perhaps it was removed before the github upload.
