### ISSUE TITLE
Pardoning

### ISSUE THREAD

**Issue by Jean-LouisMesic** [liberland/constitution#116]
Who has the power of issuing pardon?

**Comment by KacperZajc** [comment]
no one
this is always exercised for political reasons (e.g. Ford's pardon for Nixon)
it shouldnt exist in our Constitution

**Comment by terrorist96** [comment]
What if that power was exercised by the people, not a politician? The government imprisons criminals on behalf of the general population. If the majority of the population doesn't want someone to be in prison for whatever reason, they should be able to express that feeling through referendum.

**Comment by KacperZajc** [comment]
pardon by people is called jury nullification and we already embodied that

**Comment by terrorist96** [comment]
That's true

**Comment by KacperZajc** [comment]
:)

**Comment by Jean-LouisMesic** [comment]
Excellent. I just wanted to hear the rationale behind its exclusion. I agree.
