### ISSUE TITLE
Further changes to the 3.0 Draft

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#118]
To introduce:

1.   No law shall regulate any printed materials, radio, television, the Internet or any other medium of exchange of information; no rules shall regulate the rules concerning uploading, transmitting, displaying, accessing and/or publishing such information; nor shall any law introduce licensing and/or registration to infringe upon these rights; nothing in this provision shall prevent Assembly from regulating the rules concerning protection of sources used by journalists, accessing information without consent of the rightful owner and protection of persons under age.

2.   All Bills proposed by the Cabinet shall be made public prior to the Assembly's debate on them.

3.   No person shall be convicted of any criminal offence if the only evidence incriminating him or her is a testimony given by a member of the law enforcement which is not supported by any video and/or audio material.

4.   No member of the law enforcement shall be performing his or her duty undercover unless on a specific mission.

5.   One-fourth of all Assembly Representatives shall have the right to oblige the Cabinet to consider a draft of a Bill prepared by them; if such draft is rejected by the Cabinet as potential Bill, the Cabinet shall publicly give detailed reasons behind its decision; nothing in this provision shall oblige the Cabinet to submit to Assembly such a draft as a Bill.

5.   Any Justice of the Supreme Court who is recalled in a referendum shall be replaced by a person elected by the Citizens in a free election.

To debate:

1.   Gun free zones
2.   Militarisation of the police
3.   Monopolies

**Comment by Jean-LouisMesic** [comment]
(1) "protection of sources" could be construed to introduce copyright law in its most twisted interpretation.

(2) I like these both, but why are they in the same section?

(3) "No agent of the Public Administration shall operate undercover without a warrant issued by a court of the Free Republic of Liberland, and only provided that they are pursuing a specific legal and constitutional end. No agent of the Public Administration operating undercover shall pursue incriminating evidence through any method of entrapment, nor will any agent of the Public Administration of Liberland act outside of their specified mission unless to protect themselves or others in direct threat. All actions by any agent of the Public Administration operating undercover shall be scrutinized in any court proceedings which include any evidence collected from an agent operating undercover, unless said agent is still legally operating undercover in pursuit of a related warrant. Any warrant issued by any court of the Free Republic of Liberland shall expire after a determined period, and must be renewed to continue undercover operations.

(4) Any draft proposed by the Assembly to the Cabinet must be publicly announced, just like any proposal by the Cabinet to the Assembly.

(5) This really needs debate, but few seem to want to comment on it. I am of the opinion that it will not make court justicing a political position, but it is possible. Perhaps the people should elect a College of some sorts every election period that will go into effect whenever a judge is impeached to appoint a new judge to take their place.

(1) I do not believe that gun free zones should be enforced by the public administration. Property owners should reserve the right to prohibit weapons on their own property.
(2) If local police are heavily armed, there must be a way for citizens to legally obtain light weapons or other means of defense.
(3) Monopolies only grow in scale and longevity when intervened for or against. Any regulations only hurt potential competition that would alleviate the problem.

**Comment by terrorist96** [comment]
Gun free zones should be allowed as a matter of property rights. PA shall not be allowed to institute any gun free zones except in sensitive areas, which shall require armed guards/metal detectors at any and all entrances to said zone. (debatable) 
Police and citizens should have access to the same types of arms. 
I feel like there should be something stating that the state has the right to break up any monopolies in the interest of keeping a level playing field for the marketplace. 

No elections of judges. Judges can be removed via referendum but not elected. Judges should be appointed (by who? Idk) and their appointment should be approved of by the legislature (or popular vote) 
I'm fine with the rest, more or less.

**Comment by KacperZajc** [comment]
what if we add "the owner of the premises shall determine whether arms can be carried on such premises except for the members of the law enforcement where acting upon warrant" ??

Im processing the rest of the point.

**Comment by Jean-LouisMesic** [comment]
@terrorist96 Allowing the state to indiscriminately destroy monopolies allows it to destroy any firm that is not exactly like another in the same market via the mechanics of monopolistic competition. No.

@terrorist96 I agree on the issue of police vs. people armament.

@KacperZajc @terrorist96 I like Kacper's idea for gun ownership, but I still am hazy about gun-free public property. Police stations should not be gun-free zones, for instance. Military bases obviously are heavily guarded and wouldn't allow citizens in on a normal basis anyway, so they are de facto gun-free zones. Prisons should be gun free zones. Specifics should be outlined so the government can't claim a swathing strip of land for water utilities and call it a gun-free zone for the sake of making all gun owners have to go all the way around said pipeline to get to the other side. There must be a legitimate concern of security to warrant public use of this right. Probably should involve an official warrant issued by a court, as well.

**Comment by KacperZajc** [comment]
@Jean-LouisMesic could you elaborate on your point (3)?
does it have to be so detailed? 
please explain every part

**Comment by FellowTraveler** [comment]
"Gun free zone" == mass murder zone.

**Comment by FellowTraveler** [comment]
Regarding testimony by law enforcement -- what if the testimony is backed up by other evidence? For example, perhaps there is no audio or video evidence, but there is other evidence such as a fingerprint in blood, or the testimony of other witnesses, or a confession, etc. It seems there are many cases like this. I do like where this is going but I am concerned about the specifics.

**Comment by terrorist96** [comment]
> "Gun free zone" == mass murder zone.
This is true, unless it is guarded at all entrances, which is why I propose it be a requirement for all entities that implement a gun free zone (and that were anything to happen, that entity would bear the costs of forcing me to be disarmed) with the exception of private property of an individual.

**Comment by terrorist96** [comment]
> but there is other evidence such as a fingerprint in blood, or the testimony of other witnesses, or a confession, etc.

This is not precluded by the current wording. It only disallows one cop's word against yours - basically tie goes to the defendant. See:

>No person shall be convicted of any criminal offence if the only evidence incriminating him or her is a testimony given by a member of the law enforcement which is not supported by any video and/or audio material. Nothing in this section shall be construed as to preclude other forms of evidence such as a fingerprint in blood, or the testimony of other witnesses, or a confession, DNA, etc.

The wording could be worked on a bit.
As it stands now though, it could be construed as allowing two or more cops testifying against you. Could dirty police band together and try to strip you of your liberty? Definitely. You could theoretically have a whole corrupt department.

**Comment by Jean-LouisMesic** [comment]
(3) "No agent of the Public Administration shall operate undercover without a warrant issued by a court of the Free Republic of Liberland, and only provided that they are pursuing a specific legal and constitutional end."

*Undercover operations are unfair, and currently unconstitutional. This allows the court to issue warrants allowing undercover operations to attain specific ends, such as infiltrating bringing down large, violent gangs of kidnappers, rapists, or assassins.

"No agent of the Public Administration operating undercover shall pursue incriminating evidence through any method of entrapment, nor will any agent of the Public Administration of Liberland act outside of their specified mission unless to protect themselves or others in direct threat."

*No undercover agent should be allowed to walk up to someone on the street with a bag of hemp and ask them if they want to buy in. They need a warrant specifically against the person they pursue.
*Allows undercover agents to blow their cover in a shoot-out, in spite of the previous provision.

"All actions by any agent of the Public Administration operating undercover shall be scrutinized in any court proceedings which include any evidence collected from an agent operating undercover, unless said agent is still legally operating undercover in pursuit of a related warrant."

*Any complete undercover operation needs to be reviewed in court, to ensure lawfulness and constitutionality, and to ensure that no incriminating evidence against any defendants were admitted in court proceedings.

"Any warrant to operate undercover issued by any court of the Free Republic of Liberland shall expire after a determined period, and must be renewed to continue undercover operations."

*One cannot work indefinitely as an undercover agent in a biker gang for the sake of keeping tabs on the gang. Forces agents to actively pursue resolution of their warrant rather than biding time.

**Comment by Jean-LouisMesic** [comment]
"Gun free zone" == mass murder zone.
This is true, unless it is guarded at all entrances, which is why I propose it be a requirement for all entities that implement a gun free zone (and that were anything to happen, that entity would bear the costs of forcing me to be disarmed) with the exception of private property of an individual.

If a mandated gun-free area is guarded at all entrances, all those inside are more likely to be victims of the guards than they are of one-another. Gun-free areas must be restricted to absolute need, such as in military bases, prisons, courts, and police stations. These areas are already heavily guarded by their residents and maintainers. They also all pose minimal threat to slaughter large numbers of people within.

**Comment by Jean-LouisMesic** [comment]
"No person shall be PROSECUTED of any criminal offence if the only evidence incriminating him or her is testimony given by aNY NUMBER of memberS of the law enforcement THAT IS UNCORROBORATED BY ANY OTHER PRESENTED PHYSICAL EVIDENCE AND/OR WITNESS TESTIMONY."

It is up to the jury to determine conviction, so this provision must be enacted prior to prosecution.

**Comment by terrorist96** [comment]
> "No agent of the Public Administration operating undercover shall pursue incriminating evidence through any method of entrapment, nor will any agent of the Public Administration of Liberland act outside of their specified mission unless to protect themselves or others in direct threat."
---No undercover agent should be allowed to walk up to someone on the street with a bag of hemp and ask them if they want to buy in. They need a warrant specifically against the person they pursue.
---Allows undercover agents to blow their cover in a shoot-out, in spite of the previous provision.

Hemp isn't illegal. How would they blow their cover?

> "Any warrant to operate undercover issued by any court of the Free Republic of Liberland shall expire after a determined period, and must be renewed to continue undercover operations."

I would add that the maximum period of time should be set at 1 year. It would disallow warrants that don't expire for 5, 10 etc years.

> @terrorist96 If a mandated gun-free area is guarded at all entrances, all those inside are **more likely to be victims of the guards** than they are of one-another. Gun-free areas must be restricted to absolute need, such as in military bases, prisons, courts, and police stations. These areas are already heavily guarded by their residents and maintainers. They also all pose minimal threat to slaughter large numbers of people within.

This doesn't seem realistic to me.

> "No person shall be PROSECUTED of any criminal offence if the only evidence incriminating him or her is testimony given by aNY NUMBER of memberS of the law enforcement THAT IS UNCORROBORATED BY ANY OTHER PRESENTED PHYSICAL EVIDENCE AND/OR WITNESS TESTIMONY."
It is up to the jury to determine conviction, so this provision must be enacted prior to prosecution.

I agree, it should be changed to prosecuted.

**Comment by terrorist96** [comment]
No person shall be prosecuted of any criminal offence if the only evidence incriminating him or her is testimony given by law enforcement that is uncorroborated by any other presented physical and/or digital evidence and/or third party witness testimony.

Do you agree with this wording?

**Comment by KacperZajc** [comment]
I like this version :)

**Comment by KacperZajc** [comment]
as to the gun free zones - we will add:

"the owner of the premises shall determine whether arms can be carried on such premises except for the members of the law enforcement where acting upon warrant"

**Comment by Jean-LouisMesic** [comment]
@terrorist96 "Hemp isn't illegal." No, I didn't know this. /s. I was using a simple example. An undercover agent could conceivably walk up to a person offering services as an assassin to bait a response. Who knows if under normal circumstances a person would consider discussing such a thing? Is that a good enough example of entrapment to you?

"How would they blow their cover?" If an undercover agent happens to be around when some unrelated massacre starts, they should be authorized to act as a normal agent, acting on a literal probable cause to take control of the situation.

"[I would suggest 1 year]" Right, I wanted to debate the specific term.

"This doesn't seem realistic to me." I hate to pose a straw man argument, or to invoke Godwin's law, but concentration camps are a.) gun free zones and b.) guarded at all entrances. Is that not a real situation?

@terrorist96 Well-worded.

@KacperZajc I'm still leary about PA property. If we don't disallow the PA from say, claiming a tract of land to set up plumbing, they should not be able to claim that tract of land as a gun-free zone for the sake of making gun-owners travel on a certain route or risk arrest. Prisons, military bases, and police stations constitute legitimate security concerns wherein the restriction of the right to carry is warranted. The PA is not a normal land-owner, and inherently shares not the same rights and privileges, and rightfully not. There must be a legitimate security concern within the bounds of claimed PA property for the PA to claim it as a gun-free zone.

**Comment by terrorist96** [comment]
> @terrorist96 "Hemp isn't illegal." No, I didn't know this. /s. I was using a simple example. An undercover agent could conceivably walk up to a person offering services as an assassin to bait a response. Who knows if under normal circumstances a person would consider discussing such a thing? Is that a good enough example of entrapment to you?

Yes, better. :stuck_out_tongue_closed_eyes: I'm not in favor of entrapment.

> "How would they blow their cover?" If an undercover agent happens to be around when some unrelated massacre starts, they should be authorized to act as a normal agent, acting on a literal probable cause to take control of the situation.

I think the "unless to protect themselves or others in direct threat." clause covers that.

> "This doesn't seem realistic to me." I hate to pose a straw man argument, or to invoke Godwin's law, but concentration camps are a.) gun free zones and b.) guarded at all entrances. Is that not a real situation?

So you're in favor of diminishing the property rights of a person who doesn't want guns on their property?

**Comment by Jean-LouisMesic** [comment]
No, I'm in favor of diminishing the property rights of the PA to restrict gun-free zones.

I have already agreed with the right of any private owner to restrict guns on their premises. And I also don't think anyone who does that should be required to hire guards. People who enter those premises consent to the risks, if they feel unsafe, they'll find somewhere else that has guards.

**Comment by terrorist96** [comment]
What if an entire mall was a gun free zone? How would you want to address that?

**Comment by Jean-LouisMesic** [comment]
A.) People are stupid to go in unprotected if it's unguarded.
B.) People would value guards being posted in and around a mall, so they would be there anyway.
C.) No law currently forces malls to have guards, they just do.
D.) It's private property and up to the owner to decide.

**Comment by terrorist96** [comment]
The sentiment I wish to get across is that if a public property owner wishes to have a gun free zone, it has to actually be gun free. Not "only law abiding citizens disarmed but criminals still armed." This can only be accomplished by guards at all entrances. And the property owner would be liable for any harm caused to a person on their property due to the fact that they were required to be disarmed. I'd say compulsory liability insurance, but I think that'd violate a separate section of the Constitution. 
This would all act as a disincentive to desire an army free zone on your public property.

**Comment by Jean-LouisMesic** [comment]
I never said I was against guards either, we're both advocating different important points about PA gun-free zones.

My points:
*Needs to be a legitimate internal threat of security.
*Cannot be used for the sake of creating invisible barriers to gun owners.
*Cannot be used in such frequency that gun-free zones actually make gun zones more rare.

By my first point, it is a no-brainer that there will be guards anyway, though I also find it important that this be stipulated.

We're not disagreeing here. I thought you were talking about forcing private owners to hire guards, which is unconstitutional elsewhere.

**Comment by terrorist96** [comment]
My view is that owners of public property (ie a place where a pedestrian can go) should be required to secure their property if they want no arms (like if you're going to a club, there's a bouncer at the door that will stop you if you have a gun). 

Owners of private property (not open to the public other than invited guests) wouldn't be affected by this.

**Comment by Jean-LouisMesic** [comment]
Exactly.

We're not disagreeing. Again. Like I said. : P
