### ISSUE TITLE
§II.15. No law shall prohibit video and/or audio recording of any agent of the Public Administration in public space and whilst on duty.

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#119]
This needs to be modified. As it stands, it allows for prohibiting recording in public in general. Here's my suggestion:

§II.15. No law shall prohibit video and/or audio recording in a public space.

**Comment by terrorist96** [comment]
What about someone recording in a public restroom? There should be exceptions. Hmm..

**Comment by KacperZajc** [comment]
if we adopt your wording, the government will have video cameras on every corner

**Comment by Jean-LouisMesic** [comment]
@terrorist96 Use pull requests for these so we can easily see the original wording. I'll include it below for everyone else's convenience.

§II.15. No law shall prohibit video and/or audio recording of any agent of the Public Administration in public space and whilst on duty.

If it is public space, then agents of the PA are bound to be there. Thus, enacting a law prohibiting video and/or audio recording in public space violates this amendment.

"No law shall prohibit video and/or audio recording of any agent of the Public Administration in public space, nor of the general affairs of any public space, be they owned by the Public Administration or by any other person. No agent or agency of the Public Administration shall record video and/or audio outside of territory of public ownership unless in pursuit of a specific warrant granted by a criminal court of the Free Republic of Liberland. This provision shall not prohibit the use of agent monitoring devices, such as body cams, dash cams, or microphones, or any contemporary analogs, on any agent of the Public Administration patrolling or acting on probable cause or in pursuit of a warrant issued by any court of the Free Republic of Liberland in any publicly or privately owned public space."

Allows the PA to set up cameras on its own property for security purposes while also ensuring freedom from unwarranted surveillance in non-publicly owned public spaces. Also allows accountability devices to be used freely in public spaces.

**Comment by Jean-LouisMesic** [comment]
Need to revise to stipulate that any evidence obtained using footage from accountability devices is inadmissible in court unless it was obtained while the agent was actively pursuing a warrant relevant to the specific case to which the evidence is relevant.

**Comment by terrorist96** [comment]
"Nothing in this section shall be construed to allow recording of people when they have a reasonable expectation of privacy" (like a public restroom)

**Comment by KacperZajc** [comment]
isnt your idea a pass for general surveillance?
It will turn Liberland into the Orwellian state

**Comment by terrorist96** [comment]
How can we we reconcile the freedom of people to freely record in public vs facial recognition cameras on every street corner?

**Comment by Jean-LouisMesic** [comment]
@KacperZajc Mine, or @terrorist96 's wording?

Why not just revise it to say "§II.15. No law shall infringe on any person's right to record video and/or audio in any public space. No law shall prohibit video and/or audio recording of any agent of the Public Administration in public space and whilst on duty."

This allows the people to film in public, as well as for the people and the PA to monitor public servants.

@terrorist96 Restrooms are called the privy for a reason. Any filming done in a restroom is heinously illegal and socially unacceptable.

The PA still needs to be able to monitor its own property with cameras. Surely, you can run a prison without cameras, but it's a hell of a lot cheaper and more efficient with on-site surveillance.

**Comment by terrorist96** [comment]
>  "§II.15. No law shall infringe on any person's right to record video and/or audio in any public space. No law shall prohibit video and/or audio recording of any agent of the Public Administration in public space and whilst on duty."

The problem with your wording is that it's redundant. The first clause already includes the narrower circumstance in the second clause.

Recording in restrooms may be socially unacceptable, but with the above wording, it ties the hands of the Assembly from passing a law that forbids recording in a public restroom.

**Comment by KacperZajc** [comment]
I dont like this idea.
What is 'public' in liberland? Most of the areas will be private? So private open spaces are public?
What is more, this will lead to 3 video cameras at every corner which I dont like either.

**Comment by terrorist96** [comment]
I guess we need to figure out if government is going to pave streets/sidewalks or private groups. If the former, we should have the right to record. If the latter, then it would introduce the problem of the private groups not allowing some people to use those roads.

**Comment by KacperZajc** [comment]
at this point I really dont think we should change this provision

**Comment by Jean-LouisMesic** [comment]
@KacperZajc The government is not a person, specifically why I said "any person" in the first clause. The second clause allows the government to monitor only its own agents in public space.

**Comment by terrorist96** [comment]
> The government is not a person, specifically why I said "any person" in the first clause. The second clause allows the government to monitor only its own agents in public space.

The government is comprised of persons. Same reason that 'corporations' are 'persons'

**Comment by KacperZajc** [comment]
this is an obvious loophole

**Comment by Jean-LouisMesic** [comment]
This is something I've been meaning to state for awhile; we need to define our legal terms. What is public? What is a person? What is of age?

**Comment by KacperZajc** [comment]
well this is not for the constitution to define I believe

**Comment by Jean-LouisMesic** [comment]
The Constitution is supposed to be what legislation draws its jargon from, I thought.

**Comment by KacperZajc** [comment]
It sets out the general rules, they are to be specified by regular laws or court interpretation.

**Comment by Jean-LouisMesic** [comment]
What a day it will be when due process is "interpreted" or "specified" when we no longer have the pen in hand.

**Comment by Jean-LouisMesic** [comment]
The less we leave to clarification and interpretation later, the better.

**Comment by terrorist96** [comment]
> The less we leave to clarification and interpretation later, the better.

:+1:
