### ISSUE TITLE
http://liberlandpress.com/2015/06/liberlands-constitution-is-it-libertarian-enough/

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#120]
http://liberlandpress.com/2015/06/liberlands-constitution-is-it-libertarian-enough/

We should address the points brought up in this article. 
The entire country being a free speech zone has already been added. 
The Internet is being debated in other threads. 
I made a separate thread about the public recording. 
Death penalty is unconstitutional currently. No laws written have execution as a punishment. Should there be? If someone commits a mass killing or large terrorist attack, should they only be imprisoned or should they be eligible for the death penalty? 
The arms amendment has changed considerably since 2.0 but the mental health issue is still there. I personally think the fear of a rogue judge labeling one certain group as inherently having mental health issues is an unfounded fear. Plus, we have the recall process of bad judges. 
Fair compensation should be given from the salary of any and all people involved in the illegal acts towards that person. 
Losing citizenship for someone without dual citizenship has already been addressed. 
Socialized legal services is being debated in other threads. 
Same thing about the taxation. 

Thoughts?

**Comment by liberlandcitizen** [comment]
I wrote this article :)

We (Liberland Press) received an e-mail already from @KacperZajc saying that he would consider these points, and I am very appreciative that they are being considered.  Also, it's really an honor to now be sharing my thoughts here on github and I appreciate the open forum.

**Comment by KacperZajc** [comment]
@liberlandcitizen so you probably can tell that most of your concerns have been accommodated in the past few days :)

**Comment by Jean-LouisMesic** [comment]
The State should be given no additional right to kill. Not to mention the death penalty is expensive and ineffective in deterring crimes heinous enough to warrant it. If someone is messed up enough to kill 20 people, a death penalty is not going to deter them. Perhaps it could encourage them in their twisted worldview.

The rest of your points are either addressed or in discussion elsewhere.

**Comment by KacperZajc** [comment]
Personally Im for the death penalty but it would be difficult in terms of PR so the President intentionally left this issue for later.

**Comment by liberlandcitizen** [comment]
I can't think of anything more "cruel and unusual" than taking somebody's life.  

Seems weird to me that we are trying to have the world's "smallest" government but would grant that same government the greatest of powers: murdering somebody.

**Comment by FellowTraveler** [comment]
It's going to have that power anyway. Even the smallest government authority is backed up by the death penalty.

For example, if you park illegally, you get a parking ticket. It's only a fine -- but what if you refuse to pay the fine? The court will issue a summons for you to appear in court. But what if you refuse to appear? The court will put out a warrant for your arrest, and the government will send armed men to your house to kidnap you and put you in a cage. But what if you resist or otherwise defend yourself? You will be shot.

People often say this libertarian example is extreme, but it is exactly true. Policy is of no effect without violence. And all policy is ultimately enforced through the death penalty -- even parking tickets. Without this threat of death, parking tickets would not be enforceable.

_And for your lifeblood I will surely demand an accounting... I will demand an accounting for the life of another human being._

_“Whoever sheds human blood,_
_by humans shall their blood be shed;_
_for in the image of God_
_has God made mankind._

**Comment by terrorist96** [comment]
You really nailed it on the head. I say death penalty for homicide in the first degree and higher crimes.

**Comment by terrorist96** [comment]
Regarding the entire country being a free speech zone

What if a large group decide to have a spontaneous parade and occupy the roads and blocking all traffic for an extended period of time. Would this be covered by the negative rights violation clause? We need to add
> The right to locomotion locomotion is an unalienable right and that right shall not be impeded unless presented with a valid Warrant or upon probable cause by an officer; reasonable suspicion shall not be grounds to detain someone.

**Comment by Jean-LouisMesic** [comment]
Locomotion?

That would mean everyone is entitled to a car. No. If roads are privately owned, then the owners will tell the free-loaders to get the hell off of their property. Take it somewhere else.

**Comment by terrorist96** [comment]
Locomation: the ability to move from one place to another
Nothing to do with a car. Are you implying that all roads will be private? If so, then there wouldn't be any public areas to exercise free speech. Private property doesn't have to allow protesters, thus rendering the entire country being a free speech zone pointless. Speaking of which, that needs clarification to say that "nothing in this section shall be construed as to deny private property owners the right to prosecute trespassers."

**Comment by Jean-LouisMesic** [comment]
@FellowTraveler Right. But anyone who abides by officers' commands and consents to being tossed in a cage should not have to face the threat twice. All this amounts to is greater fear; you can resist and possibly survive, but most likely die, or you can comply and also die. People consumed by fear and pessimism will undoubtedly resist, and put more people into harms' ways than would have been in direct threat than would be in a guaranteed survival vs. high risk of death situation.

No complying subject should have to take the risk of losing their lives twice for the same offence.

**Comment by Jean-LouisMesic** [comment]
@terrorist96 Locomotion is a strange word to use there, to me, at least. But it makes sense in context. Detaining is already covered elsewhere. Try "No law shall impede nor infringe on any person's right to private transit of any means and/or purpose, nor shall any agent of the Public Administration unless in pursuit of a warrant issued by a criminal court of the Free Republic of Liberland, or upon probable cause."

Our definition of public place is loose at the moment. It includes au pleine aire, public property, and anywhere a consumer can go in a business. Sometimes it's stipulated, sometimes it is not. Wherever any pedestrian can go.

**Comment by terrorist96** [comment]
@KacperZajc which version do you like better?

> The right to locomotion is an unalienable right and that right shall not be impeded upon unless presented with a valid Warrant or upon probable cause by an officer; reasonable suspicion shall not be grounds to detain someone.

> No law shall impede nor infringe on any person's right to private transit of any means and/or purpose, nor shall any agent of the Public Administration unless in pursuit of a warrant issued by a criminal court of the Free Republic of Liberland, or upon probable cause.

**Comment by terrorist96** [comment]
> Wherever any pedestrian can go.

What if a certain establishment chooses to exclude certain members of the public? Then that location isn't somewhere that "any pedestrian can go."

**Comment by KacperZajc** [comment]
I dont see why we need to guarantee any right to 'locomotion' - we guarantee the right to assembly where no negative rights of others are infringed - this seems enough for me

right to locomotion seems really strange to me, especially in a libertarian constitution

**Comment by terrorist96** [comment]
It would protect against random check points or a cop trying to detain you based on a hunch.

**Comment by KacperZajc** [comment]
this is already protected by §II.18 and §III.2

**Comment by terrorist96** [comment]
We have similar provisions in America, but it doesn't stop suspicionless checkpoints 100 miles from the border, or random DUI checkpoints anywhere. For the first one, they claim you're not being seized because all they're allowed to do is ask you your citizenship (but you're not required to answer), however it is still an inconvenience being stopped temporarily. As for the DUI checkpoints, they claim them to be randomized. I basically want to protect against this by enumerating it specifically.

**Comment by KacperZajc** [comment]
We dont know how the border control (if any) will look like.
Plus we dont know how road traffic will look like.
It's too early for such a provision.

**Comment by Jean-LouisMesic** [comment]
@terrorist96 A pedestrian can feasibly walk into a business, be denied service, and asked to leave. That doesn't mean he couldn't have gone there in the first place.

**Comment by terrorist96** [comment]
> @terrorist96 A pedestrian can feasibly walk into a business, be denied service, and asked to leave. That doesn't mean he couldn't have gone there in the first place.

You could use the same reasoning for sneaking into a classified facility before being kicked out/arrested. Just playing the strawman :P

**Comment by Jean-LouisMesic** [comment]
I suppose. I'll rephrase my meaning. Anywhere a pedestrian could LEGALLY go.

We need to define public space more, because if roads are privately owned, how the hell are police going to get around if they aren't considered "soft" public (where a person can tell you to leave, but you can go and be there until asked to leave unless you've been asked to stay away before)

**Comment by terrorist96** [comment]
So what if you go into a public establishment, you're asked to leave, but refuse? It would be considered trespassing, but that's not against the law as it stands currently.So I guess you could still 'legally' go there, but that could open you to prosecution for the property owner's rights.

**Comment by Jean-LouisMesic** [comment]
That would be trespassing, and ground for arrest/indictment, because it is violating the owners' rights to allow or disallow the presence of any person for any reason. And I also think trespassing is covered in the constitution, actually, we just have no punishments set out for it, which is what the lawmaking process is for once we finalize this document.

**Comment by KacperZajc** [comment]
for trespassing see #132
