### ISSUE TITLE
New changes

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#123]
To introduce:

1.	No law shall regulate any printed materials, radio, television, the Internet or any other medium of exchange of information; no law shall regulate the rules concerning uploading, transmitting, displaying, accessing and/or publishing such information; nor shall any law introduce licensing and/or registration to infringe upon these rights; nothing in this provision shall prevent Assembly from regulating the rules concerning protection of sources used by journalists, accessing information without consent of the rightful owners and protection of persons under age.
(instead of §II.13)

2.	No agent of the Public Administration shall operate undercover without a warrant issued by a judge of the Criminal Court; no agent of the Public Administration operating undercover shall pursue incriminating evidence through any method of entrapment, nor shall any agent of the Public Administration act outside of their specified mission unless to protect themselves or others in direct threat; all actions by any agent of the Public Administration operating undercover shall be scrutinized in any court proceedings which include any evidence collected from an agent operating undercover, unless said agent is still legally operating undercover in pursuit of a related warrant.
(instead of §I.7)

3.	All Bills proposed by the Cabinet shall be made public prior to the Assembly's debate on them; all drafts of Bills proposed to the Cabinet shall be made public before the Cabinet’s acceptance or rejection.

4.	No person shall be prosecuted for any criminal offence if the only evidence incriminating him or her is testimony given by law enforcement that is uncorroborated by any other presented physical and/or digital evidence and/or third party witness testimony. 

5.	One-fourth of all Assembly Representatives shall have the right to oblige the Cabinet to consider a draft of a Bill prepared by them; if such draft is rejected by the Cabinet as potential Bill, the Cabinet shall publicly give detailed reasons behind its decision; nothing in this provision shall oblige the Cabinet to submit to Assembly such a draft as a Bill.

6.	Add to the gun provision (§III.3) "the owner of the premises shall determine whether arms can be carried on such premises except for the members of the law enforcement where acting upon warrant"

7.	Remove ‘Bill of Attainder’ provision (§II.2) which is already covered by ‘due process’ provision (§III.6)

8.	Potential new territories incorporated to Liberland might be incorporated under different status 

9.	Add ‘Treaty Bill’ which will be the only possibility to make international treaties directly enforceable in a court of law (passed with ¾ of all Assembly Representatives)

10.	Restate “No ex post facto law shall be passed” (§II.1) to “No law shall retroactively change the legal consequences and/or status of actions that were already committed, or relationships that already existed, before the enactment of that law.”

To consider: 

1.	Any Justice of the Supreme Court who is recalled in a referendum shall be replaced by a person elected by the Citizens in a free election.
2.	Militarisation of the police
3.	Monopolies

**Comment by terrorist96** [comment]
> Any warrant issued by any court of the Free Republic of Liberland shall expire after a **maximum of 1 year**, and must be renewed to continue undercover operations.

In order to disallow warrants that don't expire for 5, 10 etc years.

> Add to the gun provision (§III.3) "the owner of the premises shall determine whether arms can be carried on such premises except for the members of the law enforcement where acting upon warrant"

This means that they can disallow a cop who is on duty but not acting in pursuance of a warrant. Is that the intention? And what about a requirement that all entrances be secured to the arms free zone? (with the exclusion of private property) 

> Potential new territories incorporated to Liberland might be incorporated under different status

Please explain. 

> Add ‘Treaty Bill’

Would it be subject to referendum veto? 

> Restate “No ex post facto law shall be passed” (§II.1) to “No law shall retroactively change the legal consequences and/or status of actions that were already committed, or relationships that already existed, before the enactment of that law.”

Why is this necessary? Seems to me that the original statement covers it.

**Comment by KacperZajc** [comment]
1) Hmmm...
2) Yes this is the intention - policeman without warrant is a guest on the premises and if the owner says no guns are allowed, then he has to agree or leave.
3) We allow new territories to be incorporated to Liberland, I was asked to add that those new territories can be incorporated with different status - special relationship with 'main' Liberland.
4) yes of course, I just want to make it a special bill so that it is not passed under cover of an ordinary bill
5) yes it does cover it, I just want to expressly state what we mean to avoid any potential twisted interpretations in the future

**Comment by KacperZajc** [comment]
maybe we should make a separate provision on a general limitation for all warrants? let's discuss

**Comment by terrorist96** [comment]
> maybe we should make a separate provision on a general limitation for all warrants? let's discuss

Yes, that would be good, so anytime a warrant is referred to, it doesn't have to be defined, we can look to the warrant provision that stipulates all warrant requirements/conditions/etc

**Comment by KacperZajc** [comment]
yes this is what I mean :)
I will make a separate issue.

**Comment by Jean-LouisMesic** [comment]
(1) Yea.

(2)  Yea. *pursuance, not pursuit.

(3) "proposed to the Cabinet shall be made public prior to any motions to revise or reject any proposition of the Assembly are taken."

(4) Why third party? I understand that it is to make a distinction between defendant, state, and other, but it could also be construed to preclude victim testimony. Perhaps a better wording is available. Otherwise, yea.

(5) Yea, but perhaps we should simply add the provisions listed in 3 to this section to limit clutter?

(6) The PA should not be considered a normal "owner." There must be a reasonable concern of security within the premises to constitute the PA labeling an area as gun-free. Prisons, military bases, and police stations are reasonable. A publicly owned pipeline cannot conceivably be a property reasonably threatened by gun-carriers, and thus could only be used as a barrier to bottleneck or enclose gun-owners with invisible walls.

**Comment by Jean-LouisMesic** [comment]
@terrorist90 I agree with the general 1 year expiration on warrants, in fact, I believe it's referenced elsewhere in the Constitution. Amount of time that can go by after the issuance of a warrant and when a trial must occur.

**Comment by terrorist96** [comment]
> (4) Why third party? I understand that it is to make a distinction between defendant, state, and other, but it could also be construed to preclude victim testimony. Perhaps a better wording is available. Otherwise, yea.

"and/or victim or third party witness testimony."
?

I'm in favor of putting the Bill of Attainder language back.

**Comment by Jean-LouisMesic** [comment]
@terrorist96 Seems alright to me.
