### ISSUE TITLE
Warrant limitation

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#125]
All warrants in the Free Republic of Liberland shall be issued by a judge of the Criminal Court upon request by a member of the law enforcement or the Office of the Public Prosecutor and shall be supported by evidence of probable cause; every warrant granted for a continuous action shall expire within one year and shall be renewed by another judge in accordance with ordinary procedure.

feel free to add on :)

**Comment by terrorist96** [comment]
"upon the request of a..."

or

"upon request by a..."

**Comment by Jean-LouisMesic** [comment]
I have a problem with "...a member of the law enforcement..." There should be a chain of command. Perhaps only members of certain rank have the authority to request warrants on the behalf of others.

Why not have every warrant expire at 1 year, with mandated renewal?

**Comment by Jean-LouisMesic** [comment]
@terrorist96 I agree, should be "upon request by a" as well.

**Comment by KacperZajc** [comment]
there must by any member because if you have a policeman outside the house believing there is something bad going on inside, he must be able to call a judge and get permission to enter, there is usually no time to call his supervisor etc, this is exactly what Rand Paul discussed during his last filibuster blocking the PATRIOT Act

**Comment by Jean-LouisMesic** [comment]
Wouldn't that be covered by probable cause?

Probable cause is meant for cases where there is little time to secure a warrant. What judge is going to be awake at 3 in the morning in case a policeman walking down the street hears a bloodcurdling scream in someone's house?

Warrants are meant for planned actions, where there is time to get court approval.

**Comment by KacperZajc** [comment]
if he saw him on the side walk probable cause would suffice;
if that was inside the house, he would need a warrant to enter the premises (violation of privacy)

**Comment by Jean-LouisMesic** [comment]
Fair enough. Still, what judge is going to answer calls at 3 in the morning when there are twenty officers out every night trying to call in warrants? It would be more efficient for them to report to a supervisor who can focus on pursuing warrants for them, so they can remain vigilant rather than paying all of their attention to a dial tone.

**Comment by terrorist96** [comment]
> @KacperZajc Fair enough. Still, what judge is going to answer calls at 3 in the morning when there are twenty officers out every night trying to call in warrants? It would be more efficient for them to report to a supervisor who can focus on pursuing warrants for them, so they can remain vigilant rather than paying all of their attention to a dial tone.

Believe it or not, that's how it works in America (generally). 3am, need a warrant? Wake up a judge and get one.

**Comment by KacperZajc** [comment]
at least how it used to work in America 
but definitely this is what we want to see in Liberland;
there is more than 1 judge to answer the call :)

**Comment by Jean-LouisMesic** [comment]
Fair enough. I'll relent; I still think this is terribly inefficient, and bound to cause problems, but if it's worked before, then I'll rest and trust.
