### ISSUE TITLE
What's the status on Court cases?

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#126]
Just curious, anyone know what's going on with the court cases challenging Croatia's occupation of Liberland? Anything filed with the UN etc?

**Comment by Jean-LouisMesic** [comment]
As far as I know, they had, until recently, been enforcing the western border of Siga as referenced in their claim to all territories west of the Danube River as it flowed in 1947. This implied that they were not claiming our territory. However, they did recently arrest 4 Liberland citizens who "illegally" sailed up the Danube and landed in Siga, so now it is implying that they are claiming the territory of Siga. This would contradict their behavior for the past nearly seventy years. It also weakens their claim to the territory that lies east of the Danube river as it currently flows, but west of the territory that lies west of the Danube river as it flowed in 1947, meaning they're giving up a hell of a lot of land area to Serbia for no conceivable reason other than to fuck with us.

**Comment by KacperZajc** [comment]
please dont do it here
