### ISSUE TITLE
Recordation of the Assembly's affairs and Supreme Court challanges

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#139]
Would it be germane to submit a PR stipulating that the affairs of the Assembly and any Supreme Court challenges shall be recorded and made publicly available for consumption (i.e CSPAN) ?
It says the Assembly regulates its own affairs, I don't think they should allow themselves to deliberate in secret.

**Comment by Jean-LouisMesic** [comment]
I don't think it'd be unreasonable, and it should be encouraged. I've always dreamed of an Assembly hall in the form of an auditorium, with an orchestra housing the Assembly, the mezzanine housing committees, guests, etc., and a second balcony level being set up like a surgical theatre, where the public can come in and look down upon the politicians. TL,DR; I think anyone should be able to flick on the television and see the Supreme Court or Assembly. Trials are already "swift and public," so why not leave appeals the same way?

**Comment by terrorist96** [comment]
If @KacperZajc gives me the a-ok, I'll submit a PR

**Comment by KacperZajc** [comment]
Debates and voting records of the Assembly should be made public;
Verdicts of all courts should be recovered and made public (deliberations of judges and juries not);
you can make it a PR
