### ISSUE TITLE
Jury nullification

### ISSUE THREAD

**Issue by cpacia** [liberland/constitution#15]
I think it's a good idea to enshrine this principle into the constitution so there is no ambiguity about it.

Section 3.9 reads:

> It shall be the duty of the Judiciary to strike down as void and unlawful any laws in conflict with the Constitution.

That should extend to juries as well.

**Comment by tinkyholloway** [comment]
What is the advantage of this given that Citizen's can veto legislation in 90 days? Is it that a jury can nullify laws outside this period? Do you mean that as part of their deliberations in a criminal case, a Jury can find some law used by the state during tne trial as invalid?

**Comment by cpacia** [comment]
Yeah. Politicians don't exactly have a track record of following the constitution and neither do voters for that matter. Jury nullification is a sort of last line of defense against unjust laws.

If jurors feel the law the defendant is accused of violating is unconstitutional, then they vote not guilty.
