### ISSUE TITLE
sorting out 24hours arrest

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#155]
No person shall be detained randomly or without any evidence but only under specified charges, upon probable cause and by a member of the law enforcement acting openly and respecting all rights the detainee enjoys under this Constitution and any laws passed by the Assembly in accordance thereof.

Please comment below.

**Comment by terrorist96** [comment]
Yea. Also, I feel like we need to move some of the stuff specifying the violation of privacy with a warrant from III.2 to the warrant section, stipulating the specificity of warrants.

**Comment by KacperZajc** [comment]
could you be more specific?

**Comment by terrorist96** [comment]
Basically something in the warrant clause stating that all warrants are to particularly describe the person, places, things, etc to be searched, seized, frozen, accessed etc. This way, we won't have to mention the specifics of a warrant, such as the suggestion given for gun free zones except for police with a warrant (that is relevant specifically to the premises and/or its owner, residents, and/or patrons)

**Comment by Jean-LouisMesic** [comment]
Yea.

@terrorist96 I don't think that's relevant for this specific issue.
