### ISSUE TITLE
His or her vs their

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#159]
I propose we change all instances of "his or her" to "their". This avoids the issue of transsexuals and provides greater harmony throughout the document. Thoughts?

**Comment by Jean-LouisMesic** [comment]
I've considered this, but there is the issue of plurality. I wish there was another gender-neutral pronoun that was still as specific as "his or her" in legal terminology.

**Comment by terrorist96** [comment]
How about `one's`

**Comment by KacperZajc** [comment]
is there any reason for the change?

**Comment by terrorist96** [comment]
"This avoids the issue of transsexuals and provides greater harmony throughout the document"

**Comment by KacperZajc** [comment]
ok...
who are you quoting? :D

**Comment by terrorist96** [comment]
Myself, first post

**Comment by KacperZajc** [comment]
ok so let's go with 'one'

**Comment by terrorist96** [comment]
I agree
