### ISSUE TITLE
Taxes

### ISSUE THREAD

**Issue by tinkyholloway** [liberland/constitution#16]
Taxes are both a philosophical problem (calling them taxes implies compulsion) and a practical problem (how to stop the PA becoming bigger by looking for problems to fund and fix).

One possible solution is to fund the PA soley by a non compulsory, single value fee each year. The size of the fee must be specified in the Finance Bill. Finance Bills are then subject to veto removing the exception to this from the Constitution.

Only fee payers are counted as 'citizens'.  Only citizens can participate in goverment: stand for office, vote, veto vote, be on juries, hold the title 'Citizen' etc. it's basically a flat fee, poll tax.

All people continue to be protected under the law.

**Comment by cpacia** [comment]
That was more or less my idea as well. Only citizens pay taxes making it voluntary. This would require the legislature to keep taxes very low else people will drop their citizenship. 

This would also require a mechanism to allow people to drop citizenship and reclaim it later. And you would want to do it in a way that doesn't create an incentive for people to become citizens right before and election and drop their citizenship afterwards.

**Comment by joshmh** [comment]
Another possibility is to fund each bill directly. Each bill would have its own budget, defined in the bill. We'll assume all laws are finite in term (https://github.com/liberland/constitution/pull/13), so the funding would be for the entire duration of the bill.

In this scenario, all bills would have to be ratified by the public. If voting is done electronically, each voter would be able to commit money towards the bill. Imagine a voting app that shows you a running total of the money you've committed for all bills. A bill would pass only if it has raised enough money, and if it received a majority of votes.

**Comment by cpacia** [comment]
Now that's clever

**Comment by manchfu** [comment]
And if a law is over budget, it would either get additional voluntary funding or die. It's a crowd-funding/voting hybrid.

**Comment by tinkyholloway** [comment]
That is a great idea. A nominal percentage could be used for overhead such as keeping the office lights on at the assembly - assuming bricks and mortar exist - I'd be happy to have the Assembly, Cabinet, and Departments work out of a Starbucks.

**Comment by joshmh** [comment]
Even the funding for the Assembly would need to be a bill that expires. They'd need to put enough money into the bill to keep the lights on for the term of the bill. If they don't get it, no lights.

@cpacia I'm interested in exploring how this could merged with your polycentric cantons idea. Fancy words and restrictions can never keep power in check, we need to fundamentally distribute the power.

**Comment by tinkyholloway** [comment]
@joshmh right on.

**Comment by pmacom** [comment]
Has there been any consideration into utilizing an existing or customized cryptocurrency for any of this? I know that most people are only familiar them as a currency, however at the core, each cryptocurrency is really just a permanent public ledger.

The "ledger" is what is important, not the currency. Almost any cryptocurrency's blockchain could theoretically keep a record of each bill's donors and how money flows in and out of it. 

Having all of the governments transactions publicly visible from the start of it's creation would be a tremendous step towards true liberty.

**Comment by Zephram-C** [comment]
@pmacom > * Almost any cryptocurrency's blockchain could theoretically keep a record *
It should be cryptocurrency with robust network and high total hashrate.

Idea of directly funding bills is nice. It combines voluntary taxes idea with practical realization of citizenship.

**Comment by joshmh** [comment]
Yeah, this kind of thing is my best hope for keeping the government in check. Money talks.

**Comment by liberlandcitizen** [comment]
As I commented on the Liberland Facebook page...taxes = theft.  The President has stated in many media interviews that taxes would be voluntary in Liberland.  Allowing the assembly to create taxes for things like sales tax and land tax is in direct contradiction to what he has promised.  

I beg of you - don't legalize theft for government officials.  Let the people choose to donate to the government if they choose to.

**Comment by cpacia** [comment]
I completely agree. And given the make up of the people who are already there it seems highly unlikely that they would have a hard time raising funds voluntarily. However, I tend to think the actual constitution will more likely be influenced by the originally settlers than what we do here on github.

**Comment by Jean-LouisMesic** [comment]
Bills would be treated as investments in @joshmh 's plan.

One would merely have to hope that important programs were important enough either for people to support the public domain in funding, or to invest in similar programs in the private sector to satisfy the need.

**Comment by saintego** [comment]
There is dispute between founding fathers about voluntary taxes. I think Vitek is still strictly for voluntary one... I like @joshmh idea, but I think it can work only with bills providing services, not banning something.

**Comment by Jean-LouisMesic** [comment]
@saintego What needs to be banned, anyway?

Homicide, burglary, larseny, rape, assault... Fraud, embezzling, etc. Banning victim crimes is the same thing as offering the service of protection from these acts. People would pay for the protection.

What are you worried that we may have to ban?

**Comment by saintego** [comment]
@Jean-LouisMesic Yes, probably you are right

**Comment by terrorist96** [comment]
Let's say that a tax bill is passed. How are citizens expected to pay the tax? The government doesn't have an official currency, so could people choose to pay the tax with anything of value they choose? What if there's dispute about he value?

Basically, if the government wants to pass a tax bill, then they'd have to stipulate what currency they want to receive the taxes in, creating a de facto official currency.

**Comment by Jean-LouisMesic** [comment]
@terrorist96 It could probably be done in such a way that the government will only accept one commodity as tax, like bitcoin, or something else.

It wouldn't affect person-person transactions, only transactions with the government. It would be the same as someone who only has conceivable uses for silver, or commodity currency turning down feathers or silks as compensation.

**Comment by terrorist96** [comment]
> @terrorist96 It could probably be done in such a way that the government will only accept one commodity as tax, like bitcoin, or something else.
It wouldn't affect person-person transactions, only transactions with the government. It would be the same as someone who only has conceivable uses for silver, or commodity currency turning down feathers or silks as compensation, except the PA is the person, and they only have conceivable uses for specific commodit(ies).

Yes, but it creates the de facto currency of Liberland. Nothing in USA law prohibits people from exchanging goods for agreed upon currency. The only difference here would be that USA gov obliges you to accept dollars (and leaves you free to accept anything else).

**Comment by Jean-LouisMesic** [comment]
Well, also, not necessarily. For instance, the PA could decide to take multiple commodities. These commodities could change over time, as well, depending on what the government can use at that given moment.

 It's also more the de justo currency-in-demand by the government than de facto. The de facto currency of Liberland is whatever the people choose, because travellers will not be paying taxes, thus why would they consider the "fact" currency of Liberland to be just what the government takes? I'm arguing semantics at this point. I digress, I can be a bit contrarian. 

De justo is what the government says, de facto is what is actually going on.

**Comment by terrorist96** [comment]
I think you mean to say `de jure`

**Comment by Jean-LouisMesic** [comment]
@terrorist96 Yeah, there we go.

It's amazing how often one uses de facto without mentioning de jure, even in the circumstances of global statism.

**Comment by terrorist96** [comment]
It would be de jure currency in demand by the PA, but de facto currency of the nation as a whole. Sorta like how Croatia arrested people for crossing into liberland from Croatia, it was de facto recognition of Liberland, but not de jure.

**Comment by Jean-LouisMesic** [comment]
No it wouldn't. De facto currency would be what you could walk into a store and barter up for a candy bar. What the government accepts as tax has no bearing on that, as you can sell commodities in exchange for bitcoins or some other standard medium that can be given to the government.

**Comment by Jean-LouisMesic** [comment]
Also, Croatia recently detained people crossing into Siga from our eastern border as well, so that de facto recognition no longer stands.

**Comment by terrorist96** [comment]
When the government endorses a certain currency over all the others (let's say the common currencies in Liberland will be bitcoin, gold and silver coins, and miscellaneous spices) and the government demands its taxes be paid in bitcoin, it is endorsing bitcoin over the other forms of currency within the nation. This, in turn, will very likely lead to more people using bitcoin over gold/silver/etc and make a de facto currency of the government.

> Also, Croatia recently detained people crossing into Siga from our eastern border as well, so that de facto recognition no longer stands.

I guess it's time to get arrested crossing the border from the west side again. Further delegitimize what they deem as their actual border

**Comment by lunokhod** [comment]
Could someone let me know how Liberland citizens will pay for and obtain health insurance? (Especially for the case where they can not afford to pay any form of tax, voluntary or otherwise?) Will national health insurance be one of the socialist exceptions in Liberland?
