### ISSUE TITLE
The Assembly Committee

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#163]
1   One-fourth of all Assembly Representatives shall have the right to propose a resolution instituting the Assembly Committee; the resolution shall be passed with a majority of two-thirds of all Assembly Representatives.
1(1)   The Assembly Committee shall be composed of five Assembly Representatives;
1(2)   The Assembly Committee shall be established upon a suspicion of misconduct or mismanagement of any member of the Public Administration;
1(3)   The Assembly Committee shall have the right to summon members and agents of the Public Administration to hear testimonies given under oath;
1(4)   The Assembly Committee shall prepare the Final Conclusions reporting evidence (if any) of said misconduct or mismanagement; such conclusions shall not have any legal effect;
1(5)   The Final Conclusions shall be made public as well as passed to the Chief Public Prosecutor for  consideration of potential criminal prosecution of relevant persons as described by the Committee; the Conclusions shall not bind the Chief Public Prosecutor to institute any prosecution;
1(6)   No person shall be penalised by the Assembly Committee; testimonies given in breach of the oath shall be prosecuted in regular manner.

what do you think?

**Comment by terrorist96** [comment]
> (1) One-fourth of all Assembly Representatives shall have the right to propose a resolution instituting the Assembly Committee; the resolution shall be passed with a **simple majority** of all Assembly Representatives.

It should be easier to set up a committee to find wrong doing.

The rest is good.

**Comment by Jean-LouisMesic** [comment]
Shall the committee have the right to summon citizens to give testimony?

**Comment by KacperZajc** [comment]
only agents of the Public Administration
