### ISSUE TITLE
Taming prosecutors

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#166]
No law shall be passed that is patently unenforceable, with the sole intention of having that law act as a tack-on charge in a prosecution. 

Also, should we forbid plea deals in the constitution or allow prosecutions to offer them?

**Comment by KacperZajc** [comment]
1) your law is clearly unenforceable - it impossible to say what law will be unenforceable 
2) is there something wrong with plea deals?

**Comment by terrorist96** [comment]
An unenforceable law would be something extra that a prosecutor could charge you with after already catching you breaking some other law. 
Plea deals are used frequently in America to discourage people from going to trial. Something like 90+% of criminal cases never go to trial.

**Comment by KacperZajc** [comment]
1) its worth considering then
2) and is it a bad thing?

**Comment by terrorist96** [comment]
It's not an inherently bad thing, but is used frequently by prosecutors to strong-arm a defendant to plead guilty to a lesser charge than for the prosecution to do their job and prove guilt beyond a reasonable doubt. It basically punishes defendants for wanting to go to trial because the option to be charged with the lesser crime is only available if you plead guilty right now.

**Comment by Jean-LouisMesic** [comment]
In regard to plea deals, many innocent people see the evidence stacked against them and decide to give up and avoid trial because they don't believe anyone will find them innocent. They'd rather avoid going on to death row for a crime they didn't commit, so they say whatever the police want them to just to avoid a jury, which may or may not have acquitted them.

**Comment by Jean-LouisMesic** [comment]
:+1: @terrorist96

**Comment by KacperZajc** [comment]
I dont want to forbid plea bargains in the Constitution. 
What about charging people with different offences for the same act (if I understood correctly?)

**Comment by terrorist96** [comment]
What's the wording you want to implement?

**Comment by KacperZajc** [comment]
No law shall allow for any person to be prosecuted for more than one criminal offence for one act or omission they committed. 

Is that what you meant?

**Comment by terrorist96** [comment]
That sounds good. It would prevent "over charging" by prosecutors in order to scare defendants into a plea bargain.
