### ISSUE TITLE
No gag orders

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#168]
What about something saying that gag orders are repugnant to the right to free speech and shall not be implemented (unless absolutely necessary in order to protect others' rights)? Thoughts?

**Comment by KacperZajc** [comment]
it's worth considering, any ideas?

**Comment by terrorist96** [comment]
It could be tacked onto the "no classified documents except when necessary" section. 

§I.7. The Citizens of the Free Republic of Liberland shall have the access to information which relates to any aspect of the functioning of the Public Administration which is not classified; and no information shall be classified unless it is absolutely necessary for the purposes of national security; **no gag orders shall be implemented unless absolutely necessary to protect others' rights;** the affairs of the Assembly and the Supreme Court shall be video recorded and made public contemporaneously; any Assembly debate and votes or decision of any Court shall be recorded and archived and made available to the general public.

**Comment by KacperZajc** [comment]
yeah this is good;
what if we make this whole provision more demanding?
any thoughts?

**Comment by terrorist96** [comment]
Sure, how much more demanding? Stuff like sealed court documents?

**Comment by KacperZajc** [comment]
maybe we get rid of classified information altogether?

**Comment by terrorist96** [comment]
That'd be nice but how practical would it be? Granted we don't have a military, so there'd be less to classify. But at the same time, the government is funded by the people and keeping stuff hidden from those that are funding you is immoral. I'd be interested in hearing more arguments.

**Comment by KacperZajc** [comment]
My original wording took into account potential military. But it is clear now there wont be any, so my question is whether there is anything else that should be classified? If not, we should get rid of this possibility altogether.

**Comment by terrorist96** [comment]
If so then that would make the whistle-blower provision unnecessary. I can't really think of anything that would be worthy of classification outside military secrets.

**Comment by Jean-LouisMesic** [comment]
Classification is a major PR issue, I don't see peer governments sharing much with us without confidentiality.

Without our own army, we're going to rely on our own citizens, our police, and our neighbors for protection. Thus, PR issues are paramount to our security.

**Comment by Jean-LouisMesic** [comment]
We've also already decided that jury deliberations and justice deliberations are going to be recorded, but classified for protection of privacy. Only verdicts and sentences, and rationales will be made public.

**Comment by terrorist96** [comment]
Where did we decide that justice/jury deliberations would be recorded? The arguments and public actions will be recorded (since they're already public; recording will just provide better access). Deliberations should be conducted in private.

**Comment by Jean-LouisMesic** [comment]
It should be recorded, but not made public. See VI.15(3).

**Comment by terrorist96** [comment]
I see where you get the confusion. "in camera" doesn't mean what you think it means.
http://lmgtfy.com/?q=in+camera
:smiling_imp:

**Comment by Jean-LouisMesic** [comment]
Interesting. See, this is why using archaic words to describe new inventions that are only moderately related to said words is so dangerous. Just make a new word! xD

**Comment by KacperZajc** [comment]
in camera = in private
no recording :)

@Jean-LouisMesic so what is your opinion on classified information?
