### ISSUE TITLE
Limitations on the constitution due to PR

### ISSUE THREAD

**Issue by yopdog** [liberland/constitution#169]
Being new here, I would like to understand what limitations are there on the constitution given the efforts to become internationally recognized. I saw on a previous issue that the two sections below were removed for PR reasons alone.  

§15. No law shall restrict or hamper the free and peaceful movement of persons, goods, or capital within or across the borders of the Free Republic of Liberland.

§19. No law shall regulate the use of any chemical substance so long as the use is not designed to intentionally harm any person without his or her consent.

Why are reasonably good sections of the constitution being removed because of PR? Isn't that counterproductive to creating a good constitution that protects people's rights?

**Comment by KacperZajc** [comment]
15) certain export limitations regarding dangerous materials, money laundering issues etc.
19) already covered by ban on victimless crimes provision and the President did not want to rub drug issues into our neighbours' faces

Im striking a balance between PR and libertarian ideas the best I can here :)

**Comment by yopdog** [comment]
Are export limitations going to be enforced by Liberland? if so, couldn't that introduce a victimless crime? Will people in Liberland be put in jail for not obeying the laws of other countries?

**Comment by KacperZajc** [comment]
I hope not, hard to tell right now.
We can always change it later.

**Comment by Jean-LouisMesic** [comment]
They're not exactly complete compromises, although I believe there is a better way to "compromise" 15 in such a way that it behaves the same, but reads well to our peers.
