### ISSUE TITLE
Consider using Markdown numbered lists for sections

### ISSUE THREAD

**Issue by joshmh** [liberland/constitution#17]
Using Markdown numbered lists would make it much easier to add and remove sections without needing to renumber everything. It would also dramatically reduce noise in the visual diff. References would be an issue, but I think it's worth the tradeoff.

Example:

```
## Article II: The Executive Power

1. The executive power of the Free Republic of Liberland shall be vested in the Cabinet.
1. The Cabinet shall be formed and presided over by the Chancellor, who is the Head of State.
1. The Chancellor, on behalf of the Cabinet, shall once a year publicly give to the Assembly information on the State of the Republic, and recommend to their consideration such measures as the Cabinet shall judge necessary and expedient thereby initiating a legislative procedure in accordance with the provisions of Article I.
1. The powers of the Chancellor and the Cabinet shall be restricted to the following only:
  1. to run day-to-day state affairs;
  1. to initiate a legislative procedure including the preparation of the Financial Bill containing the Annual Budget without a budget deficit;
  1. to be Commander in Chief of the military, once the state of war is declared by the Assembly;
  1. to protect and promote the interests of the Free Republic of Liberland worldwide;
  1. to make treaties with the consent of no fewer than nineteen votes of the Assembly Representatives;
  1. to execute in good faith the laws passed by the Assembly;
  1. to produce byelaws in a form of Delegated Instruments under the powers expressly granted to it by Acts of the Assembly.
1. The Cabinet shall consist of the following Departments only:
  1. Department of Justice
  1. Department of Internal Affairs
  1. Department of Security
  1. Department of Foreign Affairs
  1. Department of Treasury
1. Each Department shall be headed by the Secretary for the respective Department who shall answer to the Chancellor and the Assembly.
1. It shall be the duty of the Cabinet to refuse to execute any laws passed by the Assembly in conflict with the Constitution.
```

**Comment by rotilho** [comment]
+1

**Comment by naconner** [comment]
Sure beats quills and hemp paper. :+1:

**Comment by rotilho** [comment]
I changed my mind. It would be a problem when a item refers another one.

**Comment by joshmh** [comment]
Yeah, I agree that references are a problem. Since I think improving PRs will have a huge effect on everyone's participation, I'm going to keep stabbing at this.

Perhaps we could try a simpler approach:

All new additions in a pull request should be written as the last item in the section, regardless of whether it would make more topical sense to group it with items higher up. We can then all discuss the PR easily.

In the case of a deletion, the item would be deleted, but no renumbering would be done.

Every once in a while, and possibly just once at the end, someone can go through and re-order everything so that it makes more sense, fix all the references, and not make any other alterations in that PR. Then, a few people can verify that nothing was changed, and we're all set.

**Comment by burningtree** [comment]
@joshmh ad rules - If you could prepare a some foundation guidelines for contributing and PRs to CONTRIBUTING.md file it would be cool. It seems that you have an good idea about it. These future rules can also be used in "laws" repo.

**Comment by joshmh** [comment]
:+1:  Good idea, I'll do that.
