### ISSUE TITLE
Removal of association provision

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#170]
* **§II.6.** No law shall mandate nor forbid any natural person of age and/or legal person to associate and/or transact with any consenting natural person of age and/or legal person.

This section was removed in order to add it to:

* **§II.17.** No law shall oblige any person to acquire any form of insurance and/or pension scheme, nor shall it provide any incentive in that respect; nor shall it mandate any person of age to transact and/or associate with any other legal and/or natural person.

Why did you remove the part about forbidding persons to transact/associate?

**Comment by KacperZajc** [comment]
I realised that the part about forbidding persons to transact/associate is already covered by §II.6. 
and it is better to add the mandating part to another article and keep the Constitution as short as possible :)

**Comment by Jean-LouisMesic** [comment]
Why did you remove "consenting" again, after it was decided that it was necessary in another pull request?
