### ISSUE TITLE
restating the whole bill of rights

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#175]
I want to restate the Bill of Rights. It got messy over time. First of all, we abolish this artificial distinction between Legislative restrictions and Individual rights. It was mostly grammatical. Secondly, I finally clarified all those exceptions about age, incarceration and mental health by introducing distinction between an Individual and a Person. Thirdly, I want to make General Provisions a separate Part of the document, not just a part of the Bill of Rights. I also defined due process of law and restated freedom of contract provision. Finally, there are some provisions I would like us to rewrite (see at the bottom).

General Provisions
•	§I.1. The enumeration in this Constitution of certain rights shall not be construed to deny or disparage others retained by the Citizens and other residents of the Free Republic of Liberland.
•	§I.2. The powers not conferred upon the Public Administration by this Constitution, shall not be exercised by it.
•	§I.3. Any person in public office who is convicted of intentional breach of this Constitution shall be immediately removed from the office and shall not hold any other public office in the future.
•	§I.4. All agents of the Public Administration shall be personally liable for any loss caused by themselves whilst acting in their official capacity but unlawfully and/or in error.
•	§I.5. All persons staying within the territory of the Free Republic of Liberland shall be bound to observe the Constitution and all laws passed by the Assembly in accordance with this Constitution; no member or agent of the Public Administration shall be excluded from the operation of any law passed by the Assembly.
•	§I.6. All administrative decisions of the Public Administration shall be subject to challenge in the Civil Court by a person in whose respect it was given, or any other person who can prove one's interest in that decision.
•	§I.7. All Warrants in the Free Republic of Liberland shall be issued by a judge of the Criminal Court upon request by a member of the Law Enforcement or the Office of the Public Prosecutor and shall be supported by evidence of probable cause; such warrants shall be as detailed as possible; every Warrant granted for a continuous action shall expire no later than after one year and shall be renewed by another judge in accordance with ordinary procedure.
•	§I.8. The state of the Free Republic of Liberland, or any part thereof, shall not be incorporated to any other jurisdiction.
•	§I.9. For the purposes of this Constitution, the term “Person” shall signify any human being whatsoever; the term “Individual” shall signify a person of age who does not lack mental capacity and is not incarcerated following a conviction in a court of law; the term “Agent of the Public Administration” shall signify any person working for, or contractually bound with, any body of the Public Administration; the term “Member of the Public Administration” shall signify anyone who is holding a public office of one of the branches of the Public Administration; the term “Agent of the Law Enforcement” shall signify any person working for the Law Enforcement; the term “Citizen” shall signify anyone holding the citizenship of the Free Republic of Liberland; the term “Resident” shall signify anyone within the jurisdiction of the Free Republic of Liberland who is not a Citizen.

Bill of Rights
•	§II.1. No law shall deprive any Citizen of the Free Republic of Liberland of one’s right of access to information which relates to any aspect of the functioning of the Public Administration which is not classified; information shall be classified by a responsible Secretary of State with the permission of 2/3 of all Assembly Representatives as discussed in camera, and for the purposes of national security only, and for a period not exceeding one year; any other Assembly debate and vote, or decision of any Court shall be recorded and archived and made available to the general public; the affairs of the Assembly and the Supreme Court shall be video recorded and made public contemporaneously.
•	§II.2. No law shall deprive any individual of one’s right to exclude from their property any person whatsoever including a agent of the Law Enforcement where acting without a Warrant; anything found in the ground under one’s land shall belong to oneself.
•	§II.3. No law shall retroactively change the legal consequences and/or status of actions that were already committed, or relationships that already existed, before the enactment of that law.
•	§II.4. No law shall establish and/or regulate the institution of marriage between any individuals; nor shall it regulate the rules regarding inheritance where there is a valid will in place.
•	§II.5. No law shall create victimless and/or consensual crimes; no individual shall be considered a victim of one's own actions or omissions.
•	§II.6. No law shall establish the institution of slavery, conscription, or any other form of involuntary servitude, within the Free Republic of Liberland, or in any place subject to its jurisdiction.
•	§II.7. No law shall allow for the private property to be fully or partially taken for the public use without the express and informed consent of, and mutually agreeable compensation to, the owner.
•	§II.8. No law shall abridge the right of any individual to the control of their own bodies, nor interfere with voluntary relations, nor impinge on the right to form cooperative ventures of any form, so long as no negative rights of others are infringed by force or fraud, or threat thereof, or unbeknownst to them.
•	§II.9. No law shall abridge the freedom of thought and religion, and expression thereof so long as no negative rights of others are infringed; no person shall have the right to be protected from opinions of others where expressed peacefully; no law shall law promote or hinder any religion, gender or specific community.
•	§II.10. No law shall abridge the right to assemble peacefully where no negative rights of others are infringed; all public areas within the Free Republic of Liberland shall constitute free speech zones.
•	§II.11. No law shall abridge the right to use or issue any commodity or item as currency unless either party to the transaction is legally prohibited to possess such item or commodity; nor shall the Public Administration engage in any form of monetary regulation or currency issue; nor shall it establish any Central Bank.
•	§II.12. No law shall abridge the right of self-defence and/or defence of one's property, the close ones and others who are under a direct threat, against initiators of aggression, including the agents of the Public Administration and the Law Enforcement where acting unlawfully and/or in error.
•	§II.13. No law shall impose any obligations as to pursuing and/or obtaining any stage of education by any person other than agents and members of the Public Administration; nor shall it regulate the content of any curriculum used by any school or any higher education institute at any stage of education.
•	§II.14. No law shall regulate any printed materials, radio, television, the Internet or any other medium of exchange of information; no law shall regulate the rules concerning uploading, transmitting, displaying, accessing and/or publishing such information; nor shall any law introduce licensing and/or registration to infringe upon these rights; nothing in this provision shall prevent the Assembly from regulating the rules concerning protection of sources used by journalists, accessing information without the consent of the rightful owners, protection of minors and vulnerable parties to a trial in a court of law.
•	§II.15. No law shall prohibit video and/or audio recording of any agent of the Public Administration or agent of the Law Enforcement in public space and whilst on duty.
•	§II.16. No law shall interfere with the content of any contract, nor shall it mandate or forbid any individual to enter into contractual relations with any other individual and/or legal person, or any body of the Public Administration; nor shall it provide any incentive in that respect.
•	§II.17. No law shall allow the Public Administration to assign a number to any individual, nor shall he or she be required to procure, carry, or otherwise maintain identification materials of any form without one's express and informed consent; no individual shall be compelled to identify themselves to any agent of the Public Administration or agent of the Law Enforcement, otherwise upon arrest or pursuant to a Warrant; any and all data collected by the Public Administration shall be used only for the direct and necessary purposes for which it was originally collected, and shall be kept confidential and shared only with the express and informed consent of the rightful owner or otherwise in accordance with the provisions of this Constitution.
•	§II.18. No law shall allow any agent of the Public Administration or agent of the Law Enforcement to operate undercover without a Warrant; no method of entrapment shall be employed to pursue incriminating evidence, nor acting outside of the specified mission shall be allowed unless to protect themselves or others in direct threat; all actions pursued undercover shall be scrutinized in any court proceedings including evidence collected, unless said agent is still legally operating undercover pursuant to a related Warrant.
•	§II.19. No law shall allow for the application of torture or other cruel, unusual, or degrading treatment against any person against their will and informed consent, nor shall any experiments be done in such manner; no individual shall be subjected to any medical treatment without one's express and informed consent; any person whatsoever responsible shall be held personally accountable for such a crime against human dignity, regardless of any law, policy, command or suggestion which might have been authorising such conduct.
•	§II.20. No law shall allow for any individual’s privacy to be violated by freeze of assets, searches, seizures, surveillance, accessing and gathering of their personal information without one's express and informed consent, including obtaining it from third parties and/or using digital means, otherwise pursuant to a Warrant, and only to an extent which is necessary to attain the end and particularly describing the assets to be frozen, the places or persons to be searched, the things or persons to be seized, the persons to be put under surveillance, including the maximum period of that surveillance, and the data to be obtained and stored, including the period for which it can be retained.
•	§II.21. No law shall deprive any individual of the right to own, manufacture, sell, transfer, transport, bear and use any small arms, arms accessories, or ammunition, be they now historic, contemporary and/or experimental, regardless of condition; no form of licensing and/or registration shall be used to infringe upon these rights; the owner of the premises shall determine whether arms can be carried on such premises except for agents of the Law Enforcement where acting pursuant to a Warrant.
•	§II.22. No law shall allow for any person to be detained randomly or without any evidence but only under specified charges, upon probable cause and by an agent of the Law Enforcement acting openly and informing the detainee about the rights one enjoys under this Constitution and any laws passed by the Assembly in accordance thereof.
•	§II.23. No law shall allow for any person to be detained without trial for more than twenty-four hours otherwise than pursuant to a Warrant and unless it is absolutely necessary for the protection of others or where the accused is likely to escape justice or interfere with the investigation; no detention pursuant to such a Warrant shall be longer than it is absolutely necessary to bring an accused to trial.
•	§II.24. No law shall allow for any person to be prosecuted for any criminal offence on the grounds of disclosure of classified information if that piece of information proves or could be reasonably believed to be proving that any agent of the Public Administration has breached, remains in breach or intends to breach the law or the Constitution.
•	§II.25. No law shall allow for any person to be arrested, prosecuted, and sentenced, without due process of law; due process of law shall include impartial hearing of one’s case, informing person of one’s rights and respecting thereof, and observing the law and the Constitution at every stage of dealing; any person who has one's rights to due process of law violated, either illegally or in error, shall receive fair compensation from all persons responsible for the violation.
•	§II.26. No law shall allow for any person to be held incommunicado either before or after the trial.
•	§II.27. No law shall allow for any person to be put twice in jeopardy of a penalty for the same offence.
•	§II.28. No law shall allow for any person to be prosecuted for disobedience against an unlawful action of any agent of the Public Administration and/or against unconstitutional law.
•	§II.29. No law shall allow for any Citizen to be deprived of one's citizenship other than by a court of law; no person shall be rendered stateless in any event.
•	§II.30. No law shall allow for any person to be prosecuted for any criminal offence any later than a year since the Warrant for custody of said person was executed and the person was taken into custody; the deadline shall be renewed for any and all subsequent Warrants for custody in the event of escape and/or subsequent offence.
•	§II.31. No law shall require any person to pay excessive bail and/or fines.
•	§II.32. No law shall allow for any person to be prosecuted for any criminal offence if the only evidence incriminating him or her is testimony given by any number of agents of the Law Enforcement that is uncorroborated by any other presented physical and/or digital evidence and/or victim or third party witness testimony.
•	§II.33. No law shall allow for any person to be prosecuted for more than one criminal offence for one act or omission they committed.
•	§II.34. No law shall allow for any evidence which was obtained illegally or unconstitutionally to be admitted in the Criminal Court unless the violation of law was merely incidental to the manner in which said evidence was obtained; in any event, any person responsible for the breach of law or Constitution shall be prosecuted.
•	§II.35. No law shall deprive a defendant under prosecution of one’s right to the following:
o	§II.35(1) a speedy and public trial;
o	§II.35(2) a trial by an impartial jury;
o	§II.35(3) to be informed of criminal charges;
o	§II.35(4) to confront witnesses and to compel witnesses to appear in court;
o	§II.35(5) to be presumed innocent until proven guilty;
o	§II.35(6) to not be compelled to be a witness against oneself, or persons whose penalization one would rightfully feel as the penalization of oneself;
o	§II.35(7) to the assistance of legal counsel free of charge where appropriate;
o	§II.35(8) to the assistance of an interpreter if one does not speak the language in which the hearing is conducted, free of charge where appropriate. 

This provision will be divided into two and added to The Legislative Power and The Judicial Power parts of the document:
•	No Assembly Representative shall be precluded from taking part in any Assembly vote by virtue of being detained prior to one's trial; 
•	No judge of any Court of the Free Republic of Liberland shall be detained on suspicion of any criminal offence unless with the express consent of at least three Justices of the Supreme Court.

What do we mean by free speech zones here? Is it necessary? Could some elaborate?
•	No law shall abridge the right to assemble peacefully where no negative rights of others are infringed; all public areas within the Free Republic of Liberland shall constitute free speech zones.

Abolishing classified information altogether? 
•	No law shall deprive any Citizen of the Free Republic of Liberland of one’s right of access to information which relates to any aspect of the functioning of the Public Administration which is not classified; and no information shall be classified unless it is absolutely necessary for the purposes of national security; the affairs of the Assembly and the Supreme Court shall be video recorded and made public contemporaneously; any Assembly debate and votes or decision of any Court shall be recorded and archived and made available to the general public.

Please comment :)

**Comment by terrorist96** [comment]
This is a lot to review. I'll take a closer look at it later on and give you my thoughts.

**Comment by KacperZajc** [comment]
sure, most of the provisions are left untouched though

**Comment by terrorist96** [comment]
edits in bold:
> • §I.3. Any person in **the Public Office,** who is convicted of intentional breach of this Constitution, shall be immediately removed from the office and shall not hold any other public office in the future.

"public office" vs "the public office"
I prefer the former; If you want the latter, it needs to be capitalized. Also need comma after office.

> • §I.4. All agents of the Public Administration shall be personally liable for any loss caused by **themselves** whilst acting in their official capacity but unlawfully and/or in error.

> • §I.5. All persons staying within the territory of the Free Republic of Liberland shall be bound to observe the Constitution and **all** laws passed by the Assembly in accordance with this Constitution

> • §I.6. All administrative decisions of the Public Administration shall be subject to ~~the~~ challenge in the Civil Court by a person in whose respect it was given, or any other person who can prove one's interest in that decision.

Either that, or capitalize "challenge"; could substitute `the` with `a`.

> • §I.7. All Warrants in the Free Republic of Liberland shall be issued by a judge of the Criminal Court upon request by a member of the **L**aw **E**nforcement 
...renewed by another judge in accordance with ~~the~~ ordinary procedure.

> • §I.9. For the purposes of this Constitution**, the** term “Person” shall signify any human being whatsoever; **the** term “Individual” shall signify a person of age who does not lack mental capacity and is not incarcerated following a conviction in a court of law; **the** term “Agent of the Public Administration” shall signify **any person** working for, or contractually bound with, any body of the Public Administration; **the** term “Member of the Public Administration” shall signify anyone who is holding a public office of one of the branches of the Public Administration; **the** term “Member of the **L**aw **E**nforcement” shall signify anyone working for, or contractually bound with any law enforcement agency of the Public Administration **[since member signifies publicly held office, agent should replace member here, unless you're talking about the elected sheriff?]**; **the** term “Citizen” shall signify anyone holding the citizenship of the Free Republic of Liberland; **the** term “Resident” shall signify anyone within the jurisdiction of the Free Republic of Liberland who is not a **C**itizen.

I think we need to capitalize anything that is defined in the rest of the constitution too. Person, Member, Agent should always be capitalized. So does `person` include groups and corporations? And what about `legal person`?
Also, "or contractually bound with..." - this could lump in businesses that have contractual relationships with law enforcement (like a software provider, etc)

> • §II.2. No law shall deprive any individual of one’s right to exclude from their property any person whatsoever including a member of the law enforcement where acting without a Warrant **[and any other person acting without an appropriate order of a court of law]**; anything found in the ground under one’s land shall belong to **oneself**; such land shall be constructed to extend to **reasonable height**.

Removing this section disallows for bounty hunters or Citizen arrests. I'd prefer keeping it.
No new Burj Khalifa?


> • §II.12. No law shall abridge the right of self-defence and/or defence of one's property, the close ones and others who are under a direct threat, against initiators of aggression, including the agents of the Public Administration and members of the **L**aw **E**nforcement where acting unlawfully and/or in error.

(and all the other times `the law enforcement` is mentioned)

> No person of age shall be deprived of the right to own, manufacture, sell, transfer, transport, bear and use any small arms, arms accessories, or ammunition, be they now historic, contemporary and/or experimental, regardless of condition, **unless decided otherwise by a decision of the court where law allows it as punishment for a crime, or on medical grounds where a person would constitute a threat to others;**

Removing this section is a bit troubling to me. Why? Better change would be to say `Individual` instead of `person of age`, then jettisoning the last clause would be acceptable.

> • §II.19. No law shall allow application of torture or other cruel, unusual, or degrading treatment against any person **[against their will/without their express and informed consent]**, nor shall any experiments be done on **any** person with**out** one's **express and** informed consent, by any agent of the Public Administration or member of the law enforcement, or with consent or knowledge thereof; no individual shall be subjected to any medical treatment without one's express and informed consent; any person whatsoever responsible shall be held personally accountable for such a crime against human dignity, regardless of any law, policy, command or suggestion which might have been authorising such conduct.

So as to not outlaw BDSM lol. 

> • §II.20. No law shall allow for **any** individual’s privacy to be violated

> • §II.23. No law shall allow for any person to be detained without trial for more than twenty-four hours otherwise than **pursuant to** a Warrant and unless it is absolutely necessary for the protection of others or where the accused is likely to escape justice or interfere with the investigation; no detention **pursuant to** such ~~a~~ Warrant shall be longer than it is absolutely necessary to bring an accused to trial.

I thought this was the only time the meaning was in pursuit of a Warrant, not pursuant to a Warrant?

> • §II.25. No law shall allow for any person to be **[why remove detention?]** arrested, prosecuted, tried and sentenced, **[I thought `prosecuted` and `tried` were synonymous?]** without due process of law...

>• §II.29. No law shall deprive any Citizen of one’s citizenship; ~~person~~ **an individual** can be deprived of **one's** citizenship only by a court of law where **the** law allows it as a part of punishment, unless such order would render a person stateless.

> • §II.33. No law shall deprive ~~the~~ **a** defendant under prosecution of one’s right to the following:
o §II.33(1) ~~to~~ a speedy and public trial;
o §II.33(2) ~~to~~ **a** trial by an impartial jury;
o §II.33(6) ~~not~~ to **not** be compelled to be a witness against **oneself**, or persons whose penalization **one** would rightfully feel as the penalization of **oneself**;

> **N**o judge of any Court of the Free Republic of Liberland shall be detained...

-

> What do we mean by free speech zones here? Is it necessary? Could some elaborate?

Free speech zone means that you are allowed to practice free speech in that area. By saying the entire public areas constitutes free speech zones, means you can't be stopped from practicing your rights.

> Abolishing classified information altogether? 

I'm still half and half. One half of me believes getting rid of the national security exception would be the principled thing to do since we have no military, but the other half feels like if we keep the exception intact, it would be easier to ratify the Constitution officially in the Assembly.

-

I have an idea: what if every time the government encroached on an individual's rights (because it will no doubt happen - government is never perfect), as restitution, the individual will have any taxes/obligations to the government waived for X number of years based on how severely their rights were infringed upon. This would be easier than awarding money to the victim, especially for a government that doesn't print currency.


Something else I noticed - you distinguish law enforcement from the PA. Wouldn't law enforcement be within the PA?

**Comment by terrorist96** [comment]
I spent way too long on that post

**Comment by KacperZajc** [comment]
I.9) Persons is a human being; legal person is a corporation 
So what is wrong with the ‘contractually bound’ formula? 
II.2) I removed court order because it would have to be included in most of the provisions, it is common sense.
II.23) let’s make it pursuant everywhere, just to be consistent, it sounds fine to me
II.25) arrest and detention is the same; prosecution and tried as well; corrected accordingly 
II.29) why individual, not person?

I adopted the rest of you suggestions

Regarding free speech zones – isn’t the obvious? On the one hand we have a provision that says that everyone can peacefully express their views, on the other we have one that guarantees that a person can be excluded from one’s property. Consequently, all public spaces remain available for people wanting to express their views.

**Comment by terrorist96** [comment]
§I.3 needs the extra comma, or remove the existing comma.

"term “Agent of the Public Administration"" still needs a 'the' preceding it.
"Law Enforcement" still needs to be capitalized everywhere. Thoughts about changing it to "Agent of the Law Enforcement" from "member"?
The issue with the wording "contractually bound" is that it is too broad and can include companies that provide services to law enforcement. I'd suggest "...anyone working for, or acting pursuant to a Warrant for the Law Enforcement". This would narrow the definition to cops and bounty hunters.

II.2 is good. Since it uses the term "member of LE" (should be changed to agent, IMO) it emcompasses the definition made previously. However, what about the "reasonable height" limitation? Since Liberland is very small, it would benefit from high-rises and skyscrapers. I'd personally like to see the next tallest building built there.

 §II.19. No law shall allow **for the** application of torture

• §II.23. Pursuant to and in pursuit of have different meanings. I thought the intent was to say that no one can be jailed unless the cop is in the process of obtaining a warrant, not that he already has one. What if he needs to jail someone for probable cause and will get a warrant afterwards? 

Arrest and detention are not the same (at least in the USA). Detention is when you are stopped by a cop and are not free to leave, but you're not being arrested (jailed). A detention is used as an investigatory stop arising from probable cause (ie getting pulled over for a traffic violation or walking down the street brandishing a weapon (not simply carrying). Arrest is when you are handcuffed and dragged to jail.

II.29 actually it should be changed to:
• §II.29. ~~No law shall deprive any Citizen of one’s citizenship;~~ **a Citizen** can be deprived of **one's** citizenship only by a court of law where **the** law allows it as a part of punishment, unless such order would render a person stateless.

It should also be reworded because the first clause contradicts the second clause. The first clause should be removed.

II.33(1) remove `to`, (2) remove `to` and add `a`, (6) `to not` instead of `not to`

Free speech zones: no, it's not obvious. In the US, there have been many instances in the past where people practicing free speech were forcibly relegated to a certain area and were forbidden from leaving that area (think presidential motorcade).
Addressing your point, this is why we need to further define what constitutes 'public area'.
Who will build the sidewalks and roads in Liberland?

**Comment by KacperZajc** [comment]
I thought we didnt allow any detention which is not arrest for 24h or pursuant to a warrant?
how do we deal with that?

**Comment by KacperZajc** [comment]
ok let's substitute agent of the LE for member;
no contractually bound;
agent of the PA encompasses agent of the LE but not the other way around;
reasonable height should be construed to mean any height which does not interfere with aviation traffic (any ideas how to qualify that?)
let's keep free speech zones then
I thought we didnt allow any detention which is not arrest for 24h or pursuant to a warrant (how do we deal with that?)

**Comment by terrorist96** [comment]
Removing "contractually bound" and not replacing it with anything allows for people not being able to capture and turn in a fugitive. Only LE/Public Prosecutor would legally be able to apprehend the fugitive because they are the only ones who can request and act upon a warrant.


> reasonable height should be construed to mean any height which does not interfere with aviation traffic (any ideas how to qualify that?)

I would ask why the need to have that qualifier? LL is very small in area, so keeping its entire airspace a no-fly zone wouldn't be such a bad thing. If we do construct an airport, it can be positioned on the border so that planes coming in will land before entering the rest of LL and planes taking off can take off and enter Croatia/Serbia airspace almost instantly, thereby avoiding the problem of tall buildings. I'm against any zoning regulations so long as people only build within the confines of their own property. (look to a city like Houston, TX for an example of no zoning laws)


> • §II.29. No law **shall** allow for any Citizen to be deprived of **one's** citizenship other~~wise~~ than by a court of law; no person shall be render**ed** stateless in any event.


regarding detention: How about something along the lines of if there's probable cause that a person has committed a crime, they can be detained, not to exceed X hours whilst the cop goes to get a warrant from a judge. And then once they get the warrant, the person can be officially charged with a crime and be freed on their recognizance (or bail if appropriate) or remained jailed if they are a flight risk, danger to others or could reasonably believed to interfere with the investigation.

**Comment by KacperZajc** [comment]
but if there is a probable cause, we have this 24h arrest, in that time they can get a warrant

**Comment by KacperZajc** [comment]
what is your idea on law for bounty haunters?

**Comment by terrorist96** [comment]
If someone is listed as a wanted fugitive, that is basically a public warrant for their capture. Anyone should be able to act on that and capture them and turn them in. Whilst doing so, that person would be acting as law enforcement. 
So just add that law enforcement includes regular cops and anyone acting upon a warrant. "...anyone working for, or acting pursuant to a Warrant for the Law Enforcement." 
Doing this would not require the extra clause in II. 2 (and any other person acting without an appropriate order of a court of law)

**Comment by KacperZajc** [comment]
"...anyone working for, or acting pursuant to a Warrant made public by the Law Enforcement or the Office of the Public Prosecutor" 

??

**Comment by terrorist96** [comment]
And yes, II.22 covers probable cause arrest. I think I may have misread it. So basically you can be arrested for probable cause and can only be kept jailed for more than 24 hours if within that time, the cop gets a warrant and charges you.

**Comment by KacperZajc** [comment]
that's correct :)
so we dont have any 'detention'

**Comment by terrorist96** [comment]
That wording is good. 
If we have no detention, then you will disallow cops stopping people based on articulable suspicion, correct?

**Comment by KacperZajc** [comment]
sure, only arrest upon probable cause, no obligation to show ID or detention of random people

**Comment by terrorist96** [comment]
Sounds good

**Comment by terrorist96** [comment]
I'm starting to think that I should eliminate "express and" prior to "informed consent". Informed consent is express consent + general knowledge/extra info thereof.

**Comment by KacperZajc** [comment]
express isn't necessarily informed

**Comment by terrorist96** [comment]
That's correct. Express isn't informed, but informed is express (plus info). I'm not saying remove "express" in sections where it doesn't mention informed.

**Comment by KacperZajc** [comment]
possibly, tbh I dont think it matters :)

**Comment by terrorist96** [comment]
That's fine :stuck_out_tongue: 
Just a little clean up

**Comment by liberlandcitizen** [comment]
<<What do we mean by free speech zones here? Is it necessary? Could some elaborate?>>

The problem in many countries is that you aren't allowed to protest/assemble without getting permission first.  And in some countries they put you in pens and only "permit" you to protest in that specified area.  

I am fine with how it is written (that everywhere is a free speech zone) but if you want to change it to something like: you have the right to assemble/protest without a permit and that the government can't dictate where you must assemble.  

<<Abolishing classified information altogether?>>

Citizens should have a right to privacy - but governments should have no such protections.  We should balance the right of citizens to keep their private information private (how much they make, how they voted, how they are registered, etc.) but government info should be public.  

As it is currently written - "unless absolutely necessary" think how easy it will be for corrupt governments to declare something necessary.  I'd like us to limit it as much as possible.
