### ISSUE TITLE
Rights of foreigners

### ISSUE THREAD

**Issue by Jean-LouisMesic** [liberland/constitution#176]
I don't believe we have affirmed well enough the rights of non-Liberland citizens in relation to our agents.

Currently, the wording of our document refers to all persons under the jurisdiction of the PA. Technically, foreigners are outside of the jurisdiction of Liberland. Additionally, "within the borders of LL" is also far too weak, as it does not cover people associating with embassies.

I'm not sure if any of you have ever seen "The Bourne Identity," but if you haven't noticed, there is a scene where embassy officers end up pursuing a foreigner through the streets of Paris. The foreigner is technically not within their jurisdiction, but clearly committed some crimes against that embassy. The embassy police should be allowed to arrest, but the detained subject should be entitled to the same rights as any other person.

Our embassy/border police should have to get warrants to act just like our normal agents do, whether they are operating within our borders, or under our jurisdiction, or acting on foreign soil in the interest of the PA with consent of the foreign government.

**Comment by terrorist96** [comment]
If Liberland agents in embassies in foreign counties are faced with the unlikely situation where they have to arrest someone, they can do so within the embassy and Liberland jurisdiction would still apply. If they have to chase them down the street, then they call in for help from the country they are in, since they have jurisdiction. The prisoner could then be transported to the embassy to face the charge or extradited into Liberland. Please point out any loopholes you see. :smile:

**Comment by Jean-LouisMesic** [comment]
Foreigners are not explicitly protected, thus they are not subject to habeus corpus, for example. Simply adding foreigners to the definition of person would fix any and all loopholes.

**Comment by terrorist96** [comment]
I would dare ask why foreigners deserve our constitutional protection. Citizens are already covered, people visiting an embassy and while within the mainland are covered. Who else deserves protection?

> Our embassy/border police should have to get warrants to act just like our normal agents do, whether they are operating within our borders, or under our jurisdiction, or acting on foreign soil in the interest of the PA with consent of the foreign government.

I believe they would be under the PA definition, so the constitution applies to embassies, etc.

**Comment by Jean-LouisMesic** [comment]
Why do foreigners deserve our protection?

I'm going to pose a hypothetical situation here, and am going to have to make a few assumptions. Let's say you're an American. Russia has an embassy in America. Naturally, this embassy has armed guards. You are walking down the street, near the embassy, when you are captured and detained by strange armed men who refuse to speak with you. They torture you and force you to confess to bogus crimes. You are executed without trial for crimes you did not commit. They go on to seize the assets of your estate and search through your belongings for other incriminating evidence, eventually implicating your family in other crimes. The American government failed to protect you from these Russian agents, but they retaliate militarily. America and Russia go to war over human rights violations.

Without constitutional protection, agents of the public administration could hypothetically do this to foreigners. There is no valid reason for this ability, only that we have not yet extended this protection to foreigners.

This is an intense PR issue, as if we allow the possibility of the PA abusing foreigners, how are we to expect to be recognized as a state?

**Comment by terrorist96** [comment]
But like I said, the Constitution apples to all agents of the PA, and if a foreigner is abducted by an agent, then that puts them under liberland jurisdiction. Am I wrong in assuming this?

**Comment by Jean-LouisMesic** [comment]
I don't think so, that's why American police can't arrest people outside of their jurisdiction, or if they do, they are transferred back to the jurisdiction in which the arrest occurred.

**Comment by terrorist96** [comment]
Let's see what @KacperZajc thinks.

**Comment by KacperZajc** [comment]
so -

a foreigner visiting Liberland is subject to our jurisdiction

the question is whether our official acting outside of Liberland in respect of a foreigner is subject to our Constitution?

question of interpretation, we can qualify :)
