### ISSUE TITLE
classified information

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#178]
let's make it more demanding:

No law shall deprive any Citizen of the Free Republic of Liberland of one’s right of access to information which relates to any aspect of the functioning of the Public Administration which is not classified; information shall be classified by a responsible Secretary of State with the permission of 2/3 of all Assembly Representatives as discussed in camera, and for the purposes of national security only, and for the period not exceeding one year; any other Assembly debate and vote, or decision of any Court shall be recorded and archived and made available to the general public; the affairs of the Assembly and the Supreme Court shall be video recorded and made public contemporaneously.

any comments?

**Comment by terrorist96** [comment]
"for **a** period not exceeding..." 
The rest looks good.
