### ISSUE TITLE
sorting out freedom of expression

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#179]
Regarding expression:

No law shall abridge the freedom of thought and religion, and expression thereof so long as no negative rights of others are infringed; no person shall have the right to be protected from opinions of others where expressed peacefully; no law shall law promote or hinder any religion, gender or specific community.

Regarding publication and gag orders:

No law shall regulate any printed materials, radio, television, the Internet or any other medium of exchange of information; no law shall regulate the rules concerning uploading, transmitting, displaying, accessing and/or publishing such information; nor shall any law introduce licensing and/or registration to infringe upon these rights; nothing in this provision shall prevent the Assembly from regulating the rules concerning protection of sources used by journalists, accessing information without the consent of the rightful owners, protection of minors and vulnerable parties to a trial in a court of law.

Comments?

**Comment by terrorist96** [comment]
Nothing jumps out at me for the first one. As for the second one, I appreciate you adding that last part, but does this sufficiently prevent gag orders? Here's a perfect example of a recent gag order: the government asked Reason.com to give up the information for some commenters on an article and then obtained a gag order so Reason couldn't even discuss the fact that they had received a subpoena. Another example is national security letters that force libraries and other institutions to give up information about their customers and prevents them from even informing the people being investigated that their information was given to the government.

**Comment by terrorist96** [comment]
I feel like II.7 and 8 should be merged into one provision.

**Comment by KacperZajc** [comment]
Id leave them separate

**Comment by terrorist96** [comment]
Any comment about the gag orders?

**Comment by KacperZajc** [comment]
what do you mean?
I added "vulnerable parties to a trial in a court of law" (see above) to allow certain gag orders, do you want to qualify that?

**Comment by terrorist96** [comment]
It allows certain gag orders, but I don't see anything expressly forbidding abusive gag orders. I'm just very sceptical of government and if it's not expressly forbidden, they will try to wiggle around the provisions.

**Comment by KacperZajc** [comment]
ok I'll open a new issue

**Comment by FellowTraveler** [comment]
_No law shall abridge the freedom of thought and religion, and expression thereof so long as no negative rights of others are infringed;_

How could the negative rights of others be infringed by freedom of thought?

As for religion, it makes sense. (A religion might choose, for example, to kill a person. So in that case, the free practice of religion should be restricted to areas where negative rights of others are not infringed.)

TYPO: _no law shall law promote or hinder any religion_  <== No law shall law?

All the rest looks good to me.
