### ISSUE TITLE
constitutional changes

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#18]
list of changes;
Preamble - I didnt change anything (dont know why it shows)
Article 1 §10 - only change of wording 
Article 1 §12 - removed the right to decalre war
Article 1 §13  - added the right to block the financial bill in referendum 
Article 1 §18-19 - added the right of the supreme court to check the constitutionality of the bill before it becomes a law
Article 2 §4 - no army
Article 3 §4 - justices of the supreme court are appointed by the chancellor but upon the recommendation of the independent judicial committee
Article 3 §5 - Justices can be removed by people in referendum
Article 3 §10 - added the right of the supreme court to check the constitutionality of the bill before it becomes a law
Bill of Rights §3 - removal from office for breach of constitution 
Bill of Rights §6-7 - too broad might block any legislation whatsoever
Bill of Rights §15 - removed due to possible conflict with important international agreements 
Bill of Rights §17 - rephrased and added at the very bottom
Bill of Rights §26 - removed because it would make impossible to give a fine etc
Bill of Rights §28 - Vit said we want to extradite people who behave badly
Bill of Rights §35-6 - added further restrictions

**Comment by rotilho** [comment]
It would be great to see these changes in individual commits

**Comment by burningtree** [comment]
@rotilho It's in the past, let's focus on the future. Every changes from now will be in individual commits.

**Comment by joshmh** [comment]
+1 Even better would be individual pull requests, with a comment period of a few days, at least.
