### ISSUE TITLE
% of population

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#186]
How will the government determine the population (thus knowing how much = 3% or 10% for purposes of the constitution) if it cannot apply a number to everyone?

**Comment by KacperZajc** [comment]
1) It can go from door to door and count.
2) it can use Citizen register - list of names of citizens which will exist in any event for Jury purposes and General Election.

**Comment by terrorist96** [comment]
#1 would be very expensive if they have to do that every time for a referendum. 
#2 makes sense, but only if the wording of the Constitution is changed to say citizens instead of population

**Comment by KacperZajc** [comment]
I think in fact it should because only citizens should be able to vote in a referendum

**Comment by terrorist96** [comment]
Side issue: will Citizens be automatically registered to vote? I feel as voting registration should be automatic upon issuance of Citizenship. [it'd probably be more cost effective for such a frugal government]. What do you think?

**Comment by KacperZajc** [comment]
I think no, because registration entails number and jury service so it should be optional.

**Comment by terrorist96** [comment]
Citizenship requires number too, doesn't it?

**Comment by terrorist96** [comment]
No answer?
@KacperZajc

**Comment by KacperZajc** [comment]
I dont know whether the citizenship itself requires a number; registration for voting etc does, but this is voluntary so no problem here

**Comment by terrorist96** [comment]
Citizenship is optional too. How can one be a citizen without a number? Citizens are issued passports, right? How can we determine someone is a citizen or not if they aren't issued a number?

**Comment by KacperZajc** [comment]
We can issue certificates of citizenship without numbers and passports upon request. Really, doest matter to me, just an idea :)

**Comment by terrorist96** [comment]
A passport without a unique number is very dangerous. Can be more easily counterfeited, whereas if it requires a number, that number can be checked in the government database to make sure the passport is legitimate. I just think that Citizenship should require a number, and also automatically registers you to vote, obtain passport, etc. People who don't want a number can just be residents.

**Comment by KacperZajc** [comment]
I meant certificates without number that only evidence the citizenship and normal passports upon request.
But I dont mind your idea, it's not my call anyway :)

**Comment by terrorist96** [comment]
> I meant certificates without number that only evidence the citizenship

The same logic applies. How can the legitimacy of the citizenship certificate be verified?
Whose call is it? Vit's? Why doesn't he post here and share his thoughts? :smile:

**Comment by KacperZajc** [comment]
yeah citizenships issues is Vit's prerogative, he is busy and not really a lawyer

**Comment by terrorist96** [comment]
I'm not a lawyer either. :stuck_out_tongue_closed_eyes:

**Comment by KacperZajc** [comment]
@terrorist96 btw you've been of tremendous help here, we are trying to launch a think-tank, please contact me if you are interested: justice@liberland.org

**Comment by terrorist96** [comment]
Email sent!
