### ISSUE TITLE
new provisions

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#187]
No law shall allow for war to be declared by any branch of the Public Administration on any Nation or group; no standing army shall be established; should any voluntary territorial defence rise, it shall not be used outside the territory of the Free Republic of Liberland.

No law shall introduce any state of emergency or war, or any other special state in which one or more of the Rights guaranteed by this Constitution would be suspended or revoked.

**Comment by terrorist96** [comment]
What about declaring war on a group (ISIS/al Qaeda)? 

"one or more Rights"

**Comment by liberlandcitizen** [comment]
Make it any nation or group, or we'll be at war against ISIS or Pirates.  But otherwise this is beautiful.

**Comment by KacperZajc** [comment]
ok

**Comment by terrorist96** [comment]
> Rights guaranteed by this Constitution would be suspended or revoked.

They could get around this by hampering the right instead of outright revocation.
