### ISSUE TITLE
Unanimous votes in the legislature

### ISSUE THREAD

**Issue by lunokhod** [liberland/constitution#189]
There are two types of votes in the legislature that require unanimous support with all representatives being present: **constitutional amendments** and **taxation bills**.

I worry that unanimity might be too high of a bar to pass such legislation in reality. How many constitutional amendments have passed *anywhere* with unanimous support? And in your own political party of like-minded individuals, how many motions ever pass with unanimous support? Any such law could thus be killed either by one person not being present, or by one person voting against. I can easily picture the situation where one member of the legislature might refuse to vote on any law. Given that legislative terms are for four years, any such person would put all constitutional and tax matters on hold until the end of their term.

The question is: *What percentage of votes should be in favor to pass such laws?* This is obviously subjective. I would like to propose for discussion a number that is commonly used in the sciences: 95%. This number corresponds to "2-sigma"  of a normal Gaussian distribution, where it is nearly universally accepted that an event that occurs with 95% probability is significant. 

For a 20 person legislature, 95% corresponds to 19 votes. I would thus propose that such laws be passed by 19 or more votes, regardless of whether all people are present.

**Comment by terrorist96** [comment]
I'm not unopposed.

**Comment by liberlandcitizen** [comment]
I'm strongly opposed to this change.  Clearly the goal of the Liberland Constitution is to limit government's power and influence over everyday life.  Our goal should make it as difficult to stray from the constitution and add taxes as possible.  Yes, this is perhaps radical but with 190+ countries on earth with big, powerful governments we need to make sure there is one place where government is weak.

**Comment by lunokhod** [comment]
It is possible to make it even more difficult to pass amendments and tax bills if you think this is required. For example, the draft constitution says

> * §III.18. Any Taxation Bill or Constitutional Bill shall be subject to the mandatory referendum to take place within ninety days after the Bill was passed by the Assembly.
 * §III.18(1) The Bill shall be deemed to be vetoed unless a majority of two-thirds of all those taking part in a referendum vote 'Aye'.

You could hence change 2/3 to something larger (like 3/4, 100%, or 95%)

Thus, could you explain why the current criteria in the draft constitution are the best (unanimity in the legislature and 2/3 in favor in a subsequent referendum), and why it should not be made harder, or easier, to pass such bills?

**Comment by KacperZajc** [comment]
@lunokhod what you are saying here makes sense, however, we keep it as it is now and get back to it when we discuss the overall number of Assembly Representatives. President personally requested it to be 20 but it is likely to change in the future.
