### ISSUE TITLE
Sanctions for bad law proposals

### ISSUE THREAD

**Issue by fare** [liberland/constitution#19]
If there is no sanction for people proposing bad laws, then they can keep proposing them until they are voted in. The late Athenian democracy had to institute rules punishing people who proposed bad laws.

**Comment by KacperZajc** [comment]
impossible to put into practice, sorry

**Comment by Zephram-C** [comment]
What is a bad law? We have general right of veto by the Citizens.
Currently: §13(1)  Any Bill vetoed by the Citizens in the referendum shall be considered void and shall not be revived for at least a year.
This seems good enough mechanism. Maybe a year is too long, maybe too short. But *forever* would be too long. Situation and priorities can change and bad law can become good law. Law conflicting with constitution are irrelevant anyway.

**Comment by fare** [comment]
In Athens, if the vote gathered fewer than 25% of ballots or so, its promoter was fined.

If we further require all laws to include a budget limit, the fine could be made proportional to the required budget.

**Comment by tinkyholloway** [comment]
I don't like the idea of the state punishing people. In this case however only the Cabinet can initiate legislation on which the Assembly needs to pass before allowing citizen veto. I'd be happy to keep the Assembly tied up debating and rejecting crap laws. The Assembly has the power to remove Cabinent members so I would see this as good enough feedback on low quality legislation being introduced.

Athens, I assume, was a direct democracy where the population could introduce legislation. The proposed C of Liberland is quite different (fortunately).

**Comment by KacperZajc** [comment]
I agree with @tinkyholloway
