### ISSUE TITLE
§V.6. The Supreme Court shall be presided over by...

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#190]
§V.6. The Supreme Court shall be presided over by the Chief Justice of the Supreme Court, and shall be composed of him or her and four other Judges called the Justices of the Supreme Court.

We need to reword this so as to eliminate the gender references.

**Comment by yopdog** [comment]
§V.6. The Supreme Court shall be presided over by the Chief Justice of the Supreme Court, and shall be composed of the Chief Justice four other Judges called the Justices of the Supreme Court.

?

**Comment by terrorist96** [comment]
That works, but the wording is redundant. I guess it can't be avoided unless we reword the whole thing. 

There needs to be an 'and'  prior to 'four'.
