### ISSUE TITLE
2/3 of the legislature = 13.33333 persons

### ISSUE THREAD

**Issue by lunokhod** [liberland/constitution#192]
The draft constitution states

> §III.2(1) The resolution shall be passed with a majority of two-thirds of all Assembly Representatives.

2/3 of 20 assembly members equals 13.33333333 people. I presume that this means that you need 14 votes to pass.

I propose to either 
* replace 2/3 with 14, or
* use 7/10, which is exactly 14 people.

I would also like to note that the draft constitution makes reference to 3/4 of the assembly, which is 15 people. Thus, 2/3 and 3/4 differs only by 1 person. In my opinion, all references to 2/3 and 3/4 should be revisited in this light. Perhaps all references to 2/3 and 3/4 could be replaced with a single number.

**Comment by terrorist96** [comment]
I'm against this change because the number of Representatives could change in the future. Though since they explicitly stated that we will have 20 Representatives, it's a moot point. If they were to amend the number of Representatives in the future, we'd have to edit those thresholds too.

**Comment by Jean-LouisMesic** [comment]
Why not just say 2/3 rounded up? We made it a fraction in case we upped the number of representatives in the future.

**Comment by lunokhod** [comment]
So, to summarize: we should keep 2/3 and 3/4 only because the constitution *might* be amended in the future, and if it was amended we would need to change about three numbers instead of just one.

If you look at this thread (https://github.com/liberland/constitution/issues/189) it seems unlikely to me that the constitution will ever be amended after it is ratified. I think it is would be best to work under the hypothesis that the number 20 will be with us for many decades to come.

**Comment by Jean-LouisMesic** [comment]
To live under 20 representatives with over 300,000 citizens is just retarded, and we have all agreed upon that fact. We should enumerate this in the Constitution. We should stick with 20 representatives up until we hit 100,000 citizens, and then add one every time there are more than 5,000 constituents per representative.

**Comment by lunokhod** [comment]
I'm in favor of setting the number of representatives based on population. 1 per 5000 seems reasonable to me.

**Comment by Jean-LouisMesic** [comment]
I'd also be cool with 1 per 5,000 after we hit 100,000 inhabitants.

**Comment by KacperZajc** [comment]
it is 20 for now, we'll see how it goes later
