### ISSUE TITLE
Should the constitution explicitly ban idiotic provisions from appearing in the Annual Budget?

### ISSUE THREAD

**Issue by lunokhod** [liberland/constitution#193]
In section III.16 of the draft constitution, the legislature is excluded from using tax revenue for four specific purposes. I believe that one of these is without doubt appropriate for the constitution:

>   * **§III.16(3)** No provision of the Annual Budget shall provide for:
    * **§III.16(3)(c)** funding or partial funding of any political party;

However, the rational for including the other three is less clear, in my opinion. 
    
>   * **§III.16(3)** No provision of the Annual Budget shall provide for:
    * **§IV.16(3)(a)** any investment that would be designed mainly to boost the economy and/or create employment and/or maintain employment; nor for acquiring any property by the Public Administration for purposes other than recognised by this Constitution;
    * **§III.16(3)(b)** any form of direct and/or indirect bail out of any legal and/or natural person;
    * **§III.16(3)(d)** funding or partial funding of any form of healthcare and/or education services, and/or pension schemes.

I do not want to debate whether the government should fund these activities or not: rather, the question is whether the constitution should outright ban these provisions, or if the citizens of Liberland and their representatives in the legislature should have the liberty to decide for themselves. If such bills were proposed, they would almost certainly not survive the vote in the Legislature, and if they did, they would be subject to a referendum.

Besides limiting the liberty of Liberland citizens, it is my opinion that there are two additional problems with this list. First, rare punctual exceptions to at least some of these rules could likely be found to be acceptable and necessary, but perhaps distasteful. Second, if one determines that these exceptions should be in the constitution, why not add a very large number of other exceptions outlawing other specific idiocies and hypothetical situations?

**Comment by terrorist96** [comment]
I think they're in the wrong section to begin with. Should be moved to the legislative restrictions section.

**Comment by liberlandcitizen** [comment]
Giving the "people" through the elected officials the power to steal money out of the pockets of their fellow citizens is not my definition of liberty.  Our goal is to be a libertarian nation, the only one on earth.  

If the people want to bail out a country of a company.....if the people want to pay for a healthcare system....if the people want to improve the economy they have the liberty to do so through the free market.  

The beauty of this constitution is that it limits the power of government.  Why is it important to write so much of this into the constitution?  Because politicians (who have to win elections) like to hand out things to the people like it's candy....candy paid for by stealing from the productivity of others.  

Yes, we have to keep things like this in the constitution and limit the power of government in Liberland forever.

**Comment by KacperZajc** [comment]
@liberlandcitizen well said :)

**Comment by lunokhod** [comment]
But aren't the sections I note above **already** banned by section III.5, and doesn't the court need to unanimously approve all laws as being constitutional (section III.21)? 

To make the point as simple as possible: *Should the legislature be allowed to knowingly propose an unconstitutional law?*

In my opinion, they should be able to do so, even if it is a waste of everyone's time.

**Comment by KacperZajc** [comment]
the US Constitution doesnt allow for employment boost spending but it happens anyway; we want to be double sure

**Comment by lunokhod** [comment]
But the US constitution does not require the entire supreme court to approve unanimously every single law as being constitutional. I don't think the comparison is valid.

**Comment by liberlandcitizen** [comment]
The writers of the US constitution wrote in the words that the legislator has the power to do all that is "necessary and proper" which was later interpreted by the Supreme Court that the legislator could write any laws that they wanted.  Basically the US constitution has been twisted every which way to allow big government to flourish.   

That is why we have to put in as many protections as possible to keep that from happening again.

**Comment by liberlandcitizen** [comment]
I'll just add that ultimately a nation is doomed if people in power are unwilling to follow the rule book, no matter how many protections you put in.  But learn from history and be as clear about your intentions as possible and then at least those people in power will look much worse when they violate the constitution.

**Comment by terrorist96** [comment]
In case you haven't noticed, the draft constitution has a necessary and proper clause as well :P

**Comment by liberlandcitizen** [comment]
Does it really?  Where and what is the context?

**Comment by terrorist96** [comment]
§III.5(6) to make such laws as shall be necessary for carrying into execution the powers vested by this Constitution in the Assembly provided that no law imposes greater restrictions on the people than absolutely necessary for the attainment of the end;

**Comment by liberlandcitizen** [comment]
All the more reason why we have to limit the scope of their legislative powers.

**Comment by KacperZajc** [comment]
the more limitations, the better
