### ISSUE TITLE
data protection

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#195]
§II.XX All data collected by the Public Administration shall be used only for the direct and necessary purposes for which it was originally collected, and shall be kept confidential and shared only with the express and informed consent of the rightful owner or otherwise in accordance with the provisions of this Constitution; all Individuals whose data is stored by any body of the Public Administration other than the Law Enforcement shall have access to it and shall retain the right to demand it is destroyed at any time.

I had to keep a window open for the police to be able to gather information on suspects etc.

**Comment by terrorist96** [comment]
Very nice

**Comment by lunokhod** [comment]
This section allows the PA to store information about individuals without their consent. Is that a good idea? It seems that you are placing the burden on the individual to continually ask the PA what is in their file.

**Comment by KacperZajc** [comment]
@lunokhod see #188 for your concern
