### ISSUE TITLE
medical treatment without consent

### ISSUE THREAD

**Issue by lunokhod** [liberland/constitution#196]
I agree with the sentiment of this provision

> §II.19. ...no Individual shall be subjected to any medical treatment without one's express and informed consent;

but what do you do in the case where an individual is found unconscious and bleeding, and a reasonable medically trained person believes that the individual's life is in immediate danger? Will it be possible to attempt to save the life of the individual by performing medical treatment without their consent? For the sake of argument, let us assume that they were found without identifying papers, and it is thus impossible to get consent from a family member.

**Comment by KacperZajc** [comment]
doctrine of necessity applies, this is implicit

**Comment by lunokhod** [comment]
Perhaps we should make it explicit to avoid problems of interpretation.

**Comment by terrorist96** [comment]
"express and informed consent" allows for no wiggle room in this regard. @lunokhod is right, we need to amend this. I suggest 
> no Individual shall be subjected to any medical treatment without one's express and informed consent absent exigent circumstances.

**Comment by yopdog** [comment]
Can people be charged for medical treatment given in exigent circumstances?

**Comment by KacperZajc** [comment]
no Individual shall be subjected to any medical treatment without one's express and informed consent absent exigent circumstances where an Individual is incapable of consenting.

??

**Comment by terrorist96** [comment]
:+1:

**Comment by yopdog** [comment]
>no Individual shall be subjected to any medical treatment without one's express and informed consent absent exigent circumstances where an Individual is incapable of consenting.
 
Seems fine to me.

**Comment by terrorist96** [comment]
Just to be clear, we're exempting children and the insane and criminals from being able to refuse medical treatment?

**Comment by KacperZajc** [comment]
we do that because there are circumstances where parents refuse treatment on behalf of their child because of their religion and it leads to child's death, clearly we dont want that
this will be all clarified by ordinary law

**Comment by terrorist96** [comment]
> parents refuse treatment on behalf of their child because of their religion and it leads to child's death, clearly we dont want that

Wouldn't this interfere with the freedom of religion? I know some religions forbid blood transfusions, and that's ok for a person of age, but we don't want to grant the same right to refuse a blood transfusion to a 17 year old?

**Comment by KacperZajc** [comment]
There are number of options how to deal with it:
- can set the majority age at 17 or 16
- can legislate that 16 and 17 year-olds can refuse even if minors

The point is to prevent parents killing their children on the grounds of their religion. Here we have rights  of others so the freedom of religion of parents is subject to the right to live of their children.

**Comment by terrorist96** [comment]
This could also be used for forced vaccinations of kids. That's contrary to freedom.

**Comment by KacperZajc** [comment]
again rights of others - a child who has not been vaccinated can be dangerous to other people, it's very controversial but small issue, can be regulated by ordinary law, we just make it possible both ways

**Comment by terrorist96** [comment]
What about eugenics? It's a medical procedure that sterilizes the person from reproducing. Or a lobotomy for autistic kids. These would all be possible without the child's/parent's consent.

**Comment by yopdog** [comment]
@terrorist96 I agree with you. We definitely need to make some changes to protect the rights of non-Individuals. 

@KacperZajc I suggest you reopen this issue.

**Comment by KacperZajc** [comment]
obviously it will be regulated but only by ordinary laws, we cant put everything in the constitution

**Comment by yopdog** [comment]
Yes, but the constitution must address the rights of non-Individuals. Children are humans in every sense of the word and deserve to have their rights protected in the constitution. Leaving this to be decided by ordinary laws is to say that the rights of children and disabled people are of lesser importance to those of Individuals.
