### ISSUE TITLE
Allow currency issue by the PA, but not central banks.

### ISSUE THREAD

**Issue by lunokhod** [liberland/constitution#197]
I would like to propose that we allow (but not require) the PA to issue currency, that this currency be considered legal tender for the sole purpose of paying taxes, and that the use of this currency will never be required for any situation. For the purpose of the constitution, this could be achieved by removing the sole phrase **or currency issue** from the following section:

> * **§II.11.** No law shall abridge the right to use or issue any commodity or item as currency unless either party to the transaction is legally prohibited to possess such item or commodity; nor shall the Public Administration engage in any form of monetary regulation or currency issue; nor shall it establish any Central Bank.

Abolishing privately run central banks will solve almost all of the problems that modern states are having, and to motivate my argument, I start by quoting Thomas Jefferson

> “If the American people ever allow private banks to control the issue of their currency, first by inflation, then by deflation, the banks…will deprive the people of all property until their children wake-up homeless on the continent their fathers conquered…. The issuing power should be taken from the banks and restored to the people, to whom it properly belongs.” – Thomas Jefferson in the debate over the Re-charter of the Bank Bill (1809)

The problem is that all currency today is created by private central banks, the government borrows this money from the central bank by the creation of bonds that require them to repay the loan with interest, but the central bank does not create the interest that is required to pay back the loan. Thus, the government is required to "steal" the interest form others if they want to meet their obligations. As all money is created as debt with interest, and as interest grows exponentially with time, the system will inevitably collapse.

I will give a simple example of how PA issued currency would work in practice: Let us say that the PA wants to create a building to house the three branches of government. Tax revenue is insufficient to pay for this infrastructure, and crowdfunding only raised a small fraction of the real cost. The PA could do the following:

1. It issues 100,000 Liberland Notes, and offers these to any private company who is willing to accept this means of payment for the construction of the building.
2. As the Liberland Notes are legal tender, the private company can use these to pay their taxes. As they are legal tender, other people in Liberland may decide to accept these for payment given that they can also pay their taxes with these.
3. After a sufficient amount of time, all of the Liberland Notes that were created for the unique purpose of making a government building will be returned to the PA via taxes. At this point, the PA is happy because they have a new building, and the company who built it is happy because the Liberland Notes had for them intrinsic value.

I do not believe that Liberland should attempt any form of monetary policy, and thus I propose leaving the original language intact, with the sole exception of removing the three words **or currency issue**. If required, a new phrase could be added stating something like "Any currency that might be issued by the PA will be considered legal tender for the sole purpose of paying taxes."

**Comment by liberlandcitizen** [comment]
I have a simple solution to the tax problem - let's honor the President's pledge to have all taxes voluntary only - get rid of the language that allows for taxes and only accept donations in any currency like an international charity would.  

Back to the topic of hand, I disagree that all money is created by a central bank.  Bitcoin has no central bank.  Gold and silver are money, and do not come from a central bank.  The people will be free to create their own currencies in addition to fiat from other nations being used.  

Remember, we want to create a new kind of state here...things are going to be different from everywhere else.  Already at the LSA base camp people are buying and selling things using a number of different currencies.  People around the world are finding a way to donate to both the LSA and Liberland too using many different currencies.  People can take care of themselves - don't worry :)

**Comment by KacperZajc** [comment]
definitely no official currency

**Comment by lunokhod** [comment]
Does that mean you are not in favor of the PA issuing currency, such as in the example I provided, or that any currency issued by the PA would not be the official currency of Liberland?

**Comment by KacperZajc** [comment]
I oppose issuing any currency. It's a slippery slope.

**Comment by terrorist96** [comment]
I like the concept but I also agree with it being a slippery slope. I feel like this is more apt for discussion and debate amongst the first assembly.

**Comment by liberlandcitizen** [comment]
No, if the constitution doesn't forbid it, then eventually it's very likely there will be a central bank someday down the line...and with it the bankers who want to control everything.  Let the people decide which currency to use - there are plenty of choices out there.

**Comment by lunokhod** [comment]
@liberlandcitizen - The proposal **is** to forbid central banks in the constitution. Please re-read what I wrote. You do not need central banks (which are private entities) to issue currency. The proposal also is not to decide which currency people should use.

@terrorist96  Nothing will be debated at the first assembly. Now is the time to do it:

> §12. The Committee shall prepare a draft of the Constitution of the Free Republic of Liberland which the Assembly shall approve with ‘aye’ or reject with ‘nay’ with a simple majority, on its first meeting after the first General Election.

**Comment by KacperZajc** [comment]
I oppose any relaxation of this provision. As I said, it's slippery slope.

**Comment by terrorist96** [comment]
That's interesting how only a simple majority is required to ratify the Constitution but unanimous required for amending it.

**Comment by FellowTraveler** [comment]
Just pointing out that the government can mandate taxes to be paid in a specific currency, without being the ISSUER of that currency.

For example, the Liberland government might require the taxes to be paid in gold or Bitcoin, or dollars, or euros, or whatever -- even though the Liberland government is not the issuer of any of those currencies.

**Comment by lunokhod** [comment]
But if Liberland decides to mandate taxes being paid in euros, they have in essence delegated currency creation to a third party (the private ECB).
