### ISSUE TITLE
Being charged with a crime 

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#198]
No law shall allow for being charged with a crime by proxy. 

This prevents tickets in the mail by a speed/red-light camera. Requires a person to be served/arrested/cited directly by a cop in person. Thoughts?

**Comment by yopdog** [comment]
What's the problem with sending a person a letter? Sounds like a great why to make law enforcement more expensive.

**Comment by lunokhod** [comment]
One potential problem with sending this by letter is this provision:

> §II.18. ...all Individuals whose data is stored by any body of the Public Administration other than the Law Enforcement shall have access to it and shall retain the right to demand it is destroyed at any time.

If the individual demands that the PA destroy all their individual data (the wording is not clear if the PA needs to comply....) then Law enforcement will not have access to their address.

**Comment by yopdog** [comment]
>any body of the Public Administration OTHER than the Law Enforcement

The provision clearly makes an exception for data collected by Law Enforcement.

**Comment by lunokhod** [comment]
But how will Law Enforcement obtain this address? They could ask the PA to look in their records, but if the Individual asked the PA to remove their address, the PA would have nothing to give. 

What you seem to be proposing is that there are certain types of data (Name, address, date of birth, photo, and other unique identifying information) that can not be deleted from the PA database. If this is the case, then this should be explicitly noted in the constitution.  For example, one might add

> The PA has the right to retain data about an Individual only for the purpose of identify this person as a Liberland citizen.

A subsequent law, not in the constitution, would provide more explicit guidance concerning what is allowable, and how these entries might be changed, etc.

**Comment by yopdog** [comment]
There are many ways in which law enforcement can obtain information on a person. If they want to know where he lives, they just follow him back home. If they want to know who he is or where he works, they just check his Facebook or Linkedin account or ask people to identify him by a picture.

**Comment by KacperZajc** [comment]
I think sending a letter should be allowed;
When it comes tickets in the mail by a speed/red-light camera I agree this should not be allowed HOWEVER at this point we dont know whether roads will be public or private so I dont want to make any rules regarding traffic.

**Comment by terrorist96** [comment]
Roads need to be public, otherwise people could exclude certain groups from using roads, which would impinge of their freedom to travel.

**Comment by KacperZajc** [comment]
Im with you but it's not my call.

**Comment by yopdog** [comment]
>Roads need to be public, otherwise people could exclude certain groups from using roads, which would impinge of their freedom to
 travel.

That's ridiculous. The road has to be built first in order for people to have the 'Freedom' to travel on it. It's like saying refusing to give someone healthcare infringes on their right to be healthy.

**Comment by KacperZajc** [comment]
this debate is outside of the scope of our competences anyway

**Comment by terrorist96** [comment]
Well we can already travel by going through the grass, but it'd be hard to distinguish whether you're encroaching on someone's private property. We need to have a way to get around the country freely.

**Comment by terrorist96** [comment]
If roads are going to be privately built, we need to add an exception to the provision about regulating one's own private property.

**Comment by KacperZajc** [comment]
we dont know and that is why we dont deal with it now :)

**Comment by terrorist96** [comment]
We do know, as of right now, since there's no authority for the PA to pave roads. :stuck_out_tongue:

**Comment by yopdog** [comment]
@terrorist96 Could you explain why private roads need to be regulated?

**Comment by KacperZajc** [comment]
there is not because there is no decision about that at this moment, this is my point

**Comment by yopdog** [comment]
@KacperZajc I don't see anything in the constitution that will prevent private roads from being built.

**Comment by KacperZajc** [comment]
@terrorist96 means public roads

**Comment by yopdog** [comment]
Even if we are talking about public roads, I honestly don't understand what's so dangerous about getting a ticket in the mail?

**Comment by terrorist96** [comment]
My point was that since we allow discrimination on private property, private roads should be exempted if those roads aren't solely to lead to a private residence (ie regular public roads that's built by private people). The problem with getting a ticket in the mail is that you are presumed guilty unless you prove yourself innocent, the opposite of what it should be. You are also deprived of the right to confront your accuser. The way it is in my state currently is that you can receive tickets in the mail but legally, you can ignore them because it can't be proven that you received those tickets because it wasn't served to you by an officer of the law. I want to ban the whole concept from the start.

**Comment by yopdog** [comment]
Ok, the part with getting a ticket in the mail makes sense now. But I still don't understand what's wrong with allowing individuals to have complete control over their property. If an owner of a road want's to discriminate, he may have a good reason or he may not. Either way, he should have the right to decide
since he owns the land and he built the road. People shouldn't have their property rights diminished because they chose to share it with others, should thay?

**Comment by terrorist96** [comment]
So what if the following situation occurs:
One person manages to acquire the majority of Liberland territory and controls all the roads to get anywhere. They then decide to exclude everyone except himself and his friends from using all the roads and set up check points and cameras along the road. This is antithetical to a free society.

**Comment by yopdog** [comment]
What if someone buys up all the houses in Monaco and turns Monaco into a ghost town? These things just don't happen because there is no incentive to do them. Secondly, no one will manage to acquire the majority of Liberland's territory since they would have to compete with everyone else who wants to live in Liberland. The only way a single person could acquire the majority of land is through the force of government.

**Comment by terrorist96** [comment]
Just because it's not likely to happen doesn't mean we should allow it to.

**Comment by yopdog** [comment]
What gives us the right to stop it? The territory of Liberland will be owned by many people. If they all want to sell their land to a single person then so be it. making a law that forbids that will be imposing on the majority something they don't want. Remember, nobody will be forced to sell out if they don't want to.
