### ISSUE TITLE
upload translations of the constitution

### ISSUE THREAD

**Issue by ohadcn** [liberland/constitution#2]
The constitution isn't close yet, but some translations of it have already uploaded to the net.
it would be nice to upload them too (here and to [liberland.org](http://www.liberland.org))
Czech translation is already on [liberland.org](http://liberland.org/cz/constitution/)  Hebrew translation can be found on [my fork](https://github.com/ohadcn/liberland-constitution/tree/master/translations), and I guess more will follow.

**Comment by burningtree** [comment]
Thanks for translation! Please create Pull Request to new created https://github.com/liberland/translations repository, which now will unite translations.
