### ISSUE TITLE
Self-limiting laws

### ISSUE THREAD

**Issue by fare** [liberland/constitution#20]
Laws should include rationale and a duration limit.

Rationale: anyone can contest in court that the official rationale is not met and thereby nullify the law.

Duration limit: Ideally, every law should be renewed by every legislature after being read in its entirety. No one would be able to vote unless they had been physically present, and mentally present (no cell-phone, laptop, book, etc., allowed, except a copy of the text), for the entire duration of the reading — maybe forced to read the text aloud. Or maybe, a "yes" vote must consist in successfully dictating the entire text of the law in a public recording. Any discrepancy in the dictated text, and the vote becomes a "no".

Forcing laws to be read by legislators also ensures a limit on the total size of the code. Then is the problem of legislators delegating legislative powers to unelected bureaucracies, like they do in modern "democracies". The constitution should prevent this power grab somehow.

But really, is there any use for human laws? The recognition of private property rights is all you need.

**Comment by fare** [comment]
Requiring an explicit rationale for any law also allows for nullification if the rationale is found to be unconstitutional.

But really, why have a legislature at all? Why preserve this myth that man can make laws?

**Comment by tinkyholloway** [comment]
I like the idea of having to read the Bill aloud. Anything that makes introducing legislation burdensome is probably a good idea.

**Comment by KacperZajc** [comment]
I agree:
any Bill should be read aloud 
and it should include rationale for it
but there are not issues to be put in the Constitution, we make it through ordinary laws

**Comment by KacperZajc** [comment]
but we need Legislature to be treated seriously by other state otherwise we wont get recognised

**Comment by cpacia** [comment]
If you make that an ordinary law, they will just change it when they find it inconvenient.

**Comment by KacperZajc** [comment]
you cannot put into constitution every detail you like otherwise all laws would be written in one constitution

**Comment by cpacia** [comment]
You put in it things you want to be permanent or at least very difficult to change (high barrier to amendment). 

If you just make a law saying, "All laws will sunset". The next legislature will have no problem reversing it at the first chance they get.

**Comment by KacperZajc** [comment]
I dont think laws should be subject to sunset, I believe any Bill should be read aloud and it should include rationale for it and these requirements should be put in ordinary laws

**Comment by cpacia** [comment]
You've heard of the expression... 
>The nearest thing to eternal life we will ever see on this earth is a government program.

Bad laws are almost never repealed. This is how you end up with millions of pages of laws on the books. More than you can read through in your lifetime. 

By sun-setting them, the public get to decide if a bad law is worth renewing. This should get rid of 90% of junk from the books.

**Comment by KacperZajc** [comment]
I know, but we would make all public and criminal laws subject to that as well and we dont want to do this because these laws be stable.
Your idea would be good to include in all the other laws we will pass as a last paragraph.
Plus, the government of Liberland wont have all those functions you are afraid of so you would mainly make the necessary laws sunset.

**Comment by fare** [comment]
If the law is good, it will be read once every four years, no discussion. If the law is bad, it will disappear as people can't stand to quibble over it every four years. If every law sunsets after five years (leaving time for the next legislature to renew it), that's perfect. If it is so essential that it really needs to not sunset, amend the constitution to include it.

**Comment by fare** [comment]
This issue should probably be made into three different issues.

**Comment by tinkyholloway** [comment]
@KacperZajc not having the criminal code sunset, was one area of concern I had when I suggested sunset. Solution might be to create an exception for criminal code. Or the Assembly would have criminal code all inside a Crimes Act as some countries do, then provided the contents are reasonable, the refresh should be simple. If the contents are controversial then perhaps there is good reason they don't pass. The Assembly would have an incentive to keep the criminal code both simple and uncontroversial.

I am really concerned that unless we restrict the PA tightly, we'll have a socialist hellscape in two generations. We will not be here to protect freedom and the population that remains will forget what it ever was. Liberland may be our last chance.

**Comment by KacperZajc** [comment]
I think the way to go is to restrict the areas they can legislate on thereby making the laws passed necessary - and we dont want necessary laws to expire or change substantially every 4 years. I understand we want very few laws and I agree but we also want them stable and predictable - what kind of message do we send to our citizens if they dont know whether all laws wont change in 4 years???

**Comment by fare** [comment]
This issue has been separated into #25 (actually duplicate of #13), #26 and #27. Closing this one.
