### ISSUE TITLE
Judges treated differently before the law?

### ISSUE THREAD

**Issue by yopdog** [liberland/constitution#202]
>§V.4(3) No Judge of any Court of the Free Republic of Liberland shall be detained on suspicion of any criminal offence unless with the express consent of at least three Justices of the Supreme Court.

Why can judges be detained only with the permission of the Supreme Court? Shouldn't everyone be equal before the law, including judges?

**Comment by terrorist96** [comment]
Because a judge could be detained politically in order for the executive to influence the judicial. Same reason why representatives can't be detained (so as to stop them from voting on a bill). They can still be convicted and imprisoned upon guilt, just like everyone else.

**Comment by yopdog** [comment]
Section II.24 should prevent situations like these from occurring:

>§II.24. No law shall allow for any Person to be detained randomly or without any evidence but only under specified charges, upon probable cause and by an Agent of the Law Enforcement acting openly and informing the detainee about the rights one enjoys under this Constitution and any laws passed by the Assembly in accordance thereof.

Even if judges are arrested, I don't see how that could seriously affect judicial process since you could  just continue the case with another judge or at most delay it.

**Comment by terrorist96** [comment]
Justice delayed is justice denied. 
I'm not opposed to changing this though. Let's see what @KacperZajc thinks.

**Comment by yopdog** [comment]
One thing we could do is prevent people from being detained unless they pose an immediate danger or threaten to interfere with the investigation against them. This should prevent situations like you described ​from occurring.

**Comment by terrorist96** [comment]
I agree. Release upon one's recognizance should be the default option, or bail if necessary or remain imprisoned until trial if one poses a danger to others or would interfere with the investigation.

**Comment by lunokhod** [comment]
I have to agree with yopdod: no one should be above the law, and there should be no exceptions for public officials. In the worst case, judges could be detained by 24 hours. Concerning members of the legislature,

> §III.1(3) No Assembly Representative shall be precluded from taking part in any Assembly vote by virtue of being detained prior to one's trial.

this does mean that they can not be detained before a pending vote. Only that the legislature can not proceed with the vote while one of their members is detained.

**Comment by KacperZajc** [comment]
@terrorist96 definitely no change here;
@lunokhod this means that they are detained but nevertheless if escorted by the police, they can appear in the Assembly to vote/debate;
@yopdog there is a provision that says that a warrant for custody can be issued only if a person poses a direct threat to others or might flee the country or interfere with the investigation

**Comment by yopdog** [comment]
The provision is for when a person is detained for more than twenty-four hours. My idea was to make it so you can't detain a person for any period of time unless he poses an immediate danger to people around him. 

Having said that, can I ask why we can't make any changes here?

**Comment by KacperZajc** [comment]
24h arrest should be available even if there is no threat but the LE wants to collect evidence, get a warrant etc.

judges and assembly representatives must be protected from arrest because of the division of powers, in this way we protect them against the executive power

**Comment by yopdog** [comment]
If the LE wants to question a person they can just ask him to come to the police station on his own will. If he refuses then there is no point in giving the LE power to force him since the person can just choose not to speak. The only situation I believe it's right to force something on person is when he is threatening the rights of other people.

Concerning the issue of Judges, I don't see how this in protects the division of powers. Judges can have all the protections of the constitution and that should be sufficient. I don't see a good reason to give them a special privilege that ordinary citizens lack.

**Comment by KacperZajc** [comment]
If there is a probable cause, they should be able to do that; they need at least some powers to do their job.

Judges safeguard the system, they need special protection.

**Comment by yopdog** [comment]
Could you explain why police need this power to do their job? I already pointed out that a person can  choose to not speak. Therefore, giving police the power to detain someone who poses no threat has no use. 

Concerning Judges, you still didn't give any explanation as to why Judges need special protection. Can you maybe give an example?

**Comment by yopdog** [comment]
@KacperZajc Given that we now have stricter rules concerning arrests, is it safe to say we can remove §V.4(3) from the constitution?

**Comment by KacperZajc** [comment]
Sorry but I definitely want to keep this provision. It is crucial to the division of powers. Please do some research on that if I am not compelling.

I can make this provision less restrictive by changing the requirement of 3 Justices of the Supreme Court to 1 if that satisfies you :)

**Comment by yopdog** [comment]
Ok, I think I may understand where you are coming from. The arresting of judges can lead to a form of blackmailing of the judicial system which could compromise the division of powers.   

That being said, I have a question about the provision itself. The provision states that judges cannot be detained on SUSPICION of any criminal offence. I'm assuming this means judges can be arrested in situations of necessity where they pose a threat, since then it will be more than just a suspicion. This would mean the provision would only cover cases where the police would anyway need a warrant to conduct an arrest. is that correct?

**Comment by KacperZajc** [comment]
Glad you see my point.

But you're right, we need better wording:

Detention and potential prosecution of any Judge of any Court of the Free Republic of Liberland shall be possible only with the consent of the Chief Justice of the Supreme Court, or if unable, any other Justice of the Supreme Court as expressed in the Supreme Warrant issued upon request of the Law Enforcement or the Office of the Chief Prosecutor.

???

**Comment by terrorist96** [comment]
**express** consent

**Comment by KacperZajc** [comment]
...as expressed in...

**Comment by terrorist96** [comment]
Also isn't the chief prosecutor within the definition of LE?

**Comment by terrorist96** [comment]
> ...as expressed in...

? Your new wording just says consent. It needs to be defined.

**Comment by KacperZajc** [comment]
possibly, in my mind I associate the Law Enforcement with the police or similar agency, and the district attorney (prosecutors) seems a bit different

**Comment by KacperZajc** [comment]
it says consent ... EXPRESSED in the Supreme Warrant

**Comment by terrorist96** [comment]
Different meaning. Leaving it as just consent would enable implied consent. Implied consent would consist of the judge being asked to consent. If he doesn't reply, you can assume implied consent since he didn't object. Express consent wild require an active statement of approval. 
'expressed in the Supreme warrant' simply means what's stated in the warrant. Also, we haven't defined 'Supreme Warrant'.

**Comment by terrorist96** [comment]
> the district attorney (prosecutors) seems a bit different

We've already defined it as such in the Constitution though.

**Comment by KacperZajc** [comment]
Supreme Warrant is statement of consent to detention of a judge. I really dont think you need another 'express' in this sentence but feel free to propose rewording of this section.

When did we define the Law Enforcement as including the Office of the Chief Public Prosecutor?

**Comment by terrorist96** [comment]
I.9

**Comment by yopdog** [comment]
@KacperZajc I'm actually more in favour of the original wording. your new suggestion that judges need supreme court approval for any arrest brings with it serious problems. Say for example a judge has committed a violent offence and is a threat to others. In such a case, there is simply no time to get an approval from the supreme court since the arrest has to be done NOW in order to protect the general public. If we go along with the changes I made to §II.24. then any arrest without a warrant would only be in cases of absolute necessity, where a person is a threat. I therefore see no other option than to have provision §II.24. apply to judges as well.

That said, in cases where a warrant has to be issued, we could make it that the warrant has to come from the supreme court. that would cover cases where LE want to conduct a search on a judge or extend his detainment.

**Comment by yopdog** [comment]
I have my own suggestion:

>§V.4(3) All Warrants concerning the detainment or investigation of a Judge of any Court of the Free Republic of Liberland shall be issued by the Supreme Court with the express consent of at least three Justices; no Judge or Jury of any Court shall be detained for their verdict and their interpretation of the law.

This still offers some protection to Judges while allowing police to conduct arrests where it is absolutely necessary as stated in the change to provision §II.24.

>§II.24. No law shall allow for any Person to be detained randomly or without any evidence but only under specified charges, upon probable cause, **and where it is absolutely necessary for the protection of others or to secure potential evidence;** such arrest shall be executed only by an Agent of the Law Enforcement acting openly and informing the detainee about the rights one enjoys under this Constitution and any laws passed by the Assembly in accordance thereof.

**Comment by KacperZajc** [comment]
whole set of amendments in this area:

§V.4(3) No Judge of any Court of the Free Republic of Liberland shall be arrested for any period whatsoever unless pursuant to the Supreme Warrant issued by a simple majority of the Supreme Court.

§I.7. All Warrants in the Free Republic of Liberland, other than the Supreme Warrant, shall be issued by a Judge of the Criminal Court upon request by an Agent of the Law Enforcement or the Office of the Public Prosecutor and shall be supported by evidence of probable cause; such Warrants shall be as detailed as possible; every Warrant granted for a continuous action shall expire no later than after one year and shall be renewed by another Judge in accordance with ordinary procedure.

§II.24. No law shall allow for any Person to be detained randomly or without any evidence but only under specified charges, upon probable cause, and where it is absolutely necessary for the protection of others or to secure potential evidence; such arrest shall be executed only by an Agent of the Law Enforcement acting openly and informing the detainee about the rights one enjoys under this Constitution and any laws passed by the Assembly in accordance thereof.

**Comment by yopdog** [comment]
@KacperZajc I still have a problem with this. What if a Judge has committed a violent offence and poses an immediate threat to people around him? In such a case, there will not be enough time to get a Warrant from the Supreme Court. I don't believe we can have a provision that completely forbids the police from arresting a person. The police have the power to arrest for a very good reason and that is to protect the public from harm. 

My  main problem with this provision is that it gives a special group of people called Judges special protections from being arrested. I know this is what you want, but I believe this can be abused. If a Judge ever commits a serious crime the police will be powerless in their ability to protect the public thanks to this provision. By the time the police get the Warrant, the Judge can already destroy vital evidence and even hurt someone. It is for these reasons that I believe we must have provision §II.24 apply to judges as well. 

Like I said before, I understand what you are trying to achieve with this provision, but I think there are better ways to do this. One way would be to constitutionally forbid police from ever arresting a Judge for his verdict and require a Supreme Warrant to conduct an investigation on a Judge. This should be sufficient to maintain the independence of the courts.
