### ISSUE TITLE
Further changes

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#208]
1) Bill of Rights preamble: substitute "It recognises the rights inherent in Persons and Individuals as well as sets limits to the prerogatives of the Public Administration. As such, the Bill of Rights shall be directly enforceable before all Courts of the Free Republic of Liberland" for "The following rights shall apply equally to all Persons under the jurisdiction of the Free Republic of Liberland unless stated otherwise".

2) §II.7: Remove "so long as no negative rights of others are infringed"

3) Remove §I.3. and §I.4. 

4) Add instead: "All Members and Agents of the Public Administration intentionally acting in breach of the law or the Constitution shall be criminally liable for their actions and, upon conviction, shall be removed from the office and shall never hold any public office again; any loss caused by Agents of the Public Administration acting contrary to the law or the Constitution, or in error, shall be personally compensated; acting pursuant to an Act which has been approved as prima facie constitutional by the Supreme Court shall not be deemed as acting unconstitutionally regardless of any future declaration of any Court as to the Act's true constitutionality; introducing, lobbying and voting for a Bill which is declared unconstitutional shall not be deemed as acting unconstitutionally."

5) §II.21: Remove "any Person whatsoever responsible shall be held personally accountable for such a crime against human dignity, regardless of any law, policy, command or suggestion which might have been authorising such conduct."

6) §II.27: Remove "and respecting thereof"

7) Remove §II.35.

8) §II.36: Substitute "the accused" for "him or her"

9) §II.37. Substitute "are accused of" for "committed"

10) §III.5(4): Substitute "the Law Enforcement" for "a militia"

11) §IV.2: Add (1) "No Person shall hold the office of a Judge of one of the courts of the Free Republic of Liberland and be a Member of the Cabinet at the same time.

12) §II.24: Restate: No law shall allow for any Person to be detained randomly or without any evidence but only under specified charges, upon probable cause, and where it is absolutely necessary for the protection of others or to secure potential evidence; such arrest shall be executed only by an Agent of the Law Enforcement acting openly and informing the detainee about the rights one enjoys under this Constitution and any laws passed by the Assembly in accordance thereof.

**Comment by terrorist96** [comment]
What are your thoughts on:

> 5) add to the Bill of Rights preamble "and its Members and Agents both within and outside the territory of the Free Republic of Liberland."
I feel like Member should be encompassed by Agent. An Agent of the PA is anyone that works for the PA. Members (elected reps) work for the PA. They are all Agents. This should be reflected in I.9 along with law enforcement.

I'll respond to your changes later. Gotta go for now.

**Comment by KacperZajc** [comment]
I'd rather keep the distinction.
Agents, such as civil servants, should have different level of responsibility than e.g. Assembly Representatives.

**Comment by terrorist96** [comment]
So if an assembly representative finds illegal evidence, or directs someone else to, it'd be ok to introduce it in a criminal case?

> introducing, lobbying and voting for a Bill which is declared unconstitutional shall not be deemed as acting unconstitutionally."

This concerns me. Since we haven't adopted recall elections of elected officials, having this section would reduce liability of Representatives' actions. I'd be in favor of adding this provision if we also enact a recall referendum process for the legislative branch too. 

> II.21

You don't need to remove 'whatsoever' if the whole section is being removed anyway. 

> Remove §II.35.

And replace it with what?

**Comment by KacperZajc** [comment]
Assembly Representatives dont work for the police and any evidence which is found by anyone who trespasses but does not work for the police is admissible anyway.

We can consider recall elections but either way we cant punish Assembly Representatives if their bill turns out to be unconstitutional because it would entirely paralyse the assembly work.

I wouldnt replace II.35 with anything. It was vague and unenforceable in the first place. It was traditional phrasing but I dont think it would be ever invoked in a court.

**Comment by KacperZajc** [comment]
Also I want to reword §I.6. to:
All decisions of any body of the Public Administration other than a court of law shall be subject to challenge in the Civil Court by a Person in whose respect it was given, or any other Person who can prove one's interest in that decision; the right shall be exercisable once all administrative appeals have been exhausted.

**Comment by KacperZajc** [comment]
Also I want to reword §I.6. to:
All decisions of any body of the Public Administration other than a court of law shall be subject to challenge in the Civil Court by a Person in whose respect it was given, or any other Person who can prove one's interest in that decision; the right shall be exercisable once all administrative appeals have been exhausted.

**Comment by terrorist96** [comment]
Re: Assembly Reps
Think of the persecution of Kim dotcom or Ross Ulbrict by US congressmen. All government workers should be restricted in gathering evidence whilst on the clock. 

> We can consider recall elections but either way we cant punish Assembly Representatives if their bill turns out to be unconstitutional because it would entirely paralyse the assembly work.

They won't be, necessarily. The people will decide. If it's egregiously unconstitutional, the people can decide to impeach/recall. If it's a minor issue, no one will care. 

We need II.35 because otherwise, it opens the flood gates for billion dollar bail for minor crimes. The details can be worked out with legislation, but we need that provision in the Constitution to provide a ceiling for excessive bail. 

I.6 change 'any body' to 'any branch'

**Comment by KacperZajc** [comment]
@terrorist96 
adopted all your changes apart punishing Assembly Reps for voting for unconstitutional bill which I think is unenforceable;
also sorry but I merged your minimum sentence ban by mistake, I think if we dont have victimless crimes, we can safely keep it

**Comment by terrorist96** [comment]
Why was this section removed:
§I.7. All Warrants in the Free Republic of Liberland shall be issued by a Judge of the Criminal Court upon request by an Agent of the Law Enforcement or the Office of the Public Prosecutor and shall be supported by evidence of probable cause; such Warrants shall be as detailed as possible; every Warrant granted for a continuous action shall expire no later than after one year and shall be renewed by another Judge in accordance with ordinary procedure.	

> punishing reps

You're not punishing them. I'm only saying the constitution should be mute regarding `introducing, lobbying and voting for a Bill which is declared unconstitutional shall not be deemed as acting unconstitutionally."`
And when you add recall referendums, it will ensure that the representatives vote on behalf of the people, not corporate lobbyists. An example I can cite is when Colorado recalled 2 reps who had voted to infringe their right to arms and a third resigned before the election could be held.
Nothing epitomizes representative democracy better than that. 

> §II.40 No law shall require a mandatory minimum prison sentence for any crime; maximum sentences shall be stipulated only.	

The less the legislative branch interferes with the judicial branch's duty to find justice, the better. I can understand the knee-jerk reaction to want mandatory life in prison or death for murder, etc, but any Jury and Judge working together can come to that conclusion if it fits the circumstances of the case. This is keeping in line with the jury nullification theme too.

**Comment by KacperZajc** [comment]
§I.7.  removed by mistake, sorry

I dont mind recall mechanism 

Im afraid of judges having the power to sentence murderers to cleaning streets, it would be ease to bribe a judge to get an inadequate sentence even upon conviction by the jury (which is hard to bribe)

**Comment by terrorist96** [comment]
The Jury could recommend a sentence that the judge would consider.
A more serious issue is that a jury could nullify and let a murderer go free, but we're ok with jury nullification.
We could eliminate the fear of a judge giving a petty sentence to a serious crime by having recall elections of regular judges too, not just Supreme Court judges.

**Comment by KacperZajc** [comment]
I think that is putting too much pressure on them. Would do more harm than good.
Id rather keep minimum sentencing, we dont have victimless crimes in any event.

**Comment by terrorist96** [comment]
So how can we avoid potential life in prison mandatory minimum for something minor like Public Nuisance?

**Comment by KacperZajc** [comment]
we regulate that via ordinary law, I dont think we should be afraid the gov goes that far...

**Comment by terrorist96** [comment]
Yeah, I know it's an unfounded fear, but giving the legislators the capability of doing so is just a bit concerning. Maybe it could be incorporated into the cruel and unusual punishment provision or the excessive bail/fine provision, something to prohibit excessive prison sentences.

**Comment by KacperZajc** [comment]
Yeah, this whole provision needs some work anyway, let's think about that :)

**Comment by KacperZajc** [comment]
see #221
