### ISSUE TITLE
Election districts

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#210]
How will elections be held? Will there be districts? Or will it be at-large? If there are districts, we will have to deal with outlining them and gerrymandering. 
I think the best option is to have at-large elections for the entire country. This way, we can have X number of people on the same ballot, people can vote for who they want, and those who are in the top 20 will win. This will allow for the minority to be represented too. Thoughts?

**Comment by lunokhod** [comment]
My preference would be single transferable voting (which is more or less what you are proposing): https://en.wikipedia.org/wiki/Single_transferable_vote

However, I'm not sure if this detail needs to be in the constitution or not. We just need to delegate the authority to one of the branches of government to set up and oversee elections.  As the constitution reads now, it is not 100% clear who is in change of running general elections.

**Comment by KacperZajc** [comment]
Hard to tell now. We will get back to it later :)

**Comment by KacperZajc** [comment]
Leaving the details aside, any idea on constitutional provisions that would delegate the authority to one of the branches of government to set up and oversee elections?

**Comment by terrorist96** [comment]
The answer depends on whether or not we will have districts. If yes, local towns/cities/villages can conduct their own elections. If no, then we can delegate the authority to a commission to conduct elections for the entire nation. I think it should be independent from the 3 branches.

**Comment by KacperZajc** [comment]
OK so it's too early to deal with it.
