### ISSUE TITLE
Supreme Court majority 

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#211]
> §V.6(1) The Supreme Court shall reach its decisions with a simple majority.

What if they can't reach a majority? What it's split 2-2-1 with one judge recusing them self? What of plurality opinions?

**Comment by KacperZajc** [comment]
noooooo
every judge gives his verdict but it must be either guilty/liable or not guilty/liable, there is no 3rd option here

**Comment by terrorist96** [comment]
Not every decision will require a guilt determination. It could be a controversy about how a law is being applied or the constitutionality of a law.

**Comment by KacperZajc** [comment]
still it is either what the claimant says or what the defendant says, there is never a 3rd option

**Comment by terrorist96** [comment]
And what if one judge reuses themselves due to a conflict of interest and the remaining 4 are split 2-2?

**Comment by KacperZajc** [comment]
then another judge takes his place, Im sure there will be 'judges in waiting' or something like that, there can be no 4judges giving a verdict if the court has originally 5 judges

**Comment by terrorist96** [comment]
> judges in waiting

This needs clarification. Who are these judges? The Chancellor gets to decide?

**Comment by KacperZajc** [comment]
the judicial non-departmental body along with the chancellor when it comes to the supreme court or this body alone when it comes to other courts, it will be regulated by ordinary law, really dont want to put everything in the constitution
