### ISSUE TITLE
New tax system proposal

### ISSUE THREAD

**Issue by Auahi** [liberland/constitution#212]
The tax system in Liberland is not adequate. Property taxes can be very unfair, just because someone has a bigger property shouldn't effect taxation. Sales taxes can severely impede free commerce, it forces businesses to apply for various licenses, and can make small business difficult. Liberland should have taxes based upon needs, for example: if Liberland wants to build a new school, the amount needed should be assessed and a tax is instated until funds are received, this would prevent the government from wasting excess money. These taxes could be generated via low corporate taxes on gains and or by governmental capitalism(Free Republic of Liberland supplying: Electricity, Water, Gas[hopefully we wouldn't need this :) ] internet etc.)

What do you think about this?

**Comment by KacperZajc** [comment]
I know it is inadequate, but we are not dealing with tax system at the moment. We will get back to it in due course.
