### ISSUE TITLE
new amendments 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#214]
1) §II.5: change "one" to "Individual" 

2) §III.4: add (8) "The Assembly Committee shall only deal with the matter for which it was established and shall cease to work no later than a year since its creation"

3) §III.9: change "(4)" to "(3)"

4) §IV.4: change "Article IV" to "Article III"

5) §II.32: add "nor shall it be used for any other purpose than defence of the territory of the Free Republic of Liberland against external enemies"

**Comment by yopdog** [comment]
Seems fine to me.

**Comment by terrorist96** [comment]
> no provision of any Act shall differentiate between genders"

So laws about a pregnant woman willfully killing her 9 month old fetus would be disallowed because it differentiations between genders. This phrase isn't needed IMO.

> 5) §II.17: change "one" to "Citizen"

Why?

**Comment by KacperZajc** [comment]
you're right

maybe Individual instead of Citizen? 
I feel like one is too broad

**Comment by terrorist96** [comment]
What are you trying to protect against?

**Comment by KacperZajc** [comment]
not sure yet, but minors could be asked to identify themselves on several occasions, seems natural to me

**Comment by terrorist96** [comment]
But how can you determine one is a minor without first seeing the identification? One could be 18 (and not require identification) but a cop could think he's 17 and force him to produce it.

**Comment by KacperZajc** [comment]
how do we deal with that? Im sure we need this change.

**Comment by terrorist96** [comment]
Why are you so sure? :sunglasses:
We already have the warrant exception.

**Comment by KacperZajc** [comment]
Ok Im not changing it now but Im sure it will come up later.

**Comment by KacperZajc** [comment]
I'll make a separate issue on that :)
