### ISSUE TITLE
excessive sentencing 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#221]
§II.35. No law shall require any Person to pay excessive bail and/or fines; nor shall it require the Criminal Court to sentence the defendant who has been held guilty by the Jury to incarceration exceeding 10 years for any offence where no actual harm was suffered by any person because of this offence alone.

This covers public disorder,  attempted crimes, aiding in committing crimes etc.

???

**Comment by terrorist96** [comment]
I would remove the number 10 and just leave it general. Let the supreme court decide if the sentence is excessive.
Also, if 'no actual harm' laws are in place, doesn't that go against 'no victimless crimes'?

**Comment by terrorist96** [comment]
You need a victim for a law to be constitutional, and you can't have a victim if there's no harm. Right?

**Comment by yopdog** [comment]
My belief is that people should be incarceration only if they pose a danger to society. Otherwise, it's just a huge waste of money. 

That said, If a person is incarcerated, then there should never be a maximum sentence in the law since the person may still pose a threat to the public. It should therefore be decided on a case by case basis

**Comment by KacperZajc** [comment]
yeah that needs clarification but Im sure we need to criminalise attempted offences, aiding etc.

**Comment by KacperZajc** [comment]
§II.35. No law shall require any Person to pay excessive bail and/or fines; nor shall it require the Criminal Court to sentence the defendant who has been held guilty by the Jury to excessive incarceration for any offence where no actual harm was suffered by any person because of this offence alone.

???
(assuming I'll clarify the victimless crimes provision)

**Comment by terrorist96** [comment]
> nor shall it require the Criminal Court to sentence **a** defendant who has been **found** guilty by the Jury to excessive incarceration for any offence where no actual harm was suffered by any **P**erson because of this offence alone.

Three changes and it's good.

**Comment by KacperZajc** [comment]
see #222
