### ISSUE TITLE
victimless crimes

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#222]
§II.5. No law shall create victimless and/or consensual crimes; no Person shall be prosecuted for any offence against society or any part thereof, nor shall one be considered a victim of one's own actions or omissions; failed attempt to commit a criminal offence which causes harm to a potential victim and/or giving any form of aid to the Person committing such offence shall not be deemed as a victimless crime.

§II.35. No law shall require any Person to pay excessive bail and/or fines; nor shall it require the Criminal Court to sentence a defendant who has been found guilty by the Jury to excessive incarceration for any offence where no actual harm was suffered by any Person because of this offence alone.

**Comment by terrorist96** [comment]
:+1:

**Comment by terrorist96** [comment]
> ~~failed~~ **an** attempt to commit a criminal offence which **would** cause~~s~~ harm to a potential victim and/or **knowingly** giving any form of aid to **a** Person committing such offence shall not be deemed as a victimless crime.

**Comment by KacperZajc** [comment]
§II.5. No law shall create victimless and/or consensual crimes; no Person shall be prosecuted for any offence against society or any part thereof, nor shall one be considered a victim of one's own actions or omissions; an attempt to commit a criminal offence which would cause harm to a potential victim and/or knowingly giving any form of aid to a Person committing such offence shall not be construed as a victimless crime.

§II.35. No law shall require any Person to pay excessive bail and/or fines; nor shall it require the Criminal Court to sentence a defendant who has been found guilty by the Jury to excessive incarceration for any offence where no actual harm was suffered by any Person because of this offence alone.

**Comment by Auahi** [comment]
This sounds good

**Comment by terrorist96** [comment]
I would also add **direct** prior to 'aid' in order to narrow it down.
