### ISSUE TITLE
sorting out II.17

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#223]
§II.17. No law shall allow the Public Administration to assign a number to any Individual without one's express and informed consent; nor shall one be required to procure, carry, or otherwise maintain identification materials of any form, or share their personal information with any branch of the Public Administration unless pursuant to a Warrant.

several problems here:
- PA can assign a number to any minor but not an adult, what if it assign a number to a baby and it sticks to it once the majority age is reached
- minor is assigned a number but cannot be required to show this number?
- how to distinguish a minor from an adult without checking his papers?

**Comment by terrorist96** [comment]
My solution would be to change Individual to Person and add "unless pursuant to a Warrant" at the end of the first clause. This would cover convicts but exclude minors.

**Comment by lunokhod** [comment]
I don't understand the reasoning of why it is bad to assign a number to a person.

Consider that each of us is assigned a name at birth, and that the PA will make a database of such names (if for no other purpose than to prove citizenship). Once your name is in the database, the name can be converted to a binary number by a simple formula

Why is the formula that converts ascii to binary bad?

**Comment by KacperZajc** [comment]
Although I think assigning a number is abhorrent, it seems that we are creating more problems here than we actually solve. It might be completely unworkable in practice. 

I propose we remove this section and add instead:

No law shall allow for any branch of the Public Administration to require any Individual to register one's whereabouts, being it permanent or temporary unless pursuant to a Warrant.

**Comment by lunokhod** [comment]
I understand where you are coming from with the number issue, but I think that the bigger threat is citizen database entries. I believe that these will be necessary (for identification), but we should strive to limit what can be stored. In my opinion, once there is an electronic database, assigning a number is just an afterthought.

**Comment by KacperZajc** [comment]
@terrorist96 what do you think?

**Comment by terrorist96** [comment]
I like your suggested replacement text. We're also covered by the provision that says anyone can request any existing info about them to be purged from any and all government databases.

**Comment by KacperZajc** [comment]
§II.18. All data collected by the Public Administration shall be used only for the direct and necessary purposes for which it was originally collected, and shall be kept confidential and shared only with the express and informed consent of the rightful owner or otherwise in accordance with the provisions of this Constitution; all Individuals whose data is stored by any body of the Public Administration other than the Law Enforcement shall have access to it and shall retain the right to demand its destruction at any time.
