### ISSUE TITLE
qualification of agents of the PA

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#224]
restate: 

§II.13. No law shall regulate the content of any curriculum used by any school or any higher education institute at any stage of education.

add:

§II.40. No law shall impose any obligations as to pursuing and/or obtaining any stage of education by any Person other than Agents and Members of the Public Administration; all Agents of the Public Administration shall be employed solely on basis of their merits and fallowing appropriate tests; no Member of the Public Administration shall employ or enable employment of any Agent who has not passed relevant tests only because of one's personal connection or political affiliation.

**Comment by Auahi** [comment]
If what you're trying to accomplish with II.40 is to regulate how they employ teachers wouldn't it be of no use since §III.16(3)(d) basically says there won't be public education...

**Comment by KacperZajc** [comment]
noooo
Im trying to ensure that Agents of the PA will not be employed based on political affiliation but on merits only
the rest is just rewarding old section
