### ISSUE TITLE
broadening judicial review 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#226]
§I.5. All decisions of any branch of the Public Administration other than a court of law as well as all actions undertaken by its Agents and every exercise of delegated power by the Cabinet shall be subject to challenge in the Civil Court by a Person in whose respect the decision was given or action undertaken, or any other Person who can prove one's interest in that decision; the right shall be exercisable once all administrative appeals have been exhausted; should no Person be in privileged position to make a claim, any Citizen shall have standing to seek redress in the Civil Court.

Designed to ensure that there is no situation wherein no person has standing to sue.

???

**Comment by terrorist96** [comment]
How do we determine if no person has standing? That's like trying to prove a negative. It's not possible.

**Comment by KacperZajc** [comment]
§I.5. All decisions of any branch of the Public Administration other than a court of law as well as all actions undertaken by its Agents and every exercise of delegated power by the Cabinet shall be subject to challenge in the Civil Court by a Person in whose respect the decision was given or action undertaken, or any other Person who can prove one's interest in that decision; the right shall be exercisable once all administrative appeals have been exhausted; should the decision, action or exercise of delegated power be not aimed at any particular person, any Citizen shall have standing to seek redress in the Civil Court.

???

**Comment by terrorist96** [comment]
That's good.
