### ISSUE TITLE
new set of changes

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#227]
1) I.7: restate: No branch of the Public Administration, nor any number of Citizens or Residents of the Free Republic of Liberland, shall propose and/or consent to the incorporation of the Free Republic of Liberland, or any part thereof, to any other jurisdiction.

2) III.4(3): add: "in order to investigate the allegations."

3) III.4(7): add: "in the Criminal Court"

4) III.21: add: "according to the procedure laid down in Article V".

5) IV.4: after "Cabinet shall judge necessary" add: "for the protection of persons and their property"

6) add IV.5(9) "to appoint the Chief Public Prosecutor and the State Attorney"

7) add IV.5(10) "to supervise all Agents of the executive branch of the Public Administration"

8) add IV.8 "The Chancellor and the Cabinet shall be advised as to the law by the State Attorney"
IV.8(1) The Office of the State Attorney shall represent all bodies of the Public Administration in all civil proceedings.
IV.8(2) The State Attorney shall be appointed by the Chancellor for a term not exceeding six years.

9) V.4(1): add: "headed by the Chief Justice of the Supreme Court"

10) V.7: restate: "All civil disputes shall be adjudicated in the Civil Court by a panel of three Judges reaching a decision with a simple majority"

11) add V.7(1) "The Civil Court shall have jurisdiction to adjudicate all administrative disputes between Citizens and Residents of the Free Republic of Liberland and any body of the Public Administration."
V.7(2) "The Civil Court shall retain the inherent jurisdiction to hear disputes related to the well-being of Minors and Persons lacking mental capacity."

**Comment by terrorist96** [comment]
> 1) I.7: restate: No branch of the Public Administration, nor any number of Citizens or Residents of the Free Republic of Liberland, shall propose and/or consent to the incorporation of the Free Republic of Liberland, or any part thereof, to any other jurisdiction.

I think you meant to say I.6

> 5) IV.4: after "Cabinet shall judge necessary" add: "for the protection of persons and their property"

Seems unnecessary.

The rest seems fine.
