### ISSUE TITLE
restating certain provisions 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#231]
§II.1. No law shall deprive any Citizen of the Free Republic of Liberland of one’s right of access to information which relates to any aspect of the functioning of the Public Administration which is not classified; information shall be classified by a responsible Secretary of State with the express and informed consent of two-thirds of all Assembly Representatives as discussed in camera, and for the purposes of national security only, and for a period not exceeding one year; no Person shall be prosecuted for disclosure of classified information if that piece of information proves or could be reasonably believed to prove that any Agent of the Public Administration has breached, remains in breach of or intends to breach the law or the Constitution.

§II.15. No law shall prohibit video and/or audio recording of any Agent of the Public Administration in public space or all other areas where there is no reasonable expectation of privacy and whilst on duty; all Assembly debates and votes, other than the debate and vote on the classification of information, and all decisions of any Court, other than proceedings involving Agents of the Law Enforcement still acting undercover, shall be recorded and archived and made available to the general public contemporaneously; the affairs of the Assembly and the Supreme Court shall be video recorded and made public contemporaneously.

§II.9. No law shall abridge the freedom of thought and religion, and expression thereof; no Person shall have the right to be protected from opinions of others where expressed peacefully.

§II.26. No law shall promote or hinder any religion, gender or specific community; no special rights or privileges shall be conferred on any Person due to one's gender, religious belief, cultural background and/or any other attribute.

§I.10. All Warrants in the Free Republic of Liberland, other than the Supreme Warrant, shall be issued by a Judge of the Criminal Court upon request by an Agent of the Law Enforcement and shall be supported by evidence of probable cause; such Warrants shall be as detailed as possible and shall refer to one Person only; every Warrant granted for a continuous action shall expire no later than after one year and shall be renewed by another Judge in accordance with ordinary procedure.

§I.8. All Members of the Public Administration shall hold the citizenship of the Free Republic of Liberland; all Individuals holding the citizenship of the Free Republic of Liberland shall have the right to register for participation in all elections and referendums in the Free Republic of Liberland.

**Comment by terrorist96** [comment]
For II.40, you could replace 'personal connection'  with 'nepotism'. Sounds cleaner and more consise. 

> or in easily accessible areas belonging to the Public Administration

So they can be filmed outside in a park, but not if they step inside a restaurant? And they can't be filmed inside a non-easily accessed area owned by the PA? Like inside a public building with security guards at the entrance? 

> no Person shall be prosecuted for disclosure of classified information if that piece of information proves or could be reasonably believed to be **prove** that any Agent of the Public Administration has breached, remains in breach or intends to breach the law or the Constitution.

So we'd also get rid of II.26?

> §II.15. No law shall prohibit video and/or audio recording of any Agent of the Public Administration in public space or in easily accessible areas belonging to the Public Administration and whilst on duty; all Assembly debates and votes, other than the debate and vote on the classification of information, and all decisions of any Court, other than proceedings involving Agents of the Law Enforcement still acting undercover, shall be recorded and archived and made available to the general public **contemporaneously**; the affairs of the Assembly and the Supreme Court shall be video recorded and made public contemporaneously.

> §II.26. No law shall promote or hinder any religion, gender or specific community; no special rights or privileges shall be conferred on any Person due to one's gender, religious belief and/or cultural background.

I would add 'and/or any other attribute.' as a catch-all phrase.

> such Warrants shall be as detailed as possible and shall refer to one Person only, no group Warrants shall be issued;

The part about group Warrants seems unnecessary since you say it can only refer to one Person only. 

> I.8

So delete I.9 then?

**Comment by KacperZajc** [comment]
II.26 was merged with II.1 and II.15 without changing the content. 

What I meant to say by 'easily accessible' was that they could be taped in the building unless they talk behind closed doors. Any better idea?

I.8 was merged with I.9.

The rest of your suggestions adopted accordingly.

**Comment by terrorist96** [comment]
> no Person shall be prosecuted for disclosure of classified information if that piece of information proves or could be reasonably believed to prove that any Agent of the Public Administration has breached, remains in breach **of** or intends to breach the law or the Constitution.

One more edit. 

>  no special rights or privileges shall be conferred on any Person due to one's gender, religious belief**,** ~~and/or~~ cultural background**,** and/or any other attribute.

Regarding the filming, I don't know. I'm still uneasy about having any restrictions. It should be allowed everywhere as the default with certain exceptions provided for in the law (like no filming in a public restroom).

**Comment by KacperZajc** [comment]
No law shall prohibit video and/or audio recording of any Agent of the Public Administration in public space or all other areas where there is no reasonable sense of privacy and whilst on duty...

???

**Comment by terrorist96** [comment]
> No law shall prohibit video and/or audio recording ~~of any Agent of the Public Administration~~ in public space**s** or all other areas where there is no reasonable ~~sense~~ **expectation** of privacy. ~~and whilst on duty~~

:D

**Comment by KacperZajc** [comment]
this is a free pass for massive surveillance xD

**Comment by terrorist96** [comment]
We already forbid surveillance without a warrant though.

**Comment by KacperZajc** [comment]
so your provision would be inconsistent with this ban 
it's unclear and too wide IMO
I would stick to the recording of Agents - this is clearly aimed at controlling police officers during their interventions

**Comment by terrorist96** [comment]
What about a news organization or blogger who is recording in public in general? This would be unprotected activity unless an agent of the PA is in the film.

**Comment by KacperZajc** [comment]
Im not sure it needs constitutional protection.
I'll think about that.

**Comment by terrorist96** [comment]
I think it does. Otherwise, the government in the US would love to ban this kind of activity if it weren't for the first amendment.

**Comment by terrorist96** [comment]
Or to only provide such protections to official news organizations (mouth pieces of the federal government), but to forbid independent news media/bloggers from engaging.

**Comment by KacperZajc** [comment]
OK, I'll open a separate issue on that.

**Comment by KacperZajc** [comment]
see #238 for discussion
