### ISSUE TITLE
sorting out potential taxes IF we go down this road 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#232]
§III.14. A Taxation Bill proposing taxation shall be passed into law with the unanimous vote, and shall be subject to the power of general veto by the Citizens as provided in §III.18.
§III.14(1) The Bill shall introduce the tax on actual land.
§III.14(2) The tax shall be fixed per meter square.
§III.14(3) No other form of tax shall be levied in the Free Republic of Liberland.
§III.14(4) No other Bill shall be capable of levying any tax in the Free Republic of Liberland.
§III.14(5) The overall tax revenue shall not exceed 5% of the Gross Domestic Product of the Free Republic of Liberland of the preceding year.
§III.14(6) The tax shall be levied for one or more of the following purposes only:
§III.14(6)(a) maintaining the infrastructure of the Public Administration;
§III.14(6)(b) providing for the Law Enforcement;
§III.14(6)(c) providing for the Courts of the Free Republic of Liberland;
§III.14(6)(d) providing for Agents and Members of the Public Administration;
§III.14(6)(e) securing and promoting the interests of the Free Republic of Liberland worldwide.

Feel free to add on this list of restrictions :)

**Comment by terrorist96** [comment]
> §III.14(5) The overall tax revenue shall not exceed 5% of the Gross Domestic Product of the Free Republic of Liberland of the preceding year.

What happens if it does? Will they be required to lower the tax rate? 

> §III.14(6) The tax shall be levied for one or more of the following purposes only:
§III.14(6)(a) covering the expenses of the Public Administration

wouldn't this cover b - d? Anything can be considered an expense of the PA.

**Comment by KacperZajc** [comment]
Yes they would have to lower the tax.

§III.14(6) The tax shall be levied solely for the purposes of covering the expenses of the Public Administration and securing and promoting the interests of the Free Republic of Liberland worldwide.

???

**Comment by terrorist96** [comment]
By using that phrase, what are we prohibiting taxes being used for?

**Comment by KacperZajc** [comment]
yeah you're right, it does not restrict anything
what do you propose?

**Comment by terrorist96** [comment]
Taxes should only be used to fund anything sanctioned by the Constitution and any laws derived thereof.

**Comment by KacperZajc** [comment]
§III.14(6) The tax shall be levied for one or more of the following purposes only:
§III.14(6)(a) maintaining the infrastructure of the Public Administration;
§III.14(6)(b) providing for the Law Enforcement;
§III.14(6)(c) providing for the Courts of the Free Republic of Liberland;
§III.14(6)(d) providing for Agents and Members of the Public Administration;
§III.14(6)(e) securing and promoting the interests of the Free Republic of Liberland worldwide.

???

**Comment by terrorist96** [comment]
That's good, though I'm sure an issue will come up in the future and we will need to add more things that taxes can be used for.

**Comment by KacperZajc** [comment]
we'll cross this bridge when we get there :)
