### ISSUE TITLE
restating Assembly's areas of competence

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#233]
§III.5. The powers of the Assembly shall be restricted to the following only:
§III.5(1) to legislate for the protection of Persons and their rights and property;
§III.5(2) to conduct the financial affairs of the Public Administration as provided in the Financial Bill;
§III.5(3) to lay the tax on land provided for in the Taxation Bill;
§III.5(4) to maintain the Courts of the Free Republic of Liberland without interfering with the affairs of the judiciary;
§III.5(5) to establish the Law Enforcement to maintain the internal security;
§III.5(6) to assent to the incorporation of any new territories to the Free Republic of Liberland with any status the Assembly shall determine;
§III.5(7) to debate on matters important to the well-being of the state;
§III.5(8) to ratify international treaties signed by the Cabinet as provided in a Treaty Bill;
§III.5(9) to establish the Assembly Committee;
§III.5(10) to assent to the classification of information for the purposes of national security as proposed by a Secretary of State;
§III.5(11) to appoint the Chancellor and the Cabinet and to withdraw the confidence if necessary.

Any suggestions?

**Comment by terrorist96** [comment]
> §III.5(1) to legislate for the protection of Persons and their **rights** and property;

Only improvement I can think of for now.
