### ISSUE TITLE
Demanding information from companies without a warrant

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#236]
What about a law that demands corporations to retain user information and for that information to be shared with the government without a warrant? Would the current draft allow for this? 
The government shouldn't be able to **require** companies to retain information about their users/customers (this would allow for no-logs VPNs for example). And the government shouldn't be able to demand info about a person from a company that has voluntarily retained info, without a warrant.

**Comment by KacperZajc** [comment]
it's covered: 

§II.22. No law shall allow for any Individual’s privacy to be violated by freeze of assets, searches, seizures, surveillance, accessing and gathering of their personal information without one's express and informed consent, including obtaining it from third parties and/or using digital means, otherwise pursuant to a Warrant, and only to an extent which is necessary to attain the end and particularly describing the assets to be frozen, the places or Persons to be searched, the things or Persons to be seized, the Persons to be put under surveillance, including the maximum period of that surveillance, and the data to be obtained and stored, including the period for which it may be retained.

**Comment by yopdog** [comment]
And here: §II.5.  §II.7. §II.8. §II.14. §II.22.

>§II.5. **No law shall create victimless and/or consensual crimes**; no Person shall be prosecuted for any offence against society or any part thereof, nor shall an Individual be considered a victim of one's own actions or omissions; an attempt to commit a criminal offence which would cause harm to a potential victim and/or knowingly giving any

>§II.7. No law shall allow for confiscation of private property, either fully or partially, for any purpose other than reparation or the collection of evidence pursuant to a Warrant; **nor shall it regulate the use of property**; anything found in proximity under one’s land or growing naturally on it shall belong to oneself.

>§II.8. No law shall abridge the right of any Individual to the control of their own bodies, **nor interfere with voluntary relations**, nor impinge on the right to form cooperative ventures of any form.

>§II.14. **No law shall regulate** any printed materials, radio, television, **the Internet or any other medium of exchange of information; no law shall regulate the rules concerning uploading, transmitting, displaying, accessing and/or publishing such information**; nor shall any law introduce licensing and/or registration to infringe upon these rights; nothing in this provision shall prevent the Assembly from regulating the rules concerning accessing of private information without the consent of the rightful owner, protection of journalists' sources and minors; no order preventing sharing any information shall be served unless sanctioned by a court of law for the sole purposes of protection of vulnerable parties to a civil or criminal trial or Agents of the Law Enforcement while acting undercover pursuant to a Warrant; the fact that an order has been served shall not be a subject matter of another order.

>§II.22. **No law shall allow for any Individual’s privacy to be violated by** freeze of assets, searches, seizures, surveillance, **accessing and gathering of their personal information without one's express and informed consent, including obtaining it from third parties and/or using digital means, otherwise pursuant to a Warrant**, and only to an extent which is necessary to attain the end and particularly describing the assets to be frozen, the places or Persons to be searched, the things or Persons to be seized, the Persons to be put under surveillance, including the maximum period of that surveillance, and the data to be obtained and stored, including the period for which it may be retained.
