### ISSUE TITLE
explicit prohibition of national debt

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#237]
No law shall allow the Cabinet, or any other branch of the Public Administration, to take a loan, being it foreign or domestic, short or long term; no government bond shall be issued; no debt shall be incurred by any branch of the Public Administration for any purpose; only voluntary donations with no expectation of repayment shall be allowed.

Anyone wants to expand this provision?

**Comment by terrorist96** [comment]
> No law shall allow ~~the Cabinet, or~~ any ~~other~~ branch of the Public Administration~~,~~ to take a loan, being it foreign or domestic, short or long term; no government bond shall be issued; no debt shall be incurred by any branch of the Public Administration for any purpose; only voluntary donations with no expectation of repayment shall be allowed.

Are you going to merge this with:

> §III.16(1) The Annual Budget shall not be with a deficit.

**Comment by KacperZajc** [comment]
No, because national debt is not the same as budget deficit. Id rather keep both.

No law shall allow any  branch of the Public Administration, to take a loan, being it foreign or domestic, short or long term, special or commercial; no government bond shall be issued; no debt shall be incurred by any branch of the Public Administration for any purpose; only voluntary donations with no expectation of repayment shall be allowed.

**Comment by terrorist96** [comment]
Remove the comma after Administration.

**Comment by KacperZajc** [comment]
OK

**Comment by terrorist96** [comment]
> only voluntary donations with no expectation of repayment or **quid pro quo** shall be allowed.

**Comment by KacperZajc** [comment]
OK
