### ISSUE TITLE
hierarchy of law

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#239]
§I.10. The Constitution of the Free Republic of Liberland shall be the supreme law of the Free Republic of Liberland and all Acts passed by the Assembly and all forms of delegated powers as well as all contracts made under the jurisdiction of the Free Republic of Liberland shall comply with the Constitution.

???

**Comment by terrorist96** [comment]
So this would prevent a private company from enslaving you.

We also have this:

> §II.16. No law shall interfere with the content of any contract, nor shall it mandate or forbid any Individual to enter into contractual relations with any other Individual and/or legal Person, or any body of the Public Administration; nor shall it provide any incentive in that respect.

Wouldn't this contradict what you are proposing?

**Comment by KacperZajc** [comment]
law means anything 'less' than the Constitution, that's why we always distinguish between the Constitution and the law

**Comment by terrorist96** [comment]
So contracts must comport with the constitution, but the constitution only says that no laws shall be made instituting slavery, etc. Contracts aren't laws. So a contract could still include slavery in it, for example.
Am I missing something?

**Comment by KacperZajc** [comment]
Surprisingly, that makes sense :/
We should restate this slavery provision.

**Comment by KacperZajc** [comment]
On second thought, it can be constructed as to outlaw slavery in contract. Matter of interpretation, we can reword it anyway.

**Comment by terrorist96** [comment]
If you reword it, wouldn't you have to reword everything?

**Comment by KacperZajc** [comment]
I'll deal with it later.
