### ISSUE TITLE
Serial Commas

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#241]
What kind of style do we want to incorporate into the Constitution? Serial commas or no serial commas?

https://en.wikipedia.org/wiki/Serial_comma
From wiki: For example, a list of three countries might be punctuated either as "France, Italy, and Spain" (with the serial comma), or as "France, Italy and Spain" (without the serial comma).

**Comment by terrorist96** [comment]
should the **decision, action or exercise** of delegated power be aimed at no particular Person, any Citizen shall have standing to seek redress in the Civil Court.

I want to keep it consistent.

No law shall allow for any Person to be held incommunicado either **before, during, or after** the trial.

**Comment by terrorist96** [comment]
From reading some other provisions, it seems like the default style has been to **not** use serial commas.

**Comment by KacperZajc** [comment]
Honestly, I dont mind either. It's up to you. Whatever sounds more formal :)

**Comment by terrorist96** [comment]
Let's put it up to a vote.

**Comment by yopdog** [comment]
I vote for what @terrorist96 votes for.

**Comment by terrorist96** [comment]
I'm personally more experienced with serial commas and prefer them, but in this case I'd vote for no serial commas simply because I don't want to try to hunt down every comma usage/nonusage and scrutinize it.

**Comment by KacperZajc** [comment]
It's entirely up to you and feel free to submit a pull if you want to change any commas.
