### ISSUE TITLE
Judiciary 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#243]
§V.4. The Judges of the Courts of the Free Republic of Liberland shall regulate their own affairs within the Secretariat of the Judiciary of the Free Republic of Liberland.
§V.4(1) The Secretariat of the Judiciary shall be headed by the Chief Justice of the Supreme Court.
§V.4(2) The Secretariat of the Judiciary shall supervise the Judicial Appointment Commission.

§V.5. The Judges of the Courts of the Free Republic of Liberland shall be independent and shall not be removable by any Member of the other branches of the Public Administration.
§V.5(1) The remuneration of the Judges as provided in the Annual Budget shall not be lowered without express consent of the Secretariat of the Judiciary of the Free Republic of Liberland.
§V.5(2) No Judge of any Court of the Free Republic of Liberland shall be arrested for any period whatsoever unless pursuant to the Supreme Warrant or under exigent circumstances where there is a threat to others or where vital evidence may be destroyed; in such case the Chief Justice of the Supreme Court shall be immediately notified about the detainment and shall have the power to order immediate release of the detained Judge.
§V.5(3) The Supreme Warrant shall be issued by the Chief Justice of the Supreme Court with express consent of at least two other Justices of the Supreme Court upon request of the Office of the Public Prosecutor supported by solid evidence of alleged offence.

§V.6. All Judges, other than the Justices of the Supreme Court, shall be appointed by the Chief Justice of the Supreme Court upon the recommendation of the the Judicial Appointment Commission.
§V.6(1) The Judicial Appointment Commission shall be composed of four Justices of the Supreme Court as well as three other members appointed by the Chief Justice of the Supreme Court.
§V.6(2) The Judicial Appointment Commission shall take decisions with a simple majority.
§V.6(3) The Judicial Appointment Commission shall have the power to recommend removal of all Judges, other than the Justice of the Supreme Court, from the office upon proven case of gross misconduct or intentional procurement of miscarriage of justice.
§V.6(4) The removal of a Judge from the office shall be executed by the Chief Justice of the Supreme Court.

Renumber the rest of the provisions in the Article...

**Comment by terrorist96** [comment]
> §V.5(1) The remuneration of the Judges as provided **for** in the Annual Budget shall not be lowered without **the** express **and informed** consent of the Secretariat of the Judiciary of the Free Republic of Liberland.

> §V.5(3) The Supreme Warrant shall be issued by the Chief Justice of the Supreme Court with **the** express **and informed** consent of at least two other Justices of the Supreme Court upon request ~~of~~ **by [or `upon the request of`]** the Office of the Public Prosecutor supported by ~~solid~~ **clear and convincing** evidence of **the** alleged offence.

So if a majority of the Justices support issuing the Supreme Warrant, but the Chief does not, it can't be issued? And what if the Chief isn't available to issue it? 

> §V.6(1) The Judicial Appointment Commission shall be composed of four Justices of the Supreme Court as well as three other members appointed by the Chief Justice of the Supreme Court.

So it's composed of all 4 of the other Justices (excluding the Chief?) plus 3 of the Chief's nominations?

> §V.6(2) The Judicial Appointment Commission shall ~~take~~ **make** decisions with a simple majority.

> §V.6(3) The Judicial Appointment Commission shall have the power to recommend **the** removal of all Judges, other than the Justice**s** of the Supreme Court, from ~~the~~ office upon **a** proven case of gross misconduct or intentional procurement of miscarriage of justice.

So the JAC can recommend removal *after* it's been proven the Judge is corrupt? What's the point of that? They should recommend for the judge to be investigated, then when found guilty, the judge would automatically be removed from office.

**Comment by KacperZajc** [comment]
§V.4. The Judges of the Courts of the Free Republic of Liberland shall regulate their own affairs within the Secretariat of the Judiciary of the Free Republic of Liberland.
§V.4(1) The Secretariat of the Judiciary shall be headed by the Chief Justice of the Supreme Court.
§V.4(2) The Secretariat of the Judiciary shall supervise the Judicial Appointment Commission.
§V.4(3) The Secretariat of the Judiciary shall supervise all Agents of the judicial branch of the Public Administration.

§V.5. The Judges of the Courts of the Free Republic of Liberland shall be independent and shall not be removable by any Member of the other branches of the Public Administration.
§V.5(1) The remuneration of the Judges as provided for in the Annual Budget shall not be lowered without the express and informed consent of the Secretariat of the Judiciary of the Free Republic of Liberland.
§V.5(2) No Judge of any Court of the Free Republic of Liberland shall be arrested for any period whatsoever unless pursuant to the Supreme Warrant or under exigent circumstances where there is a threat to others or where vital evidence may be destroyed; in such case the Chief Justice of the Supreme Court shall be immediately notified about the detainment and shall have the power to order immediate release of the detained Judge.
§V.5(3)  The Supreme Warrant shall be issued by the Secretariat of the Judiciary of the Free Republic of Liberland as signed by the Chief Justice of the Supreme Court or at least three Justices of the Supreme Court upon the request of the Office of the Public Prosecutor supported by solid clear and convincing evidence of the alleged offence.

§V.6. All Judges, other than the Justices of the Supreme Court, shall be appointed by the Chief Justice of the Supreme Court upon the recommendation of the the Judicial Appointment Commission.
§V.6(1) The Judicial Appointment Commission shall be composed of four Justices of the Supreme Court as well as three other members appointed by the Chief Justice of the Supreme Court.
§V.6(2) The Judicial Appointment Commission shall make decisions with a simple majority.
§V.6(3) The Judicial Appointment Commission shall have the power to inquire into alleged misconduct of all Judges of all Courts in the Free Republic of Liberland.
§V.6(4) The Judicial Appointment Commission shall have the power to recommend the removal of all Judges, other than the Justices of the Supreme Court, from the office upon a proven case of gross misconduct or intentional procurement of the miscarriage of justice.
§V.6(5) The removal of a Judge from the office shall be executed by the Chief Justice of the Supreme Court.

???

Yes the Judicial Appointment Commission is composed of all 4 of the other Justices (excluding the Chief) plus 3 of the Chief's nominations. Any problem with that? :)

**Comment by terrorist96** [comment]
> Yes the Judicial Appointment Commission is composed of all 4 of the other Justices (excluding the Chief) plus 3 of the Chief's nominations. Any problem with that? :)

Nope, just worded weirdly. :stuck_out_tongue:
