### ISSUE TITLE
Assembly governance 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#244]
§III.3. The Assembly shall elect the Assembly Speaker with a simple majority vote of all Assembly Representatives.
§III.3(1) The Assembly Speaker shall head the Bureau of the Assembly of the Free Republic of Liberland. 
§III.3(2) The Bureau of the Assembly shall administer the work of the Assembly.
§III.3(3) The Bureau of the Assembly shall supervise all Agents of the legislative branch of the Public Administration.
§III.3(4) No Agent of the Law Enforcement shall enter the premises of the Assembly unless with the express and informed consent of the the Bureau of the Assembly or pursuant to a Warrant.

**Comment by terrorist96** [comment]
:+1:
