### ISSUE TITLE
speedy trial

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#248]
> §II.38. No law shall deprive a defendant under prosecution of one’s right to a speedy and public trial by an impartial jury;

Combining `a speedy and public trial` with `trial by jury` will result in a guarantee to only that, and not a speedy and public trial without a jury (bench trial).

How would you prefer to resolve this?

**Comment by KacperZajc** [comment]
let's merge II.38 and II.27:

No law shall allow for any Person to be sentenced without due process of law; due process of law shall include the right to a speedy public trial, by an impartial jury, to be informed of criminal charges and to confront witnesses and to compel witnesses to appear in court, to be presumed innocent until proven guilty beyond reasonable doubt, to not be compelled to be a witness against oneself, or Persons whose penalization one would rightfully feel as the penalization of oneself, to the assistance of a legal counsel and of an interpreter if one does not speak the language in which the hearing is conducted, free of charge where appropriate, to an impartial hearing of one’s case, to be informed of one’s rights; any Person who has one's rights to due process of law violated, either illegally or in error, shall receive fair compensation from all Persons responsible for the violation.

**Comment by terrorist96** [comment]
> No law shall allow for any Person to be sentenced...

Why remove `arrested, prosecuted,`?

> without due process of law; due process of law shall include the right to a speedy**,** public **and impartial** trial~~,~~**; trial** by an impartial jury **if requested**~~,~~**;** to be informed of criminal charges and **one's rights;**~~,~~ to ~~confront witnesses and to~~ compel witnesses to appear in court **for confrontation;**~~,~~ to be presumed innocent until proven guilty beyond reasonable doubt~~,~~**;** to not be compelled to be a witness against oneself, or Persons whose penalization one would rightfully feel as the penalization of oneself~~,~~**;** to the assistance of ~~a~~ legal counsel and ~~of an interpreter~~ **interpretation,** if one does not speak the language in which the hearing is conducted, free of charge where appropriate, ~~to an impartial hearing of one’s case, to be informed of one’s rights~~; 

Why remove `and observing the law and the Constitution at every stage of dealing;`

> any Person who has one's rights to due process of law violated, either illegally or in error, shall receive fair compensation from all Persons responsible for the violation.

**Comment by KacperZajc** [comment]
we already have rules for arresting (to which what we say here does not apply really);
'process of law' is prosecution when you think about that;
trial by jury is not optional and should not be because people might be forced to 'voluntarily' choose it;
why remove 'to an impartial hearing of one’s case, to be informed of one’s rights;'?

**Comment by terrorist96** [comment]
> trial by jury is not optional and should not be because people might be forced to 'voluntarily' choose it

Even if someone wishes to be tried by a judge (and not a jury)? I don't understand why someone would be forced to 'voluntarily' choose trial by jury or judge.

> why remove 'to an impartial hearing of one’s case, to be informed of one’s rights;'?

Because I moved it to the beginning of the provision.

**Comment by KacperZajc** [comment]
it is easier to get conviction with a judge (instead of jury) only so the gov might put pressure (they are good at putting different forms of pressure) on the accused so that he or she chooses trial without jury;

No law shall deprive the defendant under prosecution of one's right to a speedy, public and impartial trial by an impartial jury; to be informed of criminal charges and of one's rights; to compel witnesses to appear in court for confrontation; to be presumed innocent until proven guilty beyond reasonable doubt; to not be compelled to be a witness against oneself, or Persons whose penalization one would rightfully feel as the penalization of oneself; to the assistance of a legal counsel and interpretation, if one does not speak the language in which the hearing is conducted, free of charge where appropriate; and to all other Rights guaranteed by the Constitution and all laws passed in accordance thereof; should any Person be prosecuted in breach of due process of law as enumerated in this provision, the trial Judges shall take that under advisement when considering dismissing the charges; should any Person be sentenced in breach of due process of law and the verdict is overturned on the appeal, the right to compensation shall be guaranteed. 

I think now this whole provision makes more sense.

???

**Comment by terrorist96** [comment]
> it is easier to get conviction with a judge (instead of jury) only so the gov might put pressure (they are good at putting different forms of pressure) on the accused so that he or she chooses trial without jury;

If they want to apply pressure, they will offer a plea deal so that no one has to go to trial. Not including trial by judge as a protected right doesn't make it disappear though. It can still be so that the trial by jury is a right, but you can also choose a trial by a judge if you don't wish to exercise the right to a jury. So I guess we can leave this the way it is. But the government can still 'force' you to not exercise your right to trial by jury unless we expressly forbid bench trials (which I'd be against).

**Comment by terrorist96** [comment]
> No law shall deprive ~~the~~ **a** defendant under prosecution of one's right to a speedy, public and impartial trial by an impartial jury; to be informed of criminal charges and of one's rights; to compel witnesses to appear in court for confrontation; to be presumed innocent until proven guilty beyond reasonable doubt; to not be compelled to be a witness against oneself, or Persons whose penalization one would rightfully feel as the penalization of oneself; to the assistance of ~~a~~ legal counsel and interpretation, if one does not speak the language in which the hearing is conducted, free of charge where appropriate; and to all other Rights guaranteed by the Constitution and all laws passed in accordance thereof.
**(1)** Should any Person be prosecuted in breach of due process of law as enumerated in this provision, the trial Judges shall take that under advisement when considering dismissing the charges; should any Person be sentenced in breach of due process of law and the verdict is overturned on the appeal, the right to **fair** compensation shall be guaranteed.

Isn't (1) covered by II.29?
> No law shall allow for any evidence which was obtained illegally or unconstitutionally by any Agent or Member of the Public Administration to be admitted in the Criminal Court

You can't be prosecuted without evidence. So any evidence obtained would be suppressed, leading to automatic dismissal. Maybe this covers legally obtained evidence, but if there were still other violations of the person's right to due process? (like not letting the suspect contact an attorney)

Additionally, compensation is awarded only if you're sentenced without full due process? What about being prosecuted without due process? What if you're sentenced with due process, but you're found innocent on appeal? Any compensation for that?

**Comment by KacperZajc** [comment]
2 separate provisions, one that deals with compensation only:

No law shall deprive a defendant under prosecution of one's right to a speedy, public and impartial trial by an impartial jury; to be informed of criminal charges and of one's rights; to compel witnesses to appear in court for confrontation; to be presumed innocent until proven guilty beyond reasonable doubt; to not be compelled to be a witness against oneself, or Persons whose penalization one would rightfully feel as the penalization of oneself; to the assistance of a legal counsel and interpretation, if one does not speak the language in which the hearing is conducted, free of charge where appropriate; and to all other Rights guaranteed by the Constitution and all laws passed in accordance thereof; should any Person be prosecuted in breach of due process of law as enumerated in this provision, the trial Judges shall take that under advisement when considering dismissing the charges or overturning the verdict.

No law shall deprive a Person of one’s right to fair compensation for all and every day spent incarcerated, either before or after the trial, should said Person be held not guilty by the Jury or, despite being held guilty by the Jury, should the verdict be overturned on the appeal.

**Comment by terrorist96** [comment]
Remove `a` prior to legal counsel.

No law shall deprive a Person of one’s right to fair compensation for **any and** all ~~and every~~ day**s** spent incarcerated, either before**, during** or after the trial, should said Person be ~~held~~ **found** not guilty by the Jury or~~, despite being held guilty by the Jury,~~ should ~~the~~ **a guilty** verdict be overturned on the appeal.

Just a clarification, there is only one court that you can appeal to (the Supreme Court), right? No intermediate Court of Appeals/Circuit Courts? If so, `the appeal` is correct. Otherwise, it should be `a appeal`.

**Comment by KacperZajc** [comment]
yes one only, changes made :)
