### ISSUE TITLE
All laws should sunset by the end of next legislature

### ISSUE THREAD

**Issue by fare** [liberland/constitution#25]
The next legislature should have time to renew the law.

Good laws that everyone agrees with will be renewed every time. Bad laws that require bickering will consume a finite pool of bickering resources, ensuring a finite amount of bad laws that can't accumulate with time.

**Comment by fare** [comment]
(This issue is split from #20)

**Comment by cpacia** [comment]
+1

**Comment by KacperZajc** [comment]
I still cant agree with this one sorry.

**Comment by fare** [comment]
If you think stability is important, have the sunset be two legislatures plus one year instead of one legislature plus one year — this way, laws that require stability can have a longer horizon.

I think it is very important to have a mechanism to prevent the accumulation of bad laws, cruft, etc., anything that will make "no one shall ignore the law" a bad joke. Automatic sunset, forcing legislators to confirm every law at every legislature, is such a mechanism. Combined with a forced reading of the law during the vote, it puts a natural cap on the total size of the code, which is a good thing.

If there are laws everyone agrees upon, each legislature will fast-track them, so that's not a problem.

**Comment by tinkyholloway** [comment]
@KacperZajc I really think this is important. Please list your concerns and allow an opportunity to convince you of the merits and allay your fears.

**Comment by KacperZajc** [comment]
we need stable laws, we need law that people now, we need to be predictable, how will you teach lawyers what the law is if it change change entirely every 4 years? not to mention that normal people dont have time to track all laws all the time because they all can change at once.

Our international partner have to know we are predictable, that we wont change the whole system every 4 years. 

i understand your intention guys but this is not the way to go

**Comment by fare** [comment]
This is a duplicate of #13

**Comment by fare** [comment]
There is no reason to believe that good laws that people expect to still be there would be voted down when set for renewal. Renewal should not require a referendum, but still a vote by the legislature and a complete reading, which ensures uncontroversial laws can be renewed quickly whereas bad laws don't last too long.

If you want a law to last long (1) make it short, (2) make it uncontroversial, (3) don't include unrelated articles (as is common practice in the US). Sunsetting is a great filter that allows good laws to survive while killing bad laws.

For more stability, make the sunset longer than one legislature, for instance two or three legislatures.

Note that as far as the threat of instability goes, legislative powers already mean that any law you trust can be repealed, modified, corrupted, etc., by the next legislature. If you really want more stabiity than is inherent in legislation, what you want is not to not have sunset laws, but to have "no amendment" article that prohibits amendements to the law for the next N legislative terms.

**Comment by fare** [comment]
Dammit, should have written that on #13. Copying...
