### ISSUE TITLE
Excessive right to privacy and free speech issues.

### ISSUE THREAD

**Issue by yopdog** [liberland/constitution#250]
>§II.22. No law shall allow for any Individual’s privacy to be violated by...  accessing and gathering of their personal information without one's express and informed consent, including obtaining it from **third parties and/or using digital means**

I have an issue with provision §II.22 concerning the part that forbids obtaining personal information about someone from a third party. I know this is meant to prevent the government from seizing personal information through companies (third parties), but this could have larger ramifications. A third-party basically includes every node on the internet. The provision could give Individuals the right to privacy even when their personal information is in the public domain. In other words, it could be illegal to share and transfer personal information about a person without his consent even when he no longer controls that information. 

The problem lies with what can be defined as private information. If someone loses control over his   personal information, and it's now all over the web, is it still illegal to share and transfer that information without his consent? 

I also have some questions about provision §II.14. concerning the second part:

>nothing in this provision shall prevent the Assembly from regulating the rules concerning accessing of private information without the consent of the rightful owner, **protection of journalists' sources and minors;** no order preventing sharing any information shall be served unless sanctioned by a court of law for the sole purposes of **protection of vulnerable parties to a civil or criminal trial** or **Agents of the Law Enforcement while acting undercover pursuant to a Warrant;** the fact that an order has been served shall not be a subject matter of another order. 

What does the "protection of journalists' sources and minors" part mean? If I discover a journalist's source, can the Government make a law that prevents me from talking about it? And what is the part about minors? Furthermore, why is the government allowed to regulate the sharing of information concerning undercover police? Am I not allowed to tell anybody that the police was in my house just because they were wearing civilian clothes?

**Comment by terrorist96** [comment]
> The problem lies with what can be defined as private information

This can be defined by law.

> If someone loses control over his personal information, and it's now all over the web, is it still illegal to share and transfer that information without his consent?

This is a valid point. I'd argue that if the private information is publicly accessible, it no longer fits the definition of `private`. The person could petition to have the information scrubbed from the Internet, and the person who posted the private info without the owner's consent can be held liable legally too.

> journalists' sources

It only means that the government can make laws that protect the sources of journalists from forced exposition. If the journalists' source is public, then they don't require protection.

> Furthermore, why is the government allowed to regulate the sharing of information concerning undercover police? Am I not allowed to tell anybody that the police was in my house just because they were wearing civilian clothes?

If a cop comes to you in civilian clothes and tells you he's a cop, then he's not really acting undercover, now is he? :stuck_out_tongue:
If his cover has been blown, then he's not undercover anymore.

I do agree that we need more discussion on these sections though.

**Comment by KacperZajc** [comment]
@terrorist96 's explanation is very accurate;

@yopdog I think you are partially right about obtaining information from 3rd parties - 

we should rephrase:

...including compelling third parties to share such information and/or using digital means...

???

**Comment by terrorist96** [comment]
Compelling > obtaining.

**Comment by KacperZajc** [comment]
... including obtaining it from third parties, unless given voluntarily, and/or using digital means...

???

**Comment by terrorist96** [comment]
You misunderstood. I am in favor of `compelling` as opposed to `obtaining`.
Compelling > obtaining means I choose compelling.

**Comment by terrorist96** [comment]
Actually let's change it to `requesting`. Because compelling sounds like they're forcing a company to give it up, whereas requesting prevents the government from even asking. Voluntary surrender of the information by the company shouldn't be allowed because the company should be responsible for keeping the info private absent a warrant.

**Comment by terrorist96** [comment]
accessing and gathering of their personal information without one's express and informed consent, including ~~obtaining~~ **requesting** it from third parties and/or using digital means

**Comment by KacperZajc** [comment]
I think they should be allowed to ask.
Id go back to compelling then :)

**Comment by terrorist96** [comment]
But they can only compel with a warrant. How could they compel without a warrant? At gunpoint? Since they can't compel without a warrant, forbidding compelling doesn't do much. The problem is the sharing of user data between companies and governments without warrants. It should be forbidden without a warrant.

**Comment by yopdog** [comment]
Concerning the issue of excessive privacy, I have my own suggestion. We could add at the end of the provision a statement that would make it clear that there is no right to privacy once information has been made public: 

§II.22. No law shall allow for any Individual’s privacy to be violated by freeze of assets, searches, seizures, surveillance, accessing and gathering of their personal information without one's express and informed consent, including obtaining it from third parties and/or using digital means, otherwise pursuant to a Warrant, and only to an extent which is necessary to attain the end and particularly describing the assets to be frozen, the places or Persons to be searched, the things or Persons to be seized, the Persons to be put under surveillance, including the maximum period of that surveillance, and the data to be obtained and stored, including the period for which it may be retained; **nothing in this provision shall prevent the accessing and sharing of information which has been made available to the public, regardless of the means by which it has been made public.**

**Comment by KacperZajc** [comment]
I think this is a matter of contract what a company does with you personal info.
But 3rd parties are also regular people who share information about their neighbours with the Police.
