### ISSUE TITLE
one-off projects

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#253]
It is the very nature of all governments that they seek the ways to extend their powers. Consequently it always leads to a distorted interpretation of the Constitution. In order to prevent that, we should include a provision that would enable certain controlled ways that allow ‘doing stuff’. Thereby we channel the pressure into the route that we control. On some occasions there might be projects worth government involvement (e.g. Louisiana Purchase). Here is my idea – one-off project financed through voluntary donations and managed by the Assembly.

The Assembly shall have power to execute the Project proposed to it by the Citizens.
1.	The Project shall be financed by the Citizens and Residents of the Free Republic of Liberland and other Persons whatsoever, through voluntary donations for that very purpose.
2.	The Project shall not be funded or partially funded from the Annual Budget.
3.	The Project shall pertain to any one material matter whatsoever.
4.	The Project shall not require the Assembly to pass any new law or amend any existing one.
5.	The Project shall not require continuous involvement and/or financing. 
6.	The Project shall be proposed to the Assembly by at least 5% of all Citizens.
7.	The Project shall not be contrary to the Constitution.
8.	The Project shall be executed only if all funds necessary for its completion are collected within one year. 
9.	The execution of the Project shall not take more than one year since the necessary funding been collected.
10.	Should the necessary funding be not obtained within one year, the Project shall be discarded. 
11.	The Project shall be consented to by the Assembly with a majority of two-thirds of all Assembly Representatives. 
12.	The execution of the Project shall be supervised by the Bureau of the Assembly.

**Comment by terrorist96** [comment]
Couldn't a private company handle such projects? Why do we need the government to be involved?

**Comment by yopdog** [comment]
As long as it's through voluntary donations I'm ok with it.

**Comment by terrorist96** [comment]
> 7. The Project shall not be contrary to the Constitution

I thought the whole point was for the Assembly to be able to do something that's not authorized by the Constitution?

**Comment by KacperZajc** [comment]
naturally, I meant other provisions than areas of competence

**Comment by KacperZajc** [comment]
#281
