### ISSUE TITLE
separating powers

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#256]
I think it would be a good idea to separate the Cabinet and the Assembly. If we forbid drawing members of the Cabinet from the Assembly Representatives there will be a better chance Assembly Representatives are more independent and do not give in to any wish of the Chancellor. Such fusion of powers is a big problem in all non-presidential system.

§IV.2(2) No Person shall be the Chancellor or a Member of the Cabinet and hold the position of the Assembly Representative at the same time.

What do you think guys?

**Comment by terrorist96** [comment]
> §IV.2(2) No Person shall ~~be the~~ **hold the position of** Chancellor or ~~a~~ Member of the Cabinet ~~and~~ **while** hold**ing** the position of ~~the~~ Assembly Representative ~~at the same time~~ **concurrently**.

**Comment by KacperZajc** [comment]
Okk
