### ISSUE TITLE
new changes

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#257]
rephrasing: 

§II.21. No law shall allow for the application of torture or other cruel, unusual or degradation treatment by any Agent of the Public Administration or under supervision or knowledge thereof, whether within or outside the jurisdiction of the Free Republic of Liberland, against any Person; nor shall any experiments, medical or otherwise, be done against any Person without one’s express and informed consent.

§II.29. No law shall allow for any evidence which was obtained illegally or unconstitutionally by any Agent or Member of the Public Administration to be admitted in the Criminal Court unless the violation of law was committed by a third party who did not act under direction and/or supervision of said Agent or knowledge thereof.

§II.10. The Constitution of the Free Republic of Liberland shall be the supreme law of the Free Republic of Liberland and as such shall be directly enforceable before all Courts of the Free Republic of Liberland; all Acts passed by the Assembly and all forms of delegated powers as exercised by the Cabinet shall comply with the Constitution; no international treaty shall be signed by the Cabinet unless the Supreme Court issues a statement confirming that a relevant treaty does not contravene the Constitution; all contracts between any legal and/or natural Persons, including all branches of the Public Administration, made under the jurisdiction of the Free Republic of Liberland shall comply with the Constitution.

§II.19. No law shall allow for any Individual to be compelled to identify themselves to any Agent of the Public Administration, otherwise upon arrest or pursuant to a Warrant; no Individual shall be searched, medically examined or otherwise tested unless pursuant to a Warrant or with the express and informed consent.

§II.6. No law shall allow for the existence of any relationship between any legal or natural Person and any other Person which would amount to slavery or any other form of involuntary servitude; no conscription or any other form of compulsory service shall be introduced by any branch of the Public Administration.

§II.18. All data collected by the Public Administration shall be used only for the direct and necessary purposes for which it was originally collected, and shall be kept confidential and shared only with the express and informed consent of the rightful owner or otherwise in accordance with the provisions of this Constitution; all Individuals whose data is stored by any body of the Public Administration other than the Law Enforcement shall have access to it and shall retain the right to demand its destruction at any time; nothing in this provision shall prevent the Public Administration from maintaining a register of owners of land within the Free Republic of Liberland.

§II.34. No law shall allow for any Person to be prosecuted for the relevant criminal offence any later than a year since the Warrant for custody of said Person was executed and the Person was taken into custody; the deadline shall be renewed for any and all subsequent Warrants for custody in the event of escape and/or subsequent offence.

§II.17. Substitute ‘Citizen’ for the first ‘Individual’

I also want to remove §II.13. as it is covered by the Freedom of Contract provision.

**Comment by terrorist96** [comment]
> §II.21. No law shall allow for the application of torture or other cruel, unusual or ~~degradation~~ **degrading** treatment by any Agent **or Member** of the Public Administration or under **the** supervision or knowledge thereof, whether within or outside the jurisdiction of the Free Republic of Liberland, against any Person **against their will**; nor shall any experiments, medical or otherwise, be done against any Person without one’s express and informed consent.

> §II.29. No law shall allow for any evidence which was obtained illegally or unconstitutionally by any Agent or Member of the Public Administration to be admitted in the Criminal Court unless the violation of law was committed by a third party who did not act under **the** direction and/or supervision of said Agent **or Member** or knowledge thereof.

> §~~II.10.~~ **I.10. The Constitution of the Free Republic of Liberland shall be the supreme law of the Free Republic of Liberland and as such shall be directly enforceable before all Courts of the Free Republic of Liberland; all Acts passed by the Assembly and all forms of delegated powers as exercised by the Cabinet shall comply with the Constitution; no international treaty shall be signed by the Cabinet unless the Supreme Court issues a statement confirming that ~~a~~ **the** relevant treaty does not contravene the Constitution; all contracts between any legal and/or natural Persons, including all branches of the Public Administration, made under the jurisdiction of the Free Republic of Liberland shall comply with the Constitution.

Simply majority required for the Supreme Court to say the treat is constitutional? Unanimous?

> §II.17. Substitute ‘Citizen’ for the first ‘Individual’

Why?

> I also want to remove §II.13. as it is covered by the Freedom of Contract provision.

Is it?

**Comment by KacperZajc** [comment]
Regarding international treaties:

§V.8(4) The Supreme Court shall have jurisdiction to issue statements which clarify the law of the Free Republic of Liberland upon the request submitted by the Cabinet; such statements are binding upon lower Courts in all future proceedings where applicable.

Default position is decision are reached with a simple majority. 
No need to change that, signing a treaty does not make it enforceable before courts (does not make it law of the land) only binds the gov vis a vis other states (which is unenforceable). Only passing a Treaty Bill makes it enforceable before national courts and this requires unanimous declaration of constitutionality as for any other Bill.

§II.17: We might wanna keep track of certain foreigners.

§II.13: Seems to me it is, if the gov regulates the contents of the curriculum, the school cannot contract with the pupil to teach any other contents of the curriculum. Does it makes sense?

**Comment by terrorist96** [comment]
Why would we need to keep track of foreigners? What if someone lives in Liberland but chooses to remain a resident and not obtain citizenship?

> §II.13: Seems to me it is, if the gov regulates the contents of the curriculum, the school cannot contract with the pupil to teach any other curriculum. Does it makes sense?

Kinda, I guess.

**Comment by KacperZajc** [comment]
I guess there might be some people we'd like to have an eye on. I just dont want to close this possibility.

**Comment by terrorist96** [comment]
We already allow for it for non-individuals.
