### ISSUE TITLE
financial provisions

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#260]
§II.7. No law shall allow for confiscation of private property, either fully or partially, for any purpose other than reparation, lawfully levied fines and/or the collection of evidence pursuant to a Warrant; nor shall it regulate the use of property; anything found in proximity under one’s land or growing naturally on it shall belong to oneself.

§III.16. The Financial Bill containing the provisions of the Annual Budget shall be passed with a simple majority vote of all Assembly Representatives and shall be subject to the power of general veto by the Citizens as provided in §III.17.
§III.16(1) The Annual Budget shall constitute the only source of financial provisions for the Free Republic of Liberland.
§III.16(1) The Annual Budget shall be financed from the State Treasury maintained by the Department of Treasury.
§III.16(2) No provision of the Annual Budget shall provide for any spending which is not authorised by this Constitution.
§III.16(3) All fees collected by the Public Administration and all pledged systematic voluntary donations shall be transferred to the State Treasury and thereby included in the Annual Budget.
§III.16(4) All fines and spontaneous voluntary donations shall be transferred to the State Reserve System.
§III.16(5) The Annual Budget shall be calculated using realistic assumptions as to the anticipated revenue.
§III.16(6) The Annual Budget shall be calculated so that the anticipated revenue does not exceed the actual revenue. 
§III.16(7) The size of the Annual Budget shall not exceed the previous year actual revenue.
§III.16(8) Should the actual revenue exceeded the anticipated revenue, the surplus shall be transferred to the State Reserve System.
§III.16(9) Should the actual revenue fell short of the anticipated revenue, the deficit shall be covered from the funds gathered in the State Reserve System.
§III.16(10) Should the funds gathered in State Reserve System were not able to cover the deficit, all Assembly Representatives shall cover the difference with their own personal assets, divided equally.
§III.16(11) The State Reserve System shall be maintained by the Bureau of the Assembly.
§III.16(12) The funds gathered in the State Reserve System shall be diversified therefore kept in various stable currencies and precious metals. 

§II.43. No law shall allow for any provision of the Annual Budget to finance or partially finance any political party, any form of insurance, healthcare services, education and/or pension schemes; no direct or indirect bailout of any legal or natural person shall be financed or partially financed by any provision of the Annual Budget; no purchase of any amount of shares of any legal Person by any branch of the Public Administration, nor any loan to any legal or natural Person shall be financed or partially financed by any provision the Annual Budget; no purchase of land and/or any movable assets shall be financed or partially financed by any provision the Annual Budget unless necessary for functioning of the Public Administration as provided in the Constitution.

**Comment by terrorist96** [comment]
> §III.16(5) The Annual Budget shall be calculated using realistic assumptions as to the anticipated revenue.
§III.16(6) The Annual Budget shall be calculated so that the anticipated revenue does not exceed the actual revenue. 

These would be hard to define and enforce.

> §III.16(9) Should the actual revenue ~~fell~~ **fall** short of the anticipated revenue, the deficit shall be covered from the funds gathered in the State Reserve System.
§III.16(10) Should the funds gathered in State Reserve System ~~were~~ not **be** able to cover the deficit, all Assembly Representatives **who voted in favor of the Financial Bill** shall cover the **remaining** difference with their own personal assets, divided equally.

I think making it so that those who voted to cause the deficit should be held responsible.

> §III.16(12) The funds gathered in the State Reserve System shall be diversified therefore kept in various stable currencies and precious metals.

Hard to define/enforce.

II.43 could probably be restated to only say "finance or partially finance" just once instead of 4 times.

**Comment by KacperZajc** [comment]
I know some are hard to enforce but they will have to pay themselves and this is the best incentive there is.
