### ISSUE TITLE
Potential contradiction between Preamble and provision §I.2. 

### ISSUE THREAD

**Issue by yopdog** [liberland/constitution#263]
I'm not sure provision §I.2. is a good idea since it seems to contradict   The Preamble to the Constitution. The Preamble basically allows for a situation where a new government can be established if a present government becomes tyrannical and unjust, as stated in the text:     

>"we declare that whenever the Public Administration becomes an obstacle to, rather than a guarantor of, our Rights, **it shall be our duty to alter or abolish such government, and to institute a new government** for the restoration of the Rights which we consider inherent in all human beings."

Provision §I.2. on the other hand says the exact opposite, essentially forbidding the creation of a new government under any circumstances.      

>§I.2. The Free Republic of Liberland shall be governed by the Public Administration and **no other form of government shall be established;** no special branch of the Public Administration which is not provided for in the Constitution shall come into existence; no municipal or district governing body shall be established.

I don't believe we should have a provision that establishes the government as the one and only government that can ever exist. A government which can never be abolished is a government which cannot be challenged.

**Comment by KacperZajc** [comment]
the purpose of the provision is to make sure the constitutional protection is not avoided by creating another form of the government;
but you are right these provision seem inconsistent;
we need to work on the preamble a bit :)

**Comment by yopdog** [comment]
I actually think the preamble is good the way it is. The problem is with this provision that basically states that the government has the right to exist no matter what it becomes. 

>the purpose of the provision is to make sure the constitutional protection is not avoided by creating another form of government;   

Yes, but what if the government isn't following the Constitution or has changed it to no longer protect the rights it originally did? I think this provision will achieve the exact opposite of what it intended. The goverment will be able to compleatly change (ignoring the Constitution in the proccess) and still be considered legitimate according to the Constitution. If the goverment is truly 'of the people' then it should be in the Citizens power to abolish a goverment that is tyrannical and institute a new goverment (or even a new Constitution) that will protect their rights.

**Comment by KacperZajc** [comment]
which one you like better:

The Free Republic of Liberland shall be governed by the Public Administration and no concurrent or otherwise form of government shall be established so long as the Constitution is observed; no special branch of the Public Administration which is not provided for in the Constitution shall come into existence; no municipal or district governing body shall be established.

or

The Free Republic of Liberland shall be governed by the Public Administration and no concurrent or otherwise form of government shall be established; no special branch of the Public Administration which is not provided for in the Constitution shall come into existence; no municipal or district governing body shall be established; should the Public Administration abandon the Constitution, the Citizens of the Free Republic of Liberland shall have the right and duty to abolish such government.

???

**Comment by terrorist96** [comment]
I prefer the second. However, if we have the Supreme Court review every law for constitutionality, it would be hard for the government to depart from the constitution. And if the Supreme Court itself departs from the constitution, they can be recalled and replaced. I feel like this is an unnecessary provision overall.

**Comment by KacperZajc** [comment]
This is in case we have a government with total disregard for the Constitution which uses violence against citizens.

**Comment by yopdog** [comment]
I agree with @terrorist96 that this provision is unnecessary. What's more, I would argue that this provision actually reduces the freedom of the Citizens rather than increasing it. The PA is already limited by provision §I.3. when it comes to creating new branches of government since the Constitution doesn't grant them that power. What this provision really does is limit the power of the citizens to choose the laws and institutions they live under. It's definitely better now with the exception for a tyrannical government, but it does bring up the question why we need this provision in the first place.

**Comment by KacperZajc** [comment]
Public Administration is prevented from creating new branches but there is nothing that would prevent creation of another government (other than PA). I want to keep this provision because it ensures that no new form of government can rise and thereby avoid constitutional restrictions.

**Comment by yopdog** [comment]
How would a new government start exactly? If a small group of citizens want to start their own government with its own laws, it will inevitably violate the constitution. In other words, any creation of a new government (and new laws) would be by it's very nature be illegal simply because it's not following the laws that already exist. The constitution already forbids the creation of new governments through provisions §I.1. and §I.5. (which should probably be merged) by asserting that the constitution is binding upon everyone. It's for these reasons that I think it's unnecessary to have this provision.
