### ISSUE TITLE
minor provisions

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#267]
new provisions:

§III.1(5) Should any Assembly Representative step down or was compelled to step down under provisions of this Article, the Supplementary Election shall be held.
§III.1(6) The Assembly shall be in session three weeks every month for nine months a year; should the situation required the Assembly might reconvene at any time whatsoever upon the call of the Assembly Speaker.
§III.1(7) All Assembly Representatives shall receive remuneration for their service as provided in the Annual Budget.

§V.8(9) The Supreme Court shall have jurisdiction to judge the validity of all elections and referendums held in the Free Republic of Liberland.

§III.14(7) Neither Taxation Bill, nor any other Bill shall impose any form of duty on goods, services and/or capital exported to, or imported from, the Free Republic of Liberland.

§IV.5(11) to bestow honours and awards on Persons who have achieved a great deal in service of Liberland and the idea of liberty worldwide. 

§IV.2(3) All Members of the Cabinet shall receive remuneration for their service as provided in the Annual Budget.

**Comment by terrorist96** [comment]
> §III.1(5) Should any Assembly Representative step down ~~or was compelled to step down under provisions of this Article~~, the Supplementary Election shall be held.

What about recall elections?

> §III.1(6) The Assembly shall be in session **for** three weeks **of** every month for nine months a year; ~~should the situation required~~ the Assembly ~~might~~ **may** reconvene at any time whatsoever upon the call of the Assembly Speaker.
§III.1(7) All Assembly Representatives shall receive remuneration for their service as provided in the Annual Budget.

We shouldn't allow for Reps to raise their own salaries.

> §V.8(9) The Supreme Court shall have jurisdiction to judge the validity of all elections and referendums held in the Free Republic of Liberland.

§III.14(7) Neither Taxation Bill, nor any other Bill shall impose any form of duty on goods, services and/or capital exported to, or imported from, the Free Republic of Liberland.

Shouldn't this be the other way around? (imported into, or exported from)

> §IV.5(11) to bestow honours and awards on Persons who have achieved a great deal in service of Liberland and the idea of liberty worldwide.
§IV.2(3) All Members of the Cabinet shall receive remuneration for their service as provided in the Annual Budget.

**Comment by KacperZajc** [comment]
I dont mind recall process, it's up for a debate.
Yes, (imported into, or exported from :)
