### ISSUE TITLE
Every law needs include an explicit rationale

### ISSUE THREAD

**Issue by fare** [liberland/constitution#27]
And citizens can sue and nullify the law if its rationale fails to hold, is not valid anymore, if the desired effect isn't achieved by the law, etc.

This makes it harder for laws to be remain on the book when they utterly fail at what they claim to do and are actually a way to subsidize special interests through their "unintended consequences".

**Comment by fare** [comment]
(This issue is split from #20)

**Comment by cpacia** [comment]
+1

**Comment by joshmh** [comment]
+1

**Comment by tinkyholloway** [comment]
If sunset #25 #13 were required, this would be covered, no? If not can you help to explain the difference.

**Comment by KacperZajc** [comment]
#28
