### ISSUE TITLE
Selling Territory, if ever needed.

### ISSUE THREAD

**Issue by Jean-LouisMesic** [liberland/constitution#270]
§I.9. No branch of the Public Administration, nor any number of Citizens or Residents of the Free Republic of Liberland, shall propose and/or consent to the incorporation of the Free Republic of Liberland, or any part thereof, to any other jurisdiction.

Many among us have already agreed that buying territory is a forseeable investment for the Free Republic of Liberland. But in the aftermath of war, or other diplomatic transactions, or economic developments, it may become necessary to sell part of Free Republican territory for the sake of survival.

Could this be amended to refer only to Siga?

**Comment by KacperZajc** [comment]
seems impossible to define Siga - I think it needs to be amended only upon incorporation of new territories, no point doing it now
