### ISSUE TITLE
Contracts with the Public Administration

### ISSUE THREAD

**Issue by Jean-LouisMesic** [liberland/constitution#271]
§I.12. For the purposes of this Constitution, the term...“Agent of the Public Administration” shall signify any Person working for, or contractually bound with, any body of the Public Administration, including the Law Enforcement;..."

With this wording, any binding agreement forged between a Person and the Public Administation renders them an agent of the public administration. You can be bound to pay tax, or to pay a fine, or to participate in community service. Because of this, Persons may see their rights limited to those of Agents should they ever transact with the government through contract.

Perhaps there is a better wording?

**Comment by KacperZajc** [comment]
let's just remove 'or contractually bound with'
