### ISSUE TITLE
Vigilante Justice through Warrants?

### ISSUE THREAD

**Issue by Jean-LouisMesic** [liberland/constitution#272]
§I.12. For the purposes of this Constitution, the term...“Agent of the Law Enforcement” shall signify any Person working for, or acting pursuant to a Warrant made public by, the Law Enforcement or the Office of the Public Prosecutor;...

This wording allows any Person with knowledge, acting in accordance with a Warrant, pursuant to a Warrant, even if not working for/deputized with the Law Enforcement shall have the right to act pursuant to a Warrant. Perhaps we should include the power to deputize certain Individuals through warrants, to assist with the pursuance of Warrants, if we want to allow this to happen without resulting in vigilante justice.

**Comment by KacperZajc** [comment]
This applies only to warrants made public so arguably only to 'wanted' ads etc.
In all other cases, only members of the LE can act pursuant to a warrant.
