### ISSUE TITLE
Persons not protected by §II.5.

### ISSUE THREAD

**Issue by Jean-LouisMesic** [liberland/constitution#273]
§II.5. No law shall allow for any branch of the Public Administration to require any Individual to register and/or share information about one's whereabouts, being it permanent or temporary, assets, medical condition, religion, political affiliation and/or any other personal attributes unless pursuant to a Warrant; nothing in this provision shall prevent the Public Administration from maintaining a register of owners of land within the Free Republic of Liberland.

Under this wording, the Free Republic of Liberland can collect any and all of this information from Persons not of age, etc. There must be additional restriction, otherwise, all Individuals of minimum age shall have all of these known to the PA without express and informed consent the moment they come of age.

**Comment by KacperZajc** [comment]
First of all, welcome back @Jean-LouisMesic. You have not been here for a while.
This is not a problem as every Person of age has the right to request all his/her personal information stored by any branch of the PA (other than the Law Enforcement) is destroyed.
