### ISSUE TITLE
Civil Court jurisdiction

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#276]
> §V.9(3) The jurisdiction of the Civil Court shall not be ousted by any contract; contracts shall be allowed to require parties to attempt private mediation and/or arbitration before the jurisdiction becomes exercisable.

So we don't want to allow for people to agree to private arbitration as being the final verdict? Because if so, the losing party will most certainly appeal to the civil court, which defeats the purpose of agreeing to private arbitration.

**Comment by KacperZajc** [comment]
§V.9(3) The jurisdiction of the Civil Court shall not be ousted by any contract unless fair arbitration proceedings are envisaged in case of dispute; contracts shall be allowed to require parties to attempt mediation before the jurisdiction of the Court becomes exercisable.

???

**Comment by terrorist96** [comment]
:+1: 
A person could then challenge the fairness in court if they so wish.

**Comment by KacperZajc** [comment]
yup
