### ISSUE TITLE
Treaty constitutionality

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#277]
> §V.8(8) The Supreme Court shall review constitutionality of international treaties the Cabinet intends to sign.

Leaving it the way it is, it only requires a simple majority. I propose we change it to unanimous declaration, similar to any new laws passed.

**Comment by KacperZajc** [comment]
§V.8(8) The Supreme Court shall review constitutionality of all international treaties the Cabinet intends to sign; no international treaty shall be signed unless the Supreme Court by unanimous vote declares the treaty to be compatible with the Constitution.

**Comment by terrorist96** [comment]
> §V.8(8) The Supreme Court shall review **the** constitutionality of all international treaties the Cabinet intends to sign; no international treaty shall be signed unless the Supreme Court**,** ~~by~~ unanimous**ly,** ~~vote~~ declares the treaty to be **constitutional.** ~~compatible with the Constitution.~~
