### ISSUE TITLE
Peacefully assemble

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#278]
> **§II.31.** No law shall abridge Individual’s right to assemble peacefully; nor shall it interfere with any voluntary relations or cooperative ventures formed by Individuals; all public areas within the Free Republic of Liberland shall constitute free speech zones.

So minors and other non-individuals can't peacefully assemble?

**Comment by KacperZajc** [comment]
default position is they can - it's just not protected by the Constitution;
we really need some rules regulating behaviour of minors, prisoners and mental patients

**Comment by terrorist96** [comment]
I don't disagree that we need rules regulating non-individuals, but we don't need to regulate peaceful assembly.

**Comment by KacperZajc** [comment]
imagine prisoners who want to exercise their right 'to assemble peacefully'; there is no way around that

**Comment by terrorist96** [comment]
How about all persons except prisoners?

**Comment by KacperZajc** [comment]
mental patients strapped to bed?
no harm leaving it the way it is

**Comment by terrorist96** [comment]
They'd be considered prisoners too. Anyone who isn't deprived of their liberty (ie not prisoners) should have their right to assemble protected.
