### ISSUE TITLE
minor changes

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#280]
•	§II.30. No law shall abridge the freedom of thought and expression thereof; no Person shall be prosecuted for any statement of opinion, whether offensive or otherwise, about any other Person, including holders of public offices, institution, idea or anything else unless expressed with the use of physical violence; nor shall anyone be prosecuted for displaying any symbols. 

•	§II.11. No law shall deprive any Person who is imprisoned before, during and/or after the trial of the right to contact one’s legal counsel, relatives and other close ones both in person and using indirect means of communication. 

•	§I.12. For the purposes of this Constitution, the term “Person” shall signify any human being whatsoever; the term “Individual” shall signify a Person of age who does not lack mental capacity and is not incarcerated before, during or after the trial; the term “Agent of the Public Administration” shall signify any Person working for any body of the Public Administration, including the Law Enforcement; the term “Member of the Public Administration” shall signify anyone who is holding a public office of one of the branches of the Public Administration; the term “Agent of the Law Enforcement” shall signify any Person working for, or acting pursuant to a Warrant made public by, the Law Enforcement or the Office of the Public Prosecutor; the term “Citizen” shall signify anyone holding the citizenship of the Free Republic of Liberland; the term “Resident” shall signify anyone within the jurisdiction of the Free Republic of Liberland who is not a Citizen.

•	§II.15. No law shall require any Person to pay excessive bail and/or fines; nor shall it allow for defendant who has been found guilty by the Jury to be sentenced to excessive incarceration for any offence where no actual and direct harm was suffered by any Person because of this offence alone.

•	§II.16. No law shall allow for any Person to be prosecuted for any criminal offence absent voluntary confession, if the only evidence incriminating the accused is testimony given by any number of Agents of the Public Administration that is uncorroborated by any other presented physical and/or digital evidence and/or victim or third party witness testimony.

**Comment by terrorist96** [comment]
> • §II.30. No law shall abridge the freedom of thought and expression thereof; no Person shall be prosecuted for any statement of opinion, whether offensive or otherwise, about any other Person, including holders of public offices, institution, idea or anything else unless expressed with the use of physical violence; nor shall anyone be prosecuted for displaying any symbols.

I think keeping it simple and broad is better than trying to make it so detailed, because then you leave out things that would be construed as not protected. Also, the current version has an issue:
`no Person shall have the right to be protected from opinions of others where expressed peacefully.`
This would disallow for restraining orders. We need to amend this provision.

> • §II.11. No law shall deprive any Person who is imprisoned before, during and/or after the trial of the right to contact one’s legal counsel, relatives and other close ones both in person and using indirect means of communication.

Again, I think the current language is sufficient and would cover this.

> • §I.12. For the purposes of this Constitution, the term “Person” shall signify any human being whatsoever; the term “Individual” shall signify a Person of age who does not lack mental capacity and is not incarcerated before, during or after the trial; the term “Agent of the Public Administration” shall signify any Person working for any body of the Public Administration, including the Law Enforcement; the term “Member of the Public Administration” shall signify anyone who is holding a public office of one of the branches of the Public Administration; the term “Agent of the Law Enforcement” shall signify any Person working for, or acting pursuant to a Warrant made public by, the Law Enforcement or the Office of the Public Prosecutor; the term “Citizen” shall signify anyone holding the citizenship of the Free Republic of Liberland; the term “Resident” shall signify anyone within the jurisdiction of the Free Republic of Liberland who is not a Citizen.

Changing the definition of Individual here conflicts with the right to be presumed innocent until proven guilty.

> • §II.15. No law shall require any Person to pay excessive bail and/or fines; nor shall it allow for defendant who has been found guilty by the Jury to be sentenced to excessive incarceration for any offence where no actual and direct harm was suffered by any Person because of this offence alone.

This language feels more awkward than the the current language.

> • §II.16. No law shall allow for any Person to be prosecuted for any criminal offence ~~absent voluntary confession,~~ if the only evidence incriminating the accused is testimony given by any number of Agents of the Public Administration that is uncorroborated by any other presented physical and/or digital evidence**,** ~~and/or~~ victim or third party witness testimony **or voluntary confession**.

**Comment by KacperZajc** [comment]
§II.30. No law shall abridge the freedom of thought and expression thereof; no Person shall be prosecuted for any statement of opinion, whether offensive or otherwise, unless expressed with the use of physical violence or amounting to psychological harassment; nor shall anyone be prosecuted for displaying any symbols.
• §II.11.: I know it is covered but I just want to make it more comprehensible for laypeople 
• §I.12.: so tell me who people placed under arrest (pursuant to a warrant or shorter than 24h) can exercise their right to bear arms, assemble, freedom of movement etc? They cant. It must be amended. 
• §II.15.: ok let’s go back to the original wording.
• §II.16.: okk

**Comment by terrorist96** [comment]
> §II.30. No law shall abridge the freedom of thought and expression thereof; no Person shall be prosecuted for any statement of opinion, whether offensive or otherwise, unless expressed with the use of physical violence or amounting to psychological harassment; nor shall anyone be prosecuted for displaying any symbols.

Good. Just get rid of the last part about symbols. Displaying symbols is part of expressing yourself.

> • §II.11.: I know it is covered but I just want to make it more comprehensible for laypeople 

If you say so.

> • §I.12.: so tell me how people placed under arrest (pursuant to a warrant or shorter than 24h) can exercise their right to bear arms, assemble, freedom of movement etc? They cant. It must be amended. 

Good point.. Okay, just change it to 'a trial' instead of 'the trial'.

> • §II.15.: ok let’s go back to the original wording.
• §II.16.: okk

Word.
