### ISSUE TITLE
Parlance Proposal 

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#283]
I propose we change `Individual` to `Sovereign Person`.

Thoughts?

**Comment by yopdog** [comment]
>§II.7. No law shall allow for any Sovereign Person to be compelled to identify themselves to any Agent of the Public Administration, otherwise upon arrest or pursuant to a Warrant; no Sovereign Person shall be medically examined or otherwise tested unless pursuant to a Warrant or with the Sovereign Person's express and informed consent.

I don't think it sounds as good. Why change it?

**Comment by terrorist96** [comment]
Because `Individual` isn't a good word either. Individual means a single person, but we've defined it to mean a person of age, who isn't imprisoned/insane.
Do you have any suggested alternatives?

**Comment by yopdog** [comment]
No, not really, but I think the word Individual is good enough. Think about it this way: Individual = single person = a person who stands on his own = an independent person = person of age/mental capacity :)

**Comment by terrorist96** [comment]
That's kind of a stretch and I think a better word exists.

**Comment by terrorist96** [comment]
@KacperZajc what do you think?

**Comment by KacperZajc** [comment]
I think Sovereign Person is too close to Person which under our Constitution has separate meaning and it might create confusion.
