### ISSUE TITLE
Renumbering

### ISSUE THREAD

**Issue by fare** [liberland/constitution#29]
The bill of rights is long and divided in many parts, which makes introducing new items hard, because it requires re-numbering everything.

What about:
1- Including article number in every item, such as I.10, I.10(40), etc.
2- Dividing the bill of rights into as many articles.
3- Putting the bill of rights FIRST instead of LAST.

**Comment by KacperZajc** [comment]
3 - I would never think of that but I love it!
1,2 - it is divided into 3 parts which I think makes sense but we can start numbering from the beginning in ever part if that helps?
