### ISSUE TITLE
free elections and other minor changes

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#291]
rephrasing: 

•	§III.5(1) to pass legislation necessary for executing prerogatives enumerated in this provision and no others;

•	§I.8. All Members of the Public Administration shall be of age twenty-one or above and shall hold the citizenship of the Free Republic of Liberland; no such Person shall be prevented from submitting one’s candidacy for a public office.

•	§II.29. No law shall allow for confiscation of private property, being it movable or immovable, tangible or intangible, either fully or partially, for any purpose other than reparation, lawfully levied fines and/or the collection of evidence pursuant to a Warrant; nor shall it regulate the use of property; anything found in proximity under one’s land or growing naturally on it shall belong to oneself.

•	§I.12. For the purposes of this Constitution, the term “Person” shall signify any human being whatsoever; the term “Individual” shall signify a Person of age who does not lack mental capacity and is not incarcerated before, during or after the trial; the term “Agent of the Public Administration” shall signify any Person working for any body of the Public Administration, including the Law Enforcement; the term “Member of the Public Administration” shall signify anyone who is holding a public office of one of the branches of the Public Administration; the term “Agent of the Law Enforcement” shall signify any Person working for, or acting pursuant to a Warrant made public by, the Law Enforcement or the Office of the Public Prosecutor; the term “Citizen” shall signify anyone holding the citizenship of the Free Republic of Liberland; the term “Resident” shall signify anyone within the jurisdiction of the Free Republic of Liberland who is not a Citizen; the term "Law" shall signify any Act passed by the Assembly and all forms of delegated powers as exercised by the Cabinet.

•	§I.1. The Constitution of the Free Republic of Liberland shall be the supreme law of the Free Republic of Liberland and as such shall be directly enforceable before all Courts of the Free Republic of Liberland; all Acts passed by the Assembly, all international treaties signed by the Cabinet and all forms of delegated powers exercised by the Cabinet shall comply with the Constitution; no other instrument invoked by any branch of the Public Administration shall be capable of binding the public; all contracts between any legal and/or natural Persons, including all branches of the Public Administration, made under the jurisdiction of the Free Republic of Liberland shall comply with the Constitution.

•	§I.7. All decisions of any branch of the Public Administration other than verdicts of any Court of the Free Republic of Liberland as well as all actions undertaken by its Agents and every exercise of delegated power by the Cabinet shall be subject to challenge in the Civil Court by a Person in whose respect the decision was given or action undertaken, or any other Person who can prove one's interest in that decision; the right shall be exercisable once all administrative appeals have been exhausted; should the decision, action or exercise of delegated power be aimed at no particular Person, any Citizen shall have standing to seek redress in the Civil Court; the right to challenge shall be exercisable within ninety days and, without prejudice to the appeal procedures, such challenge shall be admissible once only.

•	§II.34. No law shall allow for any Citizen to be deprived of one's citizenship unless by the Criminal Court upon conviction for a criminal offence and as a part of punishment; no Person shall be rendered stateless in any event; multiple citizenships shall be allowed.

•	§I.6. All Members and Agents of the Public Administration intentionally acting in breach of the law or the Constitution shall be criminally liable for their actions and, upon conviction, shall be removed from the office and shall never hold any public office again; acting pursuant to an Act which has been approved as prima facie constitutional by the Supreme Court shall not be deemed as acting unconstitutionally regardless of any future declaration of any Court as to the Act's true constitutionality; introducing, lobbying and voting for a Bill which is declared unconstitutional shall not be deemed as acting unconstitutionally.

New:

§I.13. All Individuals holding the citizenship of the Free Republic of Liberland shall have the right to register for participation in all elections and referendums in the Free Republic of Liberland by entering one’s name into the Electoral Register; keeping one’s name on the Electoral Register might entail certain obligations as prescribed by law; taking part in all elections and referendums shall be voluntary; no Person shall be compelled to vote in a specific manner, nor shall one be reprimanded for the manner in which the vote was cast; all elections and referendums shall be free from any coercion and fraud; validity of such elections shall be judged by the Supreme Court.

§II.41. No law shall deprive any Person of the right to fair compensation for any loss caused by any branch of the Public Administration acting pursuant to a provision of an Act which is subsequently declared unconstitutional by any Court of the Free Republic of Liberland within three years; such compensation shall be covered from the State Reserve System; any loss caused by any Agent of the Public Administration acting contrary to the law or the Constitution, or in error, shall be personally compensated; should said Agent not be able to cover the loss from one’s personal assets, the difference shall be covered from the State Reserve System, with the Public Administration subsequently being able to recover it from said Agent.

**Comment by terrorist96** [comment]
Since this has been closed, I'll submit my suggestions as a PR.

**Comment by terrorist96** [comment]
The changes to §I.1. weren't added in your recent commits.

**Comment by terrorist96** [comment]
> nor shall any branch of the Public Administration collect any personal assets of any natural or legal Person with expectation to return it, either partially, in entirety or in excess, whether the nature of the assets remains or alters; nor shall any personal accounts of any natural or legal Person be created.

I'm confused as to the reason for adding this.

**Comment by terrorist96** [comment]
Why remove "§III.5(1) to legislate for the protection of Persons and their rights and property"

**Comment by terrorist96** [comment]
@KacperZajc

**Comment by KacperZajc** [comment]
it's wide and does not restrict anything in fact;
Id rather allow legislating only in order to give effect to powers of the assembly as enumerated

**Comment by terrorist96** [comment]
@KacperZajc I'd argue that it's necessary because it gives the Assembly permission to make laws in regards to privacy rights, etc. The way it is now, they wouldn't be able to do so. 

And can you please explain the collection of personal assets provision I inquired about above? And did you change your mind about I.1?

Thanks!

**Comment by KacperZajc** [comment]
#302

**Comment by KacperZajc** [comment]
please repeat your concerns
