### ISSUE TITLE
types of weapons 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#294]
II.43 No law shall allow the Law Enforcement to be in disposition of any weaponry other than small arms; should the voluntary Territorial Defence rise, it shall not be in disposition of any weaponry other than small arms and light weapons. 

§IV.5(12) to be the Commander-in-Chief of the voluntary Territorial Defence, should it rise.

•	§II.35. No law shall allow for war to be declared and/or waged by any branch of the Public Administration on any Nation or group; no standing army shall be established; should any voluntary Territorial Defence rise, it shall not be used outside the territory of the Free Republic of Liberland, but only to defend the borders of the Free Republic of Liberland against external enemies; under no circumstances shall the Territorial Defence be used instead of, or in support of, the Law Enforcement against Citizens or other Residents of the Free Republic of Liberland; such voluntary Territorial Defence shall have the Chancellor as its Commander-in-Chief; the Commander-in-Chief shall not have say on the creation and/or dissolution of the potential voluntary Territorial Defence.

**Comment by terrorist96** [comment]
> should the voluntary Territorial Defence rise, it shall not be in disposition of any weaponry other than small **arms** and light ~~arms~~ **weapons**.

The rest is good.

I don't know how I feel about giving the Territorial Defence more rights in regards to arms than the average citizen.

**Comment by KacperZajc** [comment]
I understand your concerns, however, it is not a branch of the government (although the Chancellor would be the commander-in-chief it can dissolve itself and the Chancellor cant stop it). Secondly, it will not be used against citizens. Thirdly, the LE is a a governmental agency and it has the same sort of weaponry as citizens. I think the balance is struck here.
