### ISSUE TITLE
Election register

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#296]
So the constitution says that you only need to enter your name in order to vote. What about age? Or criminal/mental status? It says that only Individuals with citizenship can vote, not any person who has citizenship. How can we resolve this?

**Comment by KacperZajc** [comment]
Question of age will be dealt with later.
I dont mind ex prisoners being able to vote.

**Comment by edwardtjgerety** [comment]
After completion of their entire sentence, I would also look at including the right to have records wiped clean after seven years of completing one’s entire court mandated sentence.
