### ISSUE TITLE
amendments so far

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#30]
Can we all agree on the following amendments (???):

- for rationale and public reading:

No Bill proposed to the Assembly shall be passed unless it has been read aloud in entirety by the Assembly Speaker and includes precise calculation as to its potential impact on the budget as well as rationale behind it and means of achieving thereof, which does not conflict with the Constitution.

- for self-defence:

No law shall abridge the right of self-defense against initiators of aggression, including the agents of the Public Administration where acting unlawfully and/or in error 

- for restoring original language (merging §6 and §7 into one provision):

No law shall abridge the right of persons to the control of their own bodies and property, nor interfere with voluntary consensual or contractual relations among adult persons, or the right to form cooperative ventures of any kind so long as no rights of others are interfered.

- on jury power:

to add "acquittal by the Jury shall be final"

- on members of Cabinet:

to add "Cabinet shall be formed from citizenry"

**Comment by KacperZajc** [comment]
can someone make a pull request out of this?

**Comment by fare** [comment]
That shall be separate pull requests.

**Comment by KacperZajc** [comment]
make it separate then

**Comment by fare** [comment]
If you already know what you want, you can modify the file yourself without having to have a pull request.

**Comment by manchfu** [comment]
@fare Some of us have requested that all changes be pull requests for the sake of transparency and open discussion.

**Comment by tinkyholloway** [comment]
I can do them in 16 hours.
