### ISSUE TITLE
restating Article III

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#302]
Article III: The Legislative Power

•	§III.1. The legislative power in the Free Republic of Liberland shall be vested in the Citizens of the Free Republic of Liberland and the Assembly of the Free Republic of Liberland which shall exercise it on behalf of the Citizens.
o	§III.1(1) The Assembly shall be in session for three weeks of every month for nine months a year.
o	§III.1(2) The Assembly may reconvene at any time whatsoever upon the call of the Assembly Speaker.
o	§III.1(3) The work of the Assembly shall not be impeded by any other branch of the Public Administration. 

•	§III.2. The Assembly shall consist of twenty Assembly Representatives.
o	§III.2(1) All Assembly Representatives shall receive remuneration for their service as provided in the Annual Budget.
o	§III.2(2) No Person shall hold the office of a Judge of one of the Courts of the Free Republic of Liberland whilst holding the position of Assembly Representative concurrently.
o	§III.2(3) No Person shall hold the office of a Member of the Cabinet whilst holding the position of Assembly Representative concurrently.
o	§III.2(4) No Assembly Representative shall be precluded from taking part in any Assembly vote and/or debate by virtue of being detained prior to one's trial.
o	§III.2(5) No Assembly Representative shall hold the office for more than eight years in total.

•	§III.3. The Assembly Representatives shall be elected by the Citizens in the General Election held every four years.
o	§III.3(1) Any Assembly Representative may be recalled by the Citizens with a simple majority vote in a referendum called by 5% of all Citizens.
o	§III.3(2) Should any Assembly Representative step down, the Supplementary Election shall be held within 90 days. 
o	§III.3(3) No vote whatsoever shall take place unless all Assembly Representative are sworn in and eligible to participate. 

•	§III.4. One-fourth of all Assembly Representatives shall have the right to propose a resolution dissolving the Assembly.
o	§III.4(1) The resolution shall be passed with a majority of two-thirds of all Assembly Representatives.
o	§III.4(2) Should the Assembly be dissolved, the General Election shall be held within ninety days.

•	§III.5. The Assembly shall elect the Assembly Speaker with a simple majority vote of all Assembly Representatives.
o	§III.5(1) The Assembly Speaker shall chair the business of the Assembly.

•	§III.6. The business of the Assembly shall be administered by the Bureau of the Assembly of the Free Republic of Liberland.
o	§III.6(1) The Bureau of the Assembly shall be headed by the Assembly Speaker.
o	§III.6(2) The Bureau of the Assembly shall supervise all Agents of the legislative branch of the Public Administration.
o	§III.6(3) The Bureau of the Assembly shall maintain the State Reserve System.
o	§III.6(4) No Agent of the Law Enforcement shall enter the premises of the Assembly unless with the express and informed consent of the Bureau of the Assembly or pursuant to a Warrant.

•	§III.7. The powers of the Assembly shall be restricted to the following only:
o	§III.7(1) to pass legislation necessary for carrying into force the powers enumerated in this provision and no others;
o	§III.7(2) to conduct the financial affairs of the Public Administration as provided in the Financial Bill;
o	§III.7(3) to lay the tax on land as provided for in the Taxation Bill;
o	§III.7(4) to maintain the Courts of the Free Republic of Liberland without interfering with the affairs of the judiciary;
o	§III.7(5) to establish the Law Enforcement in order to maintain the internal security;
o	§III.7(6) to establish the rules regarding peaceful coexistence of Persons and security of their Property;
o	§III.7(7) to assent to the incorporation of any new territories to the Free Republic of Liberland with any status the Assembly shall determine;
o	§III.7(8) to debate on matters important to the well-being of the Republic;
o	§III.7(9) to ratify international treaties signed by the Cabinet as provided in a Treaty Bill;
o	§III.7(10) to establish the Assembly Committee;
o	§III.7(11) to assent to the classification of information for the purposes of national security as proposed by a Secretary of State;
o	§III.7(12) to appoint and impeach the Chancellor and/or Members of the Cabinet .

•	§III.8. The Assembly shall elect the Chancellor of the Free Republic of Liberland, who shall form the Cabinet of the Free Republic of Liberland, with a simple majority vote of all Assembly Representatives.
o	§III.8(1) Should no Chancellor be elected for more than thirty days, the General Election must be held within ninety days.
o	§III.8(2) The Assembly shall have the power to impeach the Chancellor by passing the Constructive Motion of No Confidence with a simple majority vote of all Assembly Representatives provided there is a majority for a prospective successor.
o	§III.8(3) The Assembly shall have the power to impeach a single Member of the Cabinet by passing the Ordinary Motion of No Confidence with a simple majority vote of all Assembly Representatives.

•	§III.9. One-fourth of all Assembly Representatives shall have the right to propose a resolution instituting the Assembly Committee.
o	§III.9(1) The resolution shall be passed with a simple majority of all Assembly Representatives.
o	§III.9(2) The Assembly Committee shall be composed of five Assembly Representatives.
o	§III.9(3) The Assembly Committee shall be established upon a suspicion of misconduct or mismanagement of any Member or Agent of the Public Administration in order to investigate the allegations.
o	§III.9(4) The Assembly Committee shall have the right to summon Members and Agents of the Public Administration to hear testimonies given under oath.
o	§III.9(5) The Assembly Committee shall prepare the Final Conclusions reporting evidence (if any) of said misconduct or mismanagement.
o	§III.9(6) The Final Conclusions shall be made public and passed to the Chief Public Prosecutor for consideration of potential criminal prosecution of relevant Persons as described by the Committee.
o	§III.9(7) The Final Conclusions shall not have any binding effect.
o	§III.9(8) No Person shall be penalised by the Assembly Committee; testimonies given in breach of the oath shall be prosecuted in the Criminal Court in a regular manner.
o	§III.9(9) The Assembly Committee shall only deal with the matter for which it was established and shall cease to work no later than one year since its creation.

•	§III.10. The power to initiate a legislative procedure shall lie with the Cabinet only.
o	§III.10(1) The power to initiate a legislative procedure shall be exercised only once a year upon the State of the Republic Address.
o	§III.10(2) The power to initiate a legislative procedure shall be executed by submitting a Bill to the Assembly.
o	§III.10(3) Any Bill which is not voted on before the next State of the Republic Address and any Bill which is rejected by the Assembly in a vote shall be considered lost and shall not be revived unless by resubmission by the Cabinet upon another State of the Republic Address.

•	§III.11. Any Bill proposed to the Assembly by the Cabinet upon the State of the Republic Address, shall be debated on, and shall be voted on once only.
o	§III.11(1) The Bill proposed by the Cabinet shall be made public prior to the Assembly's debate.
o	§III.11(2) No Bill shall be voted on unless all Assembly Representatives are successfully notified about the date and time of the debate and the vote.
o	§III.11(3) Every Assembly Representative shall have the right to express one's opinion on the proposed Bill at least once before the vote takes place, without any time limit.

•	§III.12. Any Bill proposed to the Assembly shall pertain to one matter only as expressed in its title.
o	§III.12(1) The Bill shall contain rationale behind it and means of achieving thereof including precise calculations as to its potential impact on the budget.
o	§III.12(2) The Bill shall specify under which power delegated by this Constitution to the Assembly it is proposed.
o	§III.12(3) The Bill shall be read aloud in its entirety by the Assembly Speaker before it is voted on.

•	§III.13. One-fourth of all Assembly Representatives shall have the right to oblige the Cabinet to consider a draft of a Bill prepared by them.
o	§III.13(1) The Draft prepared by the Assembly Representatives may be rejected or accepted by the Cabinet as a Bill.
o	§III.13(2) All drafts of Bills proposed to the Cabinet shall be made public before the Cabinet’s acceptance or rejection.
o	§III.13(3) Should the Draft be rejected, the Cabinet shall publicly give detailed reasons behind its decision.

•	§III.14. The Cabinet shall have the power to propose five types of Bills.
o	§III.14(1) Ordinary Bill;
o	§III.14(2) Constitutional Bill;
o	§III.14(3) Taxation Bill;
o	§III.14(4) Treaty Bill;
o	§III.14(5) Financial Bill.

•	§III.15. An ordinary Bill shall pertain to any matter within the powers of the Assembly which is not reserved for any other type of Bill.
o	§III.15(1) All ordinary Bills shall be passed into law with a majority of three-quarters of all Assembly Representatives.
o	§III.15(2) All ordinary Bills shall be subject to the power of general veto by the Citizens as provided in §III.21.

•	§III.16. A Constitutional Bill shall propose an Amendment to this Constitution.
o	§III.16(1) All Constitutional Bills shall be passed only with the unanimous vote with all Assembly Representatives present.
o	§III.16(2) All Constitutional Bills shall be subject to the power of general veto by the Citizens as provided in §III.22.

•	§III.17. A Taxation Bill shall propose, or alter, the tax on land of the Free Republic of Liberland.
o	§III.17(1) All Taxation Bills shall be passed into law with the unanimous vote with all Assembly Representatives present.
o	§III.17(2) All Taxation Bills shall be subject to the power of general veto by the Citizens as provided in §III.22.
o	§III.17(3) The tax shall be fixed per meter square.
o	§III.17(4) No other form of tax shall be levied in the Free Republic of Liberland.
o	§III.17(5) No other Bill shall be capable of levying any tax in the Free Republic of Liberland.
o	§III.17(6) Neither the Taxation Bill, nor any other Bill, shall impose any form of duty on goods, services and/or capital exported from, or imported into, the Free Republic of Liberland.
o	§III.17(7) The overall tax revenue shall be calculated not to exceed 5% of the Gross Domestic Product of the Free Republic of Liberland of the preceding year.
o	§III.17(8) The tax shall be levied for one or more of the following purposes only:
	§III.17(8)(a) maintaining the infrastructure of the Public Administration;
	§III.17(8)(b) providing for the Law Enforcement;
	§III.17(8)(c) providing for the Courts of the Free Republic of Liberland;
	§III.17(8)(d) providing for Agents and Members of the Public Administration;
	§III.17(8)(e) securing and promoting the interests of the Free Republic of Liberland worldwide.

•	§III.18. A Treaty Bill shall ratify an international treaty signed by the Cabinet.
o	§III.18(1) All Treaty Bills shall be passed into law with a majority of three-quarters of all Assembly Representatives.
o	§III.18(2) All Treaty Bills shall be subject to the power of general veto by the Citizens as provided in §III.21.
o	§III.18(3) All international treaties must be signed by the Chancellor on behalf of the Cabinet and ratified by the Assembly in order to constitute the law of the land in the Free Republic of Liberland.

•	§III.19. The Financial Bill shall contain the provisions of the Annual Budget.
o	§III.19(1) The Financial Bill shall be passed with a simple majority vote of all Assembly Representatives.
o	§III.19(2) The Financial Bill shall be subject to the power of general veto by the Citizens as provided in §III.21.
o	§III.19(3) The Financial Bill shall contain the Alteration Clause which shall enable the Cabinet to exercise delegated power in order to alter the provisions of the Annual Budget. 
o	§III.19(3) The Alteration Clause shall be exercisable should the Cabinet realise that the actual revenue shall not meet the anticipated revenue as provided in the Annual Budget. 
o	§III.19(4) The Executive Measure altering the provisions of the Annual Budget shall only be capable of reducing spending.
o	§III.19(4) Under no circumstances shall the Cabinet lower the remuneration of the Judges and/or Assembly Representatives unless with the express and informed consent of relevant bodies.

•	§III.20. The Annual Budget shall constitute the only source of financial provisions for the Free Republic of Liberland.
o	§III.20(1) The Annual Budget shall be financed from the State Treasury maintained by the Department of Treasury.
o	§III.20(2) No provision of the Annual Budget shall provide for any spending which is not authorised by this Constitution.
o	§III.20(3) All fees collected by the Public Administration and all pledged systematic voluntary donations shall be transferred to the State Treasury and thereby included in the Annual Budget.
o	§III.20(4) All fines and spontaneous voluntary donations shall be transferred to the State Reserve System.
o	§III.20(5) The Annual Budget shall be calculated using realistic assumptions as to the anticipated revenue so that the anticipated revenue does not exceed the actual revenue.
o	§III.20(6) The size of the Annual Budget shall not exceed the previous year actual revenue.
o	§III.20(7) Should the actual revenue exceeded the anticipated revenue, the surplus shall be transferred to the State Reserve System.
o	§III.20(8) Should the actual revenue fall short of the anticipated revenue, the deficit shall be covered from the funds gathered in the State Reserve System.
o	§III.20(9) Should the funds gathered in the State Reserve System not be able to cover the deficit, all Assembly Representatives who voted in favour of the Financial Bill shall cover the remaining difference with their own personal assets, divided equally.
o	§III.20(10) The State Reserve System shall be maintained by the Bureau of the Assembly.

•	§III.21. All ordinary Bills or Treaty Bills or the Financial Bill passed by the Assembly under this Constitution shall be subject to the right of general veto by the Citizens as expressed in the referendum.
o	§III.21(1) The referendum shall be triggered by the request of 5% of all Citizens, and shall be submitted within ninety days after the Bill was passed by the Assembly.
o	§III.21(2) The Bill shall be deemed to veto the legislative proposal if a simple majority of the Citizens taking part in that referendum vote 'Nay'.

•	§III.22. All Taxation Bills or Constitutional Bills shall be subject to the mandatory referendum.
o	§III.22(1) The referendum shall take place within ninety days after the Bill was passed by the Assembly.
o	§III.22(2) The Bill shall be deemed to be vetoed unless a majority of two-thirds of all Citizens taking part in the referendum vote 'Aye'.

•	§III.23. Any Bill vetoed by the Citizens in the referendum shall be considered void.
o	§III.23(1) Should an ordinary Bill or a Treaty Bill be vetoed, it shall not be resubmitted to the Assembly for at least three years.
o	§III.23(2) Should a Constitutional Bill or Taxation Bill be vetoed, it shall not be resubmitted to the Assembly for at least ten years.
o	§III.23(3) Should the Financial Bill be vetoed, the provisions of the Annual Budget adopted the previous year shall apply.

•	§III.24. A Bill shall become “Under Consideration” once it is passed by the Assembly in accordance with the provisions of this Article, and either ninety days have passed and no referendum was called in accordance with §III.21., or on the day the Bill obtained the assent of the Citizens in referendum under §III.21. or §III.22.

•	§III.25. A Bill shall become the law of the Free Republic of Liberland, and shall be known as “Act” once it became “Under Consideration” in accordance with the procedure provided for in §III.24., and was declared constitutional by the Supreme Court of the Free Republic of Liberland according to the procedure laid down in Article V.

•	§III.26. The law of the Free Republic of Liberland shall enter into force on the day specified in the Act but no sooner than on the thirty-first day after it is signed by the Chief Justice of the Supreme Court, or if unable, by any other Justice of the Supreme Court, which shall take place upon the declaration of constitutionality.

**Comment by terrorist96** [comment]
I'll go through this in detail later. 
But since you wanted me to repeat my concerns about #291, here:
I'd argue that it's necessary because it gives the Assembly permission to make laws in regards to privacy rights, etc. The way it is now, they wouldn't be able to do so.

And can you please explain the collection of personal assets provision I inquired about above? And did you change your mind about I.1?

Thanks!

**Comment by KacperZajc** [comment]
Areas of competence are amended as requested.
What was the inquiry? 
What was I supposed to change my mind about?

**Comment by terrorist96** [comment]
> o §III.1(3) The work of the Assembly shall not be impeded by any other branch of the Public Administration.

Except for striking down unconstitutional laws? Or arresting members who need to be arrested?

> o §III.7(6) to establish ~~the~~ rules regarding peaceful coexistence of Persons and security of their Property **and Rights**;

> o §III.7(12) to appoint and impeach the Chancellor and/or Members of the Cabinet .

Extra space between Cabinet and the period.

> o §III.8(1) Should no Chancellor be elected for more than thirty days, the General Election ~~must~~ **shall** be held within ninety days.
 
> provided there is a majority for a prospective successor.

How can this be determined ahead of time?

> • §III.10. The power to initiate a legislative procedure shall lie with the Cabinet only.
o §III.10(1) The power to initiate a legislative procedure shall be exercised only once a year upon the State of the Republic Address.
o §III.10(2) The power to initiate a legislative procedure shall be executed by submitting a Bill to the Assembly.

This could probably be shortened to say 'This power' shall be...

> • §III.14. The Cabinet shall have the power to propose five types of Bills~~.~~ **:**
o §III.14(1) **an** Ordinary Bill;
o §III.14(2) **a** Constitutional Bill;
o §III.14(3) **a** Taxation Bill;
o §III.14(4) **a** Treaty Bill;
o §III.14(5) **a**Financial Bill.

Do we want to capitalize `ordinary`? If so, it should be done elsewhere too.


> o §III.16/17(1) All Taxation/Constitutional Bills shall be passed into law with the unanimous vote **of** ~~with~~ all Assembly Representatives ~~present~~.

If they're not present, they can't vote. I initially misread it as 'with the unanimous vote of all assembly reps present' and I thought to myself that you had changed the meaning of unanimous (all) to unanimous (of those present). This change makes it clearer, IMO.

> §III.16(12) The funds gathered in the State Reserve System shall be diversified therefore kept in various stable currencies and precious metals.	

Thanks for removing this. 

> o §III.19(4) Under no circumstances shall the Cabinet lower the remuneration of ~~the~~ Judges and/or Assembly Representatives unless with the express and informed consent of relevant bodies.

> The referendum shall be triggered by the request of 5% of all Citizens, and shall be submitted within ninety days **after the Bill was passed by the Assembly.**
 o §III.22(1) The referendum shall take place within ninety days **after the Bill was passed by the Assembly.**

Shouldn't this be changed to after the Supreme Court has declared its constitutionality first?
https://liberland.org/addons/image/legislative-procedure-flowchart.png

> The Bill shall be deemed to veto the legislative proposal if a simple majority of the Citizens taking part in that referendum vote 'Nay'.	
The Bill shall be deemed to be vetoed unless a majority of two-thirds of all Citizens taking part in the referendum vote 'Aye'.

Can we standardize this language?

> o §III.23(1) Should an ordinary Bill or a Treaty Bill be vetoed, it shall not be resubmitted to the Assembly for at least three years.
 o §III.23(2) Should a Constitutional Bill or Taxation Bill be vetoed, it shall not be resubmitted to the Assembly for at least ten years.

I feel like a loophole might be resubmitting a slightly tweaked version of the rejected Bill. 

>  • §III.24. A Bill shall become “Under Consideration” once it is passed by the Assembly in accordance with the provisions of this Article, and either ninety days have passed and no referendum was called in accordance with §III.21., or on the day the Bill obtained the assent of the Citizens in referendum under §III.21. or §III.22.
• §III.25. A Bill shall become the law of the Free Republic of Liberland, and shall be known as “Act” once it became “Under Consideration” in accordance with the procedure provided for in §III.24., and was declared constitutional by the Supreme Court of the Free Republic of Liberland according to the procedure laid down in Article V.

Either this needs to be changed, or this flow chart needs to be edited: https://liberland.org/addons/image/legislative-procedure-flowchart.png

_______

The inquiry was: what's the purpose of adding this to the end of II.39:
> nor shall any branch of the Public Administration collect any personal assets of any natural or legal Person with expectation to return it, either partially, in entirety or in excess, whether the nature of the assets remains or alters; nor shall any personal accounts of any natural or legal Person be created.


You changed your mind regarding the proposed amendment to I.1. You proposed adding `no other instrument invoked by any branch of the Public Administration shall be capable of binding the public;` in #291 but never made that change in your commit.

Was just asking if you changed your mind about adding it, or did you forget?

**Comment by KacperZajc** [comment]
o §III.1(3) The Assembly shall not be dissolved, nor shall it session be interrupted, by any other branch of the Public Administration.

o §III.7(6) to establish rules regarding peaceful coexistence of Persons and security of their Property and Rights;
o §III.7(12) to appoint and impeach the Chancellor and/or Members of the Cabinet .
Yes the prospective majority is a part of the motion of no confidence. 

o §III.8(1) Should no Chancellor be elected for more than thirty days, the General Election shall be held within ninety days.

• §III.10. The power to initiate a legislative procedure shall lie with the Cabinet only.
o §III.10(1) This power shall be exercised only once a year upon the State of the Republic Address.
o §III.10(2) Initiating a legislative procedure shall be executed by submitting a Bill to the Assembly.

o §III.14(1) an ordinary Bill;
o §III.14(2) a Constitutional Bill;
o §III.14(3) a Taxation Bill;
o §III.14(4) a Treaty Bill;
o §III.14(5) a Financial Bill.

o §III.16/17(1) All Taxation/Constitutional Bills shall be passed into law with the unanimous vote with all Assembly Representatives present.

Shouldnt it be worded this way to ensure that those Bills are passed with 20/20 votes and not 18/18 (with 2 absent) etc?

o §III.19(4) Under no circumstances shall the Cabinet lower the remuneration of Judges and/or Assembly Representatives unless with the express and informed consent of relevant bodies.
o §III.21(1) The referendum shall be triggered by the request of 5% of all Citizens, and shall be submitted within ninety days after the Bill was declared constitutional by the Supreme Court.
o §III.22(1) The referendum shall take place within ninety days after the Bill was declared constitutional by the Supreme Court.

o §III.21(2) The Bill shall be deemed to be vetoed unless a simple majority of all Citizens taking part in the referendum vote 'Aye'.
o §III.22(2) The Bill shall be deemed to be vetoed unless a majority of two-thirds of all Citizens taking part in the referendum vote 'Aye'.

o §III.23(1) Should an ordinary Bill or a Treaty Bill be vetoed, it shall not be resubmitted to the Assembly for at least three years.
o §III.23(2) Should a Constitutional Bill or Taxation Bill be vetoed, it shall not be resubmitted to the Assembly for at least ten years.

Any idea how to close this loophole?

We will deal with the float chart later.

**Comment by KacperZajc** [comment]
Regarding "no other instrument invoked by any branch of the Public Administration shall be capable of binding the public;":

I changed my mind because it is unclear.
Maybe you propose a line which would ensure that Acts and Executive Measures are the only instruments the PA can use (so that they do not avoid the Constitution by issuing some other 'orders')

Regarding II.39:
Im just closing all possible loopholes - in this case creating 'insurance' (without subsiding it from the budget) such as Medicare etc.

**Comment by terrorist96** [comment]
> o §III.1(3) The Assembly shall not be dissolved, nor shall it**s** session be interrupted, by any other branch of the Public Administration.

>  §III.7(12)

Still need to remove extra space at the end.

> o §III.10(1) This power shall be exercised only once a year upon the State of the Republic Address **by submitting a Bill to the Assembly.**

Can §III.10(1) and §III.10(2) be combined?

> o §III.16/17(1) All Taxation/Constitutional Bills shall be passed into law with the unanimous vote with all Assembly Representatives present.
Shouldnt it be worded this way to ensure that those Bills are passed with 20/20 votes and not 18/18 (with 2 absent) etc?

No, because "all assembly reps" means all 20 of them. Not just the ones present. Here's another alternative:
All Taxation/Constitutional Bills shall only be voted on whilst all Assembly Representatives are present and passed ~~into law~~ with the unanimous vote **of** ~~with~~ all Assembly Representatives.
(we should also remove the 'into law' part, because nothing is passed into law when the Assembly votes for it. Only after constitutional declaration and referendum (if applicable)).

Or, better yet, make this change:
o §III.3(3) No vote whatsoever shall take place unless all Assembly Representative are sworn in and **present** ~~eligible to participate~~.

Since you don't mention anything about being present for other votes (picking a speaker, chancellor, etc), this will make it so all votes are conducted only when all members are present.

> o §III.21(2) The Bill shall be deemed ~~to be~~ vetoed unless a simple majority of all Citizens taking part in the referendum vote 'Aye'.
o §III.22(2) The Bill shall be deemed ~~to be~~ vetoed unless a majority of two-thirds of all Citizens taking part in the referendum vote 'Aye'.

> o §III.23(1) Should an ordinary Bill or a Treaty Bill be vetoed, it shall not be resubmitted to the Assembly for at least three years.
o §III.23(2) Should a Constitutional Bill or Taxation Bill be vetoed, it shall not be resubmitted to the Assembly for at least ten years.

Any idea how to close this loophole?

Sure:
> o §III.23(1) Should an ordinary Bill or a Treaty Bill be vetoed, **neither** it **nor any substantially similar Bill** shall ~~not~~ be resubmitted to the Assembly for at least three years.
o §III.23(2) Should a Constitutional Bill or Taxation Bill be vetoed, **neither** it **nor any substantially similar Bill** shall ~~not~~ be resubmitted to the Assembly for at least ten years.

> We will deal with the float chart later.

Flow chart is ok. III.24/25 need changing.

> Maybe you propose a line which would ensure that Acts and Executive Measures are the only instruments the PA can use (so that they do not avoid the Constitution by issuing some other 'orders')

"Only constitutional Acts and Executive Measures shall be capable of binding the public"

> Regarding II.39:
Im just closing all possible loopholes - in this case creating 'insurance' (without subsiding it from the budget) such as Medicare etc.

Seems kinda convoluted to me, but I'm not opposed.

**Comment by KacperZajc** [comment]
yes, we can merger III.10(1) and (2)

I like this one:
All Taxation/Constitutional Bills shall only be voted on whilst all Assembly Representatives are present and passed with the unanimous vote of  all Assembly Representatives.

I dont want to change §III.3(3) because it would make it extremely easy to blackmail the Assembly.

What we should do is change 'all AR' to 'of the overall number of all AR' to clarify that they can pass a Financial Bill with 11 votes even if there are only 12 AR present because it is a simple majority of 20 anyway. 

Regarding 'substantially similar': this is exactly why I didnt add that. It is utterly unenforceable. It means nothing when taken into court.

Is 'capable of binding the public' the right phrase? I changed my mind because it seemed odd.

**Comment by terrorist96** [comment]
> I dont want to change §III.3(3) because it would make it extremely easy to blackmail the Assembly.

Blackmail? How?

> Regarding 'substantially similar': this is exactly why I didnt add that. It is utterly unenforceable. It means nothing when taken into court.

I disagree. When you take it to court, the judge decides if it's substantially similar. This type of language is used in regular laws all the time and there's no issue for a judge to make a judgement.

> Is 'capable of binding the public' the right phrase? I changed my mind because it seemed odd.

It's not a *wrong* phrase. A better phrase could probably be concocted, but for now, it serves its purpose, IMO.

**Comment by KacperZajc** [comment]
Absent of 1 AR would make it impossible to vote on anything even where this 1 opposing vote means nothing.

I want to come up with something better than 'simialr'

OK so let's use this 'capable of binding the public' phrase.

**Comment by terrorist96** [comment]
Ok I see your point about one rep being absent when it doesn't matter.

Substantially similar is used in copyright law. 

https://en.m.wikipedia.org/wiki/Substantial_similarity

**Comment by KacperZajc** [comment]
The fact that IP rights use this phrase is just another reason not to use it xD
Now, seriously, I'll think about it :)
