### ISSUE TITLE
using fancy phrases 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#304]
Can you think of more formal/fancy wording for this provision?
Especially for 'narrow' and 'wide'

§I.12. All provisions of this Constitution, as well as all laws, which enumerate the Rights of the Citizens and other Residents of the Free Republic of Liberland shall, in all situations, be interpreted as widely as possible; all provisions which enumerate Powers of any branch of the Public Administration and their Members and Agents shall, in all situations, be interpreted as narrowly as possible.

**Comment by terrorist96** [comment]
If you don't like your current wording, how about 'shall be interpreted liberally (for rights) and strictly (for enumerated powers)' though I don't see much wrong with the current wording.

**Comment by KacperZajc** [comment]
yeah I like that

**Comment by edwardtjgerety** [comment]
The constitution is getting so long that it will be unmanageable. You are in effect creating a system that will allow lawyers and governments to swallow up individual rights.                                                                                                                                                                                                                                                                                                                                           All the best,Edward John 'Tj' George Gerety, III                                                                                                                                                                                                                 From: KacperZajcSent: Saturday, August 22, 2015 10:42To: liberland/constitutionReply To: liberland/constitutionSubject: Re: [constitution] using fancy phrases  (#304)yeah I like that

—Reply to this email directly or view it on GitHub.

**Comment by KacperZajc** [comment]
It's long because modern governments are able to do a long list of stuff they shouldnt. 
We have to predict everything they may do and make sure they wont.
