### ISSUE TITLE
Referendum -> Constitutionality 

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#306]
Do we want the veto referendum before or after Constitutional declaration? I'm in favor of after (as the current flow chart shows) because it keeps the Supreme Court independent. If the people vote to approve a Bill, the Supreme Court may be more circumspect in declaring it unconstitutional so as to not upset the majority (and risk being recalled). If the public votes to approve a Bill and 4 of the 5 Justices vote to say it's constitutional, the 5th justice who wants to vote to say it's unconstitutional would fear being recalled because his 1 vote makes the determination and goes against the majority. 

What are your arguments in favor of or against this?

**Comment by KacperZajc** [comment]
After, after
