### ISSUE TITLE
free of charge legal counsel 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#308]
II.44 No law shall deprive any defendant under prosecution of the right to the service of a legal counsel and an interpreter, should one not speak the language of court proceedings; such services shall be contracted by the defendant personally or, should one not be able to afford it, they shall be provided by the Secretariat of the Judiciary; should the service of a legal counsel and/or an interpreter be provided by the Secretariat of the Judiciary, it shall be allowed to recover reasonable expenses from the defendant unless one was found not guilty by the Jury.

what do you think?

**Comment by terrorist96** [comment]
Why do we need to add a separate new provision for this? It's already covered by II.18.

> it shall be allowed to recover reasonable expenses from the defendant unless one was found not guilty by the Jury.

What if they're found not guilty upon appeal by the Supreme Court?

**Comment by yopdog** [comment]
As @terrorist96 said, it's already covered by II.18.  

>should one not be able to afford it, they shall be provided by the Secretariat of the Judiciary

Maybe this is a topic for another discussion, but I really don't think the government should be involved in helping the poor at all. Assuming there will be no taxes, the PA will be no more special than a private charity in its ability to provide financial help. It would therefore be better if we just left everything that has to do with the poor to private charity which would probably do a better job at it.

**Comment by yopdog** [comment]
Furthermore, I would even argue it conflicts with the constitution to provide any aid to a person as stated in provision §II.39.  

§II.39. **No law shall allow for any provision of the Annual Budget to finance or partially finance** any political party, any form of insurance, healthcare services, education and/or pension schemes; nor **any form of direct or indirect financial aid, being it a loan, non-repayable grant or periodic payments, to any legal or natural Person; nor purchase of any amount of shares of any legal Person; nor purchase of land and/or any movable assets unless necessary for functioning of the Public Administration as provided in the Constitution; no provision of the Annual Budget shall transfer any assets to any legal and/or natural Person** unless as remuneration for contracted goods and/or services necessary for the functioning of the Public Administration; nor shall any branch of the Public Administration collect any personal assets of any natural or legal Person with expectation to return it, either partially, in entirety or in excess, whether the nature of the assets remains or alters; nor shall any personal accounts of any natural or legal Person be created.

**Comment by edwardtjgerety** [comment]
Agreed.                                                                                                                                                                                                                                                                                                                                         All the best,Edward John 'Tj' George Gerety, III                                                                                                                                                                                                                 From: yopdog777Sent: Monday, August 24, 2015 15:48To: liberland/constitutionReply To: liberland/constitutionSubject: Re: [constitution] free of charge legal counsel  (#308)Furthermore, I would even argue it conflicts with the constitution to provide any aid to a person as stated in provision §II.39.  

§II.39. No law shall allow for any provision of the Annual Budget to finance or partially finance any political party, any form of insurance, healthcare services, education and/or pension schemes; nor any form of direct or indirect financial aid, being it a loan, non-repayable grant or periodic payments, to any legal or natural Person; nor purchase of any amount of shares of any legal Person; nor purchase of land and/or any movable assets unless necessary for functioning of the Public Administration as provided in the Constitution; no provision of the Annual Budget shall transfer any assets to any legal and/or natural Person unless as remuneration for contracted goods and/or services necessary for the functioning of the Public Administration; nor shall any branch of the Public Administration collect any personal assets of any natural or legal Person with expectation to return it, either partially, in entirety or in excess, whether the nature of the assets remains or alters; nor shall any personal accounts of any natural or legal Person be created.

—Reply to this email directly or view it on GitHub.

**Comment by KacperZajc** [comment]
Guys it used to be free of charge and this proposal makes it payable back.
I dont understand your concerns - Im changing it the way you want.

**Comment by terrorist96** [comment]
@yopdog "equality under the law*" 

*if you can afford it 

Everyone should be equal under the law. 
II.39 refers to laws, not constitutional provisions.

**Comment by yopdog** [comment]
@terrorist96 I know provision II.39 is for laws, but the constitution should be consistent with it's one bill of rights. Why should people take a constitution seriously if it doesn't take itself seriously?? Why are we exempting ourselves from the same provisions we want everyone else to follow?

**Comment by KacperZajc** [comment]
Can I get both your opinions on the issue of paying back for legal counsel services provided by the State?

**Comment by terrorist96** [comment]
I'm in favor of paying it back if found guilty. As I've said before, that's how it is in my state. You only get free representation if you can't afford it and are found not guilty in the end.

**Comment by KacperZajc** [comment]
and this is exactly what I intended to do with this proposal :)

**Comment by Auahi** [comment]
what happens if they're found innocent? the person deemed guilty pays the fees? I don't think that should be right in every case, for example: If i lost it's not my fault the other person can't speak english so their legal fees will be higher and now I have to pay!!! If Liberland collects no or hardly any taxes it shouldn't be involved in this type of business.

**Comment by terrorist96** [comment]
> what happens if they're found innocent? 

No charge.

> he person deemed guilty pays the fees?

If found guilty, you have to pay it back.

> If i lost it's not my fault the other person can't speak english so their legal fees will be higher and now I have to pay!!!

That's not what we're saying at all.
