### ISSUE TITLE
Number of Citizens

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#309]
The number of citizens will constantly be in flux. The provisions that refer to X% of all citizens need to be amended. I propose changing it to X% of all citizens who participated in the preceeding General Election. Thoughts?

**Comment by KacperZajc** [comment]
why is that?

**Comment by terrorist96** [comment]
Because of the reasons I said above. The number of citizens will never be constant, so what number do we use if we want to determine "5% of all citizens"?

**Comment by KacperZajc** [comment]
maybe we change it to all citizens who registered with the Electoral Register? 
it would be easy to say how many people we have for the purpose of those provisions plus those are people who want to participate in elections/referendums in any event?

**Comment by terrorist96** [comment]
But that number will change too. If I start a petition one day for a referendum, how do I know how many signatures I need? There will be a different number of people registered on day I start and the day I finish gathering signatures. We need a number that doesn't change.

**Comment by KacperZajc** [comment]
I see your point.
OK but I would still change it to all Citizens registered with the Electoral Register (at the time of last General Election)

**Comment by terrorist96** [comment]
That's fine

**Comment by KacperZajc** [comment]
§III.21(1) The referendum shall be triggered by the request of 5% of the overall number of Citizens registered with the Electoral Register at the time of the last General Election, and shall be submitted within ninety days after the Bill was declared constitutional by the Supreme Court.

§V.8(3) The Chief Justice of the Supreme Court or any Justice of the Supreme Court shall only be removable from their position by the Citizens with a majority of two-thirds vote in a referendum called by 10% of the overall number of Citizens registered with the Electoral Register at the time of the last General Election.

§V.10(2) The Chief Public Prosecutor shall be removable from the office by the Citizens with a majority of two-thirds vote in a referendum called by 10% of the overall number of Citizens registered with the Electoral Register at the time of the last General Election.

§III.3(1) Any Assembly Representative may be recalled by the Citizens with a simple majority vote in a referendum called by 5% of the overall number of Citizens registered with the Electoral Register at the time of the last General Election.

???

**Comment by Auahi** [comment]
What about the first day of the month? or something along the lines of that, wouldn't that reflect a number more accurately than the time of the last General Election.

**Comment by Auahi** [comment]
maybe every six months the Electoral Register will update and they have to use the last updated number

**Comment by terrorist96** [comment]
:+1:
