### ISSUE TITLE
Restating Article IV

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#310]
Article IV: The Executive Power

•	§IV.1. The executive power in the Free Republic of Liberland shall be vested in the Cabinet.

•	§IV.2. The Cabinet shall be formed and presided over by the Chancellor, who shall be the Head of State.
o	§IV.2(1) No Person shall hold the office of a Judge of one of the Courts of the Free Republic of Liberland whilst holding the position of Member of the Cabinet concurrently.
o	§IV.2(2) No Person shall hold the position of Chancellor or Member of the Cabinet whilst holding the position of Assembly Representative concurrently.
o	§IV.2(3) All Members of the Cabinet shall receive remuneration for their service as provided in the Annual Budget.

•	§IV.3. The Chancellor may, at any time, resign from the office.
o	§IV.3(1) Should the Chancellor resign, the Assembly shall elect a new Chancellor according to the provisions of Article III.
o	§IV.3(2) Should the Chancellor resign, all Secretaries of State shall resign.

•	§IV.4. The Cabinet shall execute in good faith all laws passed by the Assembly unless any law conflicts with the Constitution.

•	§IV.5. The Chancellor, on behalf of the Cabinet, shall once a year publicly give to the Assembly information on the State of the Republic, and recommend to their consideration such measures as the Cabinet shall judge necessary thereby initiating a legislative procedure in accordance with the provisions of Article III.

•	§IV.6. The powers of the Chancellor and the Cabinet shall be restricted to the following only:
o	§IV.6(1) to run day-to-day state affairs;
o	§IV.6(2) to initiate a legislative procedure;
o	§IV.6(3) to protect and promote the interests of the Free Republic of Liberland worldwide;
o	§IV.6(4) to sign international treaties provided the Supreme Court confirmed the constitutionality of such treaties;
o	§IV.6(5) to produce byelaws in the form of Executive Measures under the powers expressly granted by the Acts of the Assembly;
o	§IV.6(6) to appoint the Chief Justice of the Supreme Court and other Justices of the Supreme Court upon the recommendation of the Judicial Appointment Commission;
o	§IV.6(7) to maintain the State Treasury;
o	§IV.6(8) to appoint the Chief Public Prosecutor and the Chief Attorney of the Republic 
o	§IV.6(9) to supervise all Agents of the executive branch of the Public Administration;
o	§IV.6(10) to bestow honours and awards on Persons who have achieved a great deal in service of Liberland and the idea of liberty worldwide;
o	§IV.6(11) to be the Commander-in-Chief of the voluntary Territorial Defence, should it rise;
o	§IV.6(12) to appoint and remove the Chief Commissioner;
o	§IV.6(13) to grant citizenship of the Free Republic of Liberland in accordance with this Constitution.

•	§IV.7. The Cabinet shall consist of the following Departments only:
o	§IV.7(1) Department of Justice;
o	§IV.7(2) Department of Internal Affairs;
o	§IV.7(3) Department of Security;
o	§IV.7(4) Department of Foreign Affairs;
o	§IV.7(5) Department of Treasury.

§IV.8. No special Department shall be established, nor shall any Department operate outside its jurisdiction.
o	§IV.8(1) Departments shall be allowed to establish Agencies. 
o	§IV.8(2) Every Agency shall be supervised by the relevant Department and no Agency shall operate outside its own jurisdiction or the jurisdiction of its Department.

•	§IV.9. Each Department shall be headed by the Secretary of State for the respective Department.
o	§IV.9(1) All Secretaries of State shall answer to the Chancellor and shall be removable from the office by the Chancellor at any time.

•	§IV.10. The Chancellor and the Cabinet shall be advised as to the law by the Chief Attorney of the Republic, who shall be independent.
o	§IV.10(1) The Chief Attorney of the Republic shall head the Office of the Chief Attorney of the Republic.
o	§IV.10(2) The Chief Attorney of the Republic shall be appointed by the Chancellor for a term of six years.
o	§IV.10(3) The Chief Attorney of the Republic shall have the right to request the Supreme Court to issue a statement clarifying the law of the Free Republic of Liberland.
o	§IV.10(4) The Chief Attorney of the Republic shall appoint, and be responsible for the work of, Attorneys of the Republic who shall represent all bodies of the Public Administration in all civil proceedings.

•	§IV.11. The work of the Law Enforcement shall be overseen by the Chief Commissioner. 
o	§IV.11(1) The Chief Commissioner shall be appointed by the Chancellor for a term not exceeding six years.
o	§IV.11(2) The Chief Commissioner shall answer to the Chancellor and shall be removable from the office by the Chancellor at any time.
o	§IV.11(3) The Chief Commissioner shall be removable form the office by the Citizens with a majority of two-thirds vote in a referendum called by 10% of the overall number of Citizens registered with the Electoral Register at the time of the last General Election.

•	§IV.12.  The Chief Public Prosecutor, Chief Attorney of the Republic and the Chief Commissioner shall not be deemed Members of the Cabinet. 

Rephrase:

§III.8(2) The Assembly shall have the power to impeach the Chancellor along with the Cabinet by passing the Constructive Motion of No Confidence with a simple majority vote of the overall number of Assembly Representatives provided there is a majority for a prospective successor.

§V.12(1) The Chief Public Prosecutor shall be appointed by the Chancellor for a term of six years. [as proposed in the Private Prosecution Issue]

**Comment by terrorist96** [comment]
> o §IV.3(2) Should the Chancellor resign, all Secretaries of State shall resign.

This makes it harder for the Chancellor to resign because he may feel beholden to the other Secretaries.

> o §IV.6(8) to appoint the Chief Public Prosecutor and the Chief Attorney of the Republic**;**

> o §IV.6(12) to appoint and remove~~, should it be necessary,~~ the Chief Commissioner ~~thereby supervise the work of the Law Enforcement~~;

> o §IV.6(13) to grant citizenship of the Free Republic of Liberland in accordance with ~~the provisions of~~ this Constitution.

> o §IV.11(1) The Chief Commissioner shall be appointed by the Chancellor for a term not exceeding ~~6~~ **six** years.

> o §IV.11(3) The Chief Commissioner shall be removable **from** the ~~position~~ **office** by the Citizens with a majority of two-thirds vote in a referendum called by 10% of **the overall number of Citizens registered with the Electoral Register at the time of the last General Election**.

> • §IV.12. The Chief Public Prosecutor, Chief Attorney of the Republic and the Chief Commissioner shall not be deemed ~~the~~ Members of the Cabinet.

**Comment by KacperZajc** [comment]
§IV.3(2): In practice all secretaries would change anyway with the new Chancellor.
