### ISSUE TITLE
Judicial Appointment Commission

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#311]
...

•	§V.3. The Courts of the Free Republic of Liberland shall protect the Citizens thereof and other Residents from any unlawful trespasses into their Rights.

•	§V.4. The Judges of the Courts of the Free Republic of Liberland shall regulate their own affairs within the Secretariat of the Judiciary of the Free Republic of Liberland.
o	§V.4(1) The Secretariat of the Judiciary shall be headed by the Chief Justice of the Supreme Court.
o	§V.4(2) The Secretariat of the Judiciary shall supervise the Judicial Appointment Commission.
o	§V.4(3) The Secretariat of the Judiciary shall supervise all Agents of the judicial branch of the Public Administration.

•	§V.5. The Judges of the Courts of the Free Republic of Liberland shall be independent and shall not be removable by any Member of the other branches of the Public Administration.
o	§V.5(1) The remuneration of the Judges as provided for in the Annual Budget shall not be lowered without the express and informed consent of the Secretariat of the Judiciary of the Free Republic of Liberland.
o	§V.5(2) No Judge of any Court of the Free Republic of Liberland shall be arrested for any period whatsoever unless pursuant to the Supreme Warrant or under exigent circumstances where there is a threat to others or where vital evidence may be destroyed; in such case the Chief Justice of the Supreme Court shall be immediately notified about the detainment and shall have the power to order immediate release of the detained Judge.
o	§V.5(3) The Supreme Warrant shall be issued by the Secretariat of the Judiciary of the Free Republic of Liberland as signed by the Chief Justice of the Supreme Court or at least three Justices of the Supreme Court upon the request of the Office of the Public Prosecutor supported by clear and convincing evidence of the alleged offence.

•	§V.6. All Judges, other than the Justices of the Supreme Court, shall be appointed by the Chief Justice of the Supreme Court upon the recommendation of the Judicial Appointment Commission.
o	§V.6(1) The Judicial Appointment Commission shall be composed of the four Justices of the Supreme Court and three other members appointed by the Chief Justice of the Supreme Court.
o	§V.6(2) The Judicial Appointment Commission shall reach its decisions with a simple majority.
o	§V.6(3) The Judicial Appointment Commission shall recommend to the Chief Justice of the Supreme Court only excellent and experienced lawyers for the judgeship. 
o	§V.6(4) Should the office of the Chief Justice of the Supreme Court become vacant, the Judicial Appointment Commission shall recommend to the Chancellor one of the Justices of the Supreme Court to be appointed the new Chief Justice.
o	§V.6(5) Should the office of any of the Justices of the Supreme Court become vacant, the Judicial Appointment Commission shall recommend to the Chancellor an experienced Judge of impeccable reputation for the replacement.

§V.7. The Judicial Appointment Commission shall have the power to inquire into alleged misconduct of all Judges of all Courts in the Free Republic of Liberland other than the Chief Justice and other Justices of the Supreme Court.
o	§V.7(1) The Judicial Appointment Commission shall have the power to subpoena Judges of the Free Republic of Liberland and Agents of the Public Administration to hear testimonies given under oath. 
o	§V.7(2) The Judicial Appointment Commission may recommend the removal of any Judge from the office upon a proven case of gross misconduct or intentional procurement of the miscarriage of justice.
o	§V.7(3) The removal of a Judge from the office shall be executed by the Chief Justice of the Supreme Court or three Justices of the Supreme Court acting together. 
o	§V.7(4) Should the Judicial Appointment Commission found evidence of any criminal conduct, it shall be passed to the Office of the Chief Public Prosecution; testimonies given in breach of oath shall be prosecuted in regular manner in the Criminal Court.

...

Requires a bit of renumbering.

rephrasing:

•	§III.9(3) The Assembly Committee shall be established upon a suspicion of misconduct or mismanagement of any Agent or Member of the Public Administration, other than Judges of any Court of the Free Republic of Liberland, in order to investigate the allegations.

•	§III.9(4) The Assembly Committee shall have the right to summon Agents and Members of the Public Administration, other than Judges of any Court of the Free Republic of Liberland, to hear testimonies given under oath.

**Comment by terrorist96** [comment]
> o §V.6(3) The Judicial Appointment Commission shall recommend to the Chief Justice of the Supreme Court only excellent and experienced lawyers for the judgeship. 

> o §V.6(5) Should the office of any of the Justices of the Supreme Court become vacant, the Judicial Appointment Commission shall recommend to the Chancellor an experienced Judge of impeccable reputation for the replacement.

How are you going to enforce this? I don't like using words like 'excellent' and 'experienced' and 'impeccable'

**Comment by KacperZajc** [comment]
The point of this provision was to specify that lawyers are to be appointed judges, and judges are to be appointed Justices of the Supreme Court, adjectives are here of secondary importance

**Comment by terrorist96** [comment]
Change them all to `qualified` plz.

**Comment by KacperZajc** [comment]
ok
