### ISSUE TITLE
How voting should work

### ISSUE THREAD

**Issue by Auahi** [liberland/constitution#314]
So I haven't been on here in while, so I'm not up to date on everything, but have we decided how voting works yet for office etc. If not it shouldn't be first past the post(whoever gets the most votes) we should have it be run off voting.

**Comment by Auahi** [comment]
Your thoughts?

**Comment by KacperZajc** [comment]
this issue will be discussed later, see #252

**Comment by Auahi** [comment]
Okay and LOL those are all things I wanted to address good thing you posted that, but when you say later do you mean once Liberland has political relations with other nations(De facto recognition) or just in a few months, sorry these are just topics I'm very interested in

**Comment by KacperZajc** [comment]
I meant it's hard to say now what kind of electoral rules should we adopt;
Feel free to submit your proposal in #252

**Comment by Auahi** [comment]
oh okay thanks
