### ISSUE TITLE
Chancellor's term life long?

### ISSUE THREAD

**Issue by Auahi** [liberland/constitution#315]
Correct me if I'm wrong but is this true? I could not find any writing limiting the chancellor's term, so is it indefinite(Until they're impeached)?

**Comment by KacperZajc** [comment]
We should consider adding this:

On the first meeting after the General Election, the Chancellor along with the Cabinet shall request the Assembly to vote on the Motion of Confidence.
Should the Assembly fail to pass the Motion of Confidence with a simple majority vote of the overall number of all Assembly Representatives, the Chancellor along with the Cabinet shall resign.

**Comment by Auahi** [comment]
that's an idea, maybe the chancellor should have 5 year terms, with no term limit, if this were to happen I'd rather have citizens vote on the chancellor then...

**Comment by KacperZajc** [comment]
if we introduce what I propose here, he will be replaced usually every 4 years (with the General Election)

**Comment by Auahi** [comment]
I know but it it almost forces him out, the other thing would allow him to stay in until people see fit... Your idea is good too, I'm just suggesting more options...

**Comment by KacperZajc** [comment]
your option would turn the whole system into presidential, Id rather keep it quasi parliamentary; but Im glad you raised this issue, it really needs fixing

**Comment by Auahi** [comment]
I think I misinterpreted you before when I read the Motion of Confidence I thought of the motion of no confidence which would spiral into a catch 22,

**Comment by terrorist96** [comment]
Are we going to add this?
