### ISSUE TITLE
New name for head of state(Chancellor)

### ISSUE THREAD

**Issue by Auahi** [liberland/constitution#316]
Calling our head of state "Chancellor" seems unfitting:

1) Chancellor typically refers to the head of government not head of state
2) Chancellor is used to describe the head of government in german speaking countries
3) In relation to 2 Liberland is not a german speaking country and it's head of state should reflect that of the people

**Comment by KacperZajc** [comment]
the Chancellor is the head of the government here (and the head of state), the very term is used in British politics as well

**Comment by Auahi** [comment]
We should consider changing this then: 

§IV.2. The Cabinet shall be formed and presided over by the Chancellor, who shall be the Head of State.

I thought UK used prime minister

**Comment by KacperZajc** [comment]
Head of State doesnt have any legal meaning, it's only an honorary title
The UK uses prime minister but the Minister of Treasury is called the Chancellor

**Comment by Auahi** [comment]
oh okay
