### ISSUE TITLE
land tax -> land fee

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#317]
•	§III.7(3) to impose the fee on land as provided for in the Land Bill;

•	§III.14(3) a Land Bill;
	
•	§III.17. A Land Bill shall propose, or alter, the fee on land of the Free Republic of Liberland.
o	§III.17(1) All Land Bills shall only be voted on whilst all Assembly Representatives are present and passed with the unanimous vote of all Assembly Representatives.
o	§III.17(2) All Land Bills shall be subject to the power of general veto by the Citizens as provided in §III.22.
o	§III.17(3) The fee shall be fixed per meter square of land.
o	§III.17(4) The fee shall be payable once a year by some or all owners of land within the territory of the Free Republic of Liberland other than the Public Administration, as prescribed in the Bill.
o	§III.17(5) The overall fee revenue shall be calculated not to exceed 5% of the Gross Domestic Product of the Free Republic of Liberland of the preceding year.
o	§III.17(6) The fee shall be levied for one or more of the following purposes only:
o	§III.17(7)(a) maintaining the infrastructure of the Public Administration;
o	§III.17(7)(b) providing for the Law Enforcement;
o	§III.17(7)(c) providing for the Courts of the Free Republic of Liberland;
o	§III.17(7)(d) providing for Agents and Members of the Public Administration;
o	§III.17(7)(e) securing and promoting the interests of the Free Republic of Liberland worldwide.

§III.22. All Land Bills or Constitutional Bills shall be subject to the mandatory referendum.
§III.23(2) Should a Constitutional Bill or Land Bill be vetoed, it shall not be resubmitted to the Assembly for at least ten years.

New:
II.XX. No law shall introduce any form of taxation within the Free Republic of Liberland, nor shall any periodic fees, other than the fee on land as provided in the Land Bill, be imposed on any natural or legal Person; only spontaneous fees for services provided or as punishment for culpable behaviour shall be allowed; nor any form of duty on goods, services and/or capital exported from, or imported into, the Free Republic of Liberland shall be introduced.

**Comment by Auahi** [comment]
I did some calculations:
If Liberland had a GDP (Nominal) of 2.5 Billion (Roughly Half of Monaco's), and the government owned 2/5 of the land (This is a small country so it's realistic) that would allow 4.2 Million square meters to be available to the public making the price per meter2 around 30 euros, this would make a 250m2 property 7500 a year

Now if something like this were to take place I think we should only tax large commercial properties, and Large rental properties (Like High rise apartments), this wouldn't be zoning per say but it would allow for buildings which generate large incomes only to pay taxes cause they could afford more...

**Comment by KacperZajc** [comment]
this provision is a cap so it certainly can be less :)

**Comment by Auahi** [comment]
that is true, but I'm still in favour of only taxing certain buildings, maybe buildings over 4 stories or something like that, or maybe buildings that are deemed commercial are taxed more than non.

**Comment by KacperZajc** [comment]
If we rephrase: 

o §III.17(4) The fee shall be payable once a year by some or all owners of land within the territory of the Free Republic of Liberland other than the Public Administration, as prescribed in the Bill.

Now the Assembly can impose a fee on some owners as you suggest, but I dont want to include such detailed conditions in the Constitution.

**Comment by Auahi** [comment]
Your right I'm not comfortable with putting that in either, maybe what I'm saying can be addressed at a later point...

**Comment by terrorist96** [comment]
§III.17(4) The fee shall be payable once a year by some or all owners of land within the territory of the Free Republic of Liberland other than the Public Administration, as prescribed in the Bill.

The wording here could be misconstrued to mean that only people who own the land, who are in Liberland, will be required to pay the fee. If you own land, but don't live in Liberland, you can avoid the fee.

**Comment by KacperZajc** [comment]
...owners of land SITUATED within the territory of the Free Republic of Liberland...

???

**Comment by terrorist96** [comment]
It's still semi-confusing because it's not clear if you're referring to the land or the owners. We'll continue this in #323
