### ISSUE TITLE
control of borders

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#318]
§I.14. The borders of the Free Republic of Liberland shall not be deemed within the territory of the Free Republic of Liberland thereby nothing in this Constitution shall not prevent the Assembly from determining what Persons and goods may and may not enter or leave the territory of the Free Republic of Liberland. 

I know it's not exactly libertarian, Im putting it here because the President wants to comply with certain international treaties for political reasons and this seems to be the only way to reconcile it with the constitution.

**Comment by Auahi** [comment]
The wording of this is horrendous!!!!

**Comment by Auahi** [comment]
how about this: 
§I.14. The borders of the Free Republic of Liberland shall be deemed on the outermost part of the territories held by the Free Republic of Liberland. No article in the constitution of the Free Republic of Liberland shall prevent the Assembly or any legal body granted by the Assembly from determining what Persons and goods may or may not enter or leave the territory of the Free Republic of Liberland.

This is hard to word

**Comment by yopdog** [comment]
This is a very dangerous provision. How can we stop it from opening the door to protectionist policies and the assembly passing unnecessary laws that restrict imports?

**Comment by KacperZajc** [comment]
I am aware it's dangerous but it's not exactly my idea.
It's all about politics and economic areas in Europe.

Having said that, Im open to suggestions.

**Comment by Auahi** [comment]
I don't think it is what's stopping people from importing waste and garbage, also this is very important:

 "I know it's not exactly libertarian, Im putting it here because the President wants to comply with certain international treaties for political reasons and this seems to be the only way to reconcile it with the constitution"

**Comment by yopdog** [comment]
May I ask what international treaties the president wants to comply with and why exactly we need this provision?

**Comment by KacperZajc** [comment]
most likely, the whole European Economic Area package 
if not, bilateral treaties which would require that anyway

**Comment by Auahi** [comment]
This is a policy every country has, we could have Liberland be like St.Peters Square, 

Are you familiar with the border policies of Vatican City, lol I like tiny countries so that's the only reason I know about them but you should definitely look them up

**Comment by Auahi** [comment]
If you look up Border Policies of San Marino there's more information on it, but basically you don't need a passport to get in or out, completely open borders with Italy.

**Comment by Auahi** [comment]
I do think Liberland should have border controls though this would allow the government to identify everyone who's in Liberland, and the amount of time they've been in Liberland, example: There aren't laws on this yet (that I'm aware of), but lets say you must live in Liberland for 5 years in order to be a citizen, how will the government know how long you were in Liberland for?

**Comment by yopdog** [comment]
I'm very much against this provision, but I understand it may be one of the few compromises we have to make in order to have any chance of recognition. I would therefore suggest we make this provision as specific and limiting as possible so it will allow Liberland to comply with international treaties and nothing else. 

This would be my suggestion:    
>§I.14. Nothing in this Constitution shall prevent the Assembly from regulating the passage of Persons and listed goods entering or leaving the Free Republic of Liberland only insofar as is necessary to comply with international treaties.
§I.14(1) The Assembly shall have the power to regulate the passage of the following goods alone: weapons, drugs, biological and chemical substances.  

??

**Comment by Auahi** [comment]
I think it's kind of 'weird' to put this is "to comply with international treaties", that just doesn't sound like something that should be in a constitution, you would have to specify what international treaties.

I rewrote mine:

§I.14. The borders of the Free Republic of Liberland shall be deemed on the outermost part of the territories held by the Free Republic of Liberland. No content in the constitution of the Free Republic of Liberland shall prevent the Assembly from determining what Persons and goods may or may not enter or leave the territory of the Free Republic of Liberland.

also The Assembly should be able to regulate other goods too, that list seems very "basic" if you understand what I'm saying

**Comment by KacperZajc** [comment]
I agree with @Auahi that 'to comply with international treaties' doesnt belong in the Consitution.
I also agree your list in too basic.

I could agree to this version:

§I.14. Nothing in this Constitution shall prevent the Assembly from regulating the passage of Persons and listed goods entering or leaving the Free Republic of Liberland.

However, I expressly mentioned that the borders are not within jurisdiction to create (lame) justification why the Assembly can do it. Id rather we use some fictitious legal construct here to reconcile this provision with the spirit of the rest of the document.

**Comment by yopdog** [comment]
Won't international treaties just limit what can be exported? I would like to know exactly what limitations these treaties bring before we make any provisions concerning them. I just feel like I don't have enough information about them to make a good suggestion for this provision. 

That said, one thing I know I don't want to see is a provision that gives the assembly the power to regulate the border however it wants. A provision like this would leave no constitutional protection against bad laws concerning imports and exports.

**Comment by yopdog** [comment]
>The EEA is based on the same "four freedoms" as the European Community: the free movement of goods, persons, services, and capital among the EEA countries. Thus, the EEA countries that are not part of the EU enjoy free trade with the European Union.
**As a counterpart, these countries have to adopt part of the Law of the European Union**. However they also contribute to and influence the formation of new EEA relevant policies and legislation at an early stage as part of a formal decision-shaping process.[6]
source - https://en.wikipedia.org/wiki/European_Economic_Area#Rights_and_obligations

Adopt part of the Law of the European Union? What laws would this include?

**Comment by Auahi** [comment]
It's not so much as international treaties as it is other governments trusting Liberland to not allow "crazy" things to happen there.

"That said, one thing I know I don't want to see is a provision that gives the assembly the power to regulate the border however it wants. A provision like this would leave no constitutional protection against bad laws concerning imports and exports."

The citizens could just veto any bad laws that would come out.

**Comment by yopdog** [comment]
>The citizens could just veto any bad laws that would come out

ok, than why have a bill of rights?

**Comment by KacperZajc** [comment]
I honestly dont know what kind of limitations will be imposed.
We can come back to this provision later :)

**Comment by Auahi** [comment]
@yopdog what things are you scarred they'd limit?

**Comment by yopdog** [comment]
@KacperZajc Good idea, we should defiantly not make changes without solid information.

**Comment by yopdog** [comment]
@Auahi Protectionism

**Comment by KacperZajc** [comment]
OK, so Im adding it to #252
