### ISSUE TITLE
Citizens right to over turn any decision made by the Assembly?

### ISSUE THREAD

**Issue by Auahi** [liberland/constitution#325]
Right now citizens can only overturn bills, but should citizens be able to overturn any decision made by the Assembly? I couldn't find any content relating to this.

**Comment by KacperZajc** [comment]
what kind of decisions you have in mind?

**Comment by Auahi** [comment]
§III.7(7) to assent to the incorporation of any new territories to the Free Republic of Liberland with any status the Assembly shall determine;

what happens if the Assembly says they'd not want to incorporate a new piece of territory yet most citizens do, or vice versa. Just things like that.

**Comment by Auahi** [comment]
Also what about citizens bringing a topic or law to the assembly rather than wait for the cabinet?

**Comment by KacperZajc** [comment]
they can lobby 1/4 of assembly representative to submit the issue to the cabinet for consideration

**Comment by terrorist96** [comment]
> Also what about citizens bringing a topic or law to the assembly rather than wait for the cabinet?

I mentioned this in #281 but wasn't fully addressed.
