### ISSUE TITLE
Chancellor resignation

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#328]
> §IV.3(2) Should the Chancellor resign, the whole Cabinet shall resign.

The Cabinet is composed of Departments. The departments can establish Agencies. Does this mean that everyone employed by the Cabinet has to resign?

**Comment by KacperZajc** [comment]
by 'whole Cabinet' I mean the Secretaries of State 
we should rephrase:

§IV.3(2) Should the Chancellor resign, all Members of the Cabinet shall resign.

???

**Comment by terrorist96** [comment]
> by 'whole Cabinet' I mean the Secretaries of State 

Then why did you change it from

>  * **§IV.3(2)** Should the Chancellor resign, all Secretaries of State shall resign.		

to

>  * **§IV.3(2)** Should the Chancellor resign, the whole Cabinet shall resign.

**Comment by KacperZajc** [comment]
Members of the Cabinet may comprise people other than the Secretaries of State who are not mentioned in the Constitution

**Comment by terrorist96** [comment]
What is the definition of "members of the cabinet"? This is important if we're going to be forcing them to resign if the chancellor resigns (or becomes incapacitated/passes away).

**Comment by KacperZajc** [comment]
No definition, I think it should be left open to interpretation.
Definitely all Secretaries of State but there might be some positions within the Cabinet not mentioned in the Constitution that would naturally fall within the definition.

**Comment by terrorist96** [comment]
I think the new Chancellor should have the liberty to decide if he wants to retain some or all of the current members of the cabinet, or replace some or all of them.
Because what happens if the Chancellor dies or becomes severely ill? A new Chancellor would be needed, but the old one never 'resigned' or was 'impeached'

**Comment by KacperZajc** [comment]
I think we should go with 'all Members of the Cabinet' here but I'll open another Issue on replacement for the Chancellor in case he resigns or is unable to act

**Comment by KacperZajc** [comment]
#335
