### ISSUE TITLE
III.24/25 changing

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#330]
These need changing in order to comply with the accepted process (bill passed by Assembly, reviewed by Supreme Court, approved in the referendum (if applicable).

> §III.23. Any Bill vetoed by the Citizens in the referendum shall be considered void.
§III.23(1) Should an ordinary Bill or a Treaty Bill be vetoed, **neither** it **nor any substantially similar Bill** shall ~~not~~ be resubmitted to the Assembly for at least three years.
§III.23(2) Should a Constitutional Bill or Land Bill be vetoed, **neither** it **nor any substantially similar Bill** shall ~~not~~ be resubmitted to the Assembly for at least ten years.
§III.23(3) Should the Financial Bill be vetoed, the provisions of the Annual Budget adopted the previous year shall apply.
§III.24. A Bill shall become “~~Under Consideration~~ **Passed**” once it is passed by the Assembly in accordance with the provisions of this Article~~, and either ninety days have passed and no referendum was called in accordance with §III.21., or on the day the Bill obtained the assent of the Citizens in referendum under §III.21. or §III.22~~.
§III.25. A Bill shall become **“Under Consideration”** ~~the law of the Free Republic of Liberland, and shall be known as “Act” once it became “Under Consideration” in accordance with the procedure provided for in §III.24., and~~ **once it has been** ~~was~~ declared constitutional by the Supreme Court of the Free Republic of Liberland according to the procedure laid down in Article V.
§III.26. A Bill shall become the law of the Free Republic of Liberland, and shall be known as “Act” once it became “Under Consideration” in accordance with the procedure provided for in §III.25., and either ninety days have passed and no referendum was called in accordance with §III.21., or on the day the Bill obtained the assent of the Citizens in referendum under §III.21. or §III.22
~~§III.26. The law of the Free Republic of Liberland shall enter into force on the day specified in the Act but no sooner than on the thirty-first day after it is signed by the Chief Justice of the Supreme Court, or if unable, by any other Justice of the Supreme Court, which shall take place upon the declaration of constitutionality.~~

Thoughts?

**Comment by KacperZajc** [comment]
Im fine with it. Make it a PR.

**Comment by KacperZajc** [comment]
Please include this 'qualified' adjective as well :)

**Comment by terrorist96** [comment]
got it :stuck_out_tongue:
