### ISSUE TITLE
Chief Justice of the Supreme Court replacement 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#332]
Maybe we should go down this road:

§V.6(4) Should the office of the Chief Justice of the Supreme Court become vacant, the Chancellor shall appoint the longest-serving Justice of the Supreme Court to be the new Chief Justice.

We would avoid a battle within the Judicial Appointment Commission between the Justices over the replacement. It would also ensure more predictability.

**Comment by terrorist96** [comment]
I'm not opposed

**Comment by terrorist96** [comment]
> §V.6(4) Should the office of the Chief Justice of the Supreme Court become vacant, the Chancellor shall appoint the ~~longest-serving~~ **most senior** Justice of the Supreme Court to be the new Chief Justice.

**Comment by KacperZajc** [comment]
Right. Make a PR :)

**Comment by terrorist96** [comment]
Done. I think we should slow down to let others catch up on all the changes and submit comments too. :)
