### ISSUE TITLE
validity of elections and referendums 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#336]
§I.14. The validity of any election or referendum held within the Free Republic of Liberland shall be reviewed by the Supreme Court upon the request of one-fourth of the overall number of Assembly Representatives submitted within twenty-four hours after the publication of the results; should the Supreme Court find any evidence of erroneous and/or fraudulent conduct, it shall have the power to declare such election or referendum invalid and order it is anew.

§III.7(13) to request the Supreme Court to review the validity of any election or referendum held within the Free Republic of Liberland.

§V.10(5) The Supreme Court shall have jurisdiction to review the validity of any election or referendum upon the request of one-quarter of the overall number of Assembly Representatives.

???

**Comment by terrorist96** [comment]
> §I.14. The validity of any election or referendum held **with**in the Free Republic of Liberland shall be reviewed by the Supreme Court upon the request of one-fourth of the overall number of Assembly Representatives submitted within twenty-four hours after the **publication of the** results ~~were published~~; should the Supreme Court find any evidence of erroneous and/or fraudulent conduct, it shall have the power to declare such election or referendum invalid and order it ~~is organised again~~ **anew**.

> §III.7(13) to request the Supreme Court to review the validity of any election or referendum held **with**in the Free Republic of Liberland~~;~~**.**

Should be a period at the end, not a semicolon.

**Comment by terrorist96** [comment]
Closed without merging a PR?
