### ISSUE TITLE
new ideas

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#347]
I want to consult something with you.

1) I would like to substitute this provision for I.4: 

No provision of this Bill of Rights shall be construed as to provide any legal justification for any act or omission which does not arise out of the inherent right of self-defence and amounts to physical or grave psychological violence towards another living being, or threat thereof, invasion of privacy, fraud or direct and grave interference with enjoyment of one’s property; nothing in such provision shall be deemed to prevent the Assembly from criminalising such conduct.

The meaning remains the same but I think it is clearer.

2) I would like to reword the 'victimless crime' provision:

§I.19. No law shall criminalise any act or omission which does not directly harm any living being; nor shall any law criminalise any act or omission which has been validly consented to by another Individual; no Individual shall be capable of harming him or herself; nothing in this provision shall prevent the Assembly from criminalising conduct interfering with the fairness of elections and referendums in the Free Republic of Liberland, the work of the criminal justice system, bribery, attempting or procuring a criminal offence, or knowingly giving any form of direct aid to a Person committing an offence.

What is more, I think we need something along these lines (it's just a preliminary draft, Im not even sure where to fit it at this point):

There shall be two sources of criminal offences in the Free Republic of Liberland.
The Assembly shall have the power to create criminal offences which are allowed under the relevant provisions of the Bill of Rights.
All such criminal offences shall specify the maximum penalty they carry.
The Constitution shall be capable of creating criminal offences where a Person acts in breach of any provision which is capable of creating a criminal offence.
Whether a provision is capable of creating a criminal offence shall be a matter resolved by the Courts of the Free Republic of Liberland.

The first part is obvious - the Assembly creates criminal offences.
The second part is less obvious - the point here is to make sure breach of the Constitution will be a criminal offence - if we leave it to the Assembly to criminalise such conduct it might decide not do so in order to protect Members of the PA (for obvious reasons). Here we make sure it does not happen by saying that the Constitution itself creates such offences and we leave it to the Courts to decide breach of what provisions do in fact result in criminal prosecution.

3) I want to strengthen the right of self-defence by adding this part:

§I.38. All Persons shall have the right of self-defence and/or defence of their property, and others who are under a direct and real threat, against initiators of aggression, including any Agent of the Public Administration acting unlawfully or in error; no Person shall be convicted of any criminal offence for any act or omission which was a direct response to another Person trespassing on that Person’s property and acting in breach of the law or the Constitution resulting in such a threat as described in this provision.

4) Finally, I want to restructure the Civil Court provision:

•	§IV.11 Civil disputes shall be adjudicated in the Civil Court.
o	§IV.11(1) All disputes which do not involve criminal prosecution shall be considered civil disputes.
o	§IV.11(2) All disputes concerning subject matter of small value as prescribed by law shall be adjudicated by one Judge.
o	§IV.11(3) All other disputes shall be adjudicated by a panel of three Judges reaching a decision with a simple majority.
•	 §IV.12 The Civil Court shall have jurisdiction to adjudicate all disputes concerning contracts which were made under, and civil wrongs which took place within, the jurisdiction of the Free Republic of Liberland.
o	§IV.12(1) The jurisdiction of the Civil Court shall not be ousted by any contract unless fair arbitration proceedings are envisaged in case of dispute; whether arbitration proceedings are fair shall be subject to a challenge in this Court.
o	§IV.12(2) Contracts may require parties to attempt mediation before the jurisdiction of the Court becomes exercisable.
o	§IV.12(3) The Civil Court shall have jurisdiction to adjudicate all administrative disputes between Citizens or Residents of the Free Republic of Liberland and any body of the Public Administration.
o	§IV.12(4) The Civil Court shall have jurisdiction to hear disputes related to the well-being of Minors and Persons lacking mental capacity.
o	§IV.12(5) The Civil Court may adjudicate civil disputes concerning contracts made outside the jurisdiction of the Free Republic of Liberland as prescribed by law. 
o	§IV.12(6)  The Civil Court shall have the power to issue Publication Orders in accordance with this Constitution and Warrants, injunctions and other orders as prescribed by law.

Feel free to comment.

**Comment by yopdog** [comment]
>nor shall any law criminalise any act or omission which has been validly consented to by the victim who is an Individual

If he has consented then he shouldn't be considered a victim. Regardless, this part can be worded a bit better:  

No law shall criminalise any act or omission which does not directly harm any living being; nor shall any law criminalise any act or omission between consenting individuals; no Individual shall be capable of harming **him or herself**; nothing in this provision shall prevent the Assembly from criminalising conduct interfering with the fairness of elections and referendums in the Free Republic of Liberland, the work of the criminal justice system, bribery, attempting or procuring a criminal offence, or knowingly giving any form of direct aid to a Person committing an offence.

??

**Comment by yopdog** [comment]
By the way, when are you going to implement all the changes from #345?

**Comment by KacperZajc** [comment]
I will update it soon, I am waiting for further comments from that barrister.

**Comment by yopdog** [comment]
>act or omission which has been **validly** consented to

Is there a reason for the use of the word "validly" before consented? Why not just say "been consented to..." ?

**Comment by terrorist96** [comment]
> no Individual shall be capable of harming him or herself

This sounds a bit weird. An individual is of course able to harm themselves. I prefer the old wording
"no Individual shall be considered a victim of one’s actions or omissions"

> §I.38. All Persons shall have the right of self-defence and/or defence of their property, and others who are under a direct and real threat, against initiators of aggression, including any Agent of the Public Administration acting unlawfully or in error; no Person shall be convicted of any criminal offence for any act or omission which was a direct response to another Person trespassing on that Person’s property **or rights** and acting in breach of the law or the Constitution resulting in such a threat as described in this provision.

> whether arbitration proceedings are fair shall be subject to a challenge in this Court.

`the fairness of arbitration shall be subject to a challenge in this Court.`

**Comment by KacperZajc** [comment]
@yopdog: validly as an equivalent of 'express and informed consent' that we use 
@terrorist96: OK

Please see #350
