### ISSUE TITLE
What is constitution? What is Governmental organization? What is law?

### ISSUE THREAD

**Issue by Ikler** [liberland/constitution#348]
I think a big issue here is that constitution, governmental organization and law are being mixed here!
I would positively include the core values and the overall governmental dedication in this document.
Legislative, Executive and any other power should be described and restricted in deviating from the Liberatarian core values but not fully regulated. That is part of the governmental and elective process.

A government and its citizens have core values: duties, responsibilities and restrictions. Those are to be emphazised! Not more.

Don`t want to be the same as other governments? Do not let your citizens get lost in legalese. Revert to simple terms and language wherever possible!

The rest is law! Lawyers and legalese have written too many items - read the Declaration of Independance of the US or the Swiss Rütlischwur - those are the core of their existance and it fairly simple and straight forward. 

So here too much is included in the constitution! Re-Classify what is what and proceed simple and positivley.

I posted a suggestion in my fork.

**Comment by KacperZajc** [comment]
The Constitution is long and includes some provisions which could be regarded as 'law' because we dont trust governments that would normally introduce such laws in the future as they might use them to limit liberty of the people. A process we have been witnessing in the US for hundred years. By including some important laws here, we ensure the greatest degree of freedom possible.

**Comment by Ikler** [comment]
And that is the problem. The constitution is not LAW - it is the core existence of the state. You want law, then prepare those for starting. Remember laws can be changed. Constitution and Bill of Rights could be set if no ammendment is possible. If written clear and concise - no law may and needs to override. Do you really want a core value of the nation full of distrust and negativity? Noone wishes that and noone will take that seriously. Different and positive - and most of all - servicing the future citizens! That should be the motto...

**Comment by yopdog** [comment]
@Ikler I agree with what you are saying. You should really stay here and help build the constitution If you wish to see your suggestions being implemented :)

**Comment by Ikler** [comment]
a) I will and b) I wrote my version for discussion and legal review...
