### ISSUE TITLE
Get a constitutional scholar to review the document

### ISSUE THREAD

**Issue by fare** [liberland/constitution#35]
Before the document is finalized, someone with a serious degree or pedigree in constitutional law (or better, comparative constitutional law) shall review it. And that's not me.

With a bit of chutzpah, maybe you can get Randy Barnett involved...

**Comment by ericalston** [comment]
I have a significant pedigree in comparative constitutional design, and would love to get involved. I have nowhere near the stature of a Randy Barnett, but by that same logic, it would require minimal to no chutzpah to obtain my involvement...

**Comment by rotilho** [comment]
+ericalston
