### ISSUE TITLE
new version updated

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#350]
I updated the draft. Some small grammatical changes not discussed here are added pursuant to the ongoing suggestions of the lawyer. 

A completely new provision - I.63.

Feel free to submit PRs.

**Comment by terrorist96** [comment]
Regarding the rewording of I.4, it removes the part about people retaining other rights that may not be enumerated.
Can that be added back? I'm working on a PR.

**Comment by terrorist96** [comment]
This:
> §I.48. No law shall interfere with the **validity** and/or content of any contract

interferes with:

> §IV.12(1) The jurisdiction of the Civil Court shall not be ousted by any contract unless fair arbitration proceedings are envisaged in case of dispute; whether arbitration proceedings are fair shall be subject to a challenge in this Court.

**Comment by terrorist96** [comment]
We need the courts to be able to nullify an invalid contract (for example, one that requires slavery, etc).

**Comment by KacperZajc** [comment]
we have already thought of that:

§I.48. No law shall interfere with the validity and/or content of any contract made exclusively between Individuals and/or legal Persons 

unless in order to give effect to relevant provisions of this Constitution, 

nor shall it mandate or forbid any Individual to enter into contractual relations with any other Individual and/or legal Person, or any body of the Public Administration; nor shall it provide any financial incentive in that respect.

:)
