### ISSUE TITLE
amending the Constitution

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#353]
What if we add this as §II.16(3):

No provision of the Bill of Rights shall be abolished in total or in substantial part, nor shall it be amendable in any manner which would defeat the purpose of the original version of provision in question.

What do you think?

**Comment by terrorist96** [comment]
I think the constitution is hard enough to amend as it is that we don't need this extra protection for the bill of rights.

**Comment by KacperZajc** [comment]
@yopdog what do you think?

**Comment by yopdog** [comment]
I agree with @terrorist96, the constitution is hard enough to amend as it is. If we make it too hard to change things in the constitution, people might stop respecting it since they will feel they have no say in the laws they live under.

**Comment by KacperZajc** [comment]
ok if you both say so :)
