### ISSUE TITLE
responsibility under the Constitution

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#355]
I want to add one subsection to each provision regarding the Chief Attoreny, Public Prosecutor and Commissioner to impose deeper responsibility:

III.11: The Chief Attorney of the Republic shall take all available measures to ensure the Cabinet is provided with a precise and impartial piece of advice as to the Constitution, international law and current domestic law of the Free Republic of Liberland.

III.12: The Chief Public Prosecutor shall take all available measures to ensure all public prosecutions are undertaken in good faith and in the interest of a Victim or the Citizens of the Free Republic of Liberland.

III.13: The Chief Commissioner shall take all available measures to ensure the enforcement of law by Law Enforcement is conducted in the least intrusive and most peaceful manner possible.

**Comment by terrorist96** [comment]
Pretty indifferent to this.

**Comment by KacperZajc** [comment]
No revolution here. I just want to put constitutional pressure on these people to stick to libertarian ideology when doing their job.
If it is proven they did not do everything they could, and harm is done, they could be removed from the office for breaching the Constitution.

**Comment by terrorist96** [comment]
:+1:
