### ISSUE TITLE
Calculating GDP

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#356]
If there's no reporting requirements for businesses, how do we calculate GDP?

**Comment by KacperZajc** [comment]
Honestly, I have no idea. I think it is possible nevertheless but it's a purely economic question to which I have no answer.

**Comment by terrorist96** [comment]
It matters because:

> §II.17(6) The overall Fee revenue shall be calculated not to exceed 5% of the Gross Domestic Product of the Free Republic of Liberland of the preceding year.

**Comment by KacperZajc** [comment]
I know it does. Im not an economist though :/

**Comment by terrorist96** [comment]
I think we should change or remove §II.17(6) until it gets figured out.

**Comment by KacperZajc** [comment]
I think we can leave it for now. It is just something that needs to be consulted at some point with economists.
