### ISSUE TITLE
Recent changes

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#358]
Can we please get an explanation for the following changes?

> I.12 removal of `and privacy of personal data`

> §III.12(4) The Chief Public Prosecutor shall be under obligation to take all available measures to ensure all public prosecutions are undertaken in good faith and in the interest of a Victim or the Citizens of the Free Republic of Liberland where applicable.

What's the rationale for adding `where applicable` at the end of this provision? In case of private prosecution?

Thanks.

**Comment by KacperZajc** [comment]
I.12: it is already covered by §I.4. 
III.12(4): public prosecution can be requested by the victim or if none it is conducted on behalf of the citizens - so this part is applicable only if there is no victim
