### ISSUE TITLE
Conflict for appointments

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#359]
As pointed out by someone on Facebook, the following two sections conflict with each other:

> §III.7(7) to appoint the Justices of the Supreme Court upon the recommendation of the Judicial Appointment Commission;
§IV.6. All Judges, other than the Justices of the Supreme Court, shall be appointed by the Chief Justice of the Supreme Court upon the recommendation of the Judicial Appointment Commission.

**Comment by KacperZajc** [comment]
Im reading it again and again and dont see the conflict?

**Comment by terrorist96** [comment]
You're right. I think the person was confused between judge and justice

**Comment by terrorist96** [comment]
You're right. I think the person was confused between judge and justice
