### ISSUE TITLE
Citizenship?

### ISSUE THREAD

**Issue by hazzik** [liberland/constitution#36]
I think that constitution shall define following regarding the citizenship:

1. How the citizenship can be obtained.
2. How a person can renounce his/her citizenship.
3. That no one can lose their citizenship for whatever reasons.
4. Dual/trial/etc citizenship?

**Comment by KacperZajc** [comment]
3 there was such a provision but the President said we would like to deport people for breached of the law so I removed it

**Comment by hazzik** [comment]
@KacperZajc then we need to make an exception "only by court"?

**Comment by KacperZajc** [comment]
ok we can do that

**Comment by KacperZajc** [comment]
No person shall be deprived of his or her citizenship otherwise than by a court of law.

**Comment by hazzik** [comment]
@KacperZajc what about 1, 2, and 4?

**Comment by KacperZajc** [comment]
I leave for ordinary laws to specify; we even dont know any details at this point

**Comment by hazzik** [comment]
Ok, I'll create an issue in https://github.com/liberland/laws

**Comment by hazzik** [comment]
But I still think that constitution shall say that these questions are regulated by a law
