### ISSUE TITLE
preliminary hearing for appeals 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#361]
To bring IV.8 in line with IV.10(1) we need to amend it a bit:

§IV.8. The Courts of the Free Republic of Liberland shall consist of the Civil Court, Criminal Court and the Supreme Court.
•	§IV.8(1) Should a defendant consider evidence gathered against him or her as grossly insufficient or a prosecution or claim as clearly unconstitutional, he or she may request the Civil Court or Criminal Court to hold a Preliminary Hearing.
•	§IV.8(2) Should a defendant request a Preliminary Hearing, it shall be held by one Judge of the relevant Court who may dismiss the case before it proceeds to a full trial on the grounds of the lack of sufficient evidence or clear unconstitutionality of the prosecution or claim.
•	§IV.8(3) Should a party to a trial be unsatisfied with the verdict or sentence given, he or she may request the Supreme Court to review the case upon appeal on the basis of the mistaken application of law, material procedural irregularity or severity of sentence.
•	§IV.8(4) The permission to such a request shall be granted or refused at a Preliminary Hearing held by one Justice of the Supreme Court depending on the merit of the application submitted; all appeals on the point of law concerning a matter of constitutionality shall be automatically granted the permission to be reviewed by the Supreme Court.
•	§IV.8(5) The Judge shall have the power to issue such orders as deemed necessary and within the powers of the relevant Court; such orders shall be reviewable at a full trial.

**Comment by terrorist96** [comment]
Only one Justice will make the decision of granting an appeal? Make it at least 3.

**Comment by KacperZajc** [comment]
that would defeat the whole purpose - non-constitutional issues will be heard by a small bench in any event so the preliminary hearing must be conducted by one Justice only
