### ISSUE TITLE
small changes + international law

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#365]
Lots of new changes, nothing revolutionary though :)

Rephrasing of various provisions:

§I.49. Any Person who has passed appropriate examination as prescribed by law, shall be eligible to obtain citizenship of the Free Republic of Liberland; should a Person be born to a Citizen of the Free Republic of Liberland, and not be eligible to obtain citizenship of any other state, he or she shall be automatically entitled to citizenship of the Free Republic of Liberland; dual and tripe citizenship shall be allowed; no Citizen shall be deprived of his or her citizenship unless by the Criminal Court upon conviction for a criminal offence and as a part of punishment as prescribed by law; no Person shall be rendered stateless in any event.

§I.4. The enumeration of certain rights in this Constitution shall not be construed as to deny or disparage others retained by the Citizens and other Residents of the Free Republic of Liberland; no provision of this Bill of Rights shall be construed as to provide any legal justification for any act or omission which does not stem from the inherent right of self-defence but amounts to physical or grave psychological violence towards another living being, or threat thereof, invasion of privacy, fraud or direct and grave interference with enjoyment of one’s property; nothing in such provision shall be deemed to prevent the Assembly from criminalising such conduct.

§I.6. No Person shall be excluded from the operation of, or granted any privilege under, any law passed by the Assembly; nor shall any Person be treated differently by law due to his or her origins, religious beliefs, sexual orientation, gender, cultural background and/or any other personal attribute; nothing in this provision shall prevent the Members of the Public Administration from enjoying certain immunities as described in this Constitution and no others; nor shall the Assembly be prevented from granting certain immunities to all legal Persons by virtue of possessing a separate legal personality or from establishing general rules governing liability of vicarious nature.

§I.19. No Person shall be convicted of any criminal offence which has not been expressly created by an Act of the Assembly unless it flows from this Constitution as deemed by the Courts; all criminal offences created by Acts of the Assembly shall specify the maximum penalty they carry; no law shall criminalise any act or omission which does not directly harm any other Person or cause unwarranted suffering to an animal capable of conscious behaviour; nor shall any law criminalise any act or omission which has been validly consented to by another Individual; no Individual shall be considered a victim of one’s actions or omissions; nothing in this provision shall prevent the Assembly from criminalising conduct interfering with the work of the criminal justice system, bribery, attempting or participating in committing a criminal offence.

§I.23 No Person shall be placed under arrest by any Agent of Law Enforcement for more than twenty-four hours without a Warrant; Agents of Law Enforcement executing arrests shall act openly and shall inform the detainee about the relevant rights he or she enjoys under this Constitution and any laws passed in accordance therewith; all arrests pursuant to a Warrant shall not be longer than necessary to bring the accused to trial; should the accused already be under arrest, he or she shall be able to address the Court at the hearing regarding the Warrant in question, either in person or by way of legal representation; where a Person is placed under arrest, Agents of Law Enforcement shall immediately inform his or her close ones as prescribed by law about the detention.

§I.27. No Person shall be convicted of a criminal offence later than a year after a Warrant permitting the detention of such Person was executed in connection with that offence; should said Person escape or commit any subsequent criminal offence, a new Warrant for custody may be issued.

§I.30. No Person shall be convicted of more than one criminal offence created by an Act of the Assembly for one act or omission he or she is accused of; nor shall one be put twice in jeopardy of a penalty for the same offence, whether by the Private or Public Prosecution.

§I.33. No torture or other cruel or grossly degrading treatment shall be inflicted by any Agent or Member of the Public Administration or under the supervision or knowledge thereof, whether within or outside the jurisdiction of the Free Republic of Liberland, against any Person; nor shall any experiments, medical or otherwise, be conducted against any Person without his or her express and informed consent.

§I.34. All Individuals shall have the right to control their own bodies; no Individual shall be subjected to any medical treatment without his or her express and informed consent absent exigent circumstances where an Individual is incapable of consenting; should life-saving experimental treatment become available at the time a Person is incapable of giving his or her consent, the doctors shall be allowed to apply to the Civil Court for the permission to conduct such treatment; no Minors or those who lack mental capacity shall be subjected to any form of treatment without either the express and informed consent of their Guardian or with their own consent where allowed by law unless under exigent circumstances where neither the Guardian nor the patient is capable of consenting; a Guardian's decision shall be capable of being overridden by an order of the Civil Court where it is proved to the satisfaction of the Civil Court that the decision in question is not in the best interest of the patient and the treatment is essential for his or her life or designed to prevent any serious permanent injury; nor shall Minors and those who lack mental capacity be subjected to any permanent and/or harmful treatment which is not medically necessary.

§I.37. All Persons shall have the right to fair compensation for any and all days spent incarcerated from the twenty-fifth hour of detention onwards before, during and/or after the trial, should said Person be found not guilty by the Jury or should a guilty verdict be overturned on the appeal; such compensation shall be paid by the Secretariat of the Judiciary.

§I.38. All Persons shall have the right of self-defence and/or defence of their property, and others who are under a direct and real threat, against initiators of aggression, including any Agent of the Public Administration acting unlawfully or in error; no Person shall be convicted of any criminal offence for any act or omission which took place on his or her property and which is a direct response to another Person trespassing on that property and acting in breach of the law or the Constitution resulting in such threat as described in this provision.

§I.48. No law shall interfere with the validity and/or content of any contract made exclusively between Individuals and/or legal Persons for the purposes which are not inherently unlawful; nor shall any law mandate or forbid any Individual to enter into contractual relations with any other Individual and/or legal Person, or any body of the Public Administration, nor shall it provide any financial incentive in that respect; nothing in this provision shall prevent the Courts from modifying any contract in order to, and insofar as, to give effect to the provisions of this Constitution; nor shall  the Assembly be prevented from establishing general rules governing the creation of contracts.

§I.47. No law shall abridge the right to issue and/or use any commodity or item as currency or provide any incentive in that respect unless any party to the transaction is legally prohibited from possessing such commodity or item; nor shall the Public Administration mange interest rates on any currency whatsoever; nothing in this provision shall prevent the Public Administration from issuing its own currency for the purposes limited to satisfying its financial liabilities vis a vis its Agents and Members.

§I.25. All Persons imprisoned pursuant to criminal proceedings or incarcerated following a conviction by a Court of law shall have the unconditional right to privately contact legal counsel; no Person shall be deprived of the right to communicate with relatives and such other Persons as may be prescribed by law both, either before or during the trial, in person and/or using indirect means of communication unless there be reasonable suspicion that so doing is likely to interfere with the course of justice and a Warrant preventing such communication on such grounds has been issued; 

§I.9. No branch of the Public Administration, nor any number of Citizens or Residents of the Free Republic of Liberland, shall propose and/or consent to the incorporation of the Free Republic of Liberland, or any part thereof, to any other jurisdiction; a majority of two-thirds of the overall number of Assembly Representatives may assent to the incorporation of any new territory to the Free Republic of Liberland upon the request of its people or government with any status the Assembly shall determine.

§II.1. The legislative power in the Free Republic of Liberland shall be vested in the Citizens of the Free Republic of Liberland and the Assembly of the Free Republic of Liberland which shall exercise it on behalf of the Citizens.
•	§II.1(1) The Assembly shall ordinarily be in session for one week of every month for nine months a year.
•	§II.1(2) The Assembly may extend or shorten its session with a simple majority vote of the overall number of Assembly Representatives.
•	§II.1(3) The Assembly may reconvene at any time whatsoever upon the call of the Assembly Speaker.
•	§II.1(5) The Assembly shall not be dissolved, nor shall its session be interrupted, by any other branch of the Public Administration.

§II.4. One-quarter of the overall number of Assembly Representatives shall have the right to propose a resolution dissolving the Assembly.
•	§II.4(1) The resolution shall be passed with a majority of two-thirds of the overall number of Assembly Representatives.
•	§II.4(2) Should the Assembly be dissolved, a General Election shall be held within sixty days.
•	§II.4(3) The newly elected Assembly shall always hold its first session in ten days after the General Election.

§II.11(3) Every Assembly Representative shall have the right to express his or her opinion on the proposed Bill or Resolution at least once before the vote takes place, without any time limit.

§IV.10(3) The Supreme Court shall have inherent jurisdiction to review the prima facie constitutionality of all Bills passed by the Assembly within ninety days and no Bill shall become the law of the Free Republic of Liberland unless the Supreme Court, unanimously, declares the Bill to be constitutional.

§IV.5(3) Where a Judge is placed under arrest without the Supreme Warrant, the Chief Justice of the Supreme Court shall be immediately notified about the detainment and shall have the power to order immediate release of the detained Judge; should the Chief Justice of the Supreme Court be the Judge arrested, the most senior Justice of the Supreme Court shall have the power to order the immediate release of him or her.

§IV.8(5) The Judge or Justice of the Supreme Court at the Preliminary Hearing shall have the power to issue such orders as deemed necessary and within the powers of the relevant Court; such orders shall be reviewable at a full trial.

§IV.9(1) The Supreme Court shall be presided over by the Chief Justice of the Supreme Court who shall nominate one Justice of the Supreme Court to hold a Preliminary Hearing and three Justices of the Supreme Court, or two Justices of the Supreme Court and himself or herself, to hear cases permitted to proceed and inquiries referred to the Supreme Court.

§IV.9(2) All declarations of constitutionality shall be issued by the full bench of the Supreme Court; all cases concerned with the constitutionality of the subject matter of appeal and any other case or inquiry of extraordinary importance as deemed by the Chief Justice of the Supreme Court shall also be heard by the full bench of the Supreme Court.

§IV.16. No special commissions or tribunals shall be instituted, nor any military or otherwise Courts which are not recognised by this Constitution; no Person shall threatened with, or subjected, to penalties other than those provided by the law.

International law issues:

Issues related to international law have been largely ignored so far which created a couple of loopholes I would like to close.

§I.1. The Constitution of the Free Republic of Liberland shall be the supreme law of the Free Republic of Liberland and as such shall be directly enforceable before all Courts of the Free Republic of Liberland; all Acts passed by the Assembly, all international treaties signed by the Chancellor and ratified by the Assembly and all Executive Measures issued by the Cabinet under powers delegated by Acts of the Assembly shall comply with the Constitution; all contracts between any legal and/or natural Persons, including all branches of the Public Administration, made under the jurisdiction of the Free Republic of Liberland, shall comply with the Constitution.

§II.18. A Treaty Bill shall propose ratification of an international treaty signed by the Cabinet.
•	§II.18(1) All Treaty Bills shall be passed with a majority of three-quarters of the overall number of Assembly Representatives.
•	§II.18(2) All Treaty Bills shall be subject to the power of general veto by the Citizens as provided in §II.21.
•	§II.18(3) All international treaties shall be signed by the Chancellor on behalf of the Cabinet and ratified by the Assembly in order to create obligations on the part of the Free Republic of Liberland vis a vis other subjects of international law.
•	II.18(4) Should any international treaty be capable by virtue of its contents of bestowing rights on, or creating obligations for, Persons, such rights and obligation shall be enforceable before the Courts of the Free Republic of Liberland.
•	II.18(5) Should any international treaty ratified by the Assembly render the Free Republic of Liberland a member of any international organisation and such organisation issue any form of legal document that is supposed to bestow rights on, or create obligation for, Persons, enforceable in the domestic Courts, such legal document shall be of no effect unless it is separately ratified by the Assembly in a form of a Treaty Bill.
•	II.18(6) Should any Treaty Bill be rejected by the Assembly, an international treaty it proposes shall be deemed not to bind the Free Republic of Liberland in any manner.

§II.7(9) to ratify international treaties signed by the Chancellor as provided in a Treaty Bill;
§III.7(4) to sign international treaties and request the Assembly ratifies them;

new:

§III.X. The Chancellor and the Cabinet shall comply, in performing their obligations and exercising their powers, with ius cogens and erga omnes rules and other aspects of customary international law insofar as it does not contravene the Constitution or any law passed by the Assembly in accordance therewith, as advised by the Chief Attorney of the Republic.

§IV.X. Should any proceeding before any Court of the Free Republic of Liberland be concerned with interpretation of any international treaty as ratified by the Assembly in a Treaty Act, the Court shall apply standard rules on interpretation and shall not treat any statements made by any other branch of the Public Administration in this regard as conclusive.

Renumbering...

Remove: §IV.10(6) 

Assembly's areas of competence:

We need to divide the powers of the Assembly into two categories - powers which are carried into effect by Acts (subject to the right of general veto) and those which are carried into effect by Resolutions (not subject to the right of general veto). This was implicit so far but it needs to be clarified I think.

§II.7. The Assembly shall have the power to pass Bills for the following purposes only:
•	§II.7(1) to establish rules regarding peaceful coexistence of Persons and security of their Property and Rights and their enforcement as provided for in ordinary Bills;
•	§II.7(2) to conduct the financial affairs of the Public Administration as provided in Financial Bills;
•	§II.7(3) to impose the Fee on land as provided for in Land Bills;
•	§II.7(4) to ratify international treaties signed by the Cabinet as provided in Treaty Bills.

§II.8. The Assembly shall have the power to pass Resolutions for the following purposes only:
•	§II.7(1) to assent to the incorporation of any new territories to the Free Republic of Liberland;
•	§II.7(2) to establish the Assembly Committee;
•	§II.7(3) to assent to the classification of information as a state secret for the purposes of national security as proposed by a Secretary of State;
•	§II.7(4) to appoint and impeach the Chancellor;
•	§II.7(5) to consent to the use of the Territorial Defence force within the ten kilometre radius from the borders of the Free Republic of Liberland;
•	§II.7(6) to request the Supreme Court to review the validity of any election or referendum held within the Free Republic of Liberland;
•	§II.7(7) to appoint the Assembly Speaker;
•	§II.7(8) to regulate its sessions and potential dissolution;
•	§II.7(9) to accept or reject the reminder of a Bill that has been declared partially unconstitutional to proceed to the stage of potential veto by the Citizens.

§II.9. The Assembly Representatives shall have the power to debate on matters important to the well-being of the Republic and inquire into any aspect of work of the Chancellor or any Member of the Cabinet who shall be under obligation to provide accurate and truthfully information.
•	§II.9(1) One-quarter of the overall number of Assembly Representatives shall have the power to oblige the Cabinet to consider a draft of a Bill prepared by them which may be rejected or accepted by the Cabinet as a future Bill.
•	§II.9(2) Should the Draft be rejected, the Cabinet shall publicly give detailed reasons behind its decision.

Remove: II.13.

Renumbering...

Finally, new provisions:

I.65 No branch of the Public Administration shall give any form of foreign aid to any state whether directly or via any international institution be it a non-repayable grant, loan or any other financial support; nothing in this provision shall prevent the Public Administration from meeting its financial liabilities flowing from the membership in any intergovernmental organisation.

I.66 All Members and Agents of the Public Administration shall take the Oath of Office before they are allowed to perform their duties; the Oath of Office shall include the pledge of allegiance to the state of the Free Republic of Liberland, obligation to uphold and abide by the Constitution of the Free Republic of Liberland, and to perform one’s duties in a manner consistent with liberty of others as far as possible.

Remove: §II.3(3) 

§IV.12(7) The access to the Court shall not be impeded by any excessive formal or otherwise requirements.

Feel free to comment :)

**Comment by terrorist96** [comment]
> §I.49. Any Person who has passed appropriate examination**, as prescribed by law,** shall be eligible to obtain citizenship of the Free Republic of Liberland; should a Person be born to a Citizen of the Free Republic of Liberland, ~~and not be eligible to obtain citizenship of any other state,~~ he or she shall ~~be~~ automatically **be** entitled to citizenship of the Free Republic of Liberland; ~~dual and tripe~~ **multiple** citizenship shall be allowed; no Citizen shall be deprived of his or her citizenship unless by the Criminal Court upon conviction for a criminal offence and as a part of punishment as prescribed by law; no Person shall be rendered stateless in any event.

Added comma, removed unnecessary qualifier (because anyone is eligible to obtain citizenship in any of the other 200 or so countries out there), and changed dual/triple to multiple.

> I.4.

Changing 'or' to 'but' makes no sense.

> I.6.

'Vicarious nature'? Sounds awkward and vague. What are you trying to accomplish with that phrase?

> I.19.

The issue I have with creating crimes within the constitution is that there's no sentencing guidelines and judges will have to mete justice according to their own conscience instead of guidelines established by the Assembly.

> I.37. from the twenty-fifth hour of detention onwards

Good idea. The police should be able to detain someone for 24 hours without worrying about paying compensation if found not guilty. But when does the 24 hour clock start ticking? Upon arrest? Upon incarceration? From the text, it seems like it begins once you are inside the jail and the bars are closed. So what if a cop arrests you, but doesn't take you directly to jail and instead holds you longer than necessary prior to jailing you? From my interpretation, that time spent in the officer's custody doesn't count towards the 24 hours.

> I.38. removal of 'or rights'

The reason I want rights mentioned here is because you should have the right to defend your property **and** your rights. If someone wants to illegally deprive you of any of your rights, you should have the right to resist that encroachment.

> I.48. No law shall interfere with the validity and/or content of any contract made exclusively between Individuals and/or legal Persons for the purposes which are not inherently unlawful

This is basically saying "no law can interfere with the validity of a contract, unless that contract is against the law." Makes no sense.

> I.48. nothing in this provision shall prevent the Courts from modifying any contract in order to, and insofar as **to**, ~~to~~ give effect to the provisions of this Constitution;

> I.25.

Should be a period at the end, not semicolon.

> I.9. a majority of two-thirds of the overall number of Assembly Representatives may assent to the incorporation of any new territory to the Free Republic of Liberland upon the request of its people or government with any status the Assembly shall determine.

This should be added to II.7, as it's already covered there. Also, I think `may determine` is more apt in this context.

> • §II.1(~~5~~ **4**) The Assembly shall not be dissolved, nor shall its session be interrupted, by any other branch of the Public Administration.

> • §II.4(3) The newly elected Assembly shall ~~always~~ hold its first session **with**in ten days after the General Election.

Also, what if the results of the election are being contested? Shouldn't they hold their first session within 10 days after the General Election's results are certified?

> §IV.10(3) The Supreme Court shall have inherent jurisdiction to review the prima facie constitutionality of all Bills passed by the Assembly **within ninety days** and no Bill shall become the law of the Free Republic of Liberland unless the Supreme Court, unanimously, declares the Bill to be constitutional.

What if they miss that deadline? Will they not be allowed to review it after the 90 days have elapsed?

> §IV.8(5) **At the Preliminary Hearing,** ~~The~~ **the** Judge or Justice of the Supreme Court ~~at the Preliminary Hearing~~ shall have the power to issue such orders as deemed necessary and within the powers of the relevant Court; such orders shall be reviewable at a full trial.

This makes it more clear that the preliminary hearing qualifier applies to both judges and justices.

> §IV.9(1) The Supreme Court shall be presided over by the Chief Justice of the Supreme Court who shall nominate one Justice of the Supreme Court to hold a Preliminary Hearing and three Justices of the Supreme Court~~, or two Justices of the Supreme Court and himself or herself,~~ to hear cases permitted to proceed and inquiries referred to the Supreme Court.

I think it's safe to omit this part because the Chief Justice is considered a Justice of the SC, so there's nothing stopping him from nominating himself.

> §IV.9(2) all cases concerned with the constitutionality of the subject matter of appeal

What if it's not an appeal, but a case that originates at the SC, like validity of elections, for example?

> §IV.16. No special commissions or tribunals shall be instituted, nor any military **Courts** or otherwise ~~Courts~~ which are not recognised by this Constitution; no Person shall **be** threatened with, or subjected **to**, ~~to~~ penalties other than those provided by the law.

Here lies the issue again: what about penalties issued by judges for constitutional violations (or for contempt of court)?

> • II.18(4) Should any international treaty be capable by virtue of its contents of bestowing rights ~~on~~ **upon**, or creating obligations for, Persons, such rights and obligation shall be enforceable before the Courts of the Free Republic of Liberland.
• II.18(5) Should any international treaty ratified by the Assembly render the Free Republic of Liberland a member of any international organisation and such organisation issue any form of legal document that ~~is supposed~~ **purports** to bestow rights ~~on~~ **upon**, or create obligation for, Persons, enforceable in the domestic Courts, such legal document shall be of no effect unless it is separately ratified by the Assembly in ~~a~~ **the** form of a Treaty Bill.
• II.18(6) Should any Treaty Bill be rejected by the Assembly, an international treaty it proposes shall be deemed not to bind the Free Republic of Liberland in any manner.

II.18(6) is incomprehensible. What do you mean to say? Who is 'it' in this circumstance?

> §III.7(4) to sign international treaties and request the Assembly ratifies them;

So will the Supreme Court not declare the constitutionality of a treaty prior to it taking effect?

> §III.X. The Chancellor and the Cabinet shall comply, in performing their obligations and exercising their powers, with ~~ius~~ **jus** cogens and erga omnes rules and other aspects of customary international law insofar as it does not contravene the Constitution or any law passed by the Assembly in accordance therewith, as advised by the Chief Attorney of the Republic.

Jus Cogens seems to be the more common spelling.

> §IV.X. Should any proceeding before any Court of the Free Republic of Liberland be concerned with **the** interpretation of any international treaty as ratified by the Assembly in a Treaty Act, the Court shall apply standard rules on interpretation and shall not treat any statements made by any other branch of the Public Administration in this regard as conclusive.

Should also change it to say Supreme Court (not any Court) because only the SC should have exclusive jurisdiction. And it should also say Treaty Bill, because it shouldn't become an Act until its constitutionality has been verified, IMO.

> Remove: §IV.10(6)

Noooooooooooooooooooooo!

> II.7/8

What about the power to make laws regarding stuff mentioned throughout the constitution?

> §II.8.

All subsections need to say II.8, not II.7.

> • §II.~~7~~**8**(9) to accept or reject the ~~reminder~~ **remainder** of a Bill that has been declared partially unconstitutional to proceed to the stage of potential veto by the Citizens.

The second half is awkward. Are you trying to say that if a law if found partially unconstitutional, the assembly can vote to keep the remainder of the law, and if they do keep it, that it still has to not be vetoed by the citizens?
I think this is unnecessary. If a law if found partially unconstitutional, by default, the remainder is still in effect. There's no need to vote to keep the remainder (because it's already been voted on when they passed the whole law to begin with), and the citizens will potentially vote on vetoing the remainder, or they already have if the law was found unconstitutional upon secondary review at the SC, not the initial review.

> §II.9. The Assembly Representatives shall have the power to debate on matters important to the well-being of the Republic and inquire into any aspect of work of the Chancellor or any Member of the Cabinet**,** who shall be under obligation to provide accurate and ~~truthfully~~ **truthful** information.

Added comma after Cabinet too.

> • §II.9(1) One-quarter of the overall number of Assembly Representatives shall have the power to oblige the Cabinet to consider a draft of a Bill prepared by them**,** which may be rejected or accepted by the Cabinet as a future Bill.

Added comma after 'them'. Also, what if a Bill wasn't prepared by the Representatives? What if a citizen or organization lobbied the bill? IMO, we should remove "prepared by them".
In addition, you're leaving out `§II.13(2) All drafts of Bills proposed to the Cabinet shall be made public before the Cabinet’s acceptance or rejection.` for this new II.9 section.

> I.65 No branch of the Public Administration shall give any form of foreign aid to any state **or group** whether directly or via any international institution**,** be it a non-repayable grant, loan or any other financial support; nothing in this provision shall prevent the Public Administration from meeting its financial liabilities flowing from the membership in any intergovernmental organisation.

Added comma after 'institution'.

> I.66 All Members and Agents of the Public Administration shall take the Oath of Office ~~before they are allowed to perform their duties~~ **prior to holding office**; the Oath of Office shall include the pledge of allegiance to the state of the Free Republic of Liberland, obligation to uphold and abide by the Constitution of the Free Republic of Liberland, and to perform one’s duties in a manner consistent with **the** liberty of others as far as possible.

> §IV.12(7) ~~The access~~ **Access** to the Court shall not be impeded by any excessive formal **requirements** or otherwise ~~requirements~~.

What about access to the Criminal and Supreme Court? This only applies to the Civil Court?

**Comment by KacperZajc** [comment]
I.49 On what grounds would any Person be entitled to any other citizenship on birth if his or her parents are not citizens of other state than Liberland (because this is the whole point of this part of the provision)?

I.4 'or' doesnt make any sense:
'...no provision of this Bill of Rights shall be construed as to provide any legal justification for any act or omission which does not stem from the inherent right of self-defence but amounts to physical or grave psychological violence towards another living being...' - no person is entitled to use physical or psychological violence unless it is in self-defence.

I.6 e.g. employer's (vicarious) liability for acts of his or her employee; parent's (vicarious) liability for acts of his or her small child etc

I.19 there is a provision preventing the Courts from sentencing any defendant to 'prolonging' incarceration where no person was harmed - it should be enough, the Supreme Court will come up with some more detailed guidance over time

I.37 it is such a small matter it can be left for the courts to decide via interpretation of this provision

I.38 What Rights do you have in mind here? give some examples 

I.48 Yeah Ive been struggling with this provision, but how do you prevent people from entering into contracts for assassination etc? if you dont deal with it, such contracts would have to be enforced by the Courts later...

§II.4(3) It is 10 days precisely because there is 7 to challenge the outcome of the elections so the SC can determine it within 3 days.

§IV.10(3) if the SC misses the deadline the law does not enter into force (as per requirements of Article II) and the SC is in breach of its duty

II.18(6) Should any Treaty Bill be rejected by the Assembly, an international treaty such a Bill proposes shall be deemed not to bind the Free Republic of Liberland in any manner.

§III.7(4)& IV.10(6) all treaties must be ratified in a Treaty Bill which means that before it enters into force it must be approved as constitutional as any other Bill. If not constitutional it will be of no effect.

§IV.X. Nooo - any Court can interpret treaties if they are relevant to the case brought before them 

II.7/8 What stuff has not been expressly mentioned by me here?

§II.78 Maybe the Assembly does not like the reminder to enter into force? Maybe what is left is not needed on its own.

§II.9(1) I want to restrict the flow of legislation as much as possible. Citizens can lobby Representatives to submit a proposal to the Cabinet, they dont have to do it themselves.
Publication is covered by general rules on transparency.

The rest of your suggestions adopted.

**Comment by terrorist96** [comment]
> I.49 On what grounds would any Person be entitled to any other citizenship on birth if his or her parents are not citizens of other state than Liberland (because this is the whole point of this part of the provision)?
Current text:
"should a Person be born to a Citizen of the Free Republic of Liberland, and not be eligible to obtain citizenship of any other state, he or she shall be automatically be entitled to citizenship of the Free Republic of Liberland"

What if a person is born to a Liberland citizen, but is born on USA soil, and thus obtains USA citizenship? Would that baby not be entitled to dual citizenship of USA and Liberland? 

> I.4

I thought the intention was to ban any action that isn't in self defence, any psychological violence, or any other physical force. What you're saying is that self defense is allowed only in these two manners. I don't really have a problem with either. 

> I.38 What Rights do you have in mind here? give some examples

Your right to life, liberty, travel, privacy, etc. Property is a type of right too. If we said just rights, it would encompass property rights, in addition to all your other rights. 

> I.48 Yeah Ive been struggling with this provision, but how do you prevent people from entering into contracts for assassination etc? if you dont deal with it, such contracts would have to be enforced by the Courts later...

You can change it to unconstitutional instead of unlawful. Murder is unconstitutional - see I.4; that's why the Assembly is allowed to outlaw it. Just because the murder is framed within a contract doesn't detract from the Assembly's capability to outlaw murder. 

> §II.4(3) It is 10 days precisely because there is 7 to challenge the outcome of the elections so the SC can determine it within 3 days.

3 days seems like a time crunch. I think there should be more time to conduct a quality investigation into the results of the election/referendum. 

> §IV.10(3) and the SC is in breach of its duty

We shouldn't make it so easy for the SC to violate the Constitution 

> II.18(6) Should any Treaty Bill be rejected by the Assembly, an international treaty such a Bill proposes shall be deemed not to bind the Free Republic of Liberland in any manner.

So this is basically saying that a treaty bill that isn't passed is of no effect? Isn't that already implied, since it didn't pass? 

> II.7/8 What stuff has not been expressly mentioned by me here?

The power to pass legislation regarding the parts of the Constitution that specifies something will be prescribed by law.

**Comment by terrorist96** [comment]
> Publication is covered by general rules on transparency.

I.13 doesn't cover drafts of bills.

**Comment by terrorist96** [comment]
What about:

> II.7/8 What stuff has not been expressly mentioned by me here?

The power to pass legislation regarding the parts of the Constitution that specifies something will be prescribed by law.

**Comment by terrorist96** [comment]
@KacperZajc

**Comment by KacperZajc** [comment]
my intention was to include it under:

**Comment by KacperZajc** [comment]
isnt it included in this provision? it is expressed in general terms:

§II.7(1) to establish rules regarding peaceful coexistence of Persons and security of their Property and Rights and their enforcement as provided for in ordinary Bills;

**Comment by terrorist96** [comment]
I guess that could be construed to include it, but it's not very specific. I could see the Assembly arguing in the future that if prescribing the specific amount of money concerning small claims court could as regulating the peaceful coexistence of people, any random act could count as such. I think we should make it specific.
