### ISSUE TITLE
Frivolous lawsuits

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#366]
Thoughts on adding a provision that says "if a party's lawsuit is dismissed for frivolity, then they have to pay the costs of both sides"? It disincentivizes blatantly frivolous suits and protects victims of persecution.

**Comment by KacperZajc** [comment]
I think it is a good idea however I would like to give a judge some discretion as not everything is black and white: 

§IV.8(6) Should a claim or prosecution be dismissed at a Preliminary Hearing, the plaintiff or prosecutor shall ordinarily be ordered to cover all reasonable expenses of the defendant as well as all court fees unless the Judge, in his discretion, recognises that there has been an honest intention on the part of the plaintiff or prosecutor.

**Comment by terrorist96** [comment]
That's why I included the word frivolous. A case can be dismissed for many reasons. If it's dismissed because it's been determined that it's a frivolous case, then the cost should always be covered by the suing party.

**Comment by KacperZajc** [comment]
so is my wording ok with you?

**Comment by terrorist96** [comment]
> §IV.8(6) Should a claim or prosecution be dismissed **for frivolity** ~~at a Preliminary Hearing~~, the plaintiff or prosecutor shall ~~ordinarily~~ be ordered to cover all reasonable expenses of the defendant connected to his or her legal defence as well as all court fees ~~unless the Judge, in his discretion, recognises that there has been an honest intention on the part of the plaintiff or prosecutor~~.

Shouldn't be limited to just the preliminary hearing. Adding the word frivolity renders the last part superfluous. If there is an honest intention, then the case wouldn't be dismissed for frivolity, but dismissed for another reason.

**Comment by KacperZajc** [comment]
I think it should be limited to Preliminary Hearing - this is exactly why we have it in the first place - to get rid of troublemakers

**Comment by terrorist96** [comment]
Okay that's fine.
