### ISSUE TITLE
Assembly term

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#367]
I think we should extend the term of the Assembly from 4 years to 6 years.
Should we also consider shortening the time of its sessions?

**Comment by terrorist96** [comment]
> 4 years to 6 years

Not opposed, but I'm not okay with anything more than 6 years/12 years if reelected.

> shortening session time

Isn't it right now only one week of every month for nine months a year? That's a total of 9 weeks per year. I think it's already pretty short.

**Comment by KacperZajc** [comment]
I think the sessions are in fact short however it has been brought to my attention that the financial burden of maintaining such Assembly would be high:

"As long as Liberland has a population of less than 700'000 citizens the "financial burden" per capita will be higher than that of Switzerland. If I take a relatively moderate "cost per day per Assembly member" of 500$ you will have a total wage cost of 450'000 USD p.a. just to cover the wages (excluding expenses). When Liberland expands and has some sort of income from Real Estate the figure might seem extremely low, however in the beginning this is a substantial cost you need to calculate with. I should also add that the constitution sees an unlimited financial liability (also criminal liability) of the Assembly members it is questionable if someone would be willing to enter this unlimited liability for 22'500 USD p.a.. I think my assumptions are very conservative and are likely to be substantially higher. The total cost of operating the state (not only the assembly) as currently proposed in the constitution will quickly be several million dollars p.a. that is currently not feasible."

What do you think?

**Comment by terrorist96** [comment]
We allow for unlimited speaking time for every assembly member, so making the sessions even shorter will allow for even less to get done. I think $500 a day is pretty high. Assembly Reps should have their own jobs to sustain a salary and not be dependent on their job as a Representative. New Hampshire, for example, pays their reps $200 a year. See:
https://ballotpedia.org/Comparison_of_state_legislative_salaries

**Comment by KacperZajc** [comment]
OK let's go with 6 years then and we'll thing about sessions on another occasion :)
