### ISSUE TITLE
Jurors

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#369]
§IV.15(9) The Jurors shall enjoy immunity against any legal action brought for anything they might have done in connection with their service. 

???

**Comment by Auahi** [comment]
Are you asking about what it means or if it should be kept?

**Comment by terrorist96** [comment]
He's asking if it should be added to the constitution and if the wording is good.

I think this is unnecessary because it's more or less covered by §IV.15(3)

**Comment by KacperZajc** [comment]
Yeah you're right
