### ISSUE TITLE
grave psychological violence

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#371]
I think we should ensure there will be no stupid emotional distress claims in Liberland:

add to I.4:

the term 'grave psychological violence' shall signify a recognised severe and prolonging mental illness and no Person shall be ever prosecuted for, or have a civil claim brought against on the basis of, any other form of non-physical injury.

???

**Comment by terrorist96** [comment]
Meh, I think judges should be able to interpret it themselves. Including 'grave' prior to 'psychological violence' is enough to say, hey, this doesn't encompass someone having their feelings hurt.

**Comment by KacperZajc** [comment]
yes but originally it covers only criminal offences, I want to extend it to civil wrongs as well, Id hate to see emotional distress claims flooding the courts

**Comment by terrorist96** [comment]
Not opposed.
