### ISSUE TITLE
Compensation for indictment

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#372]
A section that says if you're under indictment for X number of years, and if the case is dropped for whatever reason, then you are entitled to compensation. Similar to being falsely imprisoned, having your assets frozen etc while under indictment should be compensated for. I.37 should also be modified to include dismissals, not just 'not guilty' verdicts.

**Comment by KacperZajc** [comment]
this provision is not enough:

§I.27. No Person shall be convicted of a criminal offence later than a year after a Warrant permitting the detention of such Person was executed in connection with that offence; should said Person escape or commit any subsequent criminal offence, a new Warrant for custody may be issued.

???

**Comment by terrorist96** [comment]
Yeah I guess that provision precludes it from happening. The last sentence still needs to be addressed though regarding I.37
