### ISSUE TITLE
reminder instead of remainder (typo)

### ISSUE THREAD

**Issue by qm3ster** [liberland/constitution#374]
§IV.10(4) Should a Bill be declared unconstitutional by reason only of parts of the Bill which may reasonably be excised from the whole, the Supreme Court shall send the reminder of such Bill to the Assembly which may pass a resolution authorising the reminder of the Bill to enter into force, subject to the power of general veto of Citizens as provided in Article II.

**Comment by KacperZajc** [comment]
if that is to correct a grammatical or typo mistake, please submit a Pull Request not an Issue

**Comment by terrorist96** [comment]
Remainder is the correct word, not reminder.

**Comment by qm3ster** [comment]
@terrorist96 it says reminder right now on the site. That is what I am here because of.
@KacperZajc I was not sure how I should rephrase it for best clarity, but I think remainder might be the best way. I will go make a request now.

**Comment by terrorist96** [comment]
Already covered it.

**Comment by qm3ster** [comment]
nvm, https://github.com/liberland/constitution/pull/376 covers it.
@terrorist96 next time please include "closes #376" in commit message :)

**Comment by terrorist96** [comment]
My bad. :stuck_out_tongue:
