### ISSUE TITLE
Fairness of prescribed arbitration proceedings in a contract.

### ISSUE THREAD

**Issue by qm3ster** [liberland/constitution#375]
The Court is normally responsible for evaluating the compliance to a certain set of rules, for example evaluating a person's action with regard to current laws, or evaluating a proposed law with regard to the constitution, or evaluating a public servant's performance with regard to their obligations of duty.
Therefore, the following statement concerns me:

>§IV.12(1) The jurisdiction of the Civil Court shall not be ousted by any contract unless fair arbitration proceedings are envisaged in case of dispute; **the fairness of arbitration proceedings may be subject to a challenge in this Court.**

1. Is there any formal ruleset for determining the 'fairness' of proceedings described?
2. Even if there is, should the court really have the power to overrule contracts, or parts thereof, at will, during the execution of the arbitration clause?

I believe that there should be laws against intentionally obfuscating contracts with intent to commit fraud, and definitely consequences for trying to falsify contracts. However, fairness is something that is subjective, and once all parties of the contract have come to an agreement and signed it, it should not be interfered with by public authority. This would only weaken the trust in contracts and increase transaction costs.

**Comment by KacperZajc** [comment]
if that is to correct a grammatical or typo mistake, please submit a Pull Request not an Issue

**Comment by qm3ster** [comment]
@KacperZajc I accidentally hit **Enter** in the title field before I finished describing the problem, that is why there was no description.

**Comment by KacperZajc** [comment]
please see the changes made that partially accommodate your concerns :)

**Comment by qm3ster** [comment]
God damn it, I just typed a full reply and then lost it.
10/10 job, me.
Well, not typing all of that up again, I guess.

Basically, other than in case of contract requiring anyone to perform illegal activity, no court should have the authority to overrule clauses of an authentic contract entered not under coercion, with "unfairness" of contract not being sufficient evidence for reasonable suspicion of coercion.

If you agree with this basic statement, I will provide a detailed, bulletproof version as PR.
Not typing all that up yet in case you are going to argue the core principle, and we will come to a different resolution.
