### ISSUE TITLE
Sequestration?

### ISSUE THREAD

**Issue by qm3ster** [liberland/constitution#377]
> §IV.15(1) The Jury shall be composed of twelve impartial Citizens drawn randomly from the Electoral Register.
> ...
> §IV.15(7) The Jury shall render the verdict free from any form of coercion; **the Judge may order sequestration of the Jurors should it be required for the independence of the Jury.**

Sequestration of randomly drawn Citizens in and of itself is an act of coercion.
Performing as Jury should be voluntary (while still offered at random through the Registry), and rewarded financially, funds drawing from the losing party. If a case is likely to lead to sequestration, this information (including the maximum estimated period which can be less or equal to the constitutional maximum) has to be disclosed to the prospective Jury before they can enter this contract or pass it up. Those who entered the position of Jury without receiving this warning can never be sequestered.

Finally, the constitution should include the maximum period for sequestration I mentioned above.

**Comment by KacperZajc** [comment]
Inasmuch as sequestration seems to be incompatible with libertarian ideas, I believe it is necessary in some rare situations. 
The requirement of informing a jury about potential sequestration seems pointless to me because this is rarely know at the beginning of a trial. 
Even if we assume that the Court should be required to issue such a warning, it is not something we should put in the Constitution. 
Finally, jury service is voluntary because is linked to the electoral register - no one is mandated to appear on the register.
Jury service and occasional sequestration are necessary for the justice system to function properly.

**Comment by qm3ster** [comment]
IMHO, the constitution must guard it's own 'holes'. If it introduces the legality of some coercion, it must limit it as much as possible. For instance, the Law Enforcement Agents trespassing, invading privacy and kidnapping are all limited by Warrants. Those wrongfully releasing these Warrants can be impeached. All the parts of the control are within the constitution, forever. ( I do believe that the production of Warrants should be further limited, but at least there's something.)
This sequestration is introduced in one small line, as an afterthought, and not limited in any way.
The electoral register is not a suitable check, especially considering it creates the perverse incentive for people to not appear on the register. I believe the register should come with as few obligations as physically possible, to ensure representative voting.
The remuneration, on the other hand, does not need to be regulated by law. There just needs to be the ability to pay jurors for attending from the budget. The actual amount will be dictated by the market.
Perhaps I am thinking too much in terms of free market lawmaking and arbitration, and this does all need to be specified, in this system of government, I am not sure.
What I do know is that this line does need more attention, and should not be left as it is right now.

**Comment by michalptacnik** [comment]
Closing due to long term inactivity. 

We have a new draft of the constitution here: https://docs.google.com/document/d/1J2o5N9JDOzBXRkefe9Azm6P6vAwqCxw7B2jcKoHSjhg/edit
