### ISSUE TITLE
invitation of foreign armed forces

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#379]
> nor shall any branch of the Public Administration invite any armed forces of any other state or organisation into the jurisdiction of the Free Republic of Liberland

What if the president of another country is visiting, and he has security accompanying him for protection? What if his 'security' is technically part of the armed forces of his country?

**Comment by KacperZajc** [comment]
This is good question.
Id say this is implied that the security of the head of state is not considered armed forces for the purposes of this provision.

But we may add:
... except where the members of the armed forces are accompanying a diplomatic visit to the Free Republic of Liberland as a security in a number which does not exceed recognised international standards.

I wouldnt like to see any oversize security considering how small Liberland is, even a small number of well-trained soldiers might be able to overtake it...

**Comment by terrorist96** [comment]
Is there an international standard on the number of security personnel? :D

**Comment by KacperZajc** [comment]
feel free to substitute any other restriction for this part xD

**Comment by terrorist96** [comment]
Let's just say with the exception of a reasonable number of security personnel accompanying a foreign diplomat.

**Comment by KacperZajc** [comment]
sounds good
