### ISSUE TITLE
Expiration of laws.

### ISSUE THREAD

**Issue by FellowTraveler** [liberland/constitution#382]
I want to revisit the **expiration of laws.**

First, because those who are dead have no right to bind those not yet born, and so legislation naturally expires anyway. If the Constitution fails to recognize this fact, then it acts by force, not by right.

Concerning this, Thomas Jefferson wrote: _The question Whether one generation of men has a right to bind another, seems never to have been started either on this or our side of the water. Yet it is a question of such consequences as not only to merit decision, but place also, among the fundamental principles of every government...I set out on this ground, which I suppose to be self evident,_ **"that the earth belongs...to the living":** _that the dead have neither powers nor rights over it...On similar ground it may be proved that_ **no society can make a perpetual constitution, or even a perpetual law.** _The earth belongs always to the living generation. They may manage it then, and what proceeds from it, as they please..._ **Every constitution then, and every law, naturally expires at the end of 19 years.** _If it be enforced longer, it is an act of force, and not of right._

---

Second, laws should expire because **history shows us that the body of law in a nation tends to grow indefinitely over time,** and that old and antiquated laws stay on the books long past their relevance, until the people are saddled with thousands of pages of laws they could never hope to fully learn, much less obey.

Criminal liability hangs over them, even for those who do no wrong. In America, as a result of this, it is said that [everyone commits three felonies per day](http://www.threefeloniesaday.com/Youtoo/tabid/86/Default.aspx).

---

Regarding the United States Code:

_The US Code (i.e., the codified general statutes) with West's annotations is contained in 356 volumes and takes up 55 feet of shelf space, retailing for around $6,500._

_The Code itself, from the USGPO, is in 35 volumes of around 1,200 to 1,400 pages each, including 6,850 pages of index in 6 volumes and one volume that is nothing but a 1,400-page LIST of the other public laws that have not been codified (e.g, the budget, etc)._

---

The authorities will lay this heavy burden upon the people saying that **"IGNORANCE OF THE LAW IS NO EXCUSE."**

Spooner says: _As if it were in the nature of things possible that there could be an excuse more absolute and complete. What else than ignorance of the law is it that excuses persons under the years of discretion, and men of imbecile minds? What else than ignorance of the law is it that excuses judges themselves for all their erroneous decisions? Nothing. They are every day committing errors, which would be crimes, but for their ignorance of the law._

Spooner continues: _This preposterous doctrine, that "ignorance of the law excuses no one," is asserted by courts because it is an indispensable one to the maintenance of absolute power in the government. It is indispensable for this purpose, because, if it be once admitted that the people have any rights and liberties which the government cannot lawfully take from them, then the question arises in regard to every statute of the government, whether it be law, or not; that is, whether it infringe, or not, the rights and liberties of the people. Of this question every man must of course judge according to the light in his own mind. And no man can be convicted unless the jury find, not only that the statute is law, - that it does not infringe the rights and liberties of the people, - but also that it was so clearly law, so clearly consistent with the rights and liberties of the people, as that the individual himself, who transgressed it, knew it to be so, and therefore had no moral excuse for transgressing it._

_A jury, then, in judging whether an accused person knew his act to be illegal, were bound first to use their own judgments, as to whether the act were intrinsically criminal. If their own judgments told them the act was intrinsically and clearly criminal, they would naturally and reasonably infer that the accused also understood that it was intrinsically criminal..._

_But there is still another doctrine that extensively, and perhaps most generally, prevails in practice, although judges are not agreed in regard to its soundness. It is this: that it is not even necessary that the jury should see or know,_ **for themselves,** _what the law is that is charged to have been violated; nor to see or know,_ **for themselves,** _that the act charged was in violation of any law whatever; - but that it is sufficient that they be simply_ **told by the judge** _that any act whatever, charged in an indictment, is in violation of law, and that they are then bound blindly to receive the declaration as true, and convict a man accordingly, if they find that he has done the act charged._

_...the jury are the peers (equals) of the accused, and are therefore supposed to know the law as well as he does, and as well as it is known by the people at large. If they (the jury) are not presumed to know the law, neither the accused nor the people at large can be presumed to know it. Hence, it follows that one principle of the true trial by jury is, that no accused person shall be held responsible for any other or greater knowledge of the law than is common to his political equals, who will generally be men of nearly similar condition in life._

**Comment by qm3ster** [comment]
+1

**Comment by KacperZajc** [comment]
honestly, the more I think about this idea, the more inclined I am to incorporate it
It is definitely on the table now :)

**Comment by rotilho** [comment]
I can't see it working without a grade system. Cons:

* Waste of time: why do we need to review stable laws?
* Dangerous: the overwork review laws will increase the number of mistakes.
* Lose interest: more laws to review more dispersed will be the debate

Let imagine two laws:
2000 - *No minors should be allowed to sell their organs* (16 years, stable)
2016 - *All citizens of the Free Republic of Liberland shall be vaccinated against ebola* (created to address the ebola epidemic)

After 6 years the minor's law still make sense but not the ebola. Should we review both laws with the same priority and frequency?

Grade systems:

C grade - *shall be reviewed after 6 years* (after first renewal becomes B)
B grade - *shall be reviewed every 12 years* (after second renewals becomes A)
A grade - *shall be reviewed every 24 years*

**Higher the grade higher the priority.**

The only downside that I can see is it complexity.

**Comment by saintego** [comment]
Why not to use reward system I suggested in Issue #388? https://github.com/liberland/constitution/issues/388
If there had been ebola law that make no sense any more and you'd be able to count economical loses of that law, you'd be able to suggest cancelling that law to ask(or sue) government for reward of 10% of saved money.
If there had been minor selling organ law that still make sense and there is no cheaper way how to do it, even you'd sue government for reward, you'd probably lost case and that law would not be cancelled.
Assembly would be motivated to cancel outdated laws before it'd be worthy to sue them for that, so they would not look useless before election.

**Comment by qm3ster** [comment]
I believe the expiration date should be baked right into the text of the law, and the level of consensus required to enstate the law should be directly affected by this value. There should also be maximum limits of course, even at 100% consensus.
In other words:
*`[type of law]-(affects)->[maximum time until void/reviewed]-(affects)->[level of consensus required]`*
Also, a barely passing consensus can further shorten the time left until expiration.

Finally, and this is very important, laws that are not renewed/updated until their expiration date, for example due to lack of consensus on what the current version should be, automatically become void. Honoring Tacitus (and Coolidge :tongue:) we must maintain the number and complexity of laws to a minimum, which makes it doubly obvious that any law we can't agree on is much better absent than rushed and flawed.

@rotilho can we please try to base our examples on actual potential laws consistent with liberland ideology, not totalitarian dictates against non-violent behavior?
