### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by kreibich** [liberland/constitution#384]
Hi,
 I suggest to translate the constitution draft to other languages, at least to Czech, Serbian and Croatian and keep it up to date with the latest English version. Liberland translation group on Facebook: https://www.facebook.com/groups/liberlandtranslations/

Thank you.

**Comment by qm3ster** [comment]
Wouldn't it be better to only translate release versions, with strong review?
Languages don't map 1:1 all that easily, especially when we are talking about strict rational law expressed in common language...

**Comment by KacperZajc** [comment]
we should translate on ongoing basis, I agree
