### ISSUE TITLE
unconstitutional behaviour 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#385]
I.XX Should there be reasonable suspicion that the Chancellor and/or any Member of the Cabinet has breached the Constitution or remains in breach of the Constitution, the Assembly shall be under obligation to attempt to pass a Resolution with a simple majority votes of overall number of the Assembly Representatives requesting the Supreme Court to adjudicate on the case; the Resolution shall appoint one Assembly Representative to act in the capacity of the Prosecutor before the Court.

§II.8(10) to request the Supreme Court to adjudicate on the suspicion over potential unconstitutional behaviour of the Chancellor and/or any Member of the Cabinet.

§IV.10(9) The Supreme Court shall have inherent jurisdiction to rule on the suspected unconstitutional behaviour of the Chancellor and/or any Member of the Cabinet upon the request of the Assembly.

???

**Comment by terrorist96** [comment]
> I.XX Should there be reasonable suspicion that the Chancellor and/or any Member of the Cabinet has breached the Constitution or remains in breach of the Constitution, the Assembly shall be under obligation to attempt to pass a Resolution with a simple majority ~~votes~~ **vote** of **the** overall number of the Assembly Representatives requesting the Supreme Court to adjudicate on the case; the Resolution shall appoint one Assembly Representative to act in the capacity of the Prosecutor before the Court.

This is basically saying that you have to vote to impeach? We already give the Assembly the power to decide to impeach; I don't see what more this section really adds.
