### ISSUE TITLE
Legislation is broken.

### ISSUE THREAD

**Issue by qm3ster** [liberland/constitution#389]
There is a lot of confusion pertaining to legislation, for example in #281 
Perhaps a major redo is in order. Here are some changes that I propose (that were immediately obvious to me. Maybe after better thinking some of these will turn out to be redundant.):
1. Mandatory expiration of all laws, even in case of stalled/frozen government. Each law must have a concrete date within it after which it ceases being a legal document and becomes historic literature. Discussed in #382 
2. Any bill that 'passed' via the currently (2016.01.27) described process must also enter a **direct democracy round:**
   1. The document is annotated in potentially more legally ambiguous but maximally comprehensible way, with uses of concrete examples of application and, where necessary, diagrams or lists of pros and cons.
   2. The annotated document is published in a way accessible to the widest range of people.
   3. Citizens receive a notification and can begin voting on the bill online, through their unique citizenship accounts that are the final instance of their identity.
   4. If a citizen believes that the annotation or examples do not accurately represent the related bill, or are worded in a biased manner to receive more votes, they can vote that the annotation is fraudulent. A substantial minority of this vote will reset the currently submitted Yes and No votes, and lead to legal, potentially even criminal, proceedings of <_however many of the 'reporters' actually choose to participate in the lawsuit_> vs <_whoever signed off on the annotation_>.
   5. All votes are permanently recorded in the public ledger, (the same one with court records, land ownership, and government positions).
   6. After the passing of a month since the voting begun (initially, or anew after an unsuccessful 'fraudulent annotation' lawsuit) the votes determine whether the bill is legalized by comparing them with the necessary consent percentage that can differ depending on the scope of the law proposed and its expiration period.
   7. A weighted sum of the percentage of 'passed' laws accepted by the citizenry and the actual percentage of these 'acceptances' is a useful metric of government compliance and efficiency.
   8. A detail I am yet unsure about is whether not voting should count as a No or as a decrease in the denominator. Since people could be perceivably stopped from voting, I currently believe it should count as No when determining if the bill can proceed, but count as a non-citizen when calculating the performance metric.
   9. All votes, even changed, pre-reset and _ignored the vote_ must forever remain in the public ledger, giving people insight into the policies of prospective government employees and other valuable data which does a lot more harm kept private than published.
3. To make up for the 1 extra month enacting a law would take, the legislation proceedings can now be started once in 6 months. 12+1-6=5, meaning that overall, this reform improves the ability of laws to react to the environment, while making them less manipulable.
4. The `Bill proposed to the Assembly shall pertain to one matter only as expressed in its title` should be made even stricter, perhaps there should even be limits on word count and syntaxis (kinda like Cyclomatic Complexity). This will give us small, universally applicable, modular laws that can easily be voted on without confusing the average citizen (improving voter 'turnout') and can easily be reviewed upon expiration.
5. Apart from laws that state what shall and shan't be done, there should be a codex of unbiased **definitions** of certain fuzzy terms for use in all legal documents and court proceedings. (What is a person. What is a property. What is land. What is freedom of movement. What is a citizen. What is self-defense. What is 'disruptive behavior' or 'contempt of court'. These are crucial.)
6. All laws that depend on prior laws and general definitions should be explicitly linked, so that when underlying laws or legal definitions are being reviewed, everything that depends on them can be accessed.
7. All Constitutional statements, Laws, and Definitions should be tagged with tags like #minors #fraud #law_enforcement, #international_relations etc.
8. The Constitution, the Definitions, and the initial Laws should be brought to that standard and kept to that standard. A legal document that omits these important features is a violation akin to a fraudulent summary (and like that, can also be unintentional but still cause problems).

**Comment by michalptacnik** [comment]
Working on a major redo. Closing the issue. We have a new draft of the constitution here: https://docs.google.com/document/d/1J2o5N9JDOzBXRkefe9Azm6P6vAwqCxw7B2jcKoHSjhg/edit
