### ISSUE TITLE
Recorded votes

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#391]
I propose we add a provision saying that when the Assembly conducts a vote, all the Yeas and Nays shall be recorded. This would prevent passage of bills by 'voice-vote' where representatives won't have their votes recorded, thus not being able to be held accountable for their vote on particular legislation.

**Comment by KacperZajc** [comment]
isnt that already covered by §I.13. ?

**Comment by terrorist96** [comment]
It would seem so, but here's an example: the Assembly 'complies' with that section by having one video camera in the room that is always recording. They decide to vote on a bill and do it by voice vote and the bill passes.
The affairs of the Assembly have been recorded, so they've complied with that section. But looking at the recording, you can only hear the Reps saying 'Aye' and you can't see a list of those who voted in favor and those who voted against. So it's not much help.

**Comment by KacperZajc** [comment]
feel free to rephrase I.13 so that it is more detailed :)

**Comment by terrorist96** [comment]
I think it would fit better with either section II.3 or II.13 or II.14.
We should restructure it so that all matters regarding Assembly Reps voting are in one section, not spread out across multiple different sections.
