### ISSUE TITLE
strict liability offence

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#392]
No Person shall be convicted of any criminal offence which would not require any form of guilty mind as a mens rea.

for any conduct to be criminal it should require intention/recklessness/negligence (mens rea) on the part of the accused, not just committing an act while being unaware of that

**Comment by terrorist96** [comment]
Fully support this.

**Comment by terrorist96** [comment]
@KacperZajc I recommend expanding this section to say that all criminal offenses shall fall under malum in se, and disallow malum prohibitum type laws.

**Comment by terrorist96** [comment]
https://en.wikipedia.org/wiki/Malum_prohibitum
https://en.wikipedia.org/wiki/Malum_in_se

**Comment by KacperZajc** [comment]
I think this is included in the prohibition of victimless crimes.
I dont see what other non-Latin phrase would this take form of.

**Comment by terrorist96** [comment]
That's true
