### ISSUE TITLE
Best to remove "no slavery" clause or the "land fee" bill?

### ISSUE THREAD

**Issue by thetimpotter** [liberland/constitution#395]
Here in the situation of the "land fee" or "land tax" the minority is a 5% slave to the majority.

§I.35. No relationship amounting to slavery or any other form of involuntary servitude shall exist between any legal or natural Person and any other Person; no conscription or any other form of compulsory service shall be introduced by any branch of the Public Administration.

Alternatively there are many possibilities to fund government in a way that has no slave-master dynamic, such as just one proposed by tinkyholloway:

Only fee payers are counted as 'citizens'. Only citizens can participate in goverment: stand for office, vote, veto vote, be on juries, hold the title 'Citizen' etc. it's basically a flat fee, poll tax.

What are your thoughts?

**Comment by terrorist96** [comment]
That's not a bad idea and a good alternative to the land fee.

**Comment by KacperZajc** [comment]
I generally like the idea to levy some form of charge on the Electoral Register but it is likely to label us 'undemocratic' and therefore impede the recognition process.

**Comment by terrorist96** [comment]
Don't think of it as a fee to register to vote; think of it as a fee to register to be a citizen. Citizenship isn't a guaranteed right - it's a privilege. You can still live in Liberland and be a non-citizen resident.

**Comment by mherzl** [comment]
True, citizenship is not a right. If it were than there could be no jurisdiction over who to accept for citizenship.

**Comment by Auahi** [comment]
I like this idea also but you'd have to create away to where the fees don't sky rocket....

**Comment by thetimpotter** [comment]
Open

**Comment by thetimpotter** [comment]
Right I can see the concern for a poll tax.  I look at it similarly to
terrorist96.  Citizenship is a choice, and includes many benefits.  Opting
out of citizenship and being simply a resident or natural person would
exclude that person from liberland's citizen services.
