### ISSUE TITLE
Mens rea question 

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#396]
Regarding the recent commit requiring mens rea for a guilty conviction of a crime, would this allow people who commit manslaughter (unintentional murder, like due to a car accident) to walk free?

**Comment by KacperZajc** [comment]
No, those are either recklessness or negligence cases.

**Comment by terrorist96** [comment]
What if it's neither? Say something out of the control of the person happens (like a malfunction in his car) that causes the accident to happen.

**Comment by KacperZajc** [comment]
that is just an accident and not manslaughter at all, manslaughter requires some form of culpability i.e. negligence/recklessness (or be responsible for an accident while committing some other crime)

**Comment by terrorist96** [comment]
Let's disregard what it's called then. Accidental death due to no fault of the killer.

**Comment by KacperZajc** [comment]
yes, definitely 
accidents happen and we shouldnt criminalise harm if it doesn not flow from culpable behaviour
