### ISSUE TITLE
Big changes

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#397]
Please find the new version of the Constitution in a separate issue (#398).
The first thing is I divided Article I into General Provisions and the actual Bill of Rights (which is Article V now). It got too long and lost coherency.
The second big change is the second legislative chamber (personal request of the President - I have nothing to say about that).
The rest are just some small changes.

**Comment by terrorist96** [comment]
Second legislative chamber is only added cost. The people through the referendum process act as a second legislature already.

**Comment by KacperZajc** [comment]
to be fair, not in the form I put it (see II.24-26)
