### ISSUE TITLE
Supreme Court vote

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#403]
I think we should change the requirement to vote unanimously for the prima facie constitutionality of a Bill to 4 out of 5.
1 vote may always be unreasonable any place any time.
We have enough safeguards anyway.

**Comment by terrorist96** [comment]
I think every one of the 5 justices should be competent. If there's disagreement between 1 of them with the other 4, the 1 justice's opinion shouldn't be disregarded. Maybe he sees something the other 4 don't. I've always been confused as how there can be split decisions on declarations of constitutionality. It either is or isn't. There shouldn't be any gray areas. There should be just 1 correct way of interpreting the constitution. Maybe the 1 disagreeing justice is the one who is correctly interpreting the constitution. And if he is wrong, he can be removed via §IV.9(8)

**Comment by KacperZajc** [comment]
I really think we need to lower the threshold to 4 out 5 Justices.
Unanimity is very impractical and we have a whole series of other safeguards within the legislative process.

**Comment by terrorist96** [comment]
Well you know my opinion. Let's see what others think. 
@FellowTraveler @yopdog @Auahi

**Comment by Auahi** [comment]
The Liberland constitution is designed to only allow minimal changes, and there are only 5 justices so I think it should be unanimous.

**Comment by KacperZajc** [comment]
I think we need to account for reality here, 1 vote might always be cast for reasons other than merits of the law.

**Comment by Auahi** [comment]
That's true but you have to remember there's only 5 justices. I would agree with you if there were 20 justices that would be unreasonable to always have a 20/20 vote but if one justice didn't agree out of 5 I think there should be a valid reason.  But I do see your point Kacper, I'd be more okay with allowing a non-unanimous vote if there were more justices.

**Comment by KacperZajc** [comment]
only 5 judges, but multiple safeguards on the way so I think it would be reasonable to make it 4/5 :)

**Comment by liberlandcitizen** [comment]
Either something is constitutional, or it is not. The constitutionality
should be absolutely clear and it should be easy for all five to rule
something constitutional or not.

We have safeguards to remove judges if they are not behaving in a fair and
ethical way. I strongly urge you to keep the 5 out of 5 rule.

Making it 4 out of 5 would mean allowing some iffy/controversial things to
become law. We don't want that.

**Comment by KacperZajc** [comment]
as I said 1 judge can vote for reasons different than the views on constitutionality, we need to allow some room for human nature

**Comment by liberlandcitizen** [comment]
Then that judge will likely be removed for not doing his or her job
ethically.

**Comment by liberlandcitizen** [comment]
The constitutionality of a law should be obvious not only to all five
judges but to the entire citizenry as well. If a judge is voting against
something that is clearly constitutional, the citizens will know. If it
becomes a pattern, the citizens will become angry and action will be taken
to remove that judge. If the constitutionality of something is unclear,
maybe that one vote against is actually a good thing.

**Comment by liberlandcitizen** [comment]
Using US history as an example: between 1801 and 1940, 91% of court
decisions were unanimous. In the modern era, we have judges who seemingly
do not care about the original intentions of the constitution and vote
according to their desires. Despite this, you'll still find many unanimous
rulings. For example in 2013, the court was unanimous 62% of the time.

My point being, it is not particularly difficult to get unanimous decisions
when constitutionality is obvious and your fears may be unfounded.

And again, unlike the US, Liberland even allows for judges to be removed by
the citizenry, so I feel we are covered here.

**Comment by liberlandcitizen** [comment]
I also found this chart which shows in several other nations, unanimous
decisions of high courts are quite common:

http://ukscblog.com/wp-content/uploads/2010/08/unanimous1.jpg
