### ISSUE TITLE
breach of contractual obligations

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#405]
No law shall criminalise breach of contractual obligations.

???

**Comment by terrorist96** [comment]
Sure. Would this include violations of TOS/EULA/etc.?

**Comment by KacperZajc** [comment]
what are TOS/EULA?

**Comment by mherzl** [comment]
Am I missing something here? Isn't preventing fraud by enforcing contractual obligations one of the only proper purposes of government?

**Comment by mherzl** [comment]
Enforcing contracts is essential to protecting property rights.

**Comment by terrorist96** [comment]
Terms of service/end user license agreement.

**Comment by terrorist96** [comment]
Contacts can still be enforced. Violating a contract simply won't be a criminal offense.

**Comment by mherzl** [comment]
How will a court deal with cases of breached contract?

**Comment by terrorist96** [comment]
As a civil matter, I assume.

**Comment by KacperZajc** [comment]
indeed

**Comment by mherzl** [comment]
In the context of a society with no victimless crimes, I'm not convinced there should be a civil/criminal distinction.
