### ISSUE TITLE
crimes in another jurisdictions

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#406]
No law regulating conduct of Persons other than Members and/or Agents of the Public Administration shall extend beyond the territory of the Free Republic of Liberland, including aircrafts and watercrafts registered in the Free Republic of Liberland; nothing in this provision shall prevent Assembly from granting the Criminal Court jurisdiction over international crimes.

the idea is to prevent the attempt to criminalise conduct which is not a crime in another jurisdiction on the basis of nationality of the offender

**Comment by terrorist96** [comment]
Why give exceptions for members/agents?

**Comment by KacperZajc** [comment]
because if they breach the constitution in their official capacity abroad, we want to get them :)

**Comment by terrorist96** [comment]
Okay, makes sense.

**Comment by TWalls** [comment]
I'm not sure if this is dealt with in another section, but how about fugitives from justice from another jurisdiction? To what extent does the Chancellor and Assembly have the power to make extradition treaties with neighbors, and what may they or may they not agree to in such agreements?

**Comment by KacperZajc** [comment]
conducting foreign policy is one of the powers of the Cabinet
