### ISSUE TITLE
age of criminal responsibility 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#407]
No Person below the age of 14 shall be held liable for any criminal offence; no Person below the age of 18 and above the age of 14 shall be held liable for any criminal offence unless the Criminal Court is satisfied that at the time the alleged offence was committed he or she was sufficiently mature to understand its nature and consequences; no Person lacking mental capacity shall be held liable for any criminal offence unless the Criminal Court is satisfied that at the time the alleged offence was committed he or she understood its nature and consequences.

**Comment by terrorist96** [comment]
I don't think we should say that they shouldn't be liable. They should still be liable, but have a lesser punishment imposed due to the circumstances of their age/mental health/etc.

**Comment by Auahi** [comment]
I agree with terrorist.

**Comment by KacperZajc** [comment]
OK let's leave it for now then
