### ISSUE TITLE
Surveillance by proxy

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#408]
Is there anything stopping the government from receiving surveillance information about its citizens/residents from other states that scoop up Liberlander's data? Similar to how the USA has a deal with other countries like England where they share with each other the data they obtained from spying on each other's residents, I'd like to prevent this from happening.

Edit: I guess it could be covered by the "obtaining it from third parties" clause in V.7

**Comment by KacperZajc** [comment]
It is close to this:

§I.13. No branch of the Public Administration shall contract with any legal and/or natural Person for the purposes of acquiring data it itself is not entitled to acquire under this Constitution or any laws passed in accordance therewith; nor shall any branch of the Public Administration be allowed to procure any legal and/or natural person to commit what it itself is not entitled to commit under this Constitution or any laws passed in accordance therewith.

Should we add 'state' to this provision?

**Comment by terrorist96** [comment]
Add 'state' and 'entity'. I think replacing 'group' with 'entity' in 1.18 would be better too.

**Comment by KacperZajc** [comment]
done
