### ISSUE TITLE
Term shortening, and amount of times served lengthened.

### ISSUE THREAD

**Issue by Auahi** [liberland/constitution#411]
I believe the terms for ARs are quite long. 6 years makes it so views are stagnant, and there's never an inflow of ideas. If we limited terms to 2 - 4 years we could allow candidates to change often but still allow for regularity. I aslo think the amount of times one can serve in office shouldn't be limited, a comprise could be something like that of how Russia deals with its president. Maybe allow for 3 consecutive 2 year terms. and have an off period of 1 or 2 terms. Personally don't think there should be any limit though but at least this would allow for new candidates...

**Comment by terrorist96** [comment]
I'm adamantly for term limits. Indifferent towards 6 versus 4 year terms. I believe it was originally 4 but Kacper changed it to 6.

**Comment by Auahi** [comment]
What's your view on the Russian style term limits? Most countries have terms set at 5 years, I still see that as long. When you have long term limits you don't represent the publics opinion accurately, especially since Liberland will have lots of immigration I think it's imparative to have a more representational government.

**Comment by terrorist96** [comment]
Having the Russian system for term limits would be preferable to no term limits, but I'd still prefer the strict 2 term limit over the Russian version. The more turn over we have, the better representation we can have. Otherwise, people are more likely to vote for the name they recognize on the ballot. In the US, a Senator serves a 6 year term with no term limits, while members of the House of Representatives serve a 2 year term with no term limits, so having a 6 year term isn't unheard of. I'm not opposed to changing it from 6 to 4, but that's Kacper's call.

**Comment by Auahi** [comment]
I'm not in favour of a complterms but I definitely see where you're coming from. If you really want fair representation a shorter term should be considered.... And I know it's up to Kacper at the end....

**Comment by KacperZajc** [comment]
Elections are the opportunity to make stupid promises and populist claims, they should be reasonably rare.
On the other hand, some policies take time to produce good effect and the gov which introduces them should benefit from that effect (as opposed to the next gov).
Finally, more than 12 years in politics will make any person a politician as opposed to whatever he/she has been in life beforehand, we really want to avoid career politicians and instead see new faces.

**Comment by liberlandcitizen** [comment]
I agree with everything Kacper said and I think the current constitution
strikes a very reasonable balance with regard to term limits and length of
terms.

<<Elections are the opportunity to make stupid promises and populist
claims>>

Political parties seem to play a huge role in this as well. Have we
addressed how elections will work with regard to political parties? I
personally favor not having political parties and having the people vote
for candidates and not for party affiliation.

**Comment by Auahi** [comment]
New elections are also a time to allow people with populist views to be taken out of office, and shorter terms allows populists to not stay in government for a long time.

 I don't like political parties either and term lengths don't have anything to do with parties....

**Comment by KacperZajc** [comment]
> **http://www.deon.pl/religia/serwis-papieski/aktualnosci-papieskie/art,4451,wiekszosc-malzenstw-sakramentalnych-jest-niewazna00.html**

And this is why with every next presidential election, there is a better President in the US. xD

The election system is yet to be discussed.
