### ISSUE TITLE
Removal of an AR, extended.

### ISSUE THREAD

**Issue by Auahi** [liberland/constitution#412]
I think I wasn't getting my point across well and people aren't seeing what I'm seeing. So in Liberland a vote to remove an AR can take place if 5% of the population sees fit; in order for the AR to be removed 50% of the total voters must vote in favour of removal. Here's a scenario where this could be an absolute disaster:

Let's say there are two parties in Liberland (This could work with 3+ as well) A and B. A represents 55% of the population, and B 45%. 5% of the population is needed to call a vote for removal of an AR, this happens for a B AR. This now goes to the public ballot. Since 55% of the population is A it will be easy to have a majority vote in favour of the B AR removal. When the election for the new AR takes place an A representative will take his place since 55% is A (this will happen in almost every voting system). You now have replaced a B AR with an A AR. This process can repeat for the remaining B ARs making the entire Assembly A. You now no longer have a democracy. Also this cannot happen in reverse. Bs can't remove As since the majority of the population is A. This also makes it hard for small parties with non common views to be represented in the Assembly since the larger parties can easily just remove them.

This clearly is not a democracy, I hope I clarified things for you.

**Comment by terrorist96** [comment]
Well we don't know how elections will be conducted yet. If it's always simple majority, then party B would never be able to obtain a seat to begin with.

**Comment by Auahi** [comment]
First past the post would result in 11 A representatives and 9 B representatives, in most systems you'd have B Reps in the assembly even if it's 45%...

And even if we don't know the system why should we incorporate this into the constitution if it could result in terrible outcomes, the constitution should be a basic guideline to freedom, and prevent anything like this from happening.

**Comment by KacperZajc** [comment]
OK I see your point. It

**Comment by KacperZajc** [comment]
OK I see your point, it makes sense now. I think we should refrain from making any changes to the recall process until we know more about the election process as @terrorist96 pointed out.

**Comment by KacperZajc** [comment]
#252
