### ISSUE TITLE
criminal defences

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#414]
In all criminal proceedings, the prosecution shall carry the legal burden of proof, discharged beyond reasonable doubt, in relation to the defendant's guilt, including disproving any defence envisaged by the law which he or she might raise; nothing in this provision shall prevent the creation of defences which require the defendant to discharge the evidential burden of proof by raising the issue of defence available to him or her.

The idea is to prevent the creation of defences which require the defendant to prove it beyond reasonable doubt or otherwise the defence fails and that leads to conviction.

The example would be for a defendant prosecuted for murder to raise the defence of insanity (evidential burden) then the burden shift onto the prosecution to prove beyond reasonable doubt (legal burden) that the defendant was in fact sane at the time the crime was committed.

**Comment by terrorist96** [comment]
Did you forget to add this part?

**Comment by KacperZajc** [comment]
nah, just decided it's not worth adding to the text

**Comment by terrorist96** [comment]
It's probably covered by innocent until proven guilty anyway.
