### ISSUE TITLE
Loss of right to run for offices §I.7

### ISSUE THREAD

**Issue by zasadiljan** [liberland/constitution#415]
§I.7. All Members and Agents of the Public Administration intentionally acting in breach of the law relevant to the position held or the Constitution shall be criminally liable for their actions and, upon conviction, shall be removed from the office and shall never hold any public office again

a) This rids the citizen of one of their fundamental civic right to run for office and creates a class of citizenship that is unequal. A possible solution would be the loss of citizenship altogether. Criminal liability can be retained.

**Comment by Auahi** [comment]
I detest the fact that a government can revoke one's citizenship. I don't see the problem with not being able to run for office again, you still have other rights as a citizen like voting, and the possession of a passport.

**Comment by liberlandcitizen** [comment]
*<<I detest the fact that a government can revoke one's citizenship. I
don't see the problem with not being able to run for office again, you
still have other rights as a citizen like voting, and the possession of a
passport.>>*

+1 to this. Plus it can render somebody stateless.

**Comment by terrorist96** [comment]
If you oppose the government having power to revoke citizenship, would you also object to the government having power to deport people? The government needs to be able to regulate its affairs, and citizenship is a privilege granted by the government to the people, it's not a right.

**Comment by terrorist96** [comment]
> a) This rids the citizen of one of their fundamental civic right to run for office and creates a class of citizenship that is unequal. A possible solution would be the loss of citizenship altogether. Criminal liability can be retained.

A citizen that is convicted of a crime loses their liberty by being locked up. A public servant that commits a crime doesn't deserve the privilege of serving the public.

**Comment by liberlandcitizen** [comment]
<<citizenship is a privilege granted by the government to the people, it's
not a right.>>

That is an opinion, not fact, I happen to have a different opinion. Yes,
citizenship can be granted by the government on behalf of the citizens of
that country. That's called naturalization. But for many, citizenship is a
birthright. It is something you are entitled to because you were either
born on the soil or because your parents had citizenship.

It is terrifying to think that a powerful government can take something so
meaningful away from somebody. And this would be a good time to also remind
you that inevitably some who are convicted of crimes are actually innocent.

**Comment by terrorist96** [comment]
A right is something that you have independent of government. The right to defend yourself, the right to speak your mind and conscience. Citizenship is a title/status bestowed upon you by government. We reserve revocation of citizenship for only the most serious crimes, and only if it doesn't render a person stateless. I wouldn't be opposed to more regulation in regards to this, such as allowing the option of revoking citizenship only if convicted of a crime that is punishable by 50+ years imprisonment, for example.

**Comment by liberlandcitizen** [comment]
*<<A right is something that you have independent of government.>>*

Absolutely correct. Is not access to your land, your possessions, your
family and everything you've ever known the most natural of rights? Should
the government have the power to take that all away from you? Again I will
argue that citizenship (for most) is something you are born with, as a
right, and not something a powerful, overreaching government should be able
to take away from you.

**Comment by terrorist96** [comment]
Yes, property is also a natural right. Are you basically arguing that citizenship can be interpreted as a form of property?

**Comment by terrorist96** [comment]
Access to your property is revoked when you become incarcerated for an infamous crime, so I don't see why citizenship can't be as well. Also, there's nothing preventing a person from reapplying for citizenship in the future after rehabilitation.

**Comment by liberlandcitizen** [comment]
We'll get further off subject if we start discussing locking people in
cells...and if it's for protecting the public vs punishment.

I wasn't saying that citizenship itself is property, though it's debatable,
especially for a nation selling it for 10,000 dollars. I'm arguing that
citizenship is a birthright, and that a limited government shouldn't be
allowed to take away your most basic of rights no matter what. I would
include speech, religion, voting rights and citizenship (along with other
rights) on the list.

This is not to protect the scum of the earth, this is to protect the
citizens against tyranny. Don't make a government more powerful than it has
to be, history has shown countless times that they will abuse that power.

One more point I'd like to make, with respect to punishing those in public
office who breach the constitution....I'm all for making politicians
accountable but if you make things too harsh, who in their right mind is
going to serve in public office? Only the insane or criminal. Furthermore,
who will interpret if a public servant is in breach? How literal will they
be? Will this punishment ever be politically motivated, and possibly
misused?

I'd really have to think twice about running for office, even with full
intentions of abiding by the constitution. What if somebody interprets it
differently than I do? Will I lose my citizenship and end up in jail?

**Comment by terrorist96** [comment]
> Will I lose my citizenship and end up in jail?

No and no. You won't lose your citizenship if it would render you stateless and you wouldn't lose your citizenship because it's not a serious enough crime to warrant it.

> All Members and Agents of the Public Administration **intentionally** acting in breach of the law

Added for emphasis. :)
But I agree that this has gotten off topic.

**Comment by zasadiljan** [comment]
@liberlandcitizen Good point, rendering someone stateless is prohibited, too. So that's an impass... 

@terrorist96 I have figured out based on §I.7. and §I.15. (§I.7. bans officers with criminal history in office from holding further offices, §I.15. guarantees the right to stand a candidacy to everyone) that this is not a valid remark - my fear was that starting with your 2nd candidacy, you need to prove you have not breache the law (be certified by the state or something) before your name appears on the ballot, however, you only must not hold the office, so you can still run... So there is no double citizenship standard for standing a candidacy.

However, I have not found the right to stand candidacy in the Bill of Rights - it is only disperrsed between §I.7. and §I.15. I would think that this kind of right should by granted to the citizens expressly by the Bill.

**Comment by KacperZajc** [comment]
Right to citizenship is not a natural right IMO.
Natural rights exist independent from the concept of state.
Citizenship can exist only if states exist.
Same goes for the right to asylum for example.
But his is off topic.

Deprivation of citizenship can be executed only by the Court upon conviction of a serious criminal offence if this form of punishment is provided by law and not if that would render the defendant stateless. 

The right to stand candidacy is expressly provided in I.15:

§I.15. **All Members of the Public Administration shall be of age twenty-one or above and shall hold citizenship of the Free Republic of Liberland; no such Individual shall be prevented from submitting his or her candidacy for a public office;** all candidates for any public office in the Free Republic of Liberland as well as all current Members of the Public Administration shall be under obligation to disclose their assets above certain value as prescribed by law, sources of income over certain proportion of his or her overall yearly income as prescribed by law and benefaction, both current and of the past five years, as prescribed by law, to the public; should a candidacy be submitted by any such organisation as may be prescribed by law, such organisation shall be under equal obligation of disclosure.

I think we should add 'unless such Individual has been convicted of a criminal offence in relation to the position he or she held in the past', just to make clear there is this one exception.

There is no need to prove that you can stand. You cannot stand if you have been convicted of the relevant offence and upon the verdict the Court will presumably declare that you are no longer eligible to stand. Verdicts are published so it will be common knowledge who can and cannot stand.

**Comment by Auahi** [comment]
I think we should have a citizenship model similar to that of Poland.

Since 1962, Polish law (including the Constitution) does not allow the government to revoke someone's citizenship. Renunciation of Polish citizenship requires a petition with extensive supporting documentation subject to the approval of the President of Poland.[5] Administrative processing of the petition can take up to several years and the President's decision is final and cannot be appealed in court. (From Wikipedia)

They also don't recognise dual citizenship but allow it, Poland treats nationals of other countries whom it considers Polish citizens as if they were solely Polish. This is the key principle of citizenship I want for Liberland, and currently the government is set up to recognise other citizenships...

I highly suggest reading this, it's Poland's nationality laws: https://en.wikipedia.org/wiki/Polish_nationality_law

**Comment by liberlandcitizen** [comment]
Liberland will be 7 sq km. It's unknown how many countries will recognize
us. It's unknown how many countries will give us visa free travel. There
are no homes or structures, as of now, and lots of mosquitos. Nobody was
born there, and all of us have another citizenship. You are suggesting that
everybody give up their other citizenships (and passports)?

Interesting, but quite a sacrifice.

**Comment by Auahi** [comment]
@liberlandcitizen that's not what I'm saying at all, if you read The Wikipedia Article about Poland's citizenship laws it'll make more sense, but here's a summary: When someone is a citizen of Poland and another country, Poland will treat you as if you are only a Polish citizen. They won't not allow you to have more citizenships they just won't deem you as dual citizen. So dual citizenship is tolerated but not recognised, It's hard to explain.

**Comment by liberlandcitizen** [comment]
Apologies, I misread your earlier post.
