### ISSUE TITLE
legal challenge 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#416]
New provision:

§IV.10(9) Upon reviewing the prima facie constitutionality of a Bill, the Supreme Court shall hear submissions, which are of relevance for the outcome of the determination, from the Cabinet as well as from any association composed of no fewer than 30 Citizens.

Rephrased: 

§I.8.All administrative decisions of any branch of the Public Administration and actions undertaken by its Agents capable of affecting any Person and all Executive Measures issued by the Cabinet, may be subject to challenge in the Civil Court by a Person affected thereby or, in the absence of any Person specifically affected, by any association composed of no fewer than 30 Citizens; the right shall be exercisable once all administrative appeals have been exhausted; without prejudice to the appeal procedures, such challenge shall be admissible once only unless the original challenge was not genuine but brought in order to shield the defendant from liability or where a new challenge raises a different point of law.

The original provision was way too broad in my opinion. It would lead to endless lawsuits against any petty decision of any person working in the PA by any bored Citizen.

**Comment by terrorist96** [comment]
> as well as from any association composed of no fewer than 30 Citizens.

Why? Why couldn't an individual citizen submit an amicus curiae to the court?

> §I.8.All administrative decisions of any branch of the Public Administration and actions undertaken by its Agents capable of affecting any Person and all Executive Measures issued by the Cabinet, ~~shall~~ **may** be subject to challenge in the Civil Court by a Person affected thereby or, in the absence of any Person specifically affected, by any association composed of no fewer than 30 Citizens; the right shall be exercisable once all administrative appeals have been exhausted; without prejudice to the appeal procedures, such challenge shall be admissible once only unless the original challenge was not genuine but brought in order to shield the defendant from liability or where a new challenge raises a different point of law.

If it doesn't affect any specific person, doesn't that negate the right to challenge it?
**All administrative decisions of any branch of the Public Administration and actions undertaken by its Agents capable of affecting any Person**

**Comment by KacperZajc** [comment]
I think organisations are better suited to submit an amicus curiae than individuals. 
Plus, this will lead to a massive number of submission and make the whole process unworkable IMO.
I like how in the US there are organisations which are always willing to go to court. This provisions ensures standing.

I think we have to restrict jurisdiction to decisions which affect others. Otherwise, every decision to by stationary for the office will be subject to challenge. This would be crazy.

**Comment by terrorist96** [comment]
In the US,  there's no minimum requirement for the size of an organization submitting a brief. The only requirement is that it be done by a lawyer. 
https://www.law.cornell.edu/rules/supct/rule_37

And yes, I agree that it should be restricted to cases where it affects a person. But the wording right now says "only of it affects a person, but if a person isn't affected, then by a 30+ person group" 
The second clause negates the narrowing of the first clause.

**Comment by KacperZajc** [comment]
30 members requirement relates to Executive Measures which do not affect any specific person as a rule (as opposed to administrative decisions)
