### ISSUE TITLE
The prohibition of consensual crime principle

### ISSUE THREAD

**Issue by zasadiljan** [liberland/constitution#417]
Consensual crime is a principle whereby that which has been agreed by two parties can objectively still be considered as crime by the law. In Czech law, e.g., this absolute criminality ranges from murder, over pretended rape or any other allegedly pretended crime, down to consumer protection provisions of the civil code and some provisions of the labour law. It basically means that some provisions of the law may not be forfeited by the "weakers' party" consent in favour of the "stronger party".

The constitution bans the definition of consensual crime by law. Taking the first two examples mentioned, this would according to the constitution mean the following:

a) Practically, in extreme, two people can agree that one shoots the other dead (under some conditions) which then entitles them (under said conditions) to do that without being punished.

As @KacperZajc argues, "in practice it would be held that no one of sane mind could invite another person to shoot him, for a consent to be valid, one must be in capacity to give it, but it is worth debating whether we should insert an exception regarding that (subject to law regulating euthanasia)"

b) The other typical objection to this is the "fake rape scenario": parties agree that this is what the "victim" finds sexually fulfilling, and after the act, there's doubt whether or not the "victim" belies his/her previous consent to criminalize the other, or whether the real perpetrator of rape is lying about previous verbal agreement. 

I think that the sane-mind argument will not hold here, especially if the consent given is verbal and there is great room for doubt on either of the parties' side.

I do understand this is the quintessential libertarian princile, however, there is a difference between applying it to civil, corporate or labour law where relative liberties do not interfere with the right to life and personal integrity, and applying it to criminal law where the consequences are grave. 

In terms of practicality, I fear that if this becomes the cornerstone of the criminal code, then a) the constitution is going to turn into a list of exceptions and b) it is still going to have both the legislature and the judiciary looking for America all over again and all over the place for quite some years.

**Comment by liberlandcitizen** [comment]
*<<"or whether the real perpetrator of rape is lying about previous verbal
agreement.">>*

Sounds like the kind of thing you ought to get in writing (or on video,
audio recording, email, sms, etc). Most rape cases are regrettably he
said/she said anyway, and even with "consensual crime" you would have to
prove that it was consensual.

<<I* do understand this is the quintessential libertarian princile,
however, there is a difference between applying it to civil, corporate or
labour law where relative liberties do not interfere with the right to life
and personal integrity, and applying it to criminal law where the
consequences are grave.*>>

Either you believe people can take care of themselves, or you believe
people are weak/stupid and need an all-mighty, powerful and wise government
to take care them.

The dream is to have one country with the ultimate amount of freedom and
the least amount of government. Let's aim for consistency for all matters;
if two or more consenting  and able minded adults want to do something with
each other, and it doesn't harm any third parties, let them do it.

**Comment by terrorist96** [comment]
> a) Practically, in extreme, two people can agree that one shoots the other dead (under some conditions) which then entitles them (under said conditions) to do that without being punished.

This would be called a duel, which used to occur more commonly many years ago in America. I'd say if two people are stupid enough to consent to dueling each other, let 'em, as long as they're doing it on private property and there's no chance that bullets from their guns could leave the property and hurt an innocent bystander.

> b) The other typical objection to this is the "fake rape scenario": parties agree that this is what the "victim" finds sexually fulfilling, and after the act, there's doubt whether or not the "victim" belies his/her previous consent to criminalize the other, or whether the real perpetrator of rape is lying about previous verbal agreement.

I think you can prove rape more reliably if the victim has scars or bruise marks to show that she tried to resist the rape, so it's not just one's word against the other.
