### ISSUE TITLE
V.4 video/audio recording

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#418]
> **§V.4.** No law shall prohibit video and/or audio recording of any Agent of the Public Administration whilst on duty in public space and all other areas where there is no reasonable expectation of privacy

I think she should clear this up. It can be interpreted in two different ways:
1. You can record an Agent while on duty if he is in a public space or any other area there is no privacy expectation; or
2. You can record an Agent while on duty if he is in a public space, and you can also record in general where there is no expectation of privacy.

Which interpretation are we going with? I'd prefer the second interpretation, so as to protect journalists' right to gather evidence for a story, or just a regular person recording some landscapes, etc.

If the fear is the government setting up cameras everywhere to watch everyone, we can prohibit this, but allow for private businesses to have security cameras. And if the government wants to investigate a crime, they can get a warrant to get a copy of the video footage from the owner.

**Comment by Auahi** [comment]
I like the second definition as well, that being said I think it should be written in two seperate lines. And how would we stop government from filming everyone, is it possible to put something about that into the constitution?
