### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#421]
The Constitution is getting longer and longer.
I propose we review the text and discuss whether any provision could be removed on the grounds that it is not of utmost importance and as such it might as well be dealt with by ordinary law.

On my part I propose we remove:

§V.1. All statements and declarations made by any Individual to any body of the Public Administration shall be presumed to be truthful and made in good faith unless there is evidence to the contrary.

This provision is unclear any way and might have unpredictable consequences.

And:

§IV.13(3) Should a Public Prosecution be instituted, the Victim shall have the right:
§IV.13(3)(a) to be notified about the schedule of the judicial proceedings;
§IV.13(3)(b) to address the Criminal Court before the sentence is determined;
§IV.13(3)(c) to be advised of release from custody or escape of the accused.

This part can definitely be dealt with by law.

And:

§V.50. No law shall restrict the free movement of any Individual within the Free Republic of Liberland; all Individuals shall have the right to reside in any part of the Free Republic of Liberland.

Given how small Liberland is, this right is pretty much obsolete. 

Feel free to submit your proposals.

**Comment by Auahi** [comment]
I'm fine with you removing §V.1. and all of §IV.13(3), but I would prefer §V.50. to stay as a safe guard.

**Comment by terrorist96** [comment]
I thought the whole argument about having a long and detailed constitution was so we can close as many loopholes as possible. I'm wary about removing anything that's already in the current draft.
Yes, some of those things could be done as laws, but you said it yourself, laws are very hard to pass, and other things will always take precedence, like outlawing murder, rape, theft, etc. The 3 examples above might never get an opportunity to be codified into law.
