### ISSUE TITLE
The creation of a Super Constitution

### ISSUE THREAD

**Issue by Auahi** [liberland/constitution#422]
So there are many articles and pieces of legislation in the constitution which a very important, for example: Citizen's right to veto, Free speech, etc. I think we should make another document or separate article which ensures specific legislation is either impossible or very hard to repeal. The reason for making a separate document (Preferably another document) or article would be to prevent loopholes or other things of the like from happening. So for example:

The First bullet in the super constitution can read:
§I.1. Any content in this document shall supersede all conflicting text with the constitution of the Free Republic of Liberland, and any laws put into place in the Free Republic of Liberland. 
Then put important legislation after...

This makes it almost impossible to destroy fundamental freedoms and important legislation.

**Comment by Auahi** [comment]
Maybe this will be more clear: Currently any edit to the constitution requires 66% approval by voters, the supreme deem the amendment to be constitutional, and be accepted by 3/4 of the assembly. I'm proposing a way to ensure certain things in the constitution never change for example, V.3, II.24, II.25, II.26, etc. 

IMO the best way to do this is to make a "Superconstitution", This Superconstitution would be a document that supersedes the constitution. Anything in the regular constitution that conflicts with the Superconstitution is considered null and void. I'm making it a separate document, or maybe an independent part of the constitution to evade loop-holes, if this document was a part of the regular constitution it'd be subject to constitutional bills...

In order to amend the Superconstitution, the assembly and the supreme court must be unanimously in favour of the amendment, and 19/20(This can always be agreed upon later) of the citizenry must vote in favour of the amendment to the Superconstitution. This is the ultimate safeguard.

I hope I made this more clear

**Comment by liberlandcitizen** [comment]
I think this is an interesting idea. As I hinted to earlier in another
thread, maybe we should have more stringent criteria for constitutional
bills. Perhaps 90% of the assembly instead of 75%? Or better yet 90%
approval by the voters?

**Comment by Auahi** [comment]
I like that idea but only for certain legislation, not everything in the constitution needs to be under such a huge safeguard as V.3, for example. So this would mainly be for highly important legislation.

**Comment by terrorist96** [comment]
So basically you think some parts of the constitution deserve more protection than other parts? I think all of it deserves equal protection. Amending the constitution isn't easy. If by a miracle some amendment does pass, then maybe it's for the best.

**Comment by Auahi** [comment]
That's a good way to word.

The Liberland constitution is very broad and many things will be adopted or dropped in the countries early stage, this is a given. We shouldn't make repealing the constitution one step from impossible, but I do think we should make it this hard for certain legislation to be amended.

**Comment by terrorist96** [comment]
> many things will be adopted or dropped in the countries early stage, this is a given.

Is it though?
As it currently stands, the constitution can only be adopted or rejected, not amended.

§12. The Committee shall prepare a draft of the Constitution of the Free Republic of Liberland which the Assembly shall approve with ‘aye’ or reject with ‘nay’ with a simple majority, on its first meeting after the first General Election.
https://github.com/liberland/laws/blob/master/drafts/The_Articles_of_the_Preparatory_Committee.md

**Comment by Auahi** [comment]
I'm talking about constitutional bills, this is inevitable especially in a new country where nothing like this has ever happened. There's ought to be much debate and discussion about law in the first few years of the country.

**Comment by terrorist96** [comment]
If a constitutional bill is passed -- noting how difficult it is to pass a constitutional bill --that repeals or modifies a part of the constitution, then it is probably for the best.

**Comment by Auahi** [comment]
Yes true but you too have mentioned that we should limit legislation, but with this we can safeguard certain rights from ever being repealed, for example if Liberland gained many sharia supporters and the cabinet tried to amend §V.36. you could instate sharia into Liberland. With a "superconsitution" you would need full support from everybody (Except for 5% of the citizenry) which is next to impossible to achieve. Constitutional bills will undoubtedly happen in the future, especially with it's relatively small initial population, but we can ensure that basic rights can never be tampered with.

**Comment by liberlandcitizen** [comment]
Those of you who say it will be hard to pass a constitutional bill...why do
you think it's hard? Do you think it's unlikely to get 75% of the
legislators and 66.6% of the population to vote for something popular? Or
is there another aspect to it that I'm missing?

**Comment by terrorist96** [comment]
Yes, it's hard to meet those thresholds. And if it's something so popular that those thresholds are met, then perhaps it's not a bad idea to implement that idea. 

How about a compromise: have the current requirements for passing a new amendment, but require the "superconstitution" threshold for altering or removing an existing provision. Though this may be hard to enforce.

**Comment by liberlandcitizen** [comment]
I hate to be so cynical about politics and government, but I don't think it
would be very difficult to get 15 people in office to do your bidding and
get a constitutional bill passed. And sadly public opinion and therefore
direct democracy can be bought/manipulated with money too if you have
enough of it in the bank. And don't get me started with mass media and its
ability to move the needle.

And even aside from any of the above, I fear any form of government where
the majority can take away the rights of the minority.

**Comment by KacperZajc** [comment]
The legal system is already complicated.
We will not be doubling the legal rules.
All parts of the Constitution require equal protection IMO.
The Constitution in general requires some minimal flexibility otherwise it will become a dead letter within years.
The requirements for amending the Constitution are very strict already.

**Comment by Auahi** [comment]
I don't think they're that strict, especially with the small citizenry Liberland will have. I think there will be a lot of small adjustments to most of the constitution, and I don't think these small changes will impact Liberty under most circumstances, but small changes to V.3 or II.24 could be monumental, this is why I believe certain things in the constitution are far more important than others. This could essentially allow the constitution to still be edited "easily" but only for non essential legislation.

**Comment by liberlandcitizen** [comment]
I agree that we don't need a super constitution/second constitution because
I also agree that the constitution is long and complicated at this point.

But, let allow me to also agree that the constitutional amendments are not
all that strict. We really should consider making it more difficult to
change the constitution.
