### ISSUE TITLE
undisclosed evidence

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#424]
V. 53 No Person shall be convicted of any criminal offence unless he or she has the opportunity to examine all evidence gathered against him or her, including any information which has been classified as a state secret should the Prosecution wish to rely on such evidence; in such cases the proceedings shall take place in camera and the Defendant shall take an oath of secrecy for the period relevant information remains classified as a state secret.

**Comment by terrorist96** [comment]
Integrate this with V.24 and change `rely on` to `utilize` (utilise for British English?). Otherwise, :+1:

**Comment by terrorist96** [comment]
@KacperZajc I just thought: what about the jury? And the judge? Shouldn't they be sworn to secrecy too?

**Comment by KacperZajc** [comment]
Arent a Judge and the Jury always forbidden to discuss past cases?

**Comment by terrorist96** [comment]
Idk about the judge, but a jury is free to do what they wish once the case is over. They are only restricted during the case.

**Comment by KacperZajc** [comment]
ok I changed it anyway
