### ISSUE TITLE
Will Liberland be a haven for counterfeiting?

### ISSUE THREAD

**Issue by Auahi** [liberland/constitution#425]
Does V.3 allow for counterfeiting? 
§V.3. No law shall regulate any printed materials, radio, television, the Internet or any other medium of exchange of information; no law shall regulate the rules concerning uploading, transmitting, displaying, accessing and/or publishing such information; nor shall any law introduce licensing and/or registration to infringe upon these rights; nothing in this provision shall prevent the Assembly from protecting the well-being of non-Individuals; publishing and/or sharing information classified as state secret or related to the work of Agents of Law Enforcement operating undercover pursuant to a Warrant shall be subject to control as described in this Constitution.

I might not be reading it right, but doesn't this allow for pirating information and counterfeiting?

**Comment by KacperZajc** [comment]
The question of intellectual property is open at this point.

But if necessary it might be covered by:

§I.23. No provision of this Constitution shall be construed as to provide any legal justification for any act or omission which does not stem from the inherent right of self-defence but amounts to any physical, or constitutionally recognised form of non-physical, violence towards any person or animal capable of conscious behaviour, or threat thereof, invasion of privacy, fraud or direct and grave interference with enjoyment of one’s property; nothing in such provision shall be deemed to prevent the Assembly from criminalising such conduct.

**Comment by terrorist96** [comment]
I don't see how I.23 applies here. Trademarks can be protected as a form of property. Copyright in general is a dangerous road to go down. 
I think Auahi is specifically referring to printing counterfeit currency, though I'd argue that that is covered under fraud.

**Comment by KacperZajc** [comment]
Printing counterfeit currency is covered under fraud under I.23.
Trademarks (which is a form of intellectual property) is covered by 'direct and grave interference with enjoyment of one’s property' under I.23.

**Comment by Auahi** [comment]
Okay makes more sense, thanks guys.
