### ISSUE TITLE
Problem with §I.21. - Territorial Defence

### ISSUE THREAD

**Issue by Auahi** [liberland/constitution#431]
§I.21. Should the Territorial Defence force rise, it may operate within the one kilometre radius from the borders of the Free Republic of Liberland upon the order of the Commander-in-Chief; the Territorial Defence force may also operate within the ten kilometre radius from the borders of the Free Republic of Liberland upon the order of the Commander-in-Chief and the express and informed consent of two-thirds of the overall number of Assembly Representatives; the Territorial Defence force shall not operate outside the ten kilometres radius from the borders of the Free Republic of Liberland in any event; nor shall the Territorial Defence force take part in any collective international military operation whatsoever.

Liberland should not even have a territorial defense. If a country wanted to invade Liberland they would camp out right outside the 10K zone and attack when they were ready. Also Liberland being a tiny country will never stand a chance against Serbia or Croatia, or any other country, I think a territorial force is a waste of money.

**Comment by terrorist96** [comment]
The TD isn't funded by anyone. It's a voluntary militia.

**Comment by KacperZajc** [comment]
TD is not designed to fight off Croatia or Serbia.
It is designed to defend Liberland from any irregular armed groups.
In hypothetical terms, if Liberland ever expands, then TD might become a more powerful force.
