### ISSUE TITLE
Reconstruction of the Bill of Rights

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#432]
It has been brought to my attention on several occasions that our Bill of Rights is extremely complicated and that it lacks transparency. For this reason we have already separated General Provisions from the Bill of Rights. However, I think it is not enough.

Here is what I think it should look like:

(No substantial changes in the contents, just merged some provisions and separated others, also some rephrasing).

Bill of Rights

The Bill of Rights shall constitute an integral part of the Constitution and shall be binding upon all branches of the Public Administration and its Members and Agents both within and outside the territory of the Free Republic of Liberland. It shall also be capable of creating criminal offences prosecuted before the Courts of the Free Republic of Liberland.

ARTICLE V: CIVIL RIGHTS

THE RIGHTS OF THE CITIZENRY SHALL BE SECURED

•	§V.1. Any Person who has fulfilled relevant requirements, as prescribed by law, shall be eligible to obtain citizenship of the Free Republic of Liberland; should a Person be born to parents of whom both are Citizen of the Free Republic of Liberland, he or she shall automatically be entitled to citizenship thereof; multiple citizenship shall be allowed; no Citizen shall be deprived of his or her citizenship unless by the Criminal Court upon conviction for a criminal offence and as a part of punishment as prescribed by law; no Person shall be rendered stateless in any event.
•	§V.2. All Citizens of the Free Republic of Liberland shall have the right of free-of-charge access to information which relates to any aspect of the functioning of the Public Administration which is not classified as a state secret and in so far as it does not contain any private personal information; information shall be classified as a state secret by a responsible Secretary of State with the express and informed consent of two-thirds of the overall number of Assembly Representatives as discussed in camera, and for the purposes of national security only, and for a period not exceeding one year. 
•	§V.3. All Individuals who hold citizenship of the Free Republic of Liberland shall have the right to private registration and confidential ballots in all elections and referendums in the Free Republic of Liberland; such registration shall be executed by entering one’s name into the Electoral Register; keeping one’s name in the Electoral Register may entail certain obligations as prescribed by law; taking part in all elections and referendums shall be voluntary; no Person shall be compelled to vote in a specific manner, nor shall any Person be reprimanded for the manner in which the vote was cast; all elections and referendums shall be valid only if free from any coercion and fraud.

ARTICLE VI: FREEDOM OF SPEECH

THE FREEDOM OF SPEECH AND EXPRESSION SHALL BE SECURED

•	§VI.1. No law shall regulate any printed materials, radio, television, the Internet or any other medium of exchange of information; no law shall regulate the rules concerning uploading, transmitting, displaying, accessing and/or publishing such information; nor shall any law introduce licensing and/or registration to infringe upon these rights; nothing in this provision shall prevent the Assembly from protecting the interests of Minors and/or those lacking mental capacity; publishing and/or sharing information classified as state secret or related to the work of Agents of Law Enforcement operating undercover pursuant to a Warrant shall be subject to control as described in this Constitution.
•	§VI.2. No law shall abridge the freedom of thought and expression thereof; no Person shall be convicted of any criminal offence for any statement of opinion, whether offensive or otherwise.
•	§VI.3. All Individuals shall have the right to assemble peaceably; no law shall interfere with any voluntary relations or cooperative ventures formed by Individuals; free expression shall be allowed in all public areas within the Free Republic of Liberland.
•	§VI.4. No law shall prohibit video and/or audio recording of any Agent of the Public Administration whilst on duty in public space and all other areas where there is no reasonable expectation of privacy.
•	§VI.5.  All affairs of the Assembly, other than the debate and vote on the classification of information as a state secret, and all proceedings of the Courts, other than those involving information classified as state secret and Warrants concerned with Agents of Law Enforcement operating undercover, shall be recorded and transmitted contemporaneously as well as archived and made available to the general public to attend; all Bills passed by the Assembly and all verdicts and decisions given by all Courts of the Free Republic of Liberland shall be archived and published.

ARTICLE VII: RIGHT TO PROPERTY

THE RIGHT TO PROPERTY AND FREEDOM OF CONTRACT SHALL BE SECURED

•	§VII.1. No form of taxation shall be introduced within the Free Republic of Liberland, nor shall any periodic fees, other than the Fee on land as provided in Land Acts, be imposed on any natural or legal Person for any reason; only spontaneous fees for services provided by the Public Administration and fines imposed as punishment for culpable behaviour shall be allowed; nor any form of duty on goods, services and/or capital exported from, or imported into, the Free Republic of Liberland shall be introduced.
•	§VII.2. No law shall interfere with the validity and/or content of any contract made exclusively between Individuals and/or legal Persons; nor shall any law mandate or forbid any Individual to enter into contractual relations with any other Individual and/or legal Person, or any body of the Public Administration, nor shall it provide any financial incentive in that respect; nothing in this provision shall prevent the Courts from modifying any contract in order to, and insofar as to, give effect to the provisions of this Constitution; nor shall the Assembly be prevented from establishing general rules governing the creation and interpretation of contracts.
•	§VII.3. No Person’s private property, be it movable or immovable, tangible or intangible, shall be confiscated, either fully or partially, for any purpose other than such restitution or compensation as may lawfully be due, lawfully levied fines, the Land Fee, satisfaction of pre-existing debt, the collection of evidence pursuant to a Warrant or in exigent circumstances to prevent the commission of a crime where, and only for so long as, there is insufficient time to obtain a Warrant; nothing in this provision shall prevent the Civil Court from issuing orders temporarily freezing a defendant’s assets where the Court is satisfied that there is a real risk that the defendant’s assets will be dissipated with the intention of frustrating satisfaction of any judgment that a Court may make.
•	§VII.4. No law shall regulate the use of private property; anything found in proximity under one’s land or growing naturally on it shall belong to the owner; nor shall any law protecting the environment restrict the use of one's land or natural resources found thereon unless such use would pollute the air or water beyond the boundaries of one's property.
•	§VII.5. No law shall abridge the right to issue and/or use any commodity or item as currency or provide any incentive in that respect unless any party to the transaction is legally prohibited from possessing such commodity or item; nothing in this provision shall prevent the Public Administration from issuing its own currency so long as all financial liabilities vis-a-vis the Public Administration may be satisfied in any other currency.
•	§VII.6. All Individuals shall have the right to exclude from their property any Person, including any Agent of Law Enforcement where acting without, or beyond the limits of, a Warrant; Persons in charge of any premises shall have the right to regulate the conduct of every Person on the property, other than Agents of Law Enforcement where acting pursuant to, and within the limits of, a Warrant.
•	§VII.7. All Persons shall have the right to fair compensation for any loss caused by any branch of the Public Administration acting pursuant to a provision of an Act which is subsequently declared unconstitutional by any Court of the Free Republic of Liberland within one year; any loss caused by any Agent of the Public Administration acting contrary to the law or the Constitution, or in error, shall be personally compensated by the Agent so acting; should said Agent not have the means to make such payment from her or his personal assets, the difference shall be met by the Public Administration, provided that the Agent shall remain liable to the Public Administration to repay such sums.
•	§VII.8. No relationship amounting to slavery or any other form of involuntary servitude shall exist between any legal or natural Person and any other Person; no conscription or any other form of compulsory service shall be introduced by any branch of the Public Administration; no Persons shall be convicted of any criminal offence for the failure to fulfil his or her contractual obligations.
•	§VII.9. No law shall retroactively change the legal consequences and/or status of actions that have been already committed, or relationships that already existed, before the enactment of said law.

ARTICLE VIII: RIGHT TO PRIVACY

THE RIGHT TO PRIVACY AND PERSONAL DEVELOPMENT SHALL BE SECURED

•	§VIII.1. All private personal data collected by the Public Administration shall be used only for the purposes for which they were collected, shall be kept confidential and shared only with the express and informed consent of the all Persons to whom it relates, unless sharing such information is necessary for the performance of duties provided for under this Constitution; all Individuals whose data are stored by any body of the Public Administration other than Law Enforcement shall be entitled to obtain a copy of such data and require that they be destroyed if the purposes for which they were collected no longer apply; nothing in this provision shall prevent the Public Administration from (a) maintaining a fully public register of land, its owners, and charges, (b) recording and publishing the affairs of the Assembly and the Courts of the Free Republic of Liberland as provided in the Constitution, (c) storing data of Agents and Members of the Public Administration and any other legal or natural Person contracting therewith, or (d) maintaining a register of all births and deaths of Citizens or other Residents of the Free Republic of Liberland.
•	§VIII.2. No Person shall have his or her privacy violated by freezing of assets, searches, seizures, surveillance, accessing and gathering of his or her private personal information without his or her express and informed consent, including obtaining it from third parties and/or using digital means, unless pursuant to a Warrant, and only to the extent which is necessary to achieve the purpose for which the Warrant was issued and particularly describing the assets to be frozen, the places or Persons to be searched, the things or Persons to be seized, the Persons to be put under surveillance, including the maximum period of that surveillance, and the data to be obtained and stored, including the period for which it may be retained; nothing in this provision shall prevent the collection of information which has been made available to the public or shared voluntarily.
•	§VIII.3. No Individual shall be required to register and/or share information about his or her whereabouts, be it permanent or temporary, assets, be it tangible or intangible, and/or signed contracts, be it employment, commercial or otherwise, unless pursuant to a Warrant; nor shall any Person be required to register and/or share information about any personal attributes such as medical conditions, fingerprints, DNA, religion, political affiliation or others unless pursuant to a Warrant; nothing in this provision shall prevent the Public Administration from maintaining a register of owners of land within the Free Republic of Liberland. 
•	§VIII.4. No law shall establish and/or regulate the institution of marriage between any Individuals; nor shall any law restrict an Individual’s testamentary freedom.
•	§VIII.5. All Individuals shall have the right to control their own bodies; no Individual shall be subjected to any medical treatment without his or her express and informed consent absent exigent circumstances where an Individual is incapable of consenting; should life-saving experimental treatment become available at the time a Person is incapable of giving his or her consent, the doctors shall be allowed to apply to the Civil Court for the permission to conduct such treatment.
•	§VIII.6. No law shall restrict the free movement of any Individual within the Free Republic of Liberland; all Individuals shall have the right to reside in any part of the Free Republic of Liberland.
•	§VIII.7. No law shall promote any religion; nor shall any law impose any religious beliefs on any Person; no law shall hinder practising of any religion on any premises which do not belong to any body of the Public Administration; no religious symbols shall be displayed on any premises belonging to any body of the Public Administration, nor shall any religious practice impeding the work of such body be allowed on such premises.
•	§VIII.8. No law shall promote any gender; nor shall any law distinguish between genders unless such distinction is necessary owing to physiological differences between the sexes; standards of all examinations conducted by any branch of the Public Administration prior to offering employment shall equally apply to all genders; all Persons shall be assigned their natural gender on birth; all Individuals shall have the right to change the gender assigned to them on birth without any excessive administrative burdens in a manner prescribed by law.
•	§VIII.9. No law regulating conduct of Persons other than Members and/or Agents of the Public Administration shall extend beyond the territory of the Free Republic of Liberland, including aircrafts and watercrafts registered in the Free Republic of Liberland; nothing in this provision shall prevent the Assembly from granting the Criminal Court jurisdiction over international crimes.
•	§VIII.10. No law shall impose any obligations as to pursuing and/or obtaining any stage of education by any Individual other than Agents and Members of the Public Administration; all Agents of the Public Administration shall be employed solely on the basis of their merit and successful completion of appropriate examination; no Member of the Public Administration shall employ or enable employment of any Agent who has not passed relevant tests.

ARTICLE IX: RIGHT TO FAIR TRIAL

THE RIGHTS OF THE ACCUSED AND DEFENDANTS SHALL BE SECURED

•	§IX.1. The powers of arrest in the Free Republic of Liberland shall lie with Agents of Law Enforcement, Citizens and other Residents of the Free Republic of Liberland and the Courts of the Free Republic of Liberland as described in this Constitution and any laws passed in accordance therewith; such powers shall not be exercised arbitrarily or without any evidence but only upon probable cause and where it is necessary for the protection of others or where an accused would otherwise be likely to escape justice or interfere with the investigation.
•	§IX.2. No Person shall be placed under arrest by any Agent of Law Enforcement for more than twenty-four hours without a Warrant; Agents of Law Enforcement executing arrests shall act openly and shall inform the detainee about the relevant rights he or she enjoys under this Constitution and any laws passed in accordance therewith; all arrests pursuant to a Warrant shall not be longer than necessary to bring the accused to trial; should the accused already be under arrest, he or she shall be able to address the Court at the hearing regarding the Warrant in question, either in person or by way of legal representation; where a Person is placed under arrest, Agents of Law Enforcement shall immediately inform his or her close ones as prescribed by law about the detention.
•	§IX.3. No Person shall be arrested by any Citizen or other Resident of the Free Republic of Liberland unless upon a justified suspicion that such Person has committed or is committing a criminal offence, as long as reasonably necessary to allow Agents of Law Enforcement to take custody of such person.
•	§IX.4. No Person shall be convicted of any criminal offence which has not been expressly created by an Act of the Assembly unless it flows from this Constitution as deemed by the Courts; all criminal offences created by Acts of the Assembly shall specify the maximum penalty they carry.
•	§IX.5. No law shall criminalise any act or omission which does not directly harm any other Person or cause unwarranted suffering to an animal capable of conscious behaviour; nor shall any law criminalise any act or omission which has been validly consented to by another Individual; no Individual shall be considered a victim of one’s actions or omissions; nothing in this provision shall prevent the Assembly from criminalising conduct interfering with the work of the criminal justice system, bribery, attempting, participating in or benefiting from committing a criminal offence.
•	§ IX.6. No Agent of the Public Administration shall operate undercover without a Warrant, and such Warrant shall specify the purposes for which it was issued; no Agent whilst executing a Warrant shall exceed the scope of the authority expressly granted therein, nor shall any Agent acting undercover use any method of entrapment to obtain evidence incriminating any Person; once the function for which the Warrant was issued has been carried into effect or abandoned, the Agent shall disclose to the Court issuing the Warrant a full report of all actions undertaken and evidence gathered whilst acting undercover; no evidence obtained pursuant to a Warrant permitting an Agent to act undercover shall be admissible against any Person unless the aforementioned report and all evidence is disclosed to that Person and to the Court.
•	§IX.7. All Persons held by any Agent or any body of the Public Administration against their will under any circumstances shall have the right to petition the Criminal Court for a writ of habeas corpus.
•	§IX.8. All Persons imprisoned pursuant to criminal proceedings or incarcerated following a conviction by a Court shall have the unconditional right to privately contact legal counsel; no Person shall be deprived of the right to communicate with relatives and such other Persons as may be prescribed by law both, either before or during the trial, in person and/or using indirect means of communication unless there be reasonable suspicion that so doing is likely to interfere with the course of justice and a Warrant preventing such communication on such grounds has been issued.
•	§IX.9. No evidence which has been obtained contrary to law or the Constitution shall be admitted in the Criminal Court, nor shall it constitute grounds for any Warrant, unless the violation was committed by a third party who did not act under the direction and/or supervision of any Agent or Member of the Public Administration or knowledge thereof; in any event, any Person responsible for acting contrary to the criminal law shall be liable to prosecution.
•	§IX.10. No Person shall be convicted of any criminal offence for, or have a civil claim brought against on the basis of, any act or omission which is alleged to have caused any form of non-physical bodily injury unless such an injury amounts to a recognised severe and prolonging mental illness.
•	§IX.11. No Person shall be convicted of any criminal offence by virtue of mere association with other Persons suspected or found guilty of the same or related offence; some form of active participation must be proven before the Court; nor shall any Person be convicted of any criminal offence for merely considering potential commitment of an offence; some form of active planning must be proven before the Court; no Person shall be convicted of any criminal offence which would not require any form of guilty mind as a mens rea.
•	§IX.12. All defendants in criminal proceedings shall have the right to a speedy trial; in any event, no Person shall be convicted of a criminal offence later than a year after a Warrant permitting the detention of such Person was executed in connection with that offence; should said Person escape or commit any subsequent criminal offence, a new Warrant for custody may be issued.
•	§IX.13. No Person shall be required to pay excessive bail and/or fines; nor shall the Criminal Court sentence a defendant who has been convicted of a criminal offence to prolonged incarceration should such offence alone have inflicted no harm on any Person.
•	§IX.14. No Person shall be convicted of any criminal offence if the only evidence incriminating the accused is testimony given by any number of Agents and/or Members of the Public Administration that is uncorroborated by any other physical and/or digital evidence, victim and/or third party witness testimony or voluntary confession; nothing in this provision shall prevent prosecution of any accused Person solely on the basis of testimony given by an Agent or Member of the Public Administration where he or she is the only victim of an alleged offence and the act or omission which gave rise to prosecution took place whilst not on duty.
•	§IX.15. No Person shall be convicted of more than one criminal offence created by an Act of the Assembly for one act or omission he or she is accused of; nor shall one be put twice in jeopardy of a penalty for the same offence unless by Private Prosecution where there is more than one Victim and joint proceedings were not brought.
•	§IX.16. All defendants in criminal proceedings shall have the right to attend Court proceedings, to be informed of criminal charges and of his or her rights, to compel witnesses to appear in Court for examination, and to examine all evidence gathered against him or her, including any information which has been classified as a state secret should the Prosecution wish to employ such evidence; in such cases, the proceedings shall take place in camera and all Persons involved shall take an oath of secrecy for the period the relevant information remains classified.
•	§IX.17. All defendants in criminal proceedings shall have the right to be presumed innocent until proven guilty and to not be compelled to be a witness against himself or herself, or such other Persons as may be prescribed by law, without any negative inference; the Prosecution shall always carry the legal burden of proof, discharged beyond reasonable doubt, in relation to the defendant's guilt, including disproving any defence envisaged by the law which he or she might raise; nothing in this provision shall prevent the creation of defences which require the defendant to discharge the evidential burden of proof by raising the issue of defence available to him or her.
•	§IX.18. All defendants in criminal proceedings, and all Persons under arrest, shall have the right to be assisted by effective legal counsel and an interpreter, should they not speak the language of interrogation or court proceedings, and in case of trial, to have reasonable time for the preparation of their case; services of a counsel and an interpreter shall be contracted personally or, should one not be able to afford it, they shall be provided by the Secretariat of the Judiciary with the possibility to subsequently recover reasonable expenses should a defendant be convicted and the verdict not be overturned by the Supreme Court.
•	§IX.19. No Person shall be convicted of any criminal offence for disclosure of any information classified as state secret should that piece of information prove or could be reasonably believed to prove that any Agent or Member of the Public Administration has breached, remains in breach of or intends to breach the law or the Constitution.
•	§IX.20. No torture or cruel or degrading treatment shall be inflicted by any Agent or Member of the Public Administration or under the supervision or knowledge thereof against any Person; nor shall any experiments, medical or otherwise, be conducted against any Person without his or her express and informed consent; no Individual shall be medically examined or otherwise tested unless pursuant to a Warrant or with the Individual's express and informed consent.
•	§IX.21. All Persons shall have the right to fair compensation for any and all days spent incarcerated from the twenty-fifth hour of detention onwards before, during and/or after the trial, should the case be dismissed or should said Person be found not guilty by the Jury or should a guilty verdict be overturned on the appeal; such compensation shall be paid by the Secretariat of the Judiciary.

ARTICLE X: RIGHT TO SELF-DEFENCE

THE RIGHT TO SELF-DEFENCE AND DEFENCE OF ONE’S RIGHTS AND PROPERTY SHALL BE SECURED

•	§X.1. All Persons shall have the right of self-defence and/or defence of their property and constitutional Rights, and others who are under a direct and real threat, against initiators of aggression, including any Agent of the Public Administration acting unlawfully or in error; no Person shall be convicted of any criminal offence for any act or omission which took place on his or her property and which is a direct response to another Person trespassing on that property and acting in breach of the law or the Constitution resulting in such threat as described in this provision.
•	§X.2. All Individuals shall have the right to own, manufacture, sell, transfer, transport, bear and use any small arms, as defined internationally, arms accessories or ammunition, be they historic, contemporary and/or experimental, regardless of condition; no form of licensing and/or registration shall be used to infringe upon these rights; the Person in charge of the premises shall determine whether arms may be carried on such premises except for Agents of Law Enforcement where acting pursuant to, and within the limits of, a Warrant.
•	§X.3. Law Enforcement shall not be in disposition of any weaponry other than small arms equal to ones permitted to be in disposition of Individuals; should the voluntary Territorial Defence force be constituted, it shall not be in disposition of any weaponry other than small arms and light weapons, as defined internationally.

ARTICLE XI: INTERESTS OF VULNERABLE PERSONS

THE INTERESTS OF MINORS AND PERSONS LACKING MENTAL CAPACITY SHALL BE SECURED 

•	§XI.1. No Person shall be declared to be lacking mental capacity unless by an order issued by the Civil Court under relevant laws passed by the Assembly; all Persons declared to be lacking mental capacity shall be appointed a Guardian by the Court; any order declaring a Person to be lacking mental capacity shall automatically expire within three years; after the expiration such Person shall be deemed to have regained metal capacity unless the Court renews its order; the relevance of any order in such matter may be challenged by the Person concerned or his or her Guardian once in every six months before it expires.
•	§XI.2. No Minors or those who lack mental capacity shall be subjected to any form of treatment without either the express and informed consent of their Guardian or with their own consent where allowed by law unless under exigent circumstances where neither the Guardian nor the patient is capable of consenting; a Guardian's decision shall be capable of being overridden by an order of the Civil Court where it is proved to the satisfaction of the Civil Court that the decision in question is not in the best interest of the patient and the treatment is essential for his or her life or designed to prevent any serious permanent injury; nor shall Minors and those who lack mental capacity be subjected to any permanent and/or harmful treatment which is not medically necessary.
•	§XI.3. No Person shall have his or her child taken into care, nor shall his or her custody rights be restricted in relation to the child, unless pursuant to an order of the Civil Court on application of the appropriate body of the Public Administration supported by clear and convincing evidence of serious physical or psychological abuse of the child; nothing in this provision shall prevent the Court from issuing orders regulating custody rights upon request of one of the parents upon separation in accordance with the law.

**Comment by Auahi** [comment]
I skimmed it and from what it looks like I think it's great, I highly prefer this version.

**Comment by terrorist96** [comment]
I haven't looked at this in detail yet either, but I fully support breaking it into different categories.

**Comment by terrorist96** [comment]
So let's get into the details, shall we?

> nothing in this provision shall prevent the Assembly from protecting the interests of Minors and/or lacking mental capacity

Keeping it as non-Individuals would seem to be easier, to me. Otherwise,  you need to add `those` prior to `lacking`.

> other than proceedings concerned with Publication Orders
vs
other than those involving information classified as state secret

Seems to me keeping it as is would be easier, since Publication Orders are already defined elsewhere.

> • §IX.16. All defendants in criminal proceedings shall have the right to attend Court proceedings, to be informed of criminal charges and of his or her rights, to compel witnesses to appear in Court for examination, and to examine all evidence gathered against him or her, including any information which has been classified as a state secret should the Prosecution wish to employ such evidence; in such cases**,** the proceedings shall take place in camera and all Persons involved shall take an oath of secrecy for the period the relevant information remains classified.

Added comma after `cases`.

> No law shall interfere with the validity and/or content of any contract made exclusively between Individuals and/or legal Persons **for the purposes which are not unconstitutional**

Removing the bolded part will again introduce the issue of rights deprivation by corporations as opposed to by government.

> Persons in charge of any premises shall have the right to regulate the conduct of every Person on the property **within the realms of the Constitution**

Removed part in bold. Same reasoning.

> no law shall interfere with any voluntary relations or cooperative ventures formed by Individuals **for purposes which are not unconstitutional**

Same thing.

> nothing in this provision shall prevent the Public Administration from issuing its own currency so long as all financial liabilities vis-a-vis the Public Administration may be satisfied in any other currencies.

I'm realizing that this could be an issue. What if someone wishes to pay a debt they owe to the government with a [bizarre](https://www.youtube.com/watch?v=joATmqzZ4As) currency? 

> §VI.2. No law shall abridge the freedom of thought and expression thereof

Random thought: under what authority can the government outlaw people having sex in public? We can agree that public fornication shouldn't be allowed, but is it violating anyone's rights?

> • §VII.9. No law shall retroactively change the legal consequences and/or status of actions that have been already committed, or relationships that already existed, before the enactment of ~~that~~ **said** law.

Why remove:
> §V.1. All statements and declarations made by any Individual to any body of the Public Administration shall be presumed to be truthful and made in good faith unless there is evidence to the contrary.
§V.10. No Individual shall be compelled to identify himself or herself to any Agent of the Public Administration, unless upon arrest or pursuant to a Warrant;

?

**Comment by KacperZajc** [comment]
Adding 'those' (sounds more formal to me)

'other than those involving information classified as state secret' because as we discussed in #424 there might be state secret in proceedings other than those concerned with Publication Orders.

'purposes which are not unconstitutional' / 'within the realms of the Constitution' - I realised it is redundant because we expressly provide that all contracts and all Persons within the jurisdiction of FRL must comply with the Constitution

The right to assembly pertains to individuals only because non-individuals might be locked up in prison or under supervision of a Guardian etc. so they might be prevented from assembling.

Yeah I was addressing the issue of some bizarre or obscure currency there.

Sex in public place is 'peaceful co-existence of Persons' which is one of the areas of competence of the Assembly.

'no law shall hinder practising of any religion on any premises which do not belong to any body of the Public Administration' - so on premises belonging to the PA, practice of religion might be regulated, on private premises it cannot be regulated, on public premises such as parks, depends who is the legal owner.

§V.1. All statements and declarations made by any Individual to any body of the Public Administration shall be presumed to be truthful and made in good faith unless there is evidence to the contrary. - I already mentioned wanted to remove this part because it might have unintended consequences.

§V.10. No Individual shall be compelled to identify himself or herself to any Agent of the Public Administration, unless upon arrest or pursuant to a Warrant; - I realised it would be impossible to maintain general order on the street with this provision, plus it would be impossible to ascertain who is an individual with certainty just by looking at him/her. It creates all sorts of problems.

**Comment by terrorist96** [comment]
> nothing in this provision shall prevent the Public Administration from issuing its own currency so long as all financial liabilities vis-a-vis the Public Administration may be satisfied in any other currencies.

It should be `currency` (singular, not plural). 

> Sex in public place is 'peaceful co-existence of Persons' which is one of the areas of competence of the Assembly.

Yes, but we also say no laws can criminalize victimless acts.

> on public premises such as parks, depends who is the legal owner.

Wouldn't it be the state? If a private person owns it, then it's not a public park, by definition.

> §V.1. All statements and declarations made by any Individual to any body of the Public Administration shall be presumed to be truthful and made in good faith unless there is evidence to the contrary. - I already mentioned wanted to remove this part because it might have unintended consequences.

Can you give me an example of an unintended consequence that could arise from this?

> §V.10. No Individual shall be compelled to identify himself or herself to any Agent of the Public Administration, unless upon arrest or pursuant to a Warrant; - I realised it would be impossible to maintain general order on the street with this provision, plus it would be impossible to ascertain who is an individual with certainty just by looking at him/her. It creates all sorts of problems.

I'm gonna have to disagree with this. If someone is not under arrest, they have no duty to identify themselves. Removing this allows for police to harass people for doing nothing illegal, such as carrying a weapon openly. Please consider retaining this provision.

**Comment by KacperZajc** [comment]
a ticket for public sex would not fall under the category of criminal offence

public parks - so I guess restrictions on religious practice would be allowed in a public park, this makes sense IMO

V.1 - e.g. no possibility to verify one's alibi, nationality etc.

V.10 - what about immigration issues? you wouldn't be able to verify whether someone has legal basis to stay in the FLR; you wouldn't be able to give some a ticket for littering etc. this is too restrictive

**Comment by Auahi** [comment]
I think we should model nudity and public sex laws to that of Spain, you take a meh approach. Why can't one practise their religion in a public park, isn't that a violation of free speech?

**Comment by KacperZajc** [comment]
I am not saying there is a ban on religious practice, Im saying it might be potentially restricted if it interferes with rights and duties of other people.

**Comment by Auahi** [comment]
Well yes I agree that any religious practise which restricts the rights of others shouldn't be allowed. I thought you meant all religious practices in general. I'm on my phone right now so I only saw that one post.

**Comment by KacperZajc** [comment]
There will be no unrestricted flow of people across the border. I am sure about that although it is not my decision.

I said 'religious practice which interferes with rights and duties of others'. 
No one is restricting religious practice altogether. 

V.1: what if a person says he has the right to be somewhere or do sth? this provision would preclude mere fact-checking.

V.10: it is unworkable because there will be too many exceptions to this rule: tickets, court orders, immigration enforcement, mere inquiry into a potential incident on the street - you would have to arrest a person before you could inquire into what happened and who is responsible.

**Comment by terrorist96** [comment]
> There will be no unrestricted flow of people across the border. I am sure about that although it is not my decision.

So we secure the border. It's a small enough country so it shouldn't be hard. Then there's no opportunity for someone to sneak in. Allowing for this would open the doors to racial profiling by police. That's not freedom.

> I said 'religious practice which interferes with rights and duties of others'. 
No one is restricting religious practice altogether.

So then we should protect religion on public property as long as it doesn't interfere with others.

> V.1: what if a person says he has the right to be somewhere or do sth? this provision would preclude mere fact-checking.

Ok, I'll concede on this, for now. :stuck_out_tongue_closed_eyes: 

> V.10: it is unworkable because there will be too many exceptions to this rule: tickets, court orders, immigration enforcement, mere inquiry into a potential incident on the street - you would have to arrest a person before you could inquire into what happened and who is responsible.

I won't concede this though. Unless you're suspected of breaking the law, then you shouldn't be required to even talk to the police. Tickets, court orders, immigration enforcement all fall under breaking the law. Sure, if there was an incident, and you were a witness, you can freely decide to provide the police with information, but you're under no legal obligation to do so. The right to be left alone deserves the highest protection. Plus, there's the no self-incrimination right. So if police want to interrogate someone, yes, they will have to arrest them first. And you can't be arrested unless you're suspected of committing a crime.

**Comment by terrorist96** [comment]
I'll also add that not being required to ID yourself is already in practice in America, with the exception of arrest/being issued a citation, or if you're operating a motor vehicle. Unless the police suspect you of a crime, you're not required to ID.

**Comment by terrorist96** [comment]
> "Stop and identify" statutes are statutory laws in the United States that authorize police[1] to legally obtain the identification of someone whom they reasonably suspect has committed a crime. If the person is not reasonably suspected of committing a crime, they are not required to provide identification, even in states with stop and identify statutes.

https://en.wikipedia.org/wiki/Stop_and_identify_statutes

**Comment by KacperZajc** [comment]
Actually since we provide the right to compel witness to appear in court, there is an obligation to be a witness. But OK let's work on a more comprehensive provision with possible exception. I propose you open a separate Issue with suggested wording and we start from there.

Same goes for the religious freedom. I will open an Issue where we will clarify the possible restriction. This will not be difficult.

**Comment by terrorist96** [comment]
> Actually since we provide the right to compel witness to appear in court, there is an obligation to be a witness. But OK let's work on a more comprehensive provision with possible exception. I propose you open a separate Issue with suggested wording and we start from there.

Yes, only if you are legally subpoenaed though. You can't force someone on the street to talk to you though.
