### ISSUE TITLE
General Provisions

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#433]
A bit of rephrasing of some provisions, no substantial changes:

Article I: General Provisions
The General Provisions shall establish general rules governing the law of the Free Republic of Liberland and shall be taken into account when interpreting the other Parts of the Constitution.

•	§I.1. The Constitution of the Free Republic of Liberland shall be the supreme law of the Free Republic of Liberland and, as such, shall be directly enforceable before all Courts of the Free Republic of Liberland; all forms of law and all contracts between any legal and/or natural Persons, including all branches of the Public Administration, made under the jurisdiction of the Free Republic of Liberland, shall comply with the Constitution.
•	§I.2. The Free Republic of Liberland shall be governed by the Public Administration and no concurrent or otherwise form of government shall be established; no special branch of the Public Administration which is not provided for in the Constitution shall come into existence; no municipal or district governing body shall be established unless for a new territory upon its incorporation to the Free Republic of Liberland. 
•	§I.3. Should the Public Administration abandon the Constitution and assume a despotic form of governance, and should no mechanism for peaceful transformation be available, the Citizens of the Free Republic of Liberland shall have the right and duty to abolish such government and restore the legal order envisaged by this Constitution.
•	§I.4. The Powers of the Public Administration shall be derived solely from the provisions of this Constitution and neither the Public Administration, nor any Agent or Member thereof, shall possess any inherent authority; the Public Administration shall neither have nor exercise any power other than those expressly conferred upon it by this Constitution.
•	§I.5. All Persons within the jurisdiction of the Free Republic of Liberland shall be bound to observe the Constitution; all bodies of the Public Administration, its Members and Agents, shall act within the realms of the Constitution and all laws passed in accordance therewith.
•	§I.6. No provision of this Constitution shall be construed as to provide any legal justification for any act or omission which does not stem from the inherent right of self-defence but amounts to any physical, or constitutionally recognised form of non-physical, violence towards any person or animal capable of conscious behaviour, or threat thereof, invasion of privacy, fraud or direct and grave interference with enjoyment of one’s property; nothing in such provision shall be deemed to prevent the Assembly from criminalising such conduct.
•	§I.7. The enumeration of certain rights in this Constitution shall not be construed as to deny or disparage others retained by the Citizens and other Residents of the Free Republic of Liberland.
•	§I.8. No Person shall be excluded from the operation of, or granted any privilege under, any law; nor shall any Person be treated differently by law due to his or her origins, religious beliefs, sexual orientation, gender and/or cultural background; nothing in this provision shall prevent the Members of the Public Administration from enjoying certain immunities as described in this Constitution and no others; nor shall the Assembly be prevented from granting certain immunities related to legal personality, bankruptcy and vicarious liability. 
•	§I.9. All Members and Agents of the Public Administration intentionally acting in breach of the law relevant to the position held or the Constitution shall be criminally liable for their actions and, upon conviction, shall be removed from the office and shall never hold any public office again; acting pursuant to an Act which has been approved as prima facie constitutional by the Supreme Court shall not be deemed as acting unconstitutionally regardless of any future declaration of any Court as to the Act's true constitutionality; introducing, lobbying and voting for a Bill which is declared unconstitutional shall not be deemed as acting unconstitutionally.
•	§I.10. All administrative decisions of any branch of the Public Administration and actions undertaken by its Agents capable of affecting any Person and all Executive Measures issued by the Cabinet, may be subject to challenge in the Civil Court by a Person affected thereby or, in the absence of any Person specifically affected, by any association composed of no fewer than 30 Citizens; the right shall be exercisable once all administrative appeals have been exhausted; without prejudice to the appeal procedures, such challenge shall be admissible once only unless the original challenge was not genuine but brought in order to shield the defendant from liability or where a new challenge raises a different point of law.
•	§I.11. No branch of the Public Administration, nor any number of Citizens or other Residents of the Free Republic of Liberland, shall propose and/or consent to the incorporation of the Free Republic of Liberland, or any part thereof, to any other jurisdiction; a majority of two-thirds of the overall number of Assembly Representatives may assent to the incorporation of any new territory to the Free Republic of Liberland upon the request of its people or government with any status the Assembly may determine.
•	§I.12. No branch of the Public Administration shall introduce any state of emergency or war, or any other special state in which one or more of the Rights guaranteed by this Constitution would be diminished or suspended or revoked; any purported such introduction shall be a nullity and of no effect.
•	§I.13. No branch of the Public Administration shall take a loan, be it foreign or domestic, short or long term, special or commercial; no government bond shall be issued; no debt shall be incurred by any branch of the Public Administration for any purpose; only voluntary donations with no expectation of repayment or quid pro quo shall be allowed.
•	§I.14. No branch of the Public Administration shall contract with any legal and/or natural Person, state or entity for the purposes of acquiring data it itself is not entitled to acquire under this Constitution or any laws passed in accordance therewith; nor shall any branch of the Public Administration be allowed to procure any legal and/or natural person to commit what it itself is not entitled to commit under this Constitution or any laws passed in accordance therewith.
•	§I.15. No branch of the Public Administration shall give any form of foreign aid to any state or entity, whether directly or via any international institution, be it a non-repayable grant, loan or any other financial support; nothing in this provision shall prevent the Public Administration from meeting its financial liabilities flowing from the membership in any intergovernmental organisation.
•	§I.16. No branch of the Public Administration shall establish any standing army; nor shall it declare war and/or carry out military activities other than in defence of the border of the Free Republic of Liberland in reaction to an act of armed aggression against the Free Republic of Liberland which has already taken place or is imminent; nor shall any branch of the Public Administration invite any armed forces of any other state or organisation into the jurisdiction of the Free Republic of Liberland except for a reasonable number of security personnel accompanying a foreign diplomat.
•	§I.17. All candidates for any public office in the Free Republic of Liberland as well as all current Members of the Public Administration shall be under obligation to disclose their assets above certain value as prescribed by law, sources of income over certain proportion of his or her overall yearly income as prescribed by law and benefaction, both current and of the past five years, as prescribed by law, to the public; should a candidacy be submitted by any such organisation as may be prescribed by law, such organisation shall be under equal obligation of disclosure.
•	§I.18. All Members and Agents of the Public Administration shall take the Oath of Office prior to holding office; the Oath of Office shall include the pledge of allegiance to the state of the Free Republic of Liberland, obligation to uphold and abide by the Constitution of the Free Republic of Liberland, and to perform one’s duties in a manner consistent with the liberty of others as far as possible.
•	§I.19. No provision of the Annual Budget shall finance or partially finance any private organisation, insurance, healthcare services, education and/or pension schemes; no provision of the Annual Budget shall transfer any assets, be it in the form of a loan, non-repayable grant or periodic payments, to any legal and/or natural Person unless as remuneration for contracted goods and/or services necessary for the functioning of the Public Administration as envisaged in the Constitution.
•	§I.20. The validity of any election or referendum held within the Free Republic of Liberland shall be reviewed by the Supreme Court upon the request of one-quarter of the overall number of Assembly Representatives or 3% of the overall number of Citizens registered to vote at the time of the last General Election submitted within seven days after the publication of the results; should the Supreme Court find any evidence of erroneous and/or fraudulent conduct, it shall have the power to declare such election or referendum invalid and order it anew.
•	§I.21. Any ambiguity in this Constitution or any laws passed in accordance therewith shall be resolved so as to give the greatest liberty from restraint imposed by law or this Constitution on any Person's conduct; and so as to provide for the least extensive power for any branch of the Public Administration, their Members and Agents, consistent with the clear meaning of the provision in question; whenever in this Constitution words appear in the singular, such words shall be taken to include the plural and words in the plural to include the singular; should any ambiguity arise as to the manner in which any procedure envisaged by this Constitution is to be carried into effect, it shall be specified by law.
•	§I.22. For the purposes of this Constitution, the term “Person” shall signify any human being whatsoever; the term “Individual” shall signify a Person of age who does not lack mental capacity and is not incarcerated before, during or after a trial; the term “Agent of the Public Administration” shall signify any Person working for any body of the Public Administration, including the Law Enforcement; the term “Member of the Public Administration” shall signify any Person who is holding a public office of one of the branches of the Public Administration; the term “Agent of the Law Enforcement” shall signify any Person working for, or acting pursuant to a Warrant made public by, Law Enforcement or the Office of the Public Prosecutor; the term “Citizen” shall signify any Person holding citizenship of the Free Republic of Liberland; the term “Resident” shall signify any Person within the jurisdiction of the Free Republic of Liberland who is not a Citizen; the term "law" shall signify any Act passed by the Assembly in accordance with Article II and any Executive Measures as issued by the Cabinet in accordance with Article III.

To Civil Rights Article in the Bill of Rights:

§X.XX. Only Individuals above the age of twenty-one who hold citizenship of the Free Republic of Liberland shall have the right to submit his or her candidacy for a public office unless he or she has been convicted of a breach of law or the Constitution related to his or her previous position.

To Fair Trial Article in the Bill of Rights:

§X.XX. All Warrants for the purposes of criminal proceedings, other than the Supreme Warrant, shall be issued by a Judge of the Criminal Court upon request by an Agent of Law Enforcement and shall be supported by evidence of probable cause; such Warrants shall be as detailed as possible and shall refer to one Person only; every Warrant granted for a continuous action shall expire no later than after one year and shall be renewed by another Judge in accordance with ordinary procedure.

To Self-Defence Article in the Bill of Rights:

§X.XX. Voluntary Territorial Defence force may rise as a private initiative of the Citizens of the Free Republic of Liberland, such Territorial Defence shall have the Chancellor as its Commander-in-Chief; the Commander-in-Chief shall not have the power to unilaterally call or disband the Territorial Defence force in any event; the Territorial Defence force shall be used only to defend the borders of the Free Republic of Liberland against external enemies; under no circumstances shall it be used instead of, or in support of, Law Enforcement against Citizens and other Residents of the Free Republic of Liberland.

§X.XX. Should the Territorial Defence force rise, it may operate within the one kilometre radius from the borders of the Free Republic of Liberland upon the order of the Commander-in-Chief; the Territorial Defence force may also operate within the ten kilometre radius from the borders of the Free Republic of Liberland upon the order of the Commander-in-Chief and the express and informed consent of two-thirds of the overall number of Assembly Representatives; the Territorial Defence force shall not operate outside the ten kilometres radius from the borders of the Free Republic of Liberland in any event; nor shall the Territorial Defence force take part in any collective international military operation whatsoever.

**Comment by terrorist96** [comment]
> • §I.1. The Constitution of the Free Republic of Liberland shall be the supreme law of the Free Republic of Liberland and**,** as such**,** shall be directly enforceable before all Courts of the Free Republic of Liberland; all forms of law and all contracts between any legal and/or natural Persons, including all branches of the Public Administration, made under the jurisdiction of the Free Republic of Liberland, shall comply with the Constitution.

"encommafied" `as such`.

> this Constitution, Acts passed in accordance therewith and Executive Measures issued under powers delegated to the Cabinet by relevant Acts shall be the only instruments capable of binding the public at large.	

You don't think this is worth preserving?

> nor shall any Person be treated differently by law due to his or her origins, religious beliefs, sexual orientation, gender, cultural background **and/or any other personal attribute**

The bolded part is removed. Why?

> §X.XX. All Individuals above the age of twenty-one who hold citizenship of the Free Republic of Liberland shall have the right to submit his or her candidacy for a public office unless he or she has been convicted of a breach of law or the Constitution related to his or her previous position.

Not that I don't appreciate the simplification of this provision, but the previous version was a requirement that all members of the PA be 21+ and citizens, but this new version says that anyone who is 21+ and a citizen can run for public office. The old version restricted who was allowed, the new version only guarantees the right of those to apply. See the distinction? Basically, the new version doesn't forbid a 20 year old noncitizen from running for office.

**Comment by KacperZajc** [comment]
§I.1. ????

'instruments capable of binding the public at large' - I think this is misleading, judgements can also bind the public but they also might not; some acts of the cabinet can bind the public, some might not. I think with our definition of law in the General Provisions, this part is unnecessary. 

and/or any other personal attribute - this is too broad, e.g. skills are personal attribute right? but we allow selection based on skills, same goes for e.g. unprofessional appearance on certain positions etc.

§X.XX. All Individuals above the age of twenty-one who hold citizenship of the Free Republic of Liberland shall have the right to submit his or her candidacy for a public office unless he or she has been convicted of a breach of law or the Constitution related to his or her previous position; no one who fails to fulfil the criteria laid down in this provision shall become a Member of the Public Administration.

???

**Comment by terrorist96** [comment]
> §I.1. ????

I put commas around `as such` lol

> and/or any other personal attribute - this is too broad, e.g. skills are personal attribute right? but we allow selection based on skills, same goes for e.g. unprofessional appearance on certain positions etc.

I understand your concern. How about we amend it to say `and/or any other personal attribute that may be specified by law.`? It keeps the door open for protecting other personal attributes without the broad implications of the general term.

> §X.XX. All Individuals above the age of twenty-one who hold citizenship of the Free Republic of Liberland shall have the right to submit his or her candidacy for a public office unless he or she has been convicted of a breach of law or the Constitution related to his or her previous position; no one who fails to fulfil the criteria laid down in this provision shall become a Member of the Public Administration.

I think replacing `All` with `Only` fixes the issue without the need for last clause you added.

**Comment by KacperZajc** [comment]
attribute: that would make it meaningless because it would say that no persons will be treated differently by the law unless the law says so 

you are right with 'only' instead of 'all'

**Comment by terrorist96** [comment]
How about `inherent personal attribute`? The problem is that we can't foresee all instances. For example, a disabled person wouldn't be protected with your current wording. Adding `disability` to the section would fix it, but what about another attribute that we can't think of right now?

**Comment by KacperZajc** [comment]
yes that is a problem but interpretation of any such term as 'inherent' will be a nightmare
not even sure disability is inherent, it might be acquired upon birth or later in life and in some cases it might be even overcome, is that 'inherent'?

**Comment by terrorist96** [comment]
Let's back up. Isn't gender discrimination already covered by this provision:

> §V.38. No law shall promote any gender; nor shall any law distinguish between genders unless such distinction is necessary owing to physiological differences between the sexes; standards of all examinations conducted by any branch of the Public Administration prior to offering employment shall equally apply to all genders; all Persons shall be assigned their natural gender on birth; all Individuals shall have the right to change the gender assigned to them on birth without any excessive administrative burdens in a manner prescribed by law.

How about this:

No Person shall be excluded from the operation of, or granted any privilege under, any law; nor shall any Person be **denied equal protection under the law.** ~~treated differently by law due to his or her origins, religious beliefs, sexual orientation, gender and/or cultural background~~

This borrows directly from the [14th amendment](https://en.wikipedia.org/wiki/Fourteenth_Amendment_to_the_United_States_Constitution).

**Comment by KacperZajc** [comment]
I like it, it's simple.
I feel like we should add: 'equal shall not be construed to encompass equivalent'

**Comment by terrorist96** [comment]
> equal shall not be construed to encompass equivalent

What would that achieve/prevent?

**Comment by KacperZajc** [comment]
equivalent treatment is not the same as equal
I dont know yet but I have a feeling it has sth to do with Brown v Board of Education 
It's still not clear in my head xd

**Comment by terrorist96** [comment]
Separate by equal is inherently unequal? lol

**Comment by KacperZajc** [comment]
Im changing it to 'equal protection' for now :)
