### ISSUE TITLE
Regarding II.12(2)

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#434]
This was added recently:
> **§II.12(2)** Should any provision of any Act of the Assembly be struck down by the Supreme Court following the declaration of constitutionality, the Cabinet shall have the power to initiate a legislative procedure to address the legal vacum **[sic]** which might have been created by the verdict of the Supreme Court within 60 days.

Other than the typo, what if there is a provision in the bill that declares its [severability](https://en.wikipedia.org/wiki/Severability)? It is common practice nowadays for legislators to include a section saying that if any part of the bill is found unconstitutional, the remainder would remain in force.

**Comment by KacperZajc** [comment]
It's fine, there is no obligation to submit a new Bill. Just a possibility if the Cabinet so wishes. This provision provides an extra window of opportunity to initiate a legislative procedure so that the Cabinet does not have to wait until the next State of the Republic Address.

**Comment by KacperZajc** [comment]
typo fixed
