### ISSUE TITLE
Restriction of liberty provision

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#436]
We need to add the possibility to restrict liberty in connection with deportation proceedings and mental health problems:

§IV.18.** No Person shall have his or her physical liberty restricted unless pursuant to a decision of the Courts of the Free Republic of Liberland in the following circumstances:
§IV.18(1)** Upon a conviction in the Criminal Court by the Jury;
§IV.18(2)** Upon an order of the Civil Court committing a Person lacking mental capacity to a mental health institution;
§IV.18(3)** Upon an order of the Civil Court committing a Minor to an in-house care;
§IV.18(4)** Upon a decision of any Court to commit any Person to prison for no more than seven days for a contempt of court committed either by disruption of judicial proceedings or by disobeying a Court order.
§IV.18(5)** Should such Person disobey the same order of a Court more than once, he or she shall be tried in a regular manner for a criminal offence as regulated by law and not limited to a seven-day imprisonment.
§IV.18(6)** Nothing in this provision shall affect the powers of arrest, pre-deportation detention and sequestration of Jurors as enumerated in this Constitution.

We also add this provision to that Right to Liberty Article within the Bill of Rights:

§X.??. Any Resident of the Free Republic of Liberland without a valid leave to remain shall be subject to deportation; no Resident subject to deportation shall be detained for more than 7 days unless a Warrant for further detention is obtained; such Warrant shall be issued only where necessary due to the complexity of the deportation proceedings; in any event no Resident subject to deportation shall be detained for more than 180 days.

And amend this provision (without transferring it anywhere):

§XI.1. No Person shall be declared to be lacking mental capacity unless by an order issued by the Civil Court under relevant laws passed by the Assembly; all Persons declared to be lacking mental capacity shall be appointed a Guardian by the Court and, should they pose a threat to themselves or others, may be committed to a mental health institution pursuant to a Court order; any order declaring a Person to be lacking mental capacity shall automatically expire within three years; after the expiration such Person shall be deemed to have regained mental capacity unless the Court renews its order; the relevance of any order in such matter may be challenged by the Person concerned or his or her Guardian once in every six months before it expires.

**Comment by terrorist96** [comment]
> §IV.18.** No Person shall have his or her physical liberty restricted ~~otherwise than~~ **unless** pursuant to a decision of the Courts of the Free Republic of Liberland in the following circumstances:
§IV.18(1)** Upon ~~a~~ conviction in the Criminal Court by the Jury;

> §X.??. Any Resident of the Free Republic of Liberland without a valid leave to remain shall be subject to deportation; no Resident subject to deportation shall be detained for more than 7 days unless a Warrant for further detention is obtained; such Warrant shall be issued only where necessary due to the complexity of the deportation proceedings; in any event no Resident subject to deportation shall be detained for more than 30 days.

So what would happen after 30 days if the case isn't settled? They get set free?

> §XI.1. ...and, should they pose a threat to themselves or others, ~~might~~ **may** be committed to a mental health institution pursuant to a Court order; any order declaring a Person to be lacking mental capacity shall automatically expire within three years; after the expiration such Person shall be deemed to have regained ~~metal~~ **mental** capacity unless the Court renews its order; the relevance of any order in such matter may be challenged by the Person concerned or his or her Guardian once in every six months before it expires.

**Comment by KacperZajc** [comment]
I guess they would have to be released on parole. 
Maybe we should extend this period?
Not sure how long complicated deportation proceedings might be.
Should we make it up to 90 days?

**Comment by terrorist96** [comment]
There shouldn't be a time limit. They're already confirmed to be present in the country illegally. You'd just lose track of them if you release them.

**Comment by KacperZajc** [comment]
wow didnt expect you to propose more restrictive measures
but wouldn't that amount to indefinite detention?
I feel like some time limit must be set.

**Comment by terrorist96** [comment]
The way we preserve liberty is by protecting the liberty of the law abiding, and punishing the law breakers. Though I'm more in favor of open borders, if we're gonna have closed borders, might as well do it right.
If the time becomes too long, the detainee can always submit a petition for habeas corpus.

**Comment by KacperZajc** [comment]
yeah but habeas corpus does not confer any right on you 
it is merely a procedural safeguard
unless we provide a substantive right here (like restriction on detention), habeas corpus will not help

**Comment by terrorist96** [comment]
I understand your concern, but we can't just let them go loose either.

**Comment by KacperZajc** [comment]
ok let's get rid of the limitation for now but we need to find a better solution
