### ISSUE TITLE
Supreme Court bench and appeals

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#437]
What is your opinion on the short / full bench mode of case-hearing by the Supreme Court?
Should we provide for full bench at all times?

Also, should we provide for a compulsory appellate jurisdiction of the Supreme Court rather than to require a permission at a Preliminary Hearing?

The advantage would be to simplify the procedure.

What is equally important, we don't have any Court of Appeal so maybe there should be a compulsory appellate jurisdiction of the Supreme Court?

**Comment by terrorist96** [comment]
I'm in favor of full bench of the Supreme Court at all times.
And yes, an intermediary appeals court would be nice. The supreme court can't hear all cases, so without an appeals court, the judge at the lower court gets the final say, which would be suboptimal.

**Comment by KacperZajc** [comment]
done

**Comment by KacperZajc** [comment]
done
