### ISSUE TITLE
replacement of Supreme Court Justices

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#438]
§IV.9(9) Should any Justice or the Chief Justice of the Supreme Court have any personal interest in a case before the Court, he or she shall recuse him or herself from the proceedings and the Chancellor shall nominate a Judge of the Civil Court or the Criminal Court to fulfil the functions of the recused Justice or the Chief Justice of the Supreme Court for the time of the proceedings in question.

I think we should provide for automatic temporary replacement of the most senior Judge of the Civil or Criminal Court instead of Chancellor's nominee. After all it is likely that the Cabinet will have an interest in the outcome of the proceedings so they should not have a say on the composition of the bench. 

§IV.9(9) Should any Justice or the Chief Justice of the Supreme Court have any personal interest in a case before the Court, he or she shall recuse him or herself from the proceedings; in case of the Justice or the Chief Justice who has recused him or herself, or has become otherwise unavailable, he or she shall be replaced for the purposes or the proceedings in question by the most senior of Judges of the Civil Court and the Criminal Court.

'otherwise suddenly unavailable' pertains to serious health problems etc.

???

**Comment by terrorist96** [comment]
> in case of the Justice or the Chief Justice who has recused him or herself, or has ~~became~~ **become** otherwise ~~suddenly~~ unavailable, he or she shall be replaced for the purposes or the proceedings in question by the most senior of Judges of the Civil Court and the Criminal Court.

Which is it? The most senior judge from the civil or criminal court?

**Comment by KacperZajc** [comment]
the most senior of all

**Comment by terrorist96** [comment]
What if it's a tie. lol

**Comment by KacperZajc** [comment]
Then you compare age and the older the judge is, the more senior he will be deemed xd

**Comment by KacperZajc** [comment]
done
