### ISSUE TITLE
electable Judges and Judicial Appointment Commission 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#439]
I am wondering whether we should make Judges of the Criminal and Civil Court electable? 

My concern now is that we allow nominations for the Supreme Court from the lower Courts only yet those Judges are picked by the Judicial Appointment Commission composed of Justices of the Supreme Court and other Members picked by the Chief Justice. As a result, the cycle is closed and it is impossible to introduce new people into the judiciary if the current Supreme Court is against it.
We might need an outside actor to have a say in this and instead of politicians we could use the people.

And we need to enhance the powers and change the composition of the Judicial Appointment Commission:

•	§IV.6. All Judges of the Criminal Court and the Civil Court shall be elected by the Citizens of the Free Republic of Liberland for a 6 year term with the possibility of re-elections according to the rules regarding the eligibility of candidates and running elections as issued by the Judicial Ethics Commission.
o	§IV.6(1) The Judicial Ethics Commission shall be composed of the four Justices of the Supreme Court, three Members appointed by the Chief Justice of the Supreme Court and four Members appointed by the Chief Attorney of the Republic for a 6 year term.
o	§IV.6(2) The Judicial Ethics Commission shall reach its decisions with quorum of no fewer than 9 members with a simple majority vote. 
o	§IV.6(3) Should the office of any of the Justices of the Supreme Court become vacant, the Chancellor shall appoint a current or former Judge of the Criminal Court or the Civil Court for the position; should the office of any of the Chief Justices of the Supreme Court become vacant, the Chancellor shall appoint the most senior Justice of the Supreme Court for the position.
o	§IV.6(4) The Judicial Ethics Commission shall make recommendations regarding any proposed candidate for the position of Justice of the Supreme Court and no such a Justice of the Supreme Court shall be appointed unless and until the Chancellor publicly addresses the recommendations made by the Judicial Ethics Commission; nevertheless such recommendations shall not be binding.
o	§IV.6(5) No Person shall hold the office of any Judge, Justice or the Chief Justice of the Supreme Court whilst holding any other public office within the legislative or executive branch of the Public Administration concurrently.

•	§IV.7. The Judicial Ethics Commission shall have the power to inquire into alleged misconduct of any Judge of any Court of the Free Republic of Liberland other than the Chief Justice and other Justices of the Supreme Court.
o	§IV.7(1) The Judicial Ethics Commission shall have the power to subpoena Judges of the Free Republic of Liberland and Agents of the Public Administration to hear testimonies given under oath.
o	§IV.7(2) The Judicial Ethics Commission may remove any Judge from the office upon a proven case of gross misconduct or intentional procurement of the miscarriage of justice.
o	§IV.7(3) Should there be suspicion that any Judge issues Warrants too leniently, the Judicial Ethics Commission shall have the power to inquire into the justifiability of such Warrants, and may remove such a Judge form his or her office upon proving that is the case.
o	§IV.7(4) Should the Judicial Ethics Commission find evidence of any criminal conduct, it shall be passed to the Office of the Chief Public Prosecutor; testimonies given in breach of oath shall be prosecuted in a regular manner in the Criminal Court.
o	§IV.7(5) The Judicial Ethics Commission shall have the power to declare any Judge, Justice or the Chief Justice of the Supreme Court to be unable to continue to hold his or her office due to very poor health or old age but not before the age of 70.

**Comment by terrorist96** [comment]
This sums it up quite nicely:
https://www.youtube.com/watch?v=poL7l-Uk3I8

Might need a use a US proxy to see it.

**Comment by KacperZajc** [comment]
I am aware of the drawbacks of elected judges and this is why I opposed this idea at the beginning. But  we are talking about the lower Courts here and with the enhanced powers of the Judicial Ethics Commission, this might be the better option for us.

(see my edit on the Commission)

**Comment by Auahi** [comment]
We could also have the Assembly approve/deny the chancellors decision, this would make things a little more balanced.

**Comment by KacperZajc** [comment]
No way this is making it only more political.
Assembly cannot have say on judicial nominations.

**Comment by Auahi** [comment]
Really? I'd think that this would make it harder for a judge to bribe their way in. Do we have a provision that allows citizens to be able to recall judges? If not I think that's something to look into.

**Comment by terrorist96** [comment]
> o §IV.6(2) The Judicial Ethics Commission shall reach its decisions with ~~a~~ quorum of no fewer than 9 members with a simple majority vote. 

> o §IV.7(3) Should there be suspicion that any Judge issues Warrants too leniently, the Judicial Ethics Commission shall have the power to inquire into the justifiability of such Warrants, and may remove such a Judge ~~form~~ **from** his or her office upon proving that is the case.

Since we distinguish between judge, justice and chief justice, when you say "any judge", does that exclude the justices/chief?

> As a result, the cycle is closed and it is impossible to introduce new people into the judiciary if the current Supreme Court is against it.
We might need an outside actor to have a say in this and instead of politicians we could use the people.

Overall, I'm still very skeptical of electing judges. I think appointing judges is much more preferred, because it guarantees the judge's independence, as opposed to a judge having to raise money for an election campaign, taking money from prosecutors and such.

> Do we have a provision that allows citizens to be able to recall judges?

@Auahi yes, we do, and that's where the outside influence comes from.

**Comment by KacperZajc** [comment]
IV.7(3): yes it excludes the Supreme Court Justices but issuing warrants is not really they jobs anyway;

how expensive a campaign will be in such a small country as liberland?

What about electing the Criminal Court Judge but appointing the Civil Court Judge?
After all it is unlikely people would donate to criminal judge with the view that they might end up before him on trial. They are likely to donate to civil judge in case they have a contract or tort dispute . Buying influence is much more likely in civil court rather than criminal court.

**Comment by Auahi** [comment]
I think It's even worse to elect the criminal court judge, people can buy their way into the judges good side, giving them easier sentences.

**Comment by KacperZajc** [comment]
Guilty/not guilty verdict is given by the Jury and sentences are subject to appeals, so the influence is minimal.
Anyway, what are the chances that in the next 6 years from donation you will end up before a criminal judge?
There will be more than 1 judge so it's even less likely you will end up before that judge.

**Comment by liberlandcitizen** [comment]
<<what are the chances that in the next 6 years from donation you will end
up before a criminal judge?>>

Pretty good if you are a criminal/mobster/gangster.

**Comment by Auahi** [comment]
And to piggy back off of the link that terrorist posted, criminal judges increased their rate of sentencing and many judges accepted money from lawyers during their campaign. It's an awful idea to let any judge be elected.

**Comment by KacperZajc** [comment]
ok then we stick to the appointment system
