### ISSUE TITLE
Graphs 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#44]
I made some graphs explaining the check and balance system and the legislative procedure under this Constitution. I think we should publish some graphic explanation when we update the Constitution on the official website to help people understand the whole idea.

Please feel free to prepare something better, I am not good with visual effects... :) 

![](https://raw.githubusercontent.com/liberland/constitution/61cb06eafe885216da8a7a5e1b43442cf6c7f0c1/img/election-and-impeachment-graph.png)

![](https://raw.githubusercontent.com/liberland/constitution/61cb06eafe885216da8a7a5e1b43442cf6c7f0c1/img/legislative-procedure-graph.png)

commit: 61cb06eafe885216da8a7a5e1b43442cf6c7f0c1

**Comment by burningtree** [comment]
New version

![](https://raw.githubusercontent.com/liberland/constitution/master/diagrams/elections-and-impeachment-flowchart.png)

![](https://raw.githubusercontent.com/liberland/constitution/master/diagrams/legislative-procedure-flowchart.png)

**Comment by hazzik** [comment]
I think that Citizens shall have rights to submit a bill or proposal through referendum/petitions. 
Also Citizens shall have rights to dismiss current laws through referendum.

**Comment by tinkyholloway** [comment]
@hazzik there is a proposed change being worked on that would allow citizens to dismiss laws at least every 8-10 years #13.

My view is that the fewer laws there are the better and that in principle citizens should treat thr Public Administration like a legislation generator, while the citizens hold approval authority being able to get rid of officers and laws.

**Comment by hazzik** [comment]
@tinkyholloway I saw #13 before writing my comment, and so I still thing that we need ability for citizens to dismiss laws
