### ISSUE TITLE
unnecessary provisions 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#440]
I want to remove:

§IV.14(10) All Jurors shall receive symbolic remuneration for their service which does not constitute a significant burden on the Annual Budget.

It should be determined by law depending on the financial situation of the country.

I also want to remove:

§IV.8(5) Should a claim, prosecution or appeal be dismissed for frivolity at a Preliminary Hearing, the plaintiff, prosecutor or appellant shall ordinarily be ordered to cover all reasonable expenses of the defendant connected to his or her legal defence as well as all court fees unless there is compelling reason otherwise.

I agree with this provision but I don't think it is of such an importance to be in the Constitution. It is standard procedure as far as I can tell.

As I mentioned before, the feedback indicates that the Constitution is extremely long and complex so we should address those concerns.

**Comment by terrorist96** [comment]
> §IV.14(10) All Jurors shall receive symbolic remuneration for their service which does not constitute a significant burden on the Annual Budget.

If you want to remove this, fine.

> §IV.8(5) Should a claim, prosecution or appeal be dismissed for frivolity at a Preliminary Hearing, the plaintiff, prosecutor or appellant shall ordinarily be ordered to cover all reasonable expenses of the defendant connected to his or her legal defence as well as all court fees unless there is compelling reason otherwise.

I'm against removing this though. It secures your right to be free from frivolous lawsuits. That's the sort of thing a constitution should protect, not be relied upon by law.

> As I mentioned before, the feedback indicates that the Constitution is extremely long and complex so we should address those concerns.

Feedback from who, specifically? Yes, the constitution is long, but it's necessary. We can either have a long, detailed, bulletproof constitution, or a short, more general one like in the US, where its ambiguity has been abused time and time again for expanded government power.

From Wikipedia:

> The Constitution of India is the longest written constitution of any sovereign country in the world, containing 444 articles in 22 parts, 12 schedules and 118 amendments, with 117,369 words in its English-language translation, while the United States Constitution is the shortest written constitution, containing seven articles and 27 amendments, and a total of 4,400 words.

In addition, the constitution of the state of Alabama has 376,006 words.

Our current constitution is only about 14,500 words, and that's not including the impending changes that are coming to the bill of rights/general provisions, which should bring that number down even more.

Considering all the above, I think the length is fine.

**Comment by KacperZajc** [comment]
Feedback from everyone I talked to.
I am well aware it's short comparing to other constitutions and I have defended its form, basically used the same arguments as you. This why Im not carrying out a revolution here, merely looking for a couple provisions which are not indispensable.
If you care so much, we can leave  §IV.8(5).

**Comment by KacperZajc** [comment]
done
