### ISSUE TITLE
religious practice

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#443]
§VIII.6. No law shall promote any religion; nor shall any law impose any religious beliefs on any Person; no law shall hinder practising of any religion on any premises which do not belong to any body of the Public Administration; no religious symbols shall be displayed on any premises belonging to any body of the Public Administration, nor shall any religious practice impeding the work of such body be allowed on such premises; religious practice shall be allowed in all public areas unless it grossly interferes with rights and duties of others.

???

**Comment by Auahi** [comment]
There's a big problem with this:
**_No law shall hinder practising of any religion on any premises which do not belong to any body of the Public Administration_**

Even though a practice can be a religious practice doesn't mean it's non-harmful. If some religion practiced forms of torture, or some form of child endangerment, this prohibits the government from doing something about it on private properties. Also most of religion is covered under §VI, so this is very unnecessary.

**Comment by Auahi** [comment]
I aslo find this to be problematic:
**_No religious symbols shall be displayed on any premises belonging to any body of the Public Administration_**

This prohibits people from wearing religious symbols in public parks, government buildings, etc., and it also is contradictory to most of §VI.

**Comment by KacperZajc** [comment]
No no no
Display on the premises means hanging on the wall etc
Harmful practice is not protected under the Constitution by virtue of:

§I.6. No provision of this Constitution shall be construed as to provide any legal justification for any act or omission which does not stem from the inherent right of self-defence but amounts to any physical, or constitutionally recognised form of non-physical, violence towards any person or animal capable of conscious behaviour, or threat thereof, invasion of privacy, fraud or direct and grave interference with enjoyment of one’s property; nothing in such provision shall be deemed to prevent the Assembly from criminalising such conduct.

**Comment by Auahi** [comment]
Okay makes more sense, I'm fine with this.

**Comment by liberlandcitizen** [comment]
<<No religious symbols shall be displayed on any premises belonging to any
body of the Public Administration>>

It's nitpicking, but honestly I agree that this could be easily
misinterpreted. If I were to say "no guns on the premises" you would think
that applies to the public bringing guns into the park or whatever. Perhaps
we should clarify that nothing should be displayed *by the government*?

**Comment by KacperZajc** [comment]
I would argue that 'display' implies public exposure rather than personal symbol.
I think you have really try to misread it. It's common sense.

**Comment by Auahi** [comment]
The definition of display: make a prominent exhibition of (something) in a place where it can be easily seen.

I would agree that there should be a better way to articulate this.

**Comment by TWalls** [comment]
I think we might take a cue from the 1st Amendment to the US constitution.
Im not sure if we need to get into the symbols displayed on premises if we
have a general prohibition on government establishing religion, simply
stating that the government shall not support or establish any religion nor
prohibit the free, private exercise thereof.

US 1st Amendment:

*"Congress shall make no law respecting an establishment of religion, or
prohibiting the free exercise thereof..."*

Also see Estonia:

*Article 40 The Constitution of the Republic of Estonia reads: "Everyone
has freedom of conscience, religion and thought. Everyone may freely belong
to churches and religious societies. There is no state church. Everyone has
the freedom to exercise his or her religion, both alone and in community
with others, in public or in private, unless this is detrimental to public
order, health or morals."*

I would think it a bit of an overreach if Christmas trees were prohibited
in the government building - I can foresee some claiming they were implying
support of religion.

-TW

**Comment by terrorist96** [comment]
> §VIII.6. **The Public Administration shall not** ~~No law shall~~ promote any religion; ~~nor shall any law impose any religious beliefs on any Person~~ (this should be covered by the first clause); no law shall hinder practising of any religion ~~on any premises which do not belong to any body of the Public Administration~~ (this is already covered by the right to set your own rules on your own private property); ~~no religious symbols shall be displayed on any premises belonging to any body of the Public Administration~~ (covered by first clause), ~~nor shall any religious practice impeding the work of such body be allowed on such premises~~ (this is covered by §I.6); ~~religious practice shall be allowed in all public areas unless it grossly interferes with rights and duties of others~~ (again, covered by §I.6).

Let's stop trying to make it so complicated. Here's the result:

The Public Administration shall not promote any religion; nor shall any law shall hinder the practising thereof.

Short, sweet, and to the point.

**Comment by KacperZajc** [comment]
I disagree. We need a more elaborate provision. Most countries have prohibition on state religion yet pass laws which are motivated by religion.

**Comment by terrorist96** [comment]
Passing a law motivated by religion would fall under "promote". 

The Public Administration shall neither promote nor disparage any religion; nor shall any law hinder the practising thereof.

I think this covers every objection you have and it shortens the Constitution.

**Comment by terrorist96** [comment]
Most other countries don't have as great of phraseology that we do. 😁

**Comment by KacperZajc** [comment]
Agents of PA who want to practice their religion which would hinder exercise of their duties or functioning of that body of the PA would not fall within the scope of I.6. 
And if we leave it, it would contradict your bit on 'hindering practising thereof'.

**Comment by KacperZajc** [comment]
I propose it stays the way it is.

**Comment by terrorist96** [comment]
> The Public Administration shall neither promote nor disparage any religion; nor shall any law hinder the **reasonable** practising thereof.

Fixed. :)

**Comment by KacperZajc** [comment]
you can only imagine how difficult it will be to interpret what religious practice is reasonable
virtually impossible to do

**Comment by terrorist96** [comment]
I don't think so. The courts interpret reasonableness all the time - i.e. the 4th amendment to the US constitution (no unreasonable searches/seizures).
I think we can trust the court to deem prayer in a public park to be a reasonable practice of religion, whereas something like child molestation (see catholic priests) to be inherently unreasonable. If we can't trust the courts to analyze the word reasonable, then we can't trust them with anything.
I think this is the best solution. Think about it for a few days, and I think you'll come to agree with me. :smile:

**Comment by terrorist96** [comment]
Side note: we have the word `reasonable` in the constitution 8 times. By your argument, we should remove all those instances. :stuck_out_tongue_closed_eyes:

**Comment by KacperZajc** [comment]
the difficulty of interpreting the word 'reasonable' depends what this words pertains to;
reasonable force is one thing, resonable political view is another;
expression 'reasonable religious practice' will be a judicial nightmare

**Comment by terrorist96** [comment]
Any long standing common religious practice that doesn't harm anyone else is reasonable. Any religious practice that doesn't interfere with performing your job duties is reasonable. An uncommon religious practice that doesn't harm anyone is reasonable. An uncommon religious practice that interferes with the rights of others is not reasonable. We can go on and on, but I think that's a *reasonable* (lol) thing for a judge to determine.
And let's say a judge deems something reasonable that everyone else thinks is not reasonable (or the other way around). The Assembly can pass a law that says this specific religious practice is hereby deemed unreasonable. /nightmare

**Comment by terrorist96** [comment]
Unless you want to detail every kind of religious practice in the constitution, using the word `reasonable` is the way to go.

**Comment by KacperZajc** [comment]
what's wrong with the current wording?

**Comment by terrorist96** [comment]
> what's wrong with the current wording?

It's overly detailed and overlaps itself multiple times.

**Comment by TWalls** [comment]
I agree that "reasonable" in this context might be a proverbial can of
worms. These cases actually come up all the time, with religious headgear,
symbols etc. worn by government employees and members of the military.

I'm still worried that some litigious person (hopefully these kids of
people will not even seek citizenship) may sue if they see a Christmas tree
in the government building. Or if a Croatian or Serbian person we hire as a
groundskeeper wears a cross around their neck, does that open us up to a
lawsuit?

How about stating (to clarify the 'reasonable' aspect):

Any religious or decorative symbols displayed on the person of members or
employees of the Public Administration or on the property of the Public
Administration shall not be construed as a state endorsement of such
symbols.

**Comment by terrorist96** [comment]
`Reasonable` is for the Judge, the Jury, and society in general to determine. Not for the constitution to define.

**Comment by terrorist96** [comment]
> with religious headgear, symbols etc. worn by government employees and members of the military

If it doesn't hinder them from performing their jobs, then it should be fine. The PA isn't promoting a religion by allowing its employees from expressing their own faith. Putting a stone tablet of the 10 commandments at the General Assembly, that would constitute promotion of a religion.

> I'm still worried that some litigious person (hopefully these kids of
people will not even seek citizenship) may sue if they see a Christmas tree
in the government building

I would argue that this would constitute promotion of a religion and should be disallowed. A Christmas tree can be put up on private property, like a public mall. It's open to the public, but it's a private establishment that can put up whatever religious symbols they want.

> Or if a Croatian or Serbian person we hire as a
groundskeeper wears a cross around their neck, does that open us up to a
lawsuit?

See my first reply.

**Comment by KacperZajc** [comment]
for discussion in #281
