### ISSUE TITLE
comprehensive arrest and detention powers

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#447]
The same provision once again, to make sure we cover all possible scenarios and that detention powers are exhaustive:

§IV.18. No Person shall have his or her physical liberty restricted otherwise than pursuant to a decision of the Courts of the Free Republic of Liberland in the following circumstances:
§IV.18(1) Upon a conviction in the Criminal Court by the Jury;
§IV.18(2) Upon an order of the Civil Court committing a Person lacking mental capacity to a mental health institution;
§IV.18(3) Upon an order of the Civil Court providing for medical isolation of a Person suspected of being infected with any highly contagious and deadly disease;
§IV.18(4) Upon an order of the Civil Court committing a Minor to an in-house care;
§IV.18(5) Upon an order of the Civil Court providing for detention of a Resident pending deportation proceedings;
§IV.18(6) Upon a decision of any Court to commit any Person to prison for no more than seven days for a contempt of court committed either by disruption of judicial proceedings or by disobeying a Court order.
§IV.18(7) Should such Person disobey the same order of a Court more than once, he or she shall be tried in a regular manner for a criminal offence as regulated by law and not limited to a seven-day imprisonment.
§IV.18(8) Nothing in this provision shall affect the powers of arrest and sequestration of Jurors as enumerated in this Constitution.

X.??. Any Person under reasonable suspicion by a medical practitioner of being infected with any highly contagious and deadly disease shall be subject to medical isolation pursuant to an Order of the Civil Court for such time as he or she remains a serious threat to the health or life of others.

•	§X.4. Any Resident of the Free Republic of Liberland without a valid leave to remain shall be subject to deportation; no Resident subject to deportation shall be detained for more than fourteen days unless pursuant to an order of the Civil Court for further detention; such orders shall be issued only where necessary due to the complexity of the deportation proceedings.

•	§X.1. The powers of arrest in the Free Republic of Liberland shall not be exercised arbitrarily but only upon probable cause that the detainee (a) has committed or (b) is committing a criminal offence, and as such, should be brought to trial, or, that he or she is likely to have been made, or is soon to be made, a subject of a Court order regarding (c) a medical isolation on the account of a highly contagious and deadly disease, (d) an in-house care of a Minor, (e) an institutionalisation in a mental health facility, (f) deportation proceedings or (g) committal to prison for a breach of a Court order, and as such, should be brought to the disposition of the appropriate authorities or the Court.

•	§X.2. Agents of Law Enforcement executing arrests shall act openly and shall inform the detainee about the relevant rights he or she enjoys under this Constitution and any laws passed in accordance therewith; where a Person is placed under arrest, Agents of Law Enforcement shall immediately inform his or her close ones as prescribed by law about the detention.

•	§X.3. No Person shall be placed under arrest for more than twenty-four hours without a Warrant; all arrest Warrants shall be issued only (a) where it is necessary for the protection of others, (b) where an accused would otherwise be likely to escape justice or (c) interfere with the investigation, and for no longer than necessary to bring him or her to trial; where the accused is already under arrest, he or she shall be able to address the Court at the hearing regarding a Warrant for further detention, either in person or by way of legal representation.

•	§X.???. No Person shall be arrested by any Citizen or other Resident of the Free Republic of Liberland unless in exigent circumstances where no Agent of Law Enforcement is available to execute the arrest and only for so long as reasonably necessary to allow such an Agent to take custody of the detainee.

**Comment by terrorist96** [comment]
> §IV.18. No Person shall have his or her physical liberty restricted ~~otherwise than~~ **unless** pursuant to a decision of the Courts of the Free Republic of Liberland in the following circumstances:

>§IV.18(6) Upon a decision of any Court to commit any Person to prison for no more than seven days for a contempt of court committed either by disruption of judicial proceedings or by disobeying a Court order.
§IV.18(~~7~~**6**)**(a)** Should such Person disobey the same order of a Court more than once, he or she shall be tried in a regular manner for a criminal offence as regulated by law and not limited to a seven-day imprisonment.
§IV.18(~~8~~**7**) Nothing in this provision shall affect the powers of arrest and sequestration of Jurors as enumerated in this Constitution.

> • §X.4. Any Resident of the Free Republic of Liberland without a valid leave to remain shall be subject to deportation; no Resident subject to deportation shall be detained for more than fourteen days unless pursuant to **an** order of the Civil Court for further detention ~~is obtained~~; such orders shall be issued only where necessary due to the complexity of the deportation proceedings.

> • §X.1. The powers of arrest in the Free Republic of Liberland shall not be exercised arbitrarily but only upon probable cause that the detainee (a) has committed or (b) is committing a criminal offence, and as such, should be brought to trial, or, that he or she is likely to have been made, or is soon to be ~~make~~ **made**, a subject of a Court order regarding (c) a medical isolation on the account of a ~~dangerous infectious~~ **highly contagious and deadly** (keep it consistent) disease, (d) an in-house care of a Minor, (e) an institutionalisation in a mental health facility, (f) deportation proceedings~~,~~ **(remove serial comma)** or (g) committal to prison for a breach of a Court order, and as such, should be brought to the disposition of the appropriate authorities or the Court.

What if there's a public warrant out for their arrest? Isn't that different from a court order?
Like a [WANTED Poster](http://image.shutterstock.com/z/stock-vector-a-old-wanted-posters-vector-wanted-poster-image-117628360.jpg)

> • §X.3. No Person **shall be** placed under arrest for more than twenty-four hours without a Warrant; all arrest Warrants shall be issued only (a) where it is necessary for the protection of others, (b) where an accused would otherwise be likely to escape justice~~,~~ or~~,~~ **(remove both commas)** (c) interfere with the investigation, and for no longer than necessary to bring him or her to trial; where the accused is already under arrest, he or she shall be able to address the Court at the hearing regarding a Warrant for further detention, either in person or by way of legal representation.

> §X.4. No Person shall be arrested by any Citizen or other Resident of the Free Republic of Liberland unless in exigent circumstances where no Agent of Law Enforcement is available to execute the arrest and only for so long as reasonably necessary to allow such an Agent to take custody of the detainee.

We define law enforcement as anyone acting upon a warrant. That includes citizens (such as bounty hunters). I propose we don't change this provision.

**Comment by KacperZajc** [comment]
§X.4. No Person shall be arrested by any Citizen or other Resident of the Free Republic of Liberland unless in exigent circumstances where no Agent of Law Enforcement is available to execute the arrest and only for so long as reasonably necessary to allow such an Agent to take custody of the detainee; nothing in this provision shall affect the powers of Citizens and Resident of the Free Republic of Liberland where acting pursuant to a public Warrant.

???

**Comment by KacperZajc** [comment]
Why do we need mentioning citizens acting pursuant to public warrants?
Any citizen has the power to arrest a person, publishing a warrant only make them know who to arrest.
There is no need for special provision.

Plus, I.22 as stands now would confer all powers of law enforcement on citizens when a warrant is published. It is ridiculous.

We don't need this bit of the provision at all:

§I.22. For the purposes of this Constitution, the term “Person” shall signify any human being whatsoever; the term “Individual” shall signify a Person of age who does not lack mental capacity and is not incarcerated before, during or after a trial; the term “Agent of the Public Administration” shall signify any Person working for any body of the Public Administration, including the Law Enforcement; the term “Member of the Public Administration” shall signify any Person who is holding a public office of one of the branches of the Public Administration; the term “Agent of the Law Enforcement” shall signify any Person working for Law Enforcement or the Office of the Public Prosecutor; the term “Citizen” shall signify any Person holding citizenship of the Free Republic of Liberland; the term “Resident” shall signify any Person within the jurisdiction of the Free Republic of Liberland who is not a Citizen; the term "law" shall signify any Act passed by the Assembly in accordance with Article II and any Executive Measures as issued by the Cabinet in accordance with Article III.
