### ISSUE TITLE
"The Legislative Power" select members at qualified random, not by election

### ISSUE THREAD

**Issue by DirectDemo** [liberland/constitution#449]
I think the members of the parliament should be at random, certainly not by election.

Pupose is to avoid many well known "public choice Issues" about election, and reduce corruption risk (secret of the vote).

My proposition is 2 chambers :

- The juridical chamber (juges, lawers, graduates, etc.) : every smal group, like five members, can propose a law projects for a specific probléme, so we can have many law projects for the same purpose.

- The voter's chamber (kind of people not in the juridical chamber) : vote for (or against) the law projects from the juridical chamber, nominate individually the members of the governement, vote the budget orientations and the maximum fiscal butin.

every years 1/6 part of each chamber is renewed at random, so the new ones can benefit of the experience of the old ones. All votes of the members of the voter's chamber (at least) are secrets.

**Comment by KacperZajc** [comment]
Let me repeat one more time what Ive been saying for a long time now - Liberland does not exist in vacuum, it must be a democracy and its political system must look roughly like any other state's. Otherwise there will be no Liberland at all.

In any event, the structure of the Legislative power is not up to us here.

**Comment by DirectDemo** [comment]
I do not underground this non sens non argument to immediatly close the issue !

Please could you develop why you think election is supposed to be better than this proposition.

**Comment by liberlandcitizen** [comment]
I don't want to speak for Kacper, but I think what he might be saying is,
we have more to worry about than what we think would make the most
interesting experiment in government. We must also think about what will be
acceptable to the international community. It's not that we have to abandon
our belief system, it's just that if we want Liberland to truly exist (I'm
sure we all do) we have to think about what will make us more likely to
exist too. We need a system of government in at least a somewhat
traditional sense.

For what it's worth, I think your idea isn't so bad. Juries are made up of
citizenry without elections in many countries. I have sometimes wondered
why the same couldn't be true with legislative bodies too. All of this
would be a wonderful thing to discuss hypothetically in some other forum.
But ​for Liberland, we have to stay on track and make a constitution that
we can actually use, and can get our neighboring countries to be ok with.

**Comment by DirectDemo** [comment]
@liberlandcitizen 
The international community don't mind the way we select our parliament, every country as a different way to do it it is a pur product of political strategy to keep power, not to protect freedom. Other states don't like taxes competition, with the @KacperZajc argument we should think to rise taxes... and also most state in the world are pure dictatorship... should we consider there point of view ?

Selection at random is not so exotic you imagine.
The Republic of Genoa and Athene for exemple used selection at random for a couple of centuries in the legislative process.
In France we used juries at random for 100 years to protect land property against requisition and 70 years to protect freedom of speech, socialist suppress the both in 1937 and 1945.

In LLLv3 Hayek suggest two chambers with different skill, a way to divide power, i used that also to combine representativity and skill in law. For a very little population voter's chamber can be replaced by referendum.
I understand your text is still an advanced release, but you should consider new ideas now, after it will be much much more harder.

Regards
