### ISSUE TITLE
ID cards

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#451]
§VIII.6. No Individual shall be compelled to identify himself or herself to any Agent of the Public Administration, unless upon arrest, a reasonable suspicion of a violation of the law or pursuant to a Warrant or Court order or subpoena; the Public Administration shall not issue any identification cards  for the Citizens of the Free Republic of Liberland other than passports.

Should we add that?

**Comment by terrorist96** [comment]
I think the PA should be able to issue ID cards if it wants, like for voting, or purchasing alcohol/drugs that are prohibited to minors, or maybe even driving if we end up requiring a driver's license.

**Comment by KacperZajc** [comment]
aren't those cards proving qualification rather than ID?

**Comment by KacperZajc** [comment]
you might be right, this might too broad
