### ISSUE TITLE
A new Article in the Bill of Rights

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#452]
No change of the contents of the rights (except I.5). 
Just transferring them into a separate chapter.

For a discussion on the religion provision see #443 

Article XIII: Equality Rights

THE EQUALITY OF PERSONS BEFORE THE LAW SHALL BE SECURED

•	§I.8. No Person shall be excluded from the operation of, or granted any privilege under, any law; nor shall any Person be denied equal protection under the law; nothing in this provision shall prevent the Members of the Public Administration and the Citizenry from enjoying certain special rights and immunities as described in this Constitution and no others; nor shall the Assembly be prevented from granting certain immunities related to legal personality, bankruptcy and vicarious liability.
•	§VIII.7. No law shall promote any religion; nor shall any law impose any religious beliefs on any Person; no law shall hinder practising of any religion on any premises which do not belong to any body of the Public Administration; no religious symbols shall be displayed on any premises belonging to any body of the Public Administration, nor shall any religious practice impeding the work of such body be allowed on such premises.
•	§VIII.8. No law shall promote any gender; nor shall any law distinguish between genders unless such distinction is necessary owing to physiological differences between the sexes; standards of all examinations conducted by any branch of the Public Administration prior to offering employment shall equally apply to all genders; all Persons shall be assigned their natural gender on birth; all Individuals shall have the right to change the gender assigned to them on birth without any excessive administrative burdens in a manner prescribed by law.
•	§I.5. No Person shall be deprived of his or her personality before the law; all Persons within the jurisdiction of the Free Republic of Liberland shall be bound to observe the Constitution; all bodies of the Public Administration, its Members and Agents, shall act within the realms of the Constitution and all laws passed in accordance therewith.

**Comment by terrorist96** [comment]
> No Person shall be deprived of his or her personality before the law;

Not sure what this is supposed to be for. Like, a person that is part of an LLC can't be stripped of that protection?

**Comment by KacperZajc** [comment]
prevent any potential creation of outlawries
