### ISSUE TITLE
Liberland jurisdiction

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#456]
I.21 The jurisdiction of the Free Republic of Liberland shall extend to the whole territory of the Free Republic of Liberland, all aircrafts and watercrafts registered therein, its airspace, territorial waters and any area under the overall effective control of the Territorial Defence force.

Bit of rephrasing:
§VIII.7. No law regulating conduct of Persons other than Members and/or Agents of the Public Administration shall extend beyond the jurisdiction of the Free Republic of Liberland; nothing in this provision shall prevent the Assembly from granting the Criminal Court jurisdiction over international crimes.

**Comment by terrorist96** [comment]
> I.21 The jurisdiction of the Free Republic of Liberland shall extend to the whole **~~of~~** territory of the Free Republic of Liberland, all aircrafts and watercrafts registered therein, its airspace, territorial waters and any area under the overall effective control of the Territorial Defence force.

We mention aircrafts and watercrafts, what about other -crafts? Like regular motor vehicles.

And the rephrasing: it seemed like before, the VIII.7 would be interpreted to mean that the jurisdiction of liberland wouldn't include planes/boats when when they are outside the territory, but now it includes them? So if a boat or plane enters the territory of another country, the inside of the craft would be both the jurisdiction of Liberland and the other country?

**Comment by KacperZajc** [comment]
The national jurisdiction extends to 'crafts' while on international waters or in international airspace.
So it is impossible to have a car (land vehicle) which would 'carry' Liberland jurisdiction because there is no international land.

**Comment by terrorist96** [comment]
> The national jurisdiction extends to 'crafts' while on international waters or in international airspace.

Really? I thought many cruise ships don't start gambling or providing medical procedures until they exit the territory of their registered country (enter international waters) because only international law applies, not national.

**Comment by KacperZajc** [comment]
There is no international law which would regulate private conduct of individuals.

From wiki:

Ships sailing the high seas are generally under the jurisdiction of the flag state (if there is one);[3] however, when a ship is involved in certain criminal acts, such as piracy,[4] any nation can exercise jurisdiction under the doctrine of universal jurisdiction. International waters can be contrasted with internal waters, territorial waters and exclusive economic zones.

**Comment by terrorist96** [comment]
This is interesting. See this:

> Some cities and city officials do not agree if gambling ships should be allowed to go out to sea and gamble but then come back and dock in ports where gambling is illegal. The gambling ships have to travel for over forty five minutes to reach international waters before they could gamble legally.[5] In the city of New York, where gambling had been deemed illegal, there are some companies that would send their gambling ships to go out to sea into international waters which is about forty five minutes out so people could gamble on their ships legally.

https://en.wikipedia.org/wiki/Gambling_ship

**Comment by KacperZajc** [comment]
Hmm this is interesting. I heard about that but I don't really see how it works.
Need to do some research.

**Comment by terrorist96** [comment]
> So it is impossible to have a car (land vehicle) which would 'carry' Liberland jurisdiction because there is no international land.

Also, just a nitpick but wouldn't Antarctica technically count as international land? :P

**Comment by KacperZajc** [comment]
hahaha
technically I think it would
please don't tell me you want me to expressly mention Antarctica in the Constitution... xD

**Comment by terrorist96** [comment]
Lol no. But if a car is also on a ship or boat, wouldn't it also count as being in international territory? Though it can be covered by the ship/plane encompassing it, but what if the car was dumped into the sea lol. Let's just say all vehicles instead of aircraft/watercraft when we figure out the international laws situation.

**Comment by KacperZajc** [comment]
ok let's make it 'vehicles while in international space'
make it a PR please

**Comment by terrorist96** [comment]
Done. Please keep this open so we can remember to revisit the international laws issue.

**Comment by terrorist96** [comment]
@KacperZajc please reopen

**Comment by KacperZajc** [comment]
I reference it in #252
We will figure it out later/
