### ISSUE TITLE
Confiscation of property 

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#457]
> §X.10. All Persons shall have the right to fair compensation for any and all days spent incarcerated from the twenty-fifth hour of detention onwards before, during and/or after the trial, should the case be dismissed or should said Person be found not guilty by the Jury or should a guilty verdict be overturned on the appeal; such compensation shall be paid by the Secretariat of the Judiciary.

I propose we add the confiscation of property to this provision as well. My purpose is to prevent property from being confiscated without restrictions prior to conviction.

**Comment by terrorist96** [comment]
Also, I know we protect people's property underneath their land, but what about above it? Will people own the air above their property? If so, how far up? What if someone wants to fly a drone w/ camera for recreation?

**Comment by KacperZajc** [comment]
It is protected by this provision:

§VII.3. No Person’s private property, be it movable or immovable, tangible or intangible, shall be confiscated, either fully or partially, for any purpose other than such restitution or compensation as may lawfully be due, lawfully levied fines, the Land Fee, satisfaction of pre-existing debt, the collection of evidence pursuant to a Warrant **or in exigent circumstances to prevent the commission of a crime where, and only for so long as, there is insufficient time to obtain a Warrant;** nothing in this provision shall prevent the Civil Court from issuing orders temporarily freezing a defendant’s assets where the Court is satisfied that there is a real risk that the defendant’s assets will be dissipated with the intention of frustrating satisfaction of any judgement that a Court may make.
(btw I want to remove the bolded part because it's not confiscation as such and it's confusing)

Regarding air, I suggest you open a separate Issue, but as far as I remember it has been discussed in the past and we decided that it would be impossible to come up with wording which would make sense.

**Comment by liberlandcitizen** [comment]
Regarding compensation: This sounds....expensive. How will a nation with
minimum and/or voluntary taxation pay for this? And who decides what is
"fair" compensation? If your intentions here are to have a speedy trial,
why not just make rules forcing swift justice? If your intentions are to
keep people from being falsely accused, we should have harsh penalties when
there is evidence of judges, prosecutors, jury members or police knowingly
putting somebody in jail under false pretenses (I believe there is
something in the constitution about that already).

It seems unfair to the taxpaying public to pay for the missteps or crimes
of the government.

Sadly, human justice is imperfect and under any system a few innocents will
go to jail. We can minimize this by giving strong rights to the accused and
erring on the side of setting the guilty free before putting the innocent
in a cage. We should also have a strong right to appeal upon new evidence
of innocence.

But if you end up in jail despite being innocent, as bad as it was for you,
if everything was on the up and up why should the taxpayers take a hit?

**Comment by terrorist96** [comment]
I'm satisfied with that.
@liberlandcitizen the public won't pay. We specify in the constitution that if anything like this arises, the person responsible pays out of pocket, personally. It's an incentive to not act unconstitutionally and hiding behind police unions.

**Comment by liberlandcitizen** [comment]
Why then does it say "such compensation shall be paid by the Secretariat of
the Judiciary" then and what about cases when nobody did anything wrong?
There are cases when the evidence truly points to somebody being guilty,
and only years later does other evidence prove innocence. Should anybody be
held responsible in such cases?

**Comment by terrorist96** [comment]
That would only apply to a situation where the arrest was lawful but a not guilty verdict was reached in the end. 

> and only years later does other evidence prove innocence. Should anybody be
held responsible in such cases?

The innocent person was still deprived of their liberty while actually being innocent, so he deserves compensation. And because no one was directly at fault for this, that's why we 'socialize' the cost instead of making the police officer pay directly.

**Comment by liberlandcitizen** [comment]
Sometimes bad things happen in life and it's nobodies fault. Like
earthquakes. It's part of the risk of being alive. I don't see why society
owes the falsely accused compensation when society hasn't done anything
wrong. It's immoral to reach into my pocket because something bad happened
to somebody that I don't even know. We might as well have socialized
medicine too.  ​

**Comment by KacperZajc** [comment]
I think this wont be a problem.
If the state is poor, the Courts will construe 'fair' in a way that will not bankrupt us

**Comment by terrorist96** [comment]
Earthquakes can't be avoided. False arrests can.

**Comment by liberlandcitizen** [comment]
<<Earthquakes can't be avoided. False arrests can.>>

You do realize that some people are found not-guilty when they are actually
*guilty* right? A not-guilty verdict doesn't mean it was a false arrest!

And even if somebody is innocent, there could exist reasonable evidence for
a trial and sometimes even a resulting conviction beyond reasonable doubt.
This is a sad fact of life, like earthquakes and cancer. I wish bad stuff
didn't exist in the world, but sometimes bad things happen to good people.
The question is, should society be forced to reach into their pockets when
bad things happen to somebody despite it not being anybody's fault?

**Comment by KacperZajc** [comment]
I think @liberlandcitizen might be onto sth here.
Maybe we should change to compensation payable only where the case was dismissed at a Preliminary Hearing (those are baseless claims)?
I agree that an arrest might be justified even if a person is found not guilty on some legal technicality.

**Comment by terrorist96** [comment]
Also, @KacperZajc removong the bolded part in VII.3 could prevent police from confiscating a firearm from someone who is using it illegally.

**Comment by KacperZajc** [comment]
@terrorist96 good point, but we need 'unless a Person is legally prohibited from possessing such a property' exception then

**Comment by terrorist96** [comment]
> You do realize that some people are found not-guilty when they are actually
*guilty* right? A not-guilty verdict doesn't mean it was a false arrest!

Yes, especially if it's a case of jury nullification. 

> Maybe we should change to compensation payable only where the case was dismissed at a Preliminary Hearing (those are baseless claims)?

That could work. It protects who undergo "arrest and release" due to no evidence but doesn't protect those who have enough evidence against them for a trial to proceed. 

> @terrorist96 good point, but we need 'unless a Person is legally prohibited from possessing such a property' exception then

The person with the gun legally owns it and carries it up til the point that they pull it out and start shooting people. That would be an exigent circumstance where getting a warrant isn't practicable. I think keeping the exigent circumstances wording is better. Or say that the property can be confiscated upon arrest. That would cover it all, I think.

**Comment by KacperZajc** [comment]
•	§VII.3. No Person shall have his or her private property confiscated, be it movable or immovable, tangible or intangible, either fully or partially, unless he or she is legally prohibited from possessing it, for any purpose other than such restitution or compensation as may lawfully be due, lawfully levied fines, the Land Fee, satisfaction of pre-existing debt or the collection of evidence pursuant to a Warrant; nothing in this provision shall prevent the Courts from temporarily freezing Person’s assets in criminal and civil proceedings or a temporary seizure of personal property upon his or her arrest. 

???

**Comment by KacperZajc** [comment]
for compensation see #460
