### ISSUE TITLE
compensation 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#460]
§X.10. All Persons shall have the right to fair compensation for any and all days spent incarcerated from the twenty-fifth hour of detention onwards, should his or her case be dismissed at a Preliminary Hearing; such compensation shall be paid by the Secretariat of the Judiciary.

???

**Comment by liberlandcitizen** [comment]
Much better than the previous one, thank you.

**Comment by KacperZajc** [comment]
thank you for bringing this up :)

**Comment by KacperZajc** [comment]
EDIT:

§X.10. All Persons shall have the right to fair compensation for any and all days spent incarcerated from the twenty-fifth hour of detention onwards, should his or her case be dismissed at a Preliminary Hearing; such compensation shall be paid by the Secretariat of the Judiciary; Persons wrongfully convicted shall have a separate right to fair compensation as prescribed by law.
