### ISSUE TITLE
Obligations of Agents and Members of the PA

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#461]
I know this is not strictly speaking an Article listing rights of the people, but I think it fits within the Bill or Rights if it is presented in the light of accountability of Agents and Members of the PA:

(no change of contents whatsoever - provisions transferred from Chapter 1)

ARTICLE XIV: Accountability of Agents and Members of the Public Administration

THE AGENTS AND MEMBERS OF THE PUBLIC ADMINISTRATION SHALL BE ACCOUNTABLE TO THE PEOPLE

•	§XIV.1. All Members and Agents of the Public Administration shall take the Oath of Office prior to holding office; the Oath of Office shall include the pledge of allegiance to the state of the Free Republic of Liberland, obligation to uphold and abide by the Constitution of the Free Republic of Liberland, and to perform one’s duties in a manner consistent with the liberty of others as far as possible.
•	§XIV.2. All Members and Agents of the Public Administration intentionally acting in breach of the law relevant to the position held or the Constitution shall be criminally liable for their actions and, upon conviction, shall be removed from the office and shall never hold any public office again; acting pursuant to an Act which has been approved as prima facie constitutional by the Supreme Court shall not be deemed as acting unconstitutionally regardless of any future declaration of any Court as to the Act's actual constitutionality; introducing, lobbying and voting for a Bill which is declared unconstitutional shall not be deemed as acting unconstitutionally.
•	§XIV.3. All candidates for any public office in the Free Republic of Liberland as well as all current Members of the Public Administration shall be under obligation to disclose their assets above certain value as prescribed by law, sources of income over certain proportion of his or her overall yearly income as prescribed by law and benefaction, both current and of the past five years, as prescribed by law, to the public; should a candidacy be submitted by any such organisation as may be prescribed by law, such organisation shall be under equal obligation of disclosure.

**Comment by terrorist96** [comment]
I think `true constitutionality` sounds better than `actual constitutionality`

**Comment by KacperZajc** [comment]
maybe 'factual'?

**Comment by terrorist96** [comment]
That doesn't sound right either.

**Comment by KacperZajc** [comment]
feel free to make a PR with 'true'
