### ISSUE TITLE
extraordinary rendition

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#462]
No Person shall be detained or interrogated by any Agent of the Public Administration outside the jurisdiction of the Free Republic of Liberland.

No Person shall be rendered to any state or group should there be a reasonable suspicion that such a state or group may inflict torture or other inhuman or degrading treatment on such a Person.

Where do you think these provisions would fit best?

**Comment by liberlandcitizen** [comment]
Would this include the death penalty?

**Comment by KacperZajc** [comment]
@liberlandcitizen no, the death penalty as such is not torture/cruel treatment unless executed in a cruel manner.

**Comment by liberlandcitizen** [comment]
I believe we've had this discussion before. Some of us find it the cruelest
and most inhumane form of punishment of them all.

**Comment by KacperZajc** [comment]
But this is not what international law says.
These provisions addresses extraordinary rendition for the purposes of violent interrogations and deportation to other states which would employ torture.

**Comment by liberlandcitizen** [comment]
I am not aware of what international law exactly says on the matter, but
Liberland can choose its own policy. I know that Australia, Canada,  New
Zealand, South Africa, and most European nations will not extradite if the
death penalty is on the table. Important to keep in mind that though some
countries have the death penalty only for the most serious of crimes
(murder) other countries have it for things you probably believe shouldn't
be crimes at all. For example, in Iran you can be executed for marrying a
Muslim girl if you are not a Muslim. In Saudi Arabia, you can be executed
for being a homosexual. In Somalia, you can be executed for committing
adultery.

**Comment by KacperZajc** [comment]
regardless, extradition can only take place where the crime a person is accused of is a crime in both jurisdictions, so all those 'adultery', 'homosexuality' etc 'crimes' would not trigger extradition in any event;
plus, nothing in this provision prevent the Assembly from regulating the law on extradition to states which use the death penalty

**Comment by terrorist96** [comment]
> No Person shall be detained or interrogated by any Agent of the Public Administration outside the jurisdiction of the Free Republic of Liberland.

Do Agents have the authority to act outside the jurisdiction to begin with? If not, this is unnecessary. If so, that authority should be removed. It seems like the authority doesn't exist to begin with:

> §III.10. No special Department shall be established, nor shall any Department operate outside its jurisdiction.
> §III.10(2) All Agencies shall be supervised by relevant Departments and no Agency shall operate outside its own jurisdiction or the jurisdiction of its Department.
> The Bill of Rights shall constitute an integral part of the Constitution and shall be binding upon all branches of the Public Administration and its Members and Agents both within and outside the territory of the Free Republic of Liberland.

Moving on:
> No Person shall be rendered to any state or group should there be a reasonable suspicion that such a state or group may inflict torture or other inhuman or degrading treatment on such a Person.

Didn't we have a provision that said no extradition unless the receiving country has similar respect for human rights, or something to that effect?

**Comment by KacperZajc** [comment]
III.10 speaks of jurisdiction in terms of competences rather than territory;

Regarding torture - I do think there is any provision to that effect yet.
I propose we rephrase IX.17:

§IX.17. No torture or cruel or degrading treatment shall be inflicted by any Agent or Member of the Public Administration or under the supervision or knowledge thereof against any Person; no Person shall be rendered to any state or group should there be a reasonable suspicion that such a state or group may inflict torture or other inhuman or degrading treatment on such a Person; nor shall any experiments, medical or otherwise, be conducted against any Person without his or her express and informed consent; no Individual shall be medically examined or otherwise tested unless pursuant to a Warrant or with the Individual's express and informed consent.

**Comment by terrorist96** [comment]
> §IX.17. No torture or cruel or degrading treatment shall be inflicted by any Agent or Member of the Public Administration or under the supervision or knowledge thereof against any Person; no Person shall be rendered to any state or group should there be a reasonable suspicion that such ~~**a**~~ state or group may inflict torture or other inhuman**e** or degrading treatment **(wouldn't it be better to match the qualifiers from the first clause? i.e. torture or cruel or degrading treatment)** on such a Person; nor shall any experiments, medical or otherwise, be conducted against any Person without his or her express and informed consent; no Individual shall be medically examined or otherwise tested unless pursuant to a Warrant or with the Individual's express and informed consent.

**Comment by KacperZajc** [comment]
what do you mean?

**Comment by terrorist96** [comment]
We prohibit `torture or cruel or degrading treatment` in the first clause, but we prohibit `torture or other inhuman or degrading treatment` in the second clause. We should use the same wording so there's no confusion. Why use different qualifiers for different situations?

**Comment by KacperZajc** [comment]
oh right, I didnt even realise, of course
