### ISSUE TITLE
customary international law

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#466]
We should substitute this provision:

§III.6. The Chancellor and the Cabinet shall comply, in performing their obligations and exercising their powers, with jus cogens and erga omnes rules and other aspects of customary international law insofar as it does not contravene the Constitution or any law passed in accordance therewith, as advised by the Chief Attorney of the Republic.

with that provision:

I.???. Customary international law shall form part of the legal system of the Free Republic of Liberland, and as such shall be directly enforceable before the Courts, insofar as it does not contravene the Constitution or any law passed in accordance therewith.

**Comment by terrorist96** [comment]
Seems to me that we could eliminate this provision all together as it's already covered by: 

> §III.12(7) The Chief Attorney of the Republic shall be under obligation to take all available measures to ensure the Cabinet is provided with precise and impartial advice as its powers and obligations under the Constitution, international law and current domestic law of the Free Republic of Liberland.

and

> §IV.18. Should any proceeding before any Court of the Free Republic of Liberland be concerned with any provision of any international treaty or any rule of customary international law binding the Cabinet, its interpretation shall lie within competences of the Courts of the Free Republic of Liberland.

**Comment by KacperZajc** [comment]
It's not the same.

III.12 and IV 18 imply that Cabinet is bound by international law but it doesnt mean it is part of the legal system and enforceable before the courts by ordinary people.

**Comment by terrorist96** [comment]
> its interpretation shall lie within competences of the Courts of the Free Republic of Liberland.

That doesn't make it part of the legal system and enforceable?

**Comment by KacperZajc** [comment]
not really, what was intended here was that the Assembly or Cabinet cannot dictate what a treaty or customary international law rule means;
the Bush administration tried to impose its own interpretation of international law on courts and this is what we aim at here

**Comment by terrorist96** [comment]
Okay then we should combine it with either IV.18 or III.12. Probably IV.18 would be better.

**Comment by KacperZajc** [comment]
Good point:

I.???. Customary international law shall form part of the legal system of the Free Republic of Liberland, and as such shall be directly enforceable before the Courts of the Free Republic of Liberland, insofar as it does not contravene the Constitution or any law passed in accordance therewith; where any party to any proceedings before any Court wishes to rely on any principle of customary international law or provision of any international treaty, its interpretation shall lie within competences of the Courts of the Free Republic of Liberland.

???

**Comment by liberlandcitizen** [comment]
May I ask what's so great about "international law" or is this for the
international community to recognize Liberland?

**Comment by KacperZajc** [comment]
It provides certain safeguards against mistreatment (see the Bush administration's fight against international law).
It is also good in terms of PR.
There is no risk of socialist influence here.
