### ISSUE TITLE
minority rights

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#467]
little adjustment: 

§XI.1. No Person shall be excluded from the operation of, or granted any privilege under, any law; nor shall any Person be denied equal protection under the law; no special privileges shall be granted to any minority or otherwise; nothing in this provision shall prevent the Members of the Public Administration and the Citizenry from enjoying certain special rights and immunities as described in this Constitution and no others; nor shall the Assembly be prevented from granting certain immunities related to legal personality, bankruptcy and vicarious liability.

**Comment by terrorist96** [comment]
Seems redundant. Wouldn't that already be covered by the first clause that says no granting privileges under any law?

**Comment by KacperZajc** [comment]
hmmm

§XI.1. No Person or any group shall be excluded from the operation of, or granted any privilege under, any law;...

now it covers everything
