### ISSUE TITLE
IV.9(2) rephrasing?

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#468]
> +  * **§IV.9(2)** All verdicts of the Supreme Court shall be binding upon the parties to the proceedings and the Civil Court and the Criminal Court on the point of law in all future proceedings where applicable.

Using this as opposed to the previous version basically says that the Supreme Court's verdict only applies to the parties of the case. So if someone else who would be affected by the ruling wants to take advantage of that ruling, they'd have to initiate their own lawsuit since the ruling is no longer binding upon the public at large. Is this really what we're going for here?

**Comment by KacperZajc** [comment]
Hmm how can someone else take advantage of the ruling without going to court?
Courts can only bind parties to the proceedings and lower courts.
I dont think it is possible for a court to bind a 3rd party.
Am I missing sth?

**Comment by terrorist96** [comment]
Take for example the SCOTUS ruling that gay marriage is required to be allowed by the constitution. In your view, that would only allow for the parties of the case to get married. Any other gay couple would have to individually initiate a lawsuit, get the judgement, and then be able to get married.
Though from what I know, SCOTUS cases can be interpreted in the US to apply only to the parties involved, but usually it is perceived to affect everyone because it would be a waste of court resources to have every gay couple in court to receive the same judgement.

**Comment by KacperZajc** [comment]
Yeah I think the general principle is that a court can bind only parties to the proceedings.
But it affects everyone de facto (as opposed de jure?) because it binds lower courts and it would be pointless to oppose a verdict.
But Im not sure whether it is possible to say in the Constitution that a court can bind 3rd parties.

**Comment by terrorist96** [comment]
True, it's de facto binding.

**Comment by KacperZajc** [comment]
I wouldnt worry about that in any event it is the Supreme Court who is the ultimate judge of the Constitution so any attempt to apply some odd interpretation would be struck down :)
