### ISSUE TITLE
right to compensation 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#469]
§X.11. All Persons arrested in error or contrary to law or the Constitution shall have the right to fair compensation for the whole period of incarceration; all Persons placed under a valid arrest which have their charges subsequently dropped or dismissed at a Preliminary Hearing shall have the right to fair compensation for any and all days spent incarcerated from the twenty-fifth hour of detention onwards; such compensation shall be paid by the Secretariat of the Judiciary; Persons wrongfully convicted shall have a separate right to fair compensation as prescribed by law.

Now it is comprehensive.

**Comment by terrorist96** [comment]
Are you trying to combine §X.11. and §VII.7.?
If not, I think we should combine them.

**Comment by terrorist96** [comment]
I think we should also mention that any Agent acting in accordance with a prima facie constitutional law shouldn't be held to have acted unconstitutionally if that law is later ruled unconstitutional.

**Comment by KacperZajc** [comment]
§X.11. and §VII.7 are complementary but separate 

also:

§XIV.2. All Members and Agents of the Public Administration intentionally acting in breach of the law relevant to the position held or the Constitution shall be criminally liable for their actions and, upon conviction, shall be removed from the office and shall never hold any public office again; acting pursuant to an Act which has been approved as prima facie constitutional by the Supreme Court shall not be deemed as acting unconstitutionally regardless of any future declaration of any Court as to the Act's true constitutionality; introducing, lobbying and voting for a Bill which is declared unconstitutional shall not be deemed as acting unconstitutionally.
