### ISSUE TITLE
victimless crimes provisions

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#471]
§IX.3. No law shall prohibit any act or omission which does not directly harm any other Person or cause unwarranted suffering to an animal capable of conscious behaviour or  harm to environment beyond the boundaries of one’s property; nor shall any law prohibit any act or omission which has been validly consented to by another Individual; no Individual shall be considered a victim of one’s actions or omissions; nothing in this provision shall prevent the Assembly from criminalising conduct interfering with (a) the work of the criminal justice, (b) immigration or (c) electoral system, (d) bribery, (e) preparing, (f) attempting, (g) participating in or (h) benefiting from committing a criminal offence.

§I.5. No provision of this Constitution shall be construed as to provide any legal justification for any act or omission which does not stem from the inherent right of self-defence but amounts to any physical, or constitutionally recognised form of non-physical, violence towards (a) any person or (b) animal capable of conscious behaviour, or threat thereof, (c) invasion of privacy, (d) fraud, (e) direct and grave interference with enjoyment of one’s property or (f) harm to environment beyond the boundaries of one’s property; nothing in such provision shall be deemed to prevent the Assembly from criminalising such conduct.

**Comment by terrorist96** [comment]
> §IX.3. No law shall prohibit any act or omission which does not directly harm any other Person or cause unwarranted suffering to an animal capable of conscious behaviour or harm to **the** environment beyond the boundaries of one’s property; nor shall any law prohibit any act or omission which has been validly consented to by another Individual; no Individual shall be considered a victim of one’s actions or omissions; nothing in this provision shall prevent the Assembly from criminalising conduct interfering with (a) the work of the criminal justice **system**, (b) immigration or (c) electoral system, (d) bribery, (e) preparing, (f) attempting, (g) participating in or (h) benefiting from committing a criminal offence.

"nothing in this provision shall prevent the Assembly from criminalising conduct interfering with Immigration"?
This makes no sense.

Let's change it to:
> nothing in this provision shall prevent the Assembly from criminalising conduct relating to (a) active interference with the work of the Public Administration, (b) immigration, (c) corruption, or (d) (1) conspiracy to engage in, (2) knowingly aiding or abetting, (3) attempting or threatening to commit, a criminal offence.

Criminal justice and elections would fall under the work of the PA. Corruption would cover bribery.

> §I.5. No provision of this Constitution shall be construed as to provide any legal justification for any act or omission which does not stem from the inherent right of self-defence but amounts to any physical, or constitutionally recognised form of non-physical~~,~~ **(remove comma)** violence towards (a) any person or ~~(b)~~ animal capable of conscious behaviour, or threat thereof, (~~c~~ **b**) invasion of privacy, (~~d~~ **c**) fraud, (~~e~~ **d**) direct and grave interference with enjoyment of one’s property or (~~f~~ **e**) harm to environment beyond the boundaries of one’s property; nothing in such provision shall be deemed to prevent the Assembly from criminalising such conduct.

This whole provision still sounds weird and unnatural to me as it covers random things within the same clauses. I think some of it could be moved to IX.3

**Comment by KacperZajc** [comment]
I was going to criminal justice [system], immigration [system], electoral **system**
my concern is 'the work of the PA' might be too borad

**Comment by terrorist96** [comment]
So let's narrow it: public duties of the PA
?

**Comment by KacperZajc** [comment]
§IX.3. No law shall prohibit any act or omission which does not directly harm any other Person or cause unwarranted suffering to an animal capable of conscious behaviour or harm to the environment beyond the boundaries of one’s property; nor shall any law prohibit any act or omission which has been validly consented to by another Individual; no Individual shall be considered a victim of one’s actions or omissions; nothing in this provision shall prevent the Assembly from criminalising conduct interfering with (a) the public constitutional functions of the Public Administration (b) attempting, preparing or threatening to commit (c) participating in or (d) benefiting from  a criminal offence.

participating covers all forms of participation 
public constitutional functions covers all 'systems' and bribery 
benefiting covers proceeds of crime

**Comment by terrorist96** [comment]
> §IX.3. No law shall prohibit any act or omission which does not directly harm any other Person or cause unwarranted suffering to an animal capable of conscious behaviour or harm to the environment beyond the boundaries of one’s property; nor shall any law prohibit any act or omission which has been validly consented to by another Individual; no Individual shall be considered a victim of one’s actions or omissions; nothing in this provision shall prevent the Assembly from criminalising ~~conduct interfering with~~ (a) **conduct interfering with** the ~~public~~ constitutional functions of the Public Administration, (b) attempting, preparing**,** ~~or~~ threatening to commit, ~~(c)~~ participating in~~,~~ **(delete comma)** or ~~(d)~~ benefiting from, a criminal offence.

I feel like we just need to add all these powers into one section instead of having them scattered throughout the constitution. Let's mention in one comprehensive provision what powers the Assembly has instead of saying 'nothing in this provision shall prevent..."

**Comment by KacperZajc** [comment]
possibly, I'll work on that
