### ISSUE TITLE
Vague laws

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#474]
Proposal: make it unconstitutional to pass vague/arbitrarily enforced laws.

https://en.wikipedia.org/wiki/Vagueness_doctrine

**Comment by KacperZajc** [comment]
yeah it sounds great but I dont think it is possible to articulate this doctrine properly in the Constitution
I think it has been already discussed, probably at the very beginning.

**Comment by terrorist96** [comment]
> All laws shall be specific vis-a-vis the Persons being regulated, the conduct being prohibited, and punishment that may be imposed; no law shall allow for arbitrary prosecution.

Just a rough draft.

**Comment by KacperZajc** [comment]
Any law creating obligations vis-a-vis any Person, shall contain a precise definition of such an obligation, a general scope of its application, available defences and minimum (if any) and maximum punishment that may be imposed for its breach.

'no law shall allow for arbitrary prosecution' - not sure why this?
