### ISSUE TITLE
Equal access to justice 

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#475]
Problem: having a more expensive lawyer will usually get people better outcomes in the Judicial system to the detriment of the destitute. All people should be equal before the eyes of the law. Justice is blind, so on

Solution: require all actions for engaging the court system to be nonexpensive and informal

**Comment by liberlandcitizen** [comment]
Are you suggesting price controls for legal representation?

**Comment by terrorist96** [comment]
Essentially, yes. It's not a free market entity, price controls shouldn't be a big deal.

**Comment by terrorist96** [comment]
No one said you can't buy the best lawyer. I don't mean that lawyers can't charge what they wish. Everything I'm proposing is the regulation of government, not the free market. If a poor person is accused of a murder he didn't do, he should be able to exonerate himself with a standard public defender. If exoneration can only be achieved with a $1000/hr lawyer due to the complexity of the legal system, then it's not right.

**Comment by KacperZajc** [comment]
§IV.18. Access to any Court of the Free Republic of Liberland shall not be impeded by any excessive formal, financial or other requirements.

Anything else would be excessive.
