### ISSUE TITLE
Civil Rights language unclear

### ISSUE THREAD

**Issue by AlbertMokrejs** [liberland/constitution#477]
> §V.3. Only Individuals above the age of twenty-one who hold citizenship of the Free Republic of Liberland shall have the right to submit his or her candidacy for a public office unless he or she has been convicted of a breach of law or the Constitution related to his or her previous position.

This could allow to individuals under 21 to submit their candidacy if they breach the law. Simplifying the language into blocks of logic:

> Only [People over 21] can [submit their candidacy] unless [they've been convicted of a crime]. 

I have two proposed alternate versions: 

> §V.3. Only Individuals above the age of twenty-one who hold citizenship of the Free Republic of Liberland and have not been convicted of a breach of law or the Constitution related to his or her previous position(s) shall have the right to submit his or her candidacy for a public office.

> §V.3. Individuals above the age of twenty-one who hold citizenship of the Free Republic of Liberland shall have the right to submit his or her candidacy for a public office. Individuals who have been convicted of a breach of law or the Constitution related to his or her previous position(s) forfeit this right.

**Comment by KacperZajc** [comment]
It's a good point.
I like your first version.

**Comment by AlbertMokrejs** [comment]
Thanks! I've made a pull request
