### ISSUE TITLE
Chapter IV special provision

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#482]
§XV.1. Notwithstanding any provision of this Constitution, the Cabinet shall have the exclusive power to sign binding international treaties regulating the flow of Persons, goods, services and capital across the border of the Free Republic of Liberland, and to directly enforce those treaties on the borders of the Free Republic of Liberland; such power shall be reviewable by the Civil Court only on the basis whether a treaty, and/or its enforcement, falls within the scope of this provision and whether the enforcement measures undertaken are the least intrusive measures available.  

I hereby open the discussion on the proper construction of this provision.
I hope everyone here understands why we need it, even if it is painful.
I will not repeat all those arguments again, please refrain from questioning the rationale behind the existence of this provision and instead focus on its construction.

**Comment by KacperZajc** [comment]
No once wants to comment? 
I was actually expecting a war here xD

**Comment by terrorist96** [comment]
I haven't had a chance to look at this yet. 

Don't we already allow treaties? Why are we restating it?

**Comment by KacperZajc** [comment]
You didn't catch my intention here.
This provision overrides constitutional freedoms.
This allows the Cabinet to control what goes out of the Republic so that our neighbours do not worry about drug trafficking, arms sales etc.
We have discussed a similar provision in the past, discarded for a time being.

**Comment by terrorist96** [comment]
Oh, basically this is saying the Constitution doesn't apply at the border crossing. Yeah, this was to be expected. I don't see any problems with the wording.

**Comment by liberlandcitizen** [comment]
I'm not happy about this, but I understand we are not to argue about it
here. So without arguing, please consider the following:

- If we use the term "across the border" that could be interpreted as both
IN and OUT of Liberland. I see no reason to restrict anything from coming
IN (except persons perhaps, and even then that should be done as part of
the normal constitutional process).

- Can we set this clause to sunset at some point? Once Liberland is
established we won't really need treaties to exist any longer. So why keep
this power?

**Comment by KacperZajc** [comment]
Im glad everyone is sensible :)

The problem is we might need to restrict the flow of capital IN so that we are not a place to do the money laundering or hide assets from taxes.
There might be more reasons, this is just from top of my head.

The problem with the sunset clause is that it will lead to impossible pressure (or military intervention) from the neighbouring states when it will come to renewal.

**Comment by liberlandcitizen** [comment]
What I hope to sunset is this *power* to make treaties, not the treaties
themselves.

**Comment by liberlandcitizen** [comment]
To expand upon my last comment, I think we should consider if there's a
long-term benefit to having this awesome power in the hands of so few.
Obviously in the first few years of Liberland, we may need to push through
treaties just to exist. But once our nation is established and recognized,
there will no longer be a need to push through any such treaties.

We can keep the existing ones intact and keep in mind that there is a way
to create new treaties under our current constitution.

**Comment by KacperZajc** [comment]
§XV.1. Notwithstanding any provision of this Constitution, the Cabinet shall have the exclusive power to sign binding international treaties regulating the flow of Persons, goods, services and capital across the border of the Free Republic of Liberland, and to directly enforce those treaties on the borders of the Free Republic of Liberland; such power shall be reviewable by the Civil Court exclusively on the basis whether a treaty, and/or its enforcement, falls within the scope of this provision and whether the enforcement measures undertaken are the least intrusive measures available; the power described in this provision shall expire within 30 years after the Constitution enters into force, any and all treaties signed until the date shall remain fully valid.

???

**Comment by liberlandcitizen** [comment]
I appreciate you adding the sunset to this. Any chance we can reduce it? :)

I think two to five years would be plenty of time to make treaties with our
neighbors. After that point, I think we will be well established around the
world and close friends with our neighbors and any additional treaties
could make their way through government the normal way.

**Comment by KacperZajc** [comment]
Im leaving open for the debate, this is a major issue.

**Comment by terrorist96** [comment]
> the power described in this provision shall expire within thirty years after the Constitution enters into force~~,~~ **;** **(change to semicolon)** any and all treaties signed ~~until~~ **prior to** the **expiration** date shall remain fully valid and enforceable **unless otherwise repealed**.

**Comment by KacperZajc** [comment]
@terrorist96 any comments apart from grammar?

**Comment by KacperZajc** [comment]
I do love our subtle references to the Founding Fathers :)

However, my general concern is, with the sunset clause in general, that circumstances will change over time, maybe our neighbours will change their statehood, maybe some new country will raise, and we will end up without the necessary power to make new treaty with them.

The ordinary ratification process is not adequate as it does not override the Constitution.

**Comment by terrorist96** [comment]
Your argument can be used against your 30 year proposal as well. We would have to allow for this power indefinitely then.

**Comment by KacperZajc** [comment]
I know that is why we are debating this issue here xD

**Comment by terrorist96** [comment]
So let's take something like human trafficking across the border. That's something we'd want to prevent. There are many existing treaties that the government could join without the need for the special powers in this section. 
https://en.wikipedia.org/wiki/Category:Human_trafficking_treaties

I think 19 years is plenty of time for the PA to get their affairs in order. Any treaties can still apply to any new countries that may form in the future. And outside of that, I'm sure the general, permanent treaty power can be made sufficient to apply in any situations in the future.

**Comment by liberlandcitizen** [comment]
What good is it to even have a country if our freedoms and liberties can be
overridden because a new neighbor popped up and made demands?

It is my expectation that should Liberland get to exist, it will be because
of negotiations with our neighbors *prior* to entering the land and *prior*
to this constitution going into effect. We could probably even hard code
their greatest concerns into the constitution if it means they will give us
access to our land. That is assuming it's things that we can live with and
probably even agree with, such as no human trafficking or child
pornography.

But I will argue again that once our nation exists and is internationally
recognized, we won't have to worry about our neighbors. We'll be
sovereign, independent and prosperous. And again, if our security is in
such great jeopardy, there is a method for making treaties.

Lastly, I'd like to point out that borders have two sides and any neighbors
can have strict controls along our border into their country.
