### ISSUE TITLE
salary of the Assembly Representatives

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#483]
I have come to the conclusion that the best option would be to make the Assembly Representatives unpaid.

Who is for and who is against?

see #401

**Comment by liberlandcitizen** [comment]
I'm for.

The hope is that government will be so small, there won't be much need for
the Assembly Representatives to meet often anyway. They can continue with
the private/professional lives and for this reason, it seems reasonable not
to pay them.

**Comment by terrorist96** [comment]
Unpaid is better than overpaid.

**Comment by Auahi** [comment]
I disagree, ARs won't be making much money to begin with, (Max 5% of Annual Budget for all ARs combined) and if someone's doing a job they should get paid for it. Even though it doesn't look like much work on paper their jobs will be more than just them going to a meeting and that's it.

**Comment by liberlandcitizen** [comment]
People do jobs without getting paid all the time...volunteer work. I think
plenty would feel a civic duty and would be willing to serve without pay.

**Comment by KacperZajc** [comment]
Ideally, as we design it, the Assembly will not be in session often or for long.

**Comment by Auahi** [comment]
Yes that might be true but that doesn't consist of the entirety of the work of a member of parliament. They have many conferences and meetings with the community companies and other members of government. I think you should leave this in the constitution and allow the ARs to take t out if they see fit
