### ISSUE TITLE
transfer of provisions

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#485]
I propose we transfer those provisions from Article IX to Article I.
They are very general in nature and Article IX is already too long.
On the other hand, Article I will get shorter once we introduce Chapter IV.

Provisions:

§IX.3. No law shall prohibit any act or omission which does not directly harm any other Person or cause unwarranted suffering to an animal capable of conscious behaviour or harm to the environment beyond the boundaries of one’s property; nor shall any law prohibit any act or omission which has been validly consented to by another Individual; no Individual shall be considered a victim of one’s actions or omissions; nothing in this provision shall prevent the Assembly from criminalising conduct interfering with the constitutional functions of the Public Administration or attempting, preparing, threatening to commit, participating in, and benefiting from, a criminal offence.

§IX.16. Any law creating an obligation vis-a-vis any Person, shall contain a precise definition of such obligation and all of its elements, a general scope of its application, available defences and minimum (if any) and maximum punishment that may be imposed for its breach.

§IX.19. No law shall retroactively change the legal consequences and/or status of actions that have been already committed, or relationships that already existed, before the enactment of said law.

**Comment by terrorist96** [comment]
I'm fine with that. As long as the sections exist, I don't care where you put them.
