### ISSUE TITLE
community work

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#486]
I think we need to create an exception for court-ordered community work:

§X.9. No relationship amounting to slavery or any other form of involuntary servitude shall exist between any legal or natural Person and any other Person; no conscription or any other form of compulsory service shall be introduced by any branch of the Public Administration other than community work ordered by the Criminal Court as a part of the sentence upon conviction by Jury; no Persons shall be convicted of any criminal offence for the failure to fulfil his or her contractual obligations.

???

**Comment by terrorist96** [comment]
Good idea. I always figured it was implied.
