### ISSUE TITLE
right to know about a warrant

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#488]
> §VIII.2. No Person shall have his or her privacy violated by freezing of assets, searches, seizures, surveillance, accessing and gathering of his or her private personal information without his or her express and informed consent, including obtaining it from third parties and/or using digital means, unless pursuant to a Warrant, and only to the extent which is necessary to achieve the purpose for which the Warrant was issued and particularly describing the assets to be frozen, the places or Persons to be searched, the things or Persons to be seized, the Persons to be put under surveillance, including the maximum period of that surveillance, and the data to be obtained and stored, including the period for which it may be retained; nothing in this provision shall prevent the collection of information which has been made available to the public or shared voluntarily.

I propose we add a clause that states that when your things do get accessed due to a warrant, you should be notified of that. This is to prevent police from secretly hacking someone's computer and copying files. The person should be aware of the warrant.

**Comment by liberlandcitizen** [comment]
I second this.

**Comment by KacperZajc** [comment]
I agree where it is a one-off search.
What about warrants for continuing surveillance?

**Comment by terrorist96** [comment]
> What about warrants for continuing surveillance?

That can be an exception to the rule.

**Comment by liberlandcitizen** [comment]
<<What about warrants for continuing surveillance?>>

You should be notified once. If the surveillance is to continue you should
be notified of that as well, but only once.

**Comment by KacperZajc** [comment]
I think notifying sb about continuing surveillance defeats the purpose.
We need to be realistic. 
I propose we make it compulsory to notify about warrants once they are completed - which is immediately after a one-off search and immediately after a warrant for continuing surveillance expires (even if no charged have been brought at this point).

**Comment by liberlandcitizen** [comment]
Good point, but how long can the surveillance go on for? Can it be years or
even decades? And does the court review/renew this warrant during this time
or could it be just one judge signing off on perpetual surveillance? And
all the while, the person is never informed.

**Comment by KacperZajc** [comment]
This is not a problem:

§IX.2. All Warrants for the purposes of criminal proceedings, other than the Supreme Warrant, shall be issued by a Judge of the Criminal Court upon request by an Agent of Law Enforcement and shall be supported by evidence of probable cause; such Warrants shall be as detailed as possible and shall refer to one Person only; every Warrant granted for a continuous action shall expire no later than after one year and shall be renewed by another Judge in accordance with ordinary procedure.

**Comment by liberlandcitizen** [comment]
I forgot about that, thanks. With that protection, I agree it makes sense
to notify people about warrants once they are completed.

**Comment by KacperZajc** [comment]
So this is what I propose:
(including shortening the maximum period) 

§IX.2. All Warrants for the purposes of criminal proceedings, other than the Supreme Warrant, shall be issued by a Judge of the Criminal Court upon request by an Agent of Law Enforcement and shall be supported by evidence of probable cause; such Warrants shall be as detailed as possible and shall refer to one Person only; every Warrant granted for a continuous action shall expire no later than after six months and shall be renewed by another Judge in accordance with ordinary procedure; any Person subject to a Warrant shall be informed with no delay of its execution unless in case of a Warrant granted for a continuous action which has been renewed.

**Comment by terrorist96** [comment]
So a warrant for continuous action is required to be reported to the person unless it's renewed 6 months later? Well the person will already know. Since you say the person should be informed without delay.

**Comment by KacperZajc** [comment]
It was meant to mean that after 6 months (if a Warrant is NOT renewed) a Person would informed without delay
If it is renewed, then this Person is to be informed after the next 6 month period (unless it is renewed again) 
apparently it is not clear from the wording xD

**Comment by KacperZajc** [comment]
§IX.2. All Warrants for the purposes of criminal proceedings, other than the Supreme Warrant, shall be issued by a Judge of the Criminal Court upon request by an Agent of Law Enforcement and shall be supported by evidence of probable cause; such Warrants shall be as detailed as possible and shall refer to one Person only; every Warrant granted for a continuous action shall expire no later than after six months and shall be renewed by another Judge in accordance with ordinary procedure; any Person subject to a Warrant shall be informed with no delay of its execution or, in case of a Warrant for continuous action, once such a Warrant has expired and is not renewed.

???

**Comment by terrorist96** [comment]
> §IX.2. All Warrants for the purposes of criminal proceedings, other than the Supreme Warrant, shall be issued by a Judge of the Criminal Court upon request by an Agent of Law Enforcement and shall be supported by evidence of probable cause; such Warrants shall be as detailed as possible and shall refer to one Person only; every Warrant granted for a continuous action shall expire no later than after six months and shall be renewed by another Judge in accordance with ordinary procedure; any Person subject to a Warrant shall be informed ~~with no~~ **without** delay of its execution or, in case of a Warrant for **a** continuous action, once such ~~a~~ Warrant has expired and is not renewed.

**Comment by KacperZajc** [comment]
okk
