### ISSUE TITLE
Self-Incrimination clause

### ISSUE THREAD

**Issue by Auahi** [liberland/constitution#489]
Does the constitution have an anti-self-Incrimination clause? If not should we write one? 

If it does disregard this. I'm on my phone and I can't search well....

**Comment by KacperZajc** [comment]
of course it does

§IX.14. All defendants in criminal proceedings shall have the right to be presumed innocent until proven guilty and to not be compelled to be a witness against himself or herself, or such other Persons as may be prescribed by law, without any negative inference; the Prosecution shall always carry the legal burden of proof, discharged beyond reasonable doubt, in relation to the defendant's guilt, including disproving any defence envisaged by the law which he or she might raise; nothing in this provision shall prevent the creation of defences which require the defendant to discharge the evidential burden of proof by raising the issue of defence available to him or her.
