### ISSUE TITLE
Judicial Appointment Commission (again)

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#494]
I have come up with a solution that combines best qualities of both election and appointment systems:

§IV.6. The Judicial Appointment Commission shall appoint qualified lawyers for the positions of Judges of the Civil Court and the Criminal Court.
•	§IV.6(1) The Judicial Appointment Commission shall be composed of nine members appointed or elected for a six year term:
•	§IV.6(1)(a) three members appointed by the Chief Justice of Supreme Court;
•	§IV.6(1)(b) three members appointed by the Chief Attorney of the Republic;
•	§IV.6(1)(c) three members elected by the Citizens of the Free Republic of Liberland.
•	§IV.6(2) The Judicial Appointment Commission shall sit en banc and it shall reach its decisions with no fewer than seven votes.
•	§IV.6(3) No Person shall hold the office of any Judge, Justice or the Chief Justice of the Supreme Court whilst holding any other public office within the legislative or executive branch of the Public Administration concurrently.

We will have citizens elected to the Commission who will be able to prevent undesirable persons from being appointed for judgeship by other (non-elected) members of the Commission.

**Comment by Auahi** [comment]
This doesn't really change much, all it does is allow the citizens to elect fewer judges. The J.A.C. would not overturn the citizens vote on the elected judges because they would never be elected back into office by the citizens.

**Comment by KacperZajc** [comment]
there is no election of judges under the current draft, that is the point

**Comment by Auahi** [comment]
I know. Even though I'd like the election of judges to be handled democratically, the outcome of these elections are undesirable.

**Comment by Auahi** [comment]
I just reread the provision. I like the idea but I think it over complicates everything, no?

**Comment by KacperZajc** [comment]
nah, it's simple

**Comment by terrorist96** [comment]
I like it. Especially since you made the vote threshold 7, so the vote of at least 1 of 3 citizen-elected persons is needed.

**Comment by KacperZajc** [comment]
exactly my point here :)
