### ISSUE TITLE
torture provision

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#495]
I think we need to remove the word 'knowledge' from this provision.

As it stands now, a person can be tortured and then perpetrator can inform law enforcement about that and it is potentially a reason to exclude any evidence pertaining to torture because it was conducted 'with knowledge of Agents of PA'. 

Another situation would be torture conducted in front of Law Enforcement, yet against their will (e.g. hostage situation) by a 3rd party. Again it would be potentially a reason to exclude such evidence.

It is a loophole. 

§IX.16. No torture or cruel or degrading treatment shall be inflicted by any Agent or Member of the Public Administration or under the supervision or approval thereof against any Person; nor shall any Person be rendered to any state or group should there be a reasonable suspicion that the aforementioned may inflict such treatment on such Person; nor shall any experiments, medical or otherwise, be conducted against any Person without his or her express and informed consent; no Individual shall be medically examined or otherwise tested unless pursuant to a Warrant or with the Individual's express and informed consent.

**Comment by Auahi** [comment]
I think we should add: 

_**life threatening treatment**_

 as well. Even if a person did a horrendous act, I don't think any government should have the power to kill a person.

**Comment by KacperZajc** [comment]
the question of the capital punishment remains open, the constitution will be silent on it

**Comment by Auahi** [comment]
I know that the constitution should be silent on drugs other controversial things of the like, but isn't it unlibertarian to give the government so much power to where they can choose to kill someone? It goes against the concept of limited government, libertarianism, and the principals of Liberland. I think something so important like this should be included in the constitution.

But hey, that is just my two cents.

**Comment by liberlandcitizen** [comment]
A government so powerful that they can take your life is a government too
powerful for my taste. The best way to tell if a country respects human
rights is to look at how it treats its criminals.

If capital punishment is legal in Liberland, an innocent person WILL die.
It's just a matter of time before somebody who was falsely convicted gets
it. And the world will laugh at our "libertarian" country where the
government is "so small" it kills innocent people.

**Comment by KacperZajc** [comment]
Im not saying it should or should not be legal, I just want to leave it to the Assembly, that's it

**Comment by liberlandcitizen** [comment]
If we don't address it in the constitution, then as the default state it
will be legal, correct?

**Comment by KacperZajc** [comment]
the Assembly must legislate all penalties for all criminal offences so it would have to go through the legislative process in any event

**Comment by Auahi** [comment]
Currently 103 countries have a complete ban on the death penalty, 43 countries had a constitutional ban (From an amnesty internal pdf from 2005). I find it ironic that we're even debating constitutionally banning capital punishment for the world's only **Libertarian** country.

**Comment by KacperZajc** [comment]
And all of them are filled with socialism, yet we want to be special.
The majority argument is no argument at all here.
We are not creating any constitutional ban on the capital punishment, we will leave it for the Assembly to decide.
I have opened this issue to discussion a procedural problem in this provision, not a the death penalty.

**Comment by terrorist96** [comment]
Looks like this got sidetracked. I agree the word `knowledge` can cause an issue here. How about we replace it with `approval`?

**Comment by KacperZajc** [comment]
thank you for sticking to the subject
I like 'approval'
