### ISSUE TITLE
proceedings concerning warrants

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#496]
§VI.5. All affairs of the Assembly, other than the debate and vote on the classification of information as a state secret, and all proceedings of the Courts, other than those involving information classified as state secret and Warrants concerned with Agents of Law Enforcement operating undercover, shall be recorded and transmitted contemporaneously as well as archived and made available to the general public to attend; all Bills passed by the Assembly and all verdicts and decisions given by all Courts of the Free Republic of Liberland shall be archived and published.

The warrant bit is problematic. When we consider for example warrants for surveillance, such proceedings cannot be public.

**Comment by KacperZajc** [comment]
I propose simplified version:

§VI.5. The Public Administration shall conduct its business openly by recording, transmitting, archiving, publishing and rendering  available to the general public to attend (a) all affairs of the Assembly other than other than those concerned with the classification of information as a state secret and all proceedings before the Courts other than those concerned with Warrants.

**Comment by terrorist96** [comment]
> nothing in this provision shall prevent the Public Administration from protecting information classified as a state secret.

This doesn't cover the vote for whether something should be classified. It has to be classified already for it to have the protection.

Solution:
 > (a) all affairs of the Assembly other than the debate and vote on the classification of information as a state secret,

**Comment by KacperZajc** [comment]
good point
