### ISSUE TITLE
judicial review

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#497]
I want to transfer the right to institute judicial review from Article I to Article IV.

§IV.20. All administrative decisions of any branch of the Public Administration, and actions undertaken by its Agents, which are capable of affecting any Person may be subject to challenge in the Civil Court by such a Person.
§IV.20(1) All Executive Measures issued by the Cabinet may be subject to challenge in the Civil Court by a Person affected thereby or, in the absence of such a Person, by any association composed of no fewer than thirty Citizens.
§IV.20(2) Without prejudice to the appeal procedures, such challenge shall be admissible once only unless the original challenge was not genuine but brought in order to shield the defendant from liability or where a new challenge raises a different point of law.
§IV.20(3) The right described in this provision shall be exercisable once all administrative appeals have been exhausted.

**Comment by terrorist96** [comment]
> §IV.20. All administrative decisions of any branch of the Public Administration, and actions undertaken by its Agents, which are capable of affecting any **Person, may** be subject to challenge in the Civil Court by such a Person.

Remove comma in bolded part

> §IV.20(1) All Executive Measures issued by the Cabinet may be subject to challenge in the Civil Court by a Person affected thereby or, in the absence of such a **Persons**, by any association composed of no fewer than thirty Citizens.

Should be singular, not plural. Or remove `a` prior it and keep it plural.

**Comment by KacperZajc** [comment]
okk
