### ISSUE TITLE
registers

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#498]
I decided to bring all register exceptions into one place:

§XV.4. Notwithstanding any provision of this Constitution, the Public Administration shall have the power to maintain, fully public where appropriate, (a) a register of all land, its owners and charges, (b) a register of all deaths and births of Citizens and other Residents of the Free Republic of Liberland, (c) a register of all vehicles intended to be used outside the territory of the Free Republic of Liberland, (d) a register of all incorporated business entities for the purposes of conferring upon them a separate legal personality, (e) a register of all Citizens who have been issued passports of the Free Republic of Liberland, (f) a register of all Persons convicted of any criminal offence in the Free Republic of Liberland, (g) a register related to immigration procedure, and (h) the Electoral Register.

This will simplify several provisions by removing 'register' exceptions to them.

**Comment by terrorist96** [comment]
You'll need to add `a` at the beginning of all the registers.

> **(a)** register of all land

> (d) register of all incorporated business entities for the purposes of conferring **up**on them a separate legal personality

**Comment by KacperZajc** [comment]
okk
