### ISSUE TITLE
right to communication and counsel

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#499]
IX.4 and IX.14 rephrased and simplified:

All Persons held against their will by the Public Administration under any circumstances whatsoever shall have the right to communicate with relatives and other Persons as may be prescribed by law, in person and/or using indirect means of communication, unless there be reasonable suspicion that so doing is likely to interfere with the course of justice and a Warrant preventing the communication on such grounds has been issued.

All Persons held against their will by the Public Administration under any circumstances whatsoever shall have the right to be assisted by effective legal counsel and an interpreter, should they not speak the language of interrogation or court proceedings, and in case of trial, to have reasonable time for the preparation of their case; services of a counsel and an interpreter shall be contracted personally or, in criminal proceedings where a Person is not able to afford it, they shall be provided by the Secretariat of the Judiciary with the possibility to subsequently recover reasonable expenses should a defendant be convicted and the verdict not be overturned by the Supreme Court.

**Comment by terrorist96** [comment]
I'm hoping that the `right to privately contact legal counsel` is implied here. Otherwise, :+1:

**Comment by KacperZajc** [comment]
it's covered by the second provision  - 'be assisted'
this way the first provision is more about private life and the second provision is more about fair trial rights
