### ISSUE TITLE
Officeholder numbers should be relative to number of citizens

### ISSUE THREAD

**Issue by joshmh** [liberland/constitution#5]
"The Assembly shall consist of twenty Assembly Representatives."

This number is too high for a population of 100. I suggest about one officeholder for each 3,000 citizens, with a minimum number of 5 representatives.

**Comment by Zephram-C** [comment]
This could lead to fluctuation in the number of officeholders. If population decreases who shall be removed? If it increases does it always mean new elections?

**Comment by joshmh** [comment]
The adjusted number would apply at the next elections.

**Comment by Zephram-C** [comment]
Hmm, could still lead to "strategic" changes of population just before elections. (Especially if citizenship can be online.) 
But thinking about the right number, I was thinking that perhaps odd number (or prime number) of representatives would solve tie-situations and give clear majorities..

**Comment by tinkyholloway** [comment]
You could make it that franchise be available only to those who have held citizenship for at least one Assembly term.

**Comment by KacperZajc** [comment]
Vit said it should be 20, let it be 20 for now

**Comment by KacperZajc** [comment]
the constitution is to be adopted after the first general election and there will be no election with 100 people only
