### ISSUE TITLE
criminal offences of public officials 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#501]
§IV.15. Should a criminal offence be allegedly committed by a Member or Agent of the Public Administration in the course of his or her official duties, and no one Victim has been left by such an offence, a public prosecution may be instituted.
§IV.15(1) Where no public prosecution has been brought within a reasonable period of time, a private prosecution may be brought by any association composed of no fewer than thirty Citizens.
§IV.15(2) Where a private prosecution is instituted in place of a public prosecution, the Office of the Public Prosecutor shall fully cooperate with the association in charge of the proceedings.

[renumbering] 

This provision will make our private prosecution system comprehensive:
1) victim (public/private offender) - > private prosecution or (if requested) public prosecution
2) no victim (private offender) -> public prosecution
3) no victim (public offender) -> public prosecution or (if failure to institute such) private prosecution of 30 citizens 

This way we make sure that public officials do not act with impunity by pressuring the Office of the Public Prosecutor to drop the charges.

**Comment by terrorist96** [comment]
I can see your motivations behind this *ahem Hillary Clinton ahem* :stuck_out_tongue_closed_eyes: 

This provision seems related:

> §II.11(7) Should any Agent or Member of the Public Administration be found by the Assembly Committee to be in breach of the rules of conduct binding him or her in the official capacity, the Committee shall have the power to punish him or her financially according to the relevant law; testimonies given in breach of oath shall be prosecuted in a regular manner in the Criminal Court.

Also, since we're using `allegedly`, I think the following sections should have `allegedly` added too.

> §IV.13. The Victim of **an alleged** criminal offence shall have the inherent right to institute a Private Prosecution of an accused Person.
§IX.11 ...should said Person escape or **allegedly* commit any subsequent criminal offence, a new Warrant for custody may be issued.
§X.1. The powers of arrest in the Free Republic of Liberland shall not be exercised arbitrarily but only upon **allegations of** probable cause that the detainee (a) has committed or (b) is committing a criminal offence...

**Comment by KacperZajc** [comment]
Yes this provision is partially motivated by Hillary Clinton but dont get me started on her :D 

§II.11(7) would allow the Assembly to take a closer look into the work of the Prosecutor which have refused to prosecute sb he or she should have prosecuted.

Good point about 'allegedly'

**Comment by liberlandcitizen** [comment]
<<a private prosecution may be brought by any association composed of no
fewer than thirty Citizens.>>

In my opinion this is putting enormous power into the hands a very small
number of unelected people. It's hard enough to expect elected officials to
be moral, but any group of 30 immoral or crazy people can prosecute a
Member or Agent of the Public Administration? While the intentions may be
good, I can foresee this being grossly overused and abused.

**Comment by terrorist96** [comment]
If an actual crime occurred, what's wrong with that? And if it's an abuse, that can be determined in the preliminary hearing and the case can be dismissed, and if found frivolous, the suing organization will be required to pay the defense's legal fees.

Think of it as Judicial Watch would be able to bring charges against Hillary Clinton since the FBI has refused to recommend prosecution.

**Comment by KacperZajc** [comment]
It can easily be struck down at a Preliminary Hearing.
Double jeopardy kicks in and costs are paid by the association.
No harm done.

**Comment by liberlandcitizen** [comment]
<<If an actual crime occurred, what's wrong with that?>>

Sure...it'd be great for the times when an actual crime occurred, but I
forsee groups of people using this to get even with political opponents
over and over again despite knowing no crime has actually been committed.
Think of a politician that is hated in your country. Imagine 30 people
could take that person to court over and over again as part of the
constitution. You just know they would be raising money to make that
happen, just to get at the politician.

**Comment by terrorist96** [comment]
But the politician would win in court every time and have their fees paid. Additionally, the court has discretion on sanctioning organizations that abuse the judicial process. And double jeopardy applies as well,as Kacper mentioned

**Comment by liberlandcitizen** [comment]
​We all share a mistrust of politicians, and rightly so but we should be
careful not to go too far in the other direction. Even if you win and have
fees paid, going to court constantly is a huge hassle. If we make it too
stressful for our elected officials, nobody in their right mind would be
willing to hold the office. We would end up with crazies and weirdos only. ​

**Comment by KacperZajc** [comment]
Double jeopardy applies, there will be no trying over and over again.

**Comment by liberlandcitizen** [comment]
Double jeopardy is for one alleged crime at a time, right? They could be
making up new bogus charges every week.

**Comment by terrorist96** [comment]
And that's when a court can sanction the organization.

**Comment by liberlandcitizen** [comment]
The threshold of 30 people is far too small. A motivited political movement
could find 30 fresh people to bring about new bogus charges every week. I'm
all for giving power to the people to take out corrupt officials, but
allowing a mere 30 unelected citizens to have this much power seems
rediculous to me.

I could forsee "how to" guides on the internet for bringing Liberland
politicans to court. In a heated political climate I'd wager that every
last assembly member would be brought to court weekly on made-up charges.
Sure, maybe most of them would be dismissed, but our system of government
would grind to a hault from this and I can't imagine many would want to be
a part of the government when facing weekly criminal charges.

I beg of you, image this were the law in your own country. How easily and
frequently would a mere 30 people in your country make use of this? In my
country it would be hourly.

**Comment by KacperZajc** [comment]
You keep forgetting about the double jeopardy.
Even if this principle is to be bypassed by bringing prosecution on the basis of other criminal offences, they would quickly run out of criminal offences anyway.
You are panicking in vain.

**Comment by liberlandcitizen** [comment]
I'm imaginging they will bring charges for rediculous things and find new
things each day. For example, for each new donation a politician takes, it
could be claimed that it was a bribe.
