### ISSUE TITLE
Grand Juries?

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#502]
We make no mention of grand juries or indictments in the Constitution. Will prosecutors have full autonomy on deciding on prosecution?

In America, the prosecutor decides on prosecution. If he wants to prosecute, he presents the evidence to a Grand Jury. They decide whether or not the person deserves to be indicted.

Also, would the act of presenting evidence to a grand jury constitute `prosecution`? I would think it's more so `attempted prosecution`.

**Comment by KacperZajc** [comment]
I think we dont need Grand Juries.
Our primary mode of prosecution is private.
Then public prosecution is compulsory if requested by the Victim.
No we add this provision on public prosecution of public officials.
I think we have created alternative mechanisms for situations in which normally Grand jury is called in the US.
