### ISSUE TITLE
Preliminary Hearings

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#503]
§IV.16. Where a defendant in criminal or civil proceedings considers the claim or prosecution against him or her to be fundamentally flawed, he or she shall have the right to request the Civil Court or Criminal Court to hold a Preliminary Hearing.
§IV.16(1) Preliminary Hearings shall be held by one Judge of the relevant Court.
§IV.16(2) The Judge at the Preliminary Hearing shall dismiss the case before it proceeds to a full trial where:
§IV.16(2)(a) no probable cause has been proven to the satisfaction of the Court;
§IV.16(2)(b) he or she is satisfied beyond reasonable doubt that the claim or prosecution would be contrary to the Constitution;
§IV.16(2)(c) defendant's procedural rights as laid down in the Constitution and/or any laws passed in accordance therewith have been violated and such a violation has prejudiced his or her case.
§IV.16(3) The Judge at the Preliminary Hearing shall have the power to issue such Warrants and Orders as deemed necessary and within the powers of the relevant Court; such Warrants and Orders shall be reviewable at a full trial.
§IV.16(4) Should a claim or a prosecution be dismissed for frivolity at a Preliminary Hearing, the plaintiff or the prosecutor shall ordinarily be ordered to cover all reasonable expenses of the defendant connected to his or her legal defence as well as all court fees unless there is compelling reason otherwise.

§IV.2. The Courts of the Free Republic of Liberland shall consist of the Civil Court, Criminal Court and the Supreme Court.

[renumbering]

As it stands now the Grand Jury (#502) could be used under §IV.8(2)(a). Alternately, a Judge can determine the issue. This way we leave it to the law to regulate this further.

**Comment by terrorist96** [comment]
Shouldn't preliminary hearings be required by default? If not, why not?

> §IV.16. Where a defendant in criminal or civil proceedings considers the claim or prosecution against him or her to be fundamentally flawed, he or she shall have the right to ~~request~~ **demand** the Civil Court or Criminal Court to hold a Preliminary Hearing.

This removes the option for the court to deny a preliminary hearing.

> §IV.16(2)(b) he or she is satisfied beyond reasonable doubt that the claim or prosecution would be contrary to the Constitution;

Wouldn't this turn innocent until proven guilty on its head? The judge has to be satisfied beyond reasonable doubt that the prosecution is unconstitutional? I think the standard should be lowered.

> §IV.16(2)(c) defendant's procedural rights as laid down in the Constitution and/or any laws passed in accordance therewith have been violated **and such a violation has prejudiced his or her case**.

The bolded part seems like a trojan horse to me. It can be used to basically nullify the former clause.

**Comment by KacperZajc** [comment]
§IV.16. All civil and criminal proceedings shall be preceded by a Preliminary Hearing held by one Judge of the relevant Court.
§IV.16(1) The parties to the proceedings at the Preliminary Hearing shall enter their positions in relation to the claim or prosecution against them.
§IV.16(2) The Judge at the Preliminary Hearing shall have the power to issue preliminary Warrants and Orders within the powers of the relevant Court which shall be reviewable at a full trial.
§IV.16(3) The Judge at the Preliminary Hearing shall dismiss the case before it proceeds to a full trial where:
§IV.16(3)(a) no probable cause has been proven to the satisfaction of the Court;
§IV.16(3)(b) he or she is satisfied that the claim or prosecution would be contrary to the Constitution;
§IV.16(3)(c) defendant's procedural rights as laid down in the Constitution and/or any laws passed in accordance therewith have been violated and such a violation has prejudiced his or her case.
§IV.16(4) Should a claim or a prosecution be dismissed for frivolity at a Preliminary Hearing, the plaintiff or the prosecutor shall ordinarily be ordered to cover all reasonable expenses of the defendant connected to his or her legal defence as well as all court fees unless there is compelling reason otherwise.

"and such a violation has prejudiced his or her case" - this part is necessary IMO. Otherwise any small, presumably inadvertent breach, would lead to dismissal. 
Plus, evidence obtained in breach of law is excluded anyway so even though it is not employed, the breach itself would lead to dismissal. 
We should leave it to the judge to ascertain the consequences of the breach, then to the trial judge and then to the Supreme Court on appeal.
