### ISSUE TITLE
Motion of Confidence

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#505]
§II.10. The Assembly shall elect the Chancellor of the Free Republic of Liberland, who shall form the Cabinet of the Free Republic of Liberland, with a simple majority vote of the overall number of Assembly Representatives.
§II.10(1) Should no Chancellor be elected within thirty days of a General Election, a new General Election shall be held within sixty days.
§II.10(2) The Assembly shall have the power to impeach the Chancellor along with the Cabinet by passing a Motion of No Confidence with a simple majority vote of the overall number of Assembly Representatives provided there is a simple majority for a prospective successor.
**§II.10(3) On the first meeting after the General Election, the Chancellor along with the Cabinet shall request the Assembly to vote on the Motion of Confidence.
§II.10(4) Should the Assembly fail to pass the Motion of Confidence with a simple majority vote of the overall number of Assembly Representatives, the Chancellor along with the Members of the Cabinet shall immediately cease to hold their offices.**

I think we dont need §II.10(3) and §II.10(4). If the newly elected Assembly wants to change the Chancellor, they can do it under §II.10(2). Plus, impeachment under §II.10(4) can result in interregnum and political chaos whereas impeachment under §II.10(2) is a smooth change of the gov by impeaching the old Chancellor and electing the new one at the same time.

The same goes for:

§III.5. Should the Chancellor become unable to perform one’s duties, the Members of the Cabinet shall, amongst themselves, elect the Vice-Chancellor with a simple majority vote.
§III.5(1) The inability of the Chancellor to perform one’s duties shall be declared by the Supreme Court upon request by a simple majority of all Members of the Cabinet.
§III.5(2) The Vice-Chancellor shall perform the duties of the Chancellor until his or her return or resignation upon the Assembly’s failure to pass a Motion of Confidence.
§III.5(3) Should the Chancellor's ability to return be in question, the Vice-Chancellor shall request the Supreme Court to rule on the issue.
**§III.5(4) Should the Chancellor not be able to return within sixty days, the Vice-Chancellor shall request the Assembly to pass the Motion of Confidence.
§III.5(5) Should the Assembly fail to pass the Motion of Confidence with a simple majority vote of the overall number of Assembly Representatives, the Vice-Chancellor along with all Members of the Cabinet shall cease to hold their office and the Assembly shall elect the new Chancellor in accordance with Article II.**

If the Assembly is not satisfied with the Vice-Chancellor, they can pass the Motion of No Confidence under §II.10(2) and replace him with a new figure.

**Comment by terrorist96** [comment]
So the only change here is that the Assembly will have autonomy on whether or not it wishes to vote on a MoC instead of being required to do so at the beginning of every session. I don't know, I kinda like having the Assembly be required to be on record every session regarding their views on the Chancellor.

**Comment by KacperZajc** [comment]
I think it is unnecessary and might create a deadlock when they impeach the current Chancellor but will not be able to put together a majority for another candidate to replace him. 
These changes will also simplify the whole process.
