### ISSUE TITLE
limitation on freedom of contract 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#507]
§XV.5. Notwithstanding any provision of this Constitution, the Courts of the Free Republic of Liberland shall not enforce any contract for (a) a permanent service, (b) sexual services, (c) a transfer of parental rights, (d) a restrain of trade, (e) a participation in a criminal offence or (f) a marriage; in cases of contracts for a specific performance, should the performing Person refuse to comply with the terms of such a contract, it may, where appropriate, be enforced by way of financial repatriation instead.

Some of those limitations have been implied in the Constitution but I think they should be expressly stated and some further limitations should be added.

[I have modelled this provision after Hayek's views on the freedom of contract]

**Comment by liberlandcitizen** [comment]
​A few concerns I have with this language:

<<(a) a permanent service>>

If you mean slavery, why not just say slavery? There are legit services
that have lifetime (permanent) service and perhaps this language is
confusing? For example, a satellite company could contract with you for
lifetime television service.


<<(b) sexual services>>

Is this to say that prostitution would be illegal in Liberland?


<<(c) a transfer of parental rights>>

I assume that this is to protect against people selling their children for
profit? Noble, but what about in cases of death? What about in cases where
you have personal problems and can no longer care for your children? Should
you not have the right to transfer the rights to somebody better if you so
choose, in the interest of the child? Should the state be in charge of
deciding these things, and if so would the state do a better job than the
actual parents?


<<(d) a restrain of trade >>

This deserves a discussion/debate.


<<(e) a participation in a criminal offence>>

But is something still criminal if all parties involved consent?

**Comment by KacperZajc** [comment]
a) a permanent service amounts to slavery but slavery is not exactly the same
b) prostitution is legal, all it means is that if a girls agrees to perform such services and then refuses, you can't sue her for breach of contract
c) it includes surrogacy, selling children etc - you CAN transfer your rights, it just means that if you want to transfer them for money and then change your mind, this agreement cannot be enforced against you  
d) I agree it deserves a debate
e) criminal offence by our definition is a situation where sb does not consent

**Comment by liberlandcitizen** [comment]
Thank you clarifying. I'm ok with everything you said, I just hope it's
clear enough for future judges to understand intent.

**Comment by terrorist96** [comment]
> b) prostitution is legal, all it means is that if a girls agrees to perform such services and then refuses, you can't sue her for breach of contract

Why not?

>  financial repatriation

I think you meant to say financial reparation?

Overall, I think this provision might be used to limit the areas that contracts cannot cover. Basically, if we list out the things that contracts cannot enforce, then another area that isn't covered in the list could be enforced that we may not want it to be. Since we say contracts cannot violate the constitution, I think that's a better catch-all phrase than listing individual subjects here.

Also, this says nothing of arbitration. If a contract stipulates arbitration, which it most likely will, then limiting enforcement before the courts becomes meaningless.

**Comment by KacperZajc** [comment]
traditionally, even libertarians do not think sexual services should form binding contracts and I do not see any reason we should insist otherwise

yes I meant 'financial restitution' 

I would like to make the list of non-enforceable contracts exhaustive. The freedom of contract is crucial for us so any exceptions should be expressly articulated in the Constitution IMO. Is there anything else you would like to add to this list here?

Good point about arbitration:

§XV.5. Notwithstanding any provision of this Constitution, the Courts of the Free Republic of Liberland, or any body charged with arbitration proceedings, shall not enforce any contract for (a) a permanent service, (b) sexual services, (c) a transfer of parental rights, (d) a restrain of trade, (e) a participation in a criminal offence or (f) a marriage; in cases of contracts for a specific performance, should the performing Person refuse to comply with the terms of such a contract, it may, where appropriate, be enforced by way of financial restitution instead.
