### ISSUE TITLE
transparency of the PA

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#508]
remove:

§II.9(3) All drafts of Bills proposed to the Cabinet shall be made public before the Cabinet’s acceptance or rejection.
§II.13(2) No vote whatsoever shall take place unless the Bureau of the Assembly has published a schedule of the affairs of the Assembly.
§II.3(4) No vote whatsoever shall take place without the recordation of the Yeas and Nays.

rephrase:

§VI.5. The Public Administration shall conduct its business openly by, where applicable, recording, transmitting, archiving, rendering available to the general public to attend and publishing planned and completed (a) all affairs of the Assembly other than the debate and vote on the classification of information as a state secret, (b) all proceedings before the Courts other than those concerned with Warrants and (c) all documents officially produced by the Cabinet; nothing in this provision shall prevent the Public Administration from protecting information classified as a state secret.

I think VI.5 covers those 3 provisions.

On a completely different subject - 
I think this provision is completely unnecessary:

§II.4(3) The newly elected Assembly shall hold its first session within fourteen days after the General Election.

**Comment by terrorist96** [comment]
> §II.3(4) No vote whatsoever shall take place without the recordation of the Yeas and Nays.

I oppose removing this because:
https://github.com/liberland/constitution/issues/391

And I'm not convinced that the other two removed sections are adequately covered in your revised VI.5 version.

Also, moving `and publishing planned and completed` makes the provision incomprehensible.

> On a completely different subject - 
I think this provision is completely unnecessary:
§II.4(3) The newly elected Assembly shall hold its first session within fourteen days after the General Election.

Really? I think the Constitution stipulating when each session should begin is pretty appropriate.

**Comment by KacperZajc** [comment]
I am sure II.9(3) would be covered.

Let's combine II.13(2) and II.3(4):

No vote whatsoever shall take place unless the Bureau of the Assembly has published a schedule of the affairs of the Assembly and made an official record of the Yeas and Nays.

Why is Vi.5 incomprehensible now?
Would you suggest any better wording?

I am pretty sure we do not need to stipulate when the first session should take place.
As far as we are concerned, it might not take place at all - no harm done, right? :D
It only requires the Assembly Speaker or 5 ARs to reconvene the Assembly so they can manage without any compulsory dates.
On top of that, this 15 days deadline would not make sense in case the election is invalidated by the Supreme Court for some reason.
