### ISSUE TITLE
Internet Freedom

### ISSUE THREAD

**Issue by burningtree** [liberland/constitution#51]
What about internet freedom? Nowadays the Internet is a basic human need and every citizen should have guaranteed uncensored and private access to it. In future decades, on the Internet will be absolutely everything and who will control access to it will have more and more power.

I see a danger especially in small shifts, masquerading often as "fighting agains evil" anti-[something], like anti-pornography, anti-piracy, anti-terorrism etc.

Some governments and IT industry solve this with principle called "**Net neutrality**" ([wikipedia article](http://en.wikipedia.org/wiki/Net_neutrality#Netherlands)), but this solves mainly censorship from internet providers side and technical aspects of data transfer. Do not address a citizens or laws.

We can not expect that the state will not play any role in the operation of the Internet in Liberland, and thus the state can control critical infrastructure.

Maybe it's a much bigger topic of  "communication freedom", because it is in principle irrelevant whether those data are going to the internet or not. Please think about it.

Some example threats: 
* UK - [David Cameron's internet porn filter](http://www.theguardian.com/commentisfree/2014/jan/03/david-cameron-internet-porn-filter-censorship-creep)
* Germany - ["wifi problem"](http://www.dw.de/germanys-wi-fi-problem/a-18060000]) - "Unlike in other countries, in Germany, Wi-Fi providers can be held responsible for what other people using their networks do online."
* Turkey - massive censorship of Twitter & other sites: [Censorship in Turkey](http://en.wikipedia.org/wiki/Censorship_in_Turkey)
* Egypt - [Internet censorship in the Arab Spring](http://en.wikipedia.org/wiki/Internet_censorship_in_the_Arab_Spring)
* USA - problems with NSA

Other references:
* [Declaration of Internet Freedom](http://www.internetdeclaration.org/)
* [US H.R.4070 - Internet Freedom Act](https://www.congress.gov/bill/113th-congress/house-bill/4070)
* ["Internet governance" wikipedia article](http://en.wikipedia.org/wiki/Internet_governance)
* ["Internet censorship" wikipedia article](http://en.wikipedia.org/wiki/Internet_censorship)
* ["Right to internet access" wikipedia article](http://en.wikipedia.org/wiki/Right_to_Internet_access)

**Comment by tinkyholloway** [comment]
How do you think this needs strengthening beyond protecting thr private property of ISPs and their and their customers freedom to enter into contract?

**Comment by KacperZajc** [comment]
I like the idea to put a safeguard for this:

No law shall regulate the rules regarding accessing any part of the content of the Internet by adults; nor shall it regulate the rules regarding uploading and/or displaying any materials other than pornography involving minors. 

what do you think?

**Comment by Zephram-C** [comment]
@burningtree: *Internet is a basic human need and every citizen should have __guaranteed__ uncensored and private access to it*
This seems like positive right to me. Internet access can not be guaranteed nor the parameters of the service (including censorship, speed diferentiation), provided by private ISPs, forced.

@KacperZajc: *...other than pornography involving minors.* 
This is unnecessary exception and potential loophole. Either CP violates property rights of others (in the case of children necessarily defined not strictly by themselves by also by their parents and some common values) or it does not. What about CGI? What about existing materials? Malevolent judge can use this loophole to ban anime, innocent family photos or institute censorship by very imaginative definition of pornography. Also planted evidence is very dangerous with such vague and broad definition.

**Comment by KacperZajc** [comment]
we need this exception, we can formulate it in different terms though, any ideas?

**Comment by Zephram-C** [comment]
Actually, I think that the whole safeguard is unnecessary and potentially dangerous.

_... nor shall it regulate the rules regarding uploading and/or displaying any materials ..._
What about copyrighted material? What about closed-source and confidential information? Even if we omit intellectual property debate, let's stay with less controversial contract between two people. One providing some electronic data under strict, contractual obligation *You will not upload it anywhere!* to another. And the second later replying *It is my constitutional right to upload anything!*.
(I do not mean more problematic situations like third person independently creating, stealing or overhearing the data. That one is not bound by any contract he/she did not agree to.)

**Comment by joshmh** [comment]
I'm also concerned that this document is turning into a laundry list of prohibitions for the legislators. I really think this constitution has to be grounded in a simple philosophy, and it has to create a structure with a distributed balance of power and a strong consensus. As soon as a few individuals are able to amass power, they will figure out how to bypass any prohibition. The more individual, detailed rights we throw in here, the more the document loses its core focus.

**Comment by burningtree** [comment]
@Zephram-C I do not want to regulate private ISP, but the government and legislators.

I see the problem of gradual tightening the loop through legislation. I just wanted to draw attention to this problem, whether it could be addressed in the constitution.

**Comment by KacperZajc** [comment]
Ok let's not go down this road, no provision for the Internet freedom

**Comment by Zephram-C** [comment]
Reopening.
After some discussion, I realized that Internet access might be one of the essential things for the state to function. As we are not anarchocapitalists, we already acknowledge need of some "positive rights", that is state provides and guarantees eg. laws, citizenships, some enforcement of security, §35. 
Historically this debate between anarchists and minarchists did not include Internet access as an issue, because it was not so important in the past. 
Liberland might crossed some threshold in this because many of (minimal) state functions are dependent on it.This means elections, communication, open-source version control of laws, payments in cryptocurrency, official announcements, citizenship database and provable identity, cryptographically secured pseudonymity, maybe transparent accounts of crowfunded projects (or laws).
So for example if we allow (only) electronic elections in Constitution, we should also somehow grant means to do so. If we accept voluntary taxes in cryptocurrency, access to network should not be restricted.

So I think we need two things. Barrier for state to limit Internet access and guarantee of some communication minimum. I propose these quite simple formulations:
- No law shall limit the access to the Internet by adult individuals, unless the realization of such access violates property rights of the other person.
- No citizen shall be precluded from using communication means necessary for effectively realizing his voting rights, right to fair trial,  or right to other indispensable communication (as specified in §23, §34, §35) with the state. Minimal necessary means for such communication and access to information shall be provided in all circumstances.

Second point is met even by providing 33.6 kbs access (minimum necessary means is met) or by official Notice Board, paper and pencil (on the expense of the Free Republic of Liberland) in the extreme case.

**Comment by KacperZajc** [comment]
I can get on board with this:
No law shall limit the access to the Internet by adult individuals, unless the realization of such access violates property rights of the other person.

This is too vague and doesnt sound too libertarian:
No citizen shall be precluded from using communication means necessary for effectively realizing his voting rights, right to fair trial, or right to other indispensable communication (as specified in §23, §34, §35) with the state. Minimal necessary means for such communication and access to information shall be provided in all circumstances.

**Comment by Zephram-C** [comment]
Sorry, bad references. Three §, now strokentrough should be. §III.1, §III.7, §III.11, §III.12.
I know that it is not too libertarian, I just thought about something like current:
**§III.12.** An accused who does not speak the language in which the criminal proceedings are conducted shall be provided without expense with the services of an interpreter.

Perhaps last sentence *Minimal neccessary...* can be omitted. I am open to suggestions. I want to open this issue again, not to close it again.
But if we want to grant some rights (fair and speedy trial), we have to grant some (minimal) means to realize them. I suppose that there will be many electronic or on-line trials in Liberland. Elections and payments are the main problem here.
I also think that in fact private subject will provide the means.

**Comment by KacperZajc** [comment]
I doubt a proper trial can be conducted online. I dont see any connection between those rights.

**Comment by Zephram-C** [comment]
We shall give it some time and gather some other insights.

The connection would be:
**§III.12.** An accused who does not speak the language in which the criminal proceedings are conducted shall be provided without expense with the services of an interpreter.

**§III.??.** *Citizen* who does not *have means* in which *the elections/trial/referendum* are conducted shall be provided without expense with the services of *ISP*.

**Comment by KacperZajc** [comment]
this is socialism my friend ...
right to an interpreter is inherent to a due process of law which is crucial because there is jail at stake, right to participate in referendum does not carry such a heavy risk

**Comment by KacperZajc** [comment]
on second thought, this -
No law shall limit the access to the Internet by adult individuals, unless the realization of such access violates property rights of the other person.
allows to watch child pornography so we cant do it either.

**Comment by burningtree** [comment]
Another reference to discussion:

> **Open Internet**
> The idea of an open Internet is the idea that the full resources of the Internet and means to operate on it are easily accessible to all individuals and companies. This often includes ideas such as net neutrality, open standards, transparency, lack of Internet censorship, and low barriers to entry. The concept of the open Internet is sometimes expressed as an expectation of decentralized technological power, and is seen by some as closely related to open-source software.[10]

http://en.wikipedia.org/wiki/Net_neutrality#Open_Internet

**Comment by KacperZajc** [comment]
No law shall regulate the rules concerning uploading to the Internet any materials where all parties of age involved consent; nor shall it regulate the rules concerning displaying and/or accessing such material.

???

**Comment by tinkyholloway** [comment]
Is there a way to express the intent on keeping the medium of communication free from regulation without limiting it to a specific instance of that medium?

In a few years the internet may be dead just like the telex, and hopefully the fax machine.

**Comment by KacperZajc** [comment]
No law shall regulate the rules concerning uploading and/or sending any materials through any medium of exchange where all parties of age involved consent; nor shall it regulate the rules concerning displaying and/or accessing such material.

better???

**Comment by KacperZajc** [comment]
any objections?

**Comment by burningtree** [comment]
I like it, but i have no experience with law.

Minor note: words "uploading" and "sending" are incoherent for me. (upload-download, sending-receiving). What about simply "transferring"?

**Comment by KacperZajc** [comment]
No law shall regulate the rules concerning uploading and/or transmitting any materials through the Internet and/or any other medium of exchange where all parties of age involved consent; nor shall it regulate the rules concerning displaying and/or accessing such material.

I think this covers every possible loophole.

Is everyone happy?

**Comment by KacperZajc** [comment]
Guys I would like to slowly wrap up our discussion, do you have any suggestions or comments of the last version I proposed?

**Comment by KacperZajc** [comment]
does anyone object?
