### ISSUE TITLE
Recent changes

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#512]
> +  * **§II.2(3)** No Assembly Representative shall be precluded from taking part in any Assembly vote and/or debate by virtue of being detained unless his or her release would cause direct and grave danger to others, as certified by the Court on application by the Office of the Public Prosecutor or a medical practitioner where appropriate.

We already cover this in:

> §XII.3. No Person shall be placed under arrest for more than twenty-four hours without a Warrant; all Warrants for further detention shall be issued only where the accused (a) constitutes a direct and grave danger to others, (b) is likely to escape justice or (c) interfere with the investigation, and for no longer than necessary to bring him or her to trial; where the accused is already under arrest, he or she shall have the right to address the Court at the hearing regarding such a Warrant, either in person or by way of legal representation.

Regarding:

> §VI.9(4) Upon reviewing the prima facie constitutionality of a Bill, the Supreme Court shall hear submissions, which are of relevance for the outcome of the determination, from the Cabinet and any association composed of no fewer than thirty Citizens in the form of amicus curiae briefs.

Why not allow for amicus briefs for any and all supreme court cases, not just prima facie hearings?

**Comment by KacperZajc** [comment]
II.2(3) is different from XII.3 because it limits the circumstances in which an Assembly Representative can remain in detention.

§VI.9(4) expanded accordingly
