### ISSUE TITLE
Independent oversight

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#513]
The problem: police departments and other government groups routinely "investigate" themselves for alleged misconduct and clear themselves of any wrong doing.

The solution: an independent oversight group should be established composed of ordinary citizens. Thoughts?

**Comment by KacperZajc** [comment]
I thought of such a body rooted in the Constitution but decided ordinary think-tanks will do that much much better without any official arrangements (see the Judicial Watch in the US)

**Comment by terrorist96** [comment]
If we leave it open, it could be the system in the US where Internal Affairs investigates the misconduct and would be more likely to find no wrong doing, case closed.

**Comment by KacperZajc** [comment]
we leave it 'closed' by ensuring full transparency, it's the best way
