### ISSUE TITLE
Border control

### ISSUE THREAD

**Issue by ConnectorLL** [liberland/constitution#515]
As I understand the constitution there will be prohibited for law enforcement to check your identity unless your're suspect of some crime. Does this mean there will be no border control for people coming in and checking their documents. This might be a problem, becouse noone would know who came into a country... if you have criminal past you can't become citizen, but you can freely enter countries territory? There could be also people streaming in area and overflowing it but there is no law to prevent that.
What are solutions for this issue?

**Comment by terrorist96** [comment]
The solution is already in the Constitution :smile:

§XVI.1. Notwithstanding any provision of this Constitution, the Cabinet shall have the exclusive power to sign binding international treaties regulating the flow of Persons, goods, services and capital across the border of the Free Republic of Liberland, and to directly enforce those treaties on the borders of the Free Republic of Liberland; such power shall be reviewable by the Civil Court exclusively on the basis whether a treaty, and/or its enforcement, falls within the scope of this provision and whether the enforcement measures undertaken are the least intrusive measures available.

**Comment by KacperZajc** [comment]
I am not sure it is covered by XVI.1.
This provision requires first a treaty to introduce any legal rule.
In the absence of any such treaty, there would be no legal basis for checking the ID on the border.
For that reason I added this possibility to the relevant provision.
