### ISSUE TITLE
Different voting systems 

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#516]
I've compiled all the videos about voting made by CGP Grey on YouTube. Hopefully it'll provide some options and information for when we make a final decision on how elections will be conducted in Liberland. 

https://youtu.be/s7tWHJfhiyo
https://youtu.be/3Y3jE3B8HsE
https://youtu.be/Mky11UJb9AY
https://youtu.be/uR2DfpjIuXo
https://youtu.be/kUS9uvYyn3A
https://youtu.be/QT0I-sdoSXU
https://youtu.be/7wC42HgLA4k
https://youtu.be/OUS9mM8Xbbw
https://youtu.be/l8XOZJkozfI
https://youtu.be/wRc630BSTIg
https://youtu.be/PukSDm0RD2E
https://youtu.be/8DNtsjB7L_I
https://youtu.be/Ac9070OIMUg
https://youtu.be/orybDrUj4vA

https://vimeo.com/190024419

**Comment by Auahi** [comment]
GCP Grey has amazing videos on voting systems, good call!

**Comment by DirectDemo** [comment]
Have a look to that very good voting system
Created by Michel Balinski and Rida Laraki

In english
M.I.T https://mitpress.mit.edu/books/majority-judgment
the book https://www.amazon.fr/dp/B009S59BG2/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1

in french video
College of France http://www.college-de-france.fr/site/pierre-rosanvallon/seminar-2012-02-29-10h00.htm
Polytechnique https://www.youtube.com/watch?v=ODuPoepQ1tY

**Comment by Auahi** [comment]
@DirectDemo So is it essential a rated voting method?

**Comment by DirectDemo** [comment]
@Auahi 

Yes and no, its an ordering way (you choose words in a scale for each option) instead of a cardinal way (numbers to sum).
As économiste I realy apraciate that.
you could probably find some english video.

**Comment by KacperZajc** [comment]
Nice job @terrorist96.
A profound discussion is welcome.

**Comment by terrorist96** [comment]
I just added another video I found. It shows that every voting system has a downside, unfortunately.
