### ISSUE TITLE
Announcement

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#519]
As some of you might know, on Saturday I gave a presentation about the Constitution at the Liberland Convention in Novi Sad (Serbia).
I am happy to report that the document was rather well-received.
Keep up the good work everyone! :)

**Comment by liberlandcitizen** [comment]
I caught your presentation online. Well done Kacper!

**Comment by jorgebg** [comment]
Hey, is it recorded? 😄

**Comment by Auahi** [comment]
I've been looking for the recording as well, if you know where it is Kacper please post it, and woohoo!

**Comment by liberlandcitizen** [comment]
Yes it was recorded but the website locked our channel for some reason.
Somebody will re-upload it sooner or later.

**Comment by terrorist96** [comment]
I'd like to see a recording as well.

**Comment by jorgebg** [comment]
Any news on the recording? 😞

**Comment by liberlandcitizen** [comment]
I'm asking around to find out who will be uploading. I'll update here once
I find out.

**Comment by liberlandcitizen** [comment]
Here is Kacper's speech at the Liberland conference.
<https://www.youtube.com/watch?v=Cy7PI6b77a4&list=PLhICyUUBScjmpFyvHyQA70bDsbz3S4FmM&index=3>
Apologies that it took so long to find a link. The playlist to the right of
the page features other speakers from the conference which are well worth a
watch as well.
