### ISSUE TITLE
Ideological foundation consolidation?

### ISSUE THREAD

**Issue by Zephram-C** [liberland/constitution#52]
First, I must say that I have not followed *all* issues, pull requests and discussions thoroughly.
However, I have feeling that some ideological framework or basic guidelines are urgently needed. Otherwise much effort and work will be done resulting in something incompatible with Liberland´s president&founding group intentions. And subsequently (yet revocably) thrown away.
So is there something like it? Some meta-declaration, some philosophy which consistently and coherently guides principles of all Constitution changes, pull requests and issues?

Something like: Constitution should be based on libertarianism, liberty as principal value and negative rights. Constitution should be simple and beautiful.
* Anarchocapitalism is not a way - Otherwise we would not need any Constitution or government.
* Pure Libertarianism is not a way - We need some realistic international recognition and to focus on moving far away from current state of socialism not on moving close towards theoretical pure solutions.
* Any form of socialism is not a way
* Liberty is a value per se - We do not want to guide citizens to do something or to refrain from doing something. We want to give them liberty to set their values and priorities on their own. Constitution is not utilitarian. It is not based on intended consequences, but on principles.
* Constitution should be simple - That means as short as possible. Every example, exception and specification of general principle is potential loophole.
* Constitution should be beautiful - Some formulations are technically redundant, but they make Constitution stylistically nice, formulations familiar with ideas&formulations people already know and understandable&inspiring for people not so familiar with libertarianism,
* Constitution is based on negative rights - Constitution should primarily limit power and define what government and citizens can not do. It should not grant something, force people to provide some service or good or standard.

Some points are contradictory (simple *vs.* beautiful, negative rights *vs.* no anarchocapitalism) and compromise must be constituted between them. Is this set somewhere? Is it in the state of flow and created by discussion? Do we know the boundaries and intervals acceptable for *Liberland's founding parents*?

**Comment by tinkyholloway** [comment]
@Zephram-C I think something like this would be useful. In lieu of some agreement on this, I am assuming that some type of Randian state is being developed. Perhaps less the Objectivist view on IP.

**Comment by jasoneriksen** [comment]
@tinkyholloway When you say less the Objectivist view on IP, what do you propose instead?

**Comment by Zephram-C** [comment]
Ok. It seems we have clear lead here [#76](https://github.com/liberland/constitution/issues/76). This is what is needed.

**Comment by KacperZajc** [comment]
closing then
