### ISSUE TITLE
II.1 and VI.9(9) changes

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#521]
> nothing in this provision shall prevent the Assembly from criminalising conduct interfering with the constitutional functions of the Public Administration or any form of direct or indirect participating in a criminal offence.

Any form of indirect participation? Sounds like a huge loophole. If there's human trafficking occurring in a hotel, unbeknownst to the hotel owner, should the owner be held liable? He's indirectly participating. Though it wouldn't pass muster for mens rea, I still don't like the broad language used here.

**Comment by terrorist96** [comment]
Also,

> §VI.9(9) In all ex parte proceedings resulting from the inherent jurisdiction of the Supreme Court, the Court shall hear submissions which are of relevance for the outcome of the determination from the Cabinet and any association composed of no fewer than thirty Citizens, where volunteered, in the form of amicus curiae briefs.

So amicus curiae briefs can no longer be submitted for cases on appeal? Only cases with "inherent jurisdiction"? Why not for any and all cases before the supreme court?

**Comment by KacperZajc** [comment]
The broad wording is not dangerous when read in conjunction with XI.2.
Your example is a classic strict liability offence which is precluded by XI.2.
'direct and indirect participation' makes more sense than listing 'encouraging, assisting, aiding, abetting, counselling, procuring, forming a JCE, benefiting from', etc, etc. 
This basically closes a loophole.

VI.9(9) gives constitutional right to submit a amicus curiae brief. This includes only ex parte proceedings. 
Submission of brief for appeals will be regulated by ordinary law regulating admission of evidence and court procedure. This doesn't mean there will be no such right. There is a huge difference between appeals and ex parte proceedings and not all appeal will benefit from such amicus curiae briefs.
