### ISSUE TITLE
Restricting rights on private property

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#523]
I know we allow for restriction of people's rights when on private property (or private property open to the public, like a store), but what about a person who rents their home? The home is technically owned by the leasing company, but the person pays to live there, so it's their home (their private property). Would a leasing company be allowed, under our constitution, to restrict the rights of the lessee (forbidding guns in the building, for example)?
I personally think when you rent your home, it's your private property for that period of time and you shouldn't be able to have your rights restricted by the leasing company.

**Comment by liberlandcitizen** [comment]
​Your rights aren't restricted, you negotiate what is and is not allowed in
the contract. Both parties sign and therefore both parties agree to the
terms. If you don't like the terms, you don't sign. ​

**Comment by terrorist96** [comment]
Yeah, but in reality, the leasing company has a lot more power when it comes to the contract. They give you a pre-written contract, and if you don't agree with it, they will just lease the place to the next person in line. The tenant would actually have negotiating room if there were a lot of places for rent and a dearth of potential tenants, but it's usually the opposite.
If a leasing company has a general rule "no guns allowed", they won't change that for just one person. And if every single leasing company in Liberland has that rule, then what can a renter do other than buy their own home (which they may not be able to afford)?

**Comment by liberlandcitizen** [comment]
​I find it hard to believe that every contract in Liberland would have the
same policies towards things like guns and even harder to believe that you
can't negotiate on things that are important to you (perhaps by offering
more per month or whatever). But let's say that somehow you are right.
Sounds like a good time to save up to buy a home. Our government should not
be getting involved in what the terms of contracts between private parties
should be. ​

**Comment by terrorist96** [comment]
What if you buy a home, and that home has an HOA, and that HOA forbids guns?

**Comment by liberlandcitizen** [comment]
The A in HOA is association. If the community has rules that you don't
like, don't associate with them. Go find a gun loving community, or form
your own. I just don't see why the government should get involved with what
free associations of people want to do.

**Comment by terrorist96** [comment]
What if in the future, people who like guns are a very small minority? All of Liberland could effectively become a gun free zone via contracts/associations. I do see your point about government not getting involved in the freedom of contract, but government is also tasked with safeguarding your rights. It essentially goes back to being enslaved via contract which is why we had to say that there has to be restrictions on contracts (XVI.2.).

**Comment by liberlandcitizen** [comment]
Your scenario to me sounds like the vast majority of people have little to
no interest in guns and therefore the needs of most citizens would be met.
Meanwhile the small minority can carve out a place to have it their way. I
think everybody would be happy. I think it's reasonable. When you get
government involved, it would mean government would have to play favorites.
It means you would politicize the matter rather than allowing the
free-market to sort it out. The issue would spill into elections. That is
messy. That is every other country. Let people sign contracts and vote with
their money.

**Comment by Auahi** [comment]
I'm siding with LiberlandCitizen for this one. Don't get me wrong I'm very pro-gun, but this isn't the government regulating guns, rather private property owners regulating _THEIR_ property. I want government to have little to no regulation in place, all this would do is add more regulation.

**Comment by terrorist96** [comment]
And if virtually all of the land in Liberland is private property, guns can essentially be banned in all of Liberland. Since the government won't be building roads or sidewalks either, you won't be able to carry a gun in public if the company that built the road/sidewalk objects.
I believe in private property and being able to control private property, but not if everywhere is considered private, rendering all your constitutional rights as just theoretical, at the whim of the property owner. Feels like when the government sets up "free speech zones".

**Comment by liberlandcitizen** [comment]
I hope there will be public spaces in Liberland. Parks and squares and
such. It is undetermined as of yet if streets will be public or private.
Anyway, do keep in mind that Liberland is 7 square kilometers in size.
There will be tens of thousands if not hundreds of thousands of different
private properties there. Only governments can ban things everywhere. If
it's left up to private property owners you should trust that things will
not be uniform throughout the country.

In fact, I plan on owning private property there and I invite you to come
enjoy your guns on my property :)

**Comment by terrorist96** [comment]
> Only governments can ban things everywhere.

Yeah, but in this case, it's actually the government that's forbidden from banning guns from public property. So in this unique case, private property is more of a threat to your rights than public property, since public property is owned by the government, and the government has to abide by the constitution; private property owners don't.

> In fact, I plan on owning private property there and I invite you to come
enjoy your guns on my property :)

As do I. Likewise, my friend. :smile:

**Comment by KacperZajc** [comment]
XIV.2. ... **person in charge of the premises** shall determine...
The problem raised by @terrorist96 has been already addressed.
A lessee is the person in charge whereas a lessor is the owner.

**Comment by terrorist96** [comment]
@KacperZajc what about for other rights, like freedom of speech or religion? The right to bear arms was just an example of a right that could be curtailed.

**Comment by KacperZajc** [comment]
A constitution regulates the so called vertical relationship, i.e. between the gov and the people.
It doesn't regulate the horizontal relationship, i.e. between the people themselves. 
Such relations are regulated by contractual relationships.
The argument about the imbalance of power could as well be used to support consumer protection, employment laws etc. 
Either we believe in the freedom of contract or we don't.
