### ISSUE TITLE
classified info and trials

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#525]
XI.15. Where any Person seeks information classified as a state secret for the purposes of bringing Private Prosecution or civil claim, he or she shall have the right to such information provided he or she can satisfy the Court upon Preliminary Hearing that such information is indispensable to proceed with the trial; in such cases the proceedings shall take place in camera and all Persons involved shall take an oath of secrecy for the period the relevant information remains classified.

**Comment by terrorist96** [comment]
Seems to overlap with:
> §XI.8. All defendants in criminal proceedings shall have the right to attend Court proceedings, to be informed of criminal charges and of his or her rights, to compel witnesses to appear in Court for examination, and to examine all evidence gathered against him or her, including any information which has been classified as a state secret should the Prosecution wish to employ such evidence; in such cases, the proceedings shall take place in camera and all Persons involved shall take an oath of secrecy for the period the relevant information remains classified.

**Comment by KacperZajc** [comment]
No, those are complementary.
the former is about getting info to prosecute/sue
the latter is about getting info to defend against prosecution brought by the state

**Comment by terrorist96** [comment]
Since they're so closely related, I feel like they could be combined into one provision. Or at least take the classified info part from XI.8 and combine it with XI.15. :stuck_out_tongue:

**Comment by KacperZajc** [comment]
XI.8. All defendants in criminal proceedings shall have the right to attend Court proceedings, to be informed of criminal charges and of his or her rights, to compel witnesses to appear in Court for examination, to confront the accuser and to examine all evidence gathered against him or her.

XI.15 All Persons wishing to institute Private Prosecution or to bring a civil claim on the basis of information classified as a state secret shall have the right to obtain such information provided they shall satisfy the Court upon Preliminary Hearing that such information is indispensable to proceed with the trial; all defendants in criminal and civil proceedings against whom classified information is employed as evidence shall have the right to examine such information; in cases where classified information is brought before the Court, the proceedings shall take place in camera and all Persons involved in such proceedings shall take an oath of secrecy for the period the relevant information remains classified.

**Comment by terrorist96** [comment]
> XI.15 All Persons wishing to institute Private Prosecution or ~~to~~ bring a civil claim on the basis of information classified as a state secret shall have the right to obtain such information provided they ~~shall~~ satisfy the Court upon Preliminary Hearing that such information is indispensable to proceed with the trial; all defendants in criminal and civil proceedings against whom classified information is employed shall have the right to examine such information; in cases where classified information is brought before the Court, the proceedings shall take place in camera and all Persons involved in such proceedings shall take an oath of secrecy for the period the relevant information remains classified.

**Comment by KacperZajc** [comment]
okk
