### ISSUE TITLE
education

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#528]
§X.8. No law shall impose any obligations as to pursuing and/or obtaining any stage of education by any Individual other than Agents and Members of the Public Administration.

This provision as it stands is completely superfluous and I think we can remove it.

**Comment by terrorist96** [comment]
:+1: 
I also noticed that the preamble and §I.3. have some overlap.

**Comment by KacperZajc** [comment]
yeah but the Preamble is not enforceable as such so it is OK
