### ISSUE TITLE
Land Fee/ordinary Bill overlap

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#529]
We say that only a Land Bill can impose/alter a Land Fee, but also say that an ordinary Bill can abolish a Land Fee. So, if the Land Fee is $100, and the Assembly wants to lower it to say $50, it needs to pass a Land Bill (which needs 3/4 margin). But if the Assembly wants to abolish the Land Fee, it only needs a 2/3 margin.
So, it seems weird to me that it's harder to lower the Land Fee than it is to abolish it. Maybe we can change it so that it's only hard to implement and raise a Land Fee, but lowering/abolishing it is easier (via an ordinary Bill)?

**Comment by KacperZajc** [comment]
funny I had the same thought recently :)
fixed it anyway
