### ISSUE TITLE
immigration system

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#535]
Any idea where to put it?

The Public Administration shall maintain an efficient immigration system and no Person shall be given a leave to enter the territory of the Free Republic of Liberland without first fully complying with the relevant immigration procedure as laid down by law;
No Person seeking leave to enter the territory of the Free Republic of Liberland for any reason whatsoever shall be provided with any accommodation and/or any maintenance provisions by any body of the Public Administration;
Any Person seeking refuge in the Free Republic of Liberland shall only be admitted to the territory of the Free Republic of Liberland provided any one Citizen or association thereof financially vouch for his or her accommodation and maintenance.

???

**Comment by terrorist96** [comment]
Looks fine to me. As for where to put it, ummmm how about in the executive branch section?

**Comment by KacperZajc** [comment]
I propose:

Article XVI: Cross-Border Rights 

THE RIGHTS OF PERSONS CROSSING BORDER TO AND FROM THE FREE REPUBLIC OF LIBERLAND SHALL BE SECURED

XVI. 1. No person shall be prevented from leaving the jurisdiction of the Free Republic of Liberland unless pursuant to a Warrant on the grounds that criminal prosecution is being conducted against such Person and his or her presence in the Free Republic of Liberland is necessary for the prosecution to be effective. [NEW]

XVI. 2. No Person shall be rendered to any state or group should there be a reasonable suspicion that the aforementioned may inflict on such Person torture or cruel or degrading treatment. [PART OF XI.12]

XVI. 3. Any Resident of the Free Republic of Liberland without a valid leave to remain shall be subject to deportation. [PART OF XII.5]

XVI. 4. Any Person seeking refuge in the Free Republic of Liberland shall only be admitted to the territory of the Free Republic of Liberland provided any one Citizen or association thereof financially vouch for his or her accommodation and maintenance and neither of those shall be provided by any body of the Public Administration. [NEW]

Rephrase:

§V.5 In foreign affairs, the Cabinet shall work towards the maintenance of international peace and seek political and economic cooperation with other Nations as far as possible.

§XI.12. No torture or cruel or degrading treatment shall be inflicted by any Agent or Member of the Public Administration or under the supervision or approval thereof against any Person; nor shall any experiments, medical or otherwise, be conducted against any Person without his or her express and informed consent; no Individual shall be medically examined or otherwise tested unless pursuant to a Warrant or with his or her express and informed consent.

§XII.5. No Resident subject to deportation shall be detained for more than fourteen days unless pursuant to an Order of the Civil Court for further detention; such Orders shall be issued only where necessary due to the complexity of the deportation proceedings.

Add:

II.12 The Public Administration shall secure the borders of the Free Republic of Liberland and duly maintain an efficient immigration system so that no Person shall be granted a leave to enter the Free Republic of Liberland without first fully complying with the relevant immigration procedure as prescribed by law.

**Comment by liberlandcitizen** [comment]
In addition to §V.5 I propose that we set forth a policy of neutrality
directly in our constitution, disallowing our nation's government from
interfering in international conflicts. I believe this will serve
Liberland well. Thoughts?

**Comment by terrorist96** [comment]
> XVI. 1. No person shall be prevented from leaving the jurisdiction of the Free Republic of Liberland unless pursuant to a Warrant on the grounds that criminal prosecution is being conducted against such Person and his or her presence in the Free Republic of Liberland is necessary for the prosecution to be ~~effective~~ **effectuated**. [NEW]

> XVI. 4. Any Person seeking refuge in the Free Republic of Liberland shall only be admitted to the territory of the Free Republic of Liberland provided any one Citizen or association thereof financially vouch for his or her accommodation and maintenance and neither of those shall be provided by any body of the Public Administration. [NEW]

Why limit it to only citizens? What about residents?

**Comment by KacperZajc** [comment]
@liberlandcitizen I think those provisions take care of it:

§II.8. No branch of the Public Administration shall establish any standing army; nor shall it declare war and/or carry out military activities other than in defence of the border of the Free Republic of Liberland in reaction to an act of armed aggression against the Free Republic of Liberland which has already taken place or is imminent; nor shall any branch of the Public Administration invite any armed forces of any other state or organisation into the jurisdiction of the Free Republic of Liberland except for a reasonable number of security personnel accompanying a foreign visit.

§XIV.6. Should the Territorial Defence force rise, it may operate within the one kilometre radius from the borders of the Free Republic of Liberland upon the order of the Commander-in-Chief; the Territorial Defence force may also operate within the ten kilometre radius from the borders of the Free Republic of Liberland upon the order of the Commander-in-Chief and the express and informed consent of two-thirds of the overall number of Assembly Representatives; the Territorial Defence force shall not operate outside the ten kilometres radius from the borders of the Free Republic of Liberland in any event; nor shall the Territorial Defence force take part in any collective international military operation whatsoever

@terrorist96 I think only Citizens should be able to 'import' people into the country. So we remain in control of who comes in.

One more provision in this Article actually:

XVI. 5. No Citizen shall be prevented from entering the territory of the Free Republic of Liberland in any circumstances whatsoever.

**Comment by liberlandcitizen** [comment]
I feel those two provisions prevent us from involving ourselves in military
conflicts outside of our borders (which is great) but I am urging
neutrality for all international conflicts including non-military conflicts
between states.

Also I've been meaning to point out that the "10 kilometer" language in the
above provision may not be well received by our neighbors as Liberland
tries to gain recognition from them. Something to consider. I of course
understand why we may want it for Liberland's security though.

**Comment by KacperZajc** [comment]
OK we can work further on the wording of:

§V.5 In foreign affairs, the Cabinet shall work towards the maintenance of international peace and seek political and economic cooperation with other Nations as far as possible.

**Comment by liberlandcitizen** [comment]
Thank you for considering my point, very much appreciated. I would be a
little uncomfortable with the words "maintenance of international peace"
since for many crazies out there (especially those in governments) the way
to "peace" is through war. So I suggest that we use the word neutrality
specifically.

**Comment by KacperZajc** [comment]
V.5 The Cabinet, on behalf of the Free Republic of Liberland, shall seek economic cooperation with other Nations and shall not interfere with internal matters of such Nations whether militarily or by financing any group or individual therein.

???

**Comment by terrorist96** [comment]
> or by financing any group or individual therein.

overlaps with:

> §II.7. No branch of the Public Administration shall give any form of foreign aid whatsoever to any state or entity, whether directly or via any international institution; nothing in this provision shall prevent the Public Administration from meeting its financial liabilities flowing from the membership in any intergovernmental organisation.

**Comment by KacperZajc** [comment]
you are right, so:

V.5 The Cabinet, on behalf of the Free Republic of Liberland, shall seek economic cooperation with other Nations and shall not interfere with internal matters of such Nations by means other than diplomatic pressure.

???

**Comment by terrorist96** [comment]
Diplomacy sounds better than `diplomatic pressure`

**Comment by KacperZajc** [comment]
okk

**Comment by KacperZajc** [comment]
@liberlandcitizen are you satisfied?

**Comment by liberlandcitizen** [comment]
With the change to the word diplomacy I am most satisfied. Thank you!

**Comment by terrorist96** [comment]
@KacperZajc I just noticed that we say that no citizen can be denied entry. What about residents? If you're not a citizen, but still reside in Liberland, can you be denied entry?

**Comment by liberlandcitizen** [comment]
I would expect that yes, as a resident you should be allowed in but that
residency could be taken away from you under certain conditions.

**Comment by KacperZajc** [comment]
we define a 'resident' as a person who is already IN the jurisdiction so it wouldnt make any sense to guarantee them any right of entry

**Comment by terrorist96** [comment]
I thought a resident was someone who lives (resides) in Liberland but isn't a citizen. So if that person were to cross the border, then try to return, he wouldn't be guaranteed right of entry, even though his home, job, family are all in Liberland. 
The way you are saying it, it makes it seem like citizenship is a requirement to be able to live in Liberland. I thought it was optional.

**Comment by KacperZajc** [comment]
Resident is sb who finds himself in the Liberland's territory.
Im sure laws which will set up the whole immigration procedure will guarantee the right of entry for people with a valid leave to remain (for when they leave the territory for some reason).

**Comment by terrorist96** [comment]
So let's say no citizen or anyone with a valid leave of stay  shall be denied entry.

**Comment by KacperZajc** [comment]
as a matter of law it seems that all persons with a valid leave to enter must be allowed in, on the other hand, Im not sure we need a constitutional guarantee of this right, maybe some leeway could be useful in times of emergency

**Comment by terrorist96** [comment]
> §II.4. No branch of the Public Administration shall introduce any state of emergency or war, or any other special state in which one or more of the Rights guaranteed by this Constitution would be diminished or suspended or revoked; any purported such introduction shall be of no effect.

**Comment by KacperZajc** [comment]
Yes, exactly.
So if we leave the right of entry for non-citizens to be regulated by the law, it would not fall within II.4 and therefore could be suspended in the time of emergency.

**Comment by terrorist96** [comment]
My point was that emergencies can't even be declared, so they will never exist as a matter of law.

**Comment by KacperZajc** [comment]
yeah any general emergency cannot be declared but an Act which will set up the immigration system can potentially stipulate that persons who get a leave to enter might be denied the right to entry if X happens

**Comment by terrorist96** [comment]
I don't know, it just doesn't sit right with me. We'd be treating people differently as a matter of law based on their status. It would violate the equal protection under the law clauses. We've established that citizenship is not a right, but a privilege. But now we're saying you need citizenship to be guaranteed entry into your home country.
