### ISSUE TITLE
§X.6.  provision

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#538]
I think we should broaden §X.6.:

§X.6. No Individual shall stopped by any Agent of the Public Administration and compelled to answer any question; nor shall any Individual be compelled to identify himself or herself to any such Agent, unless upon (a) a valid arrest, (b) a probable cause of a violation of the law, (c) the crossing of the border of the Free Republic of Liberland or (d) a Warrant, Court order or subpoena.

**Comment by terrorist96** [comment]
> §X.6. No Individual shall **be** stopped by any Agent of the Public Administration and compelled to answer any question as to the ~~causes~~ **cause** of his or her present whereabouts or any future plans; nor shall any Individual be compelled to identify himself or herself to any such Agent, unless upon (a) a valid arrest, (b) a probable cause of a violation of the law, (c) the crossing of the border of the Free Republic of Liberland or (d) a Warrant, Court order or subpoena.

**Comment by KacperZajc** [comment]
I just edited it...

**Comment by KacperZajc** [comment]
okk

**Comment by terrorist96** [comment]
> §X.6. No Individual shall **be** stopped by any Agent of the Public Administration and compelled to answer any ~~question~~ **questions**; nor shall any Individual be compelled to identify himself or herself to any such Agent, unless upon (a) a valid arrest, (b) a probable cause of a violation of the law, (c) the crossing of the border of the Free Republic of Liberland or (d) a Warrant, Court order or subpoena.
