### ISSUE TITLE
Secession issue

### ISSUE THREAD

**Issue by ConnectorLL** [liberland/constitution#539]
I have a question... how does constitution deal with someone, group of landowners or residents if they want to secede their land and declare new independant country... Countries usually have in it's constitutuon that territory is undividable which prevent such situations. What I found in our constitution which might cover that is:
§I.2. "no municipal or district governing body shall be established unless for a new territory upon its incorporation to the Free Republic of Liberland."

But that doesn't explicitly say that this prevent someone to secede and form a new country.
It might not sound real issue, since there is only 7km^2 of the land, but still if someone or group of people come together, they can basicly convert Liberland or large portion of it to something else.

**Comment by KacperZajc** [comment]
§II.6. No branch of the Public Administration, nor any number of Citizens or Residents of the Free Republic of Liberland, shall propose and/or consent to the incorporation of the Free Republic of Liberland, or any part thereof, to any other jurisdiction; a majority of two-thirds of the overall number of Assembly Representatives may assent to the incorporation of any new territory to the Free Republic of Liberland upon the request of its people or government with any status the Assembly may determine.
