### ISSUE TITLE
§IX.3.

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#540]
I think §IX.3. should be divided into two separate provisions:

No Person shall have his or her property confiscated, whether tangible or intangible, either fully or partially, unless where a) he or she is legally prohibited from possessing it, b) for the purpose of such restitution as may lawfully be ordered, b) lawfully levied fines, c) payment of outstanding fees for services provided by the Public Administration as envisaged in the Constitution, d) the Land Fee, or e) satisfaction of pre-existing debt.

No Person shall have his or her property temporarily seized or frozen unless a) pursuant to a Warrant where such property is considered evidence in court proceedings, b) pursuant to a Court order where there is reasonable suspicion that such property would be disposed of in order to frustrate any future verdict of the Court or c) upon arrest where such property if found on the Person subject to the arrest.

**Comment by terrorist96** [comment]
> No Person shall have his or her property confiscated, whether tangible or intangible, either fully or partially, unless where a) he or she is legally prohibited from possessing it, b) for the purpose of such restitution as may lawfully be ordered, b) lawfully levied fines, c) payment of outstanding fees for services provided by the Public Administration as envisaged in the Constitution, d) the Land Fee, or e) satisfaction of pre-existing debt.

By making this change, all the abcd clauses don't read correctly anymore. E.g. "unless where the Land Fee"

> No Person shall have his or her property temporarily seized or frozen unless a) pursuant to a Warrant where such property is considered evidence in court proceedings, b) pursuant to a Court order where there is reasonable suspicion that such property would be disposed of in order to frustrate any future verdict of the Court or c) upon arrest where such property if found on the Person subject to the arrest.

**Comment by KacperZajc** [comment]
No Person shall have his or her property confiscated, whether tangible or intangible, either fully or partially, unless for the purpose of (a) such restitution as may lawfully be ordered, (b) lawfully levied fines, (c) payment of outstanding fees for services provided by the Public Administration as envisaged in the Constitution, (d) the Land Fee, or (d) satisfaction of pre-existing debt or (e) execution of law which prohibits possessing of such property.

**Comment by terrorist96** [comment]
Remove "or" before (d), change second (d) to (e) end (e) to (f)
:+1:

**Comment by KacperZajc** [comment]
okk
