### ISSUE TITLE
Will Liberland take part in international sanctions?

### ISSUE THREAD

**Issue by yopdog** [liberland/constitution#543]
As you may know, economic sanctions are a big part of international politics and it's how countries pressure one another to behave in their interests. Examples of this include sanctions on Russia for annexing Crimea or on North Korea for its human rights abuses. Will Liberland take part in such sanctions?

The problem is, that sanctions involve restrictions on trade which is a restriction of personal liberty. On the other hand, sanctions may be important for preserving security and for maintaining relations with allies (who may be calling for such sanctions) and for not supporting terror organizations who may be funding themselves by selling certain products. Regardless, I think we need to find some type of balance here and come up with rules on when sanctions can and cannot be used.

Any thoughts?

**Comment by terrorist96** [comment]
Personally, I view sanctions as an act of war. I would err on the side of free trade. As Jefferson said: "peace, commerce, and honest friendship with all nations, entangling alliances with none"

**Comment by yopdog** [comment]
I agree, we should try to err on the side free trade as much as possible but my question was should we have the *option* of applying sanctions?

Maybe we can have a rule that economic sanctions can only be applied against countries that are deemed "enemy" or "hostile" to Liberland as a country.

**Comment by Auahi** [comment]
I'd prefer to not allow sanctions, if the residents don't want to support a country they can choose not to buy their products etc.

**Comment by KacperZajc** [comment]
This falls under §XVII.1. so it must stay unregulated.
