### ISSUE TITLE
Constitution would make it impossible for Liberland to join NATO

### ISSUE THREAD

**Issue by yopdog** [liberland/constitution#544]
There are a few provisions in the constitution that severely limit the ability of Liberland to defend itself and form defensive alliances with other nations. For example, Provision §XIV.6 forbids the use of the Territorial Defence outside a ten-kilometer radius surrounding  Liberland and explicitly states the Liberland cannot take part in military operations with other nation. All these restrictions, including those mentioned in §II.8., which forbids any military action unless an attack is "imminent" and specifically against Liberland, are not only unprecedented restrictions on self-defense that no sane country would impose on itself, it would also block Liberlands ability to become a NATO member.

Now, the reason this is important should be obvious. Liberland is super tiny and even with the most advanced economy, we will never be able to produce a military that could even remotely defend itself from another country. It's physically impossible. 

That's why the only way to effectively provide defense for Liberland would be to enter into a defensive alliances with other nations; and yes, if one of those nations is attacked, we would need to send some soldiers or logistic personal to help that nation as it would do the same for us.

Entering into the NATO alliance could give the tiny Republic of Liberland an effective military strength that could deter the Russian military (not that I have anything against Russia) or any other country that could theoretically attack us in the next 100+ years. 

For these reasons, I think we should think about making some changes to §II.8 and  §XIV.6 so that Liberland can effectively defend itself.

**Comment by terrorist96** [comment]
Wouldn't this also open the door to other countries installing military bases in Liberland?

**Comment by yopdog** [comment]
In the specific case of Liberland, I think not. Liberland is very small and a military base could take up most of the land. It would be unreasonable for an alley to ask to establish a military base in liberland and they would understand that.

That said, theoretically, if Liberland was bigger, I could see that happening.

**Comment by Auahi** [comment]
I don't see any benefit Liberland would receive from joining NATO; Liberland is never going to physically deter Russia. And I agree with the constitution in the fact that the country shouldn't be joining alliances or any other political associations, this allows other countries to exercise control over Liberland.

**Comment by michalptacnik** [comment]
It will be difficult for Liberland to enter NATO, but not because of the Constitution. We have a new Constitution, which in Book 2 specifies the rules for entering defensive alliances and allows it: https://docs.google.com/document/d/1J2o5N9JDOzBXRkefe9Azm6P6vAwqCxw7B2jcKoHSjhg/edit

The real problems are
1) NATO is not really made for small countries like Liberland
2) Liberland has and will have no standing army
3) the 2 % budget spending on defense is untenable for many reasons.

If you are interested in more, please, reopen. Closing the issue.
