### ISSUE TITLE
Running for office while under investigation 

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#545]
Let's add 

> §VII.4. No Persons other than Individuals above the age of twenty-one who hold citizenship of the Free Republic of Liberland and have never been convicted of, **nor under current investigation for,** the criminal offence of breach of the Constitution or of any law related to his or her previous official position shall have the right to submit his or her candidacy for a public office.

**Comment by Auahi** [comment]
I don't agree, by adding this you're presuming they are guilty before sentencing. And I know why you put it, but I don't think people should be punished before sentencing. Impeach said person once they are convicted.

**Comment by terrorist96** [comment]
Their freedoms aren't restricted and aren't being punished. Running for public office is a privilege subject to meeting whatever qualifications we wish to establish; it's not a right. Else, you could argue 20 year old are being punished since they can't run either.

**Comment by Auahi** [comment]
This is a lost political term for the candidate just for the fact they are being interrogated for something that may or may not be true.

The government can't selectively disadvantage citizens with not allowing 20-year-olds to serve in office, rather it disadvantages everyone at some point in their life. Unlike that, this text allows for the government to selectively target people to ensure they can't be voted into office, this is another problem.

**Comment by Auahi** [comment]
This is a lost political term for the candidate just for the fact they are being interrogated for something that may or may not be true.

The government can't selectively disadvantage citizens with not allowing 20-year-olds to serve in office, rather it disadvantages everyone at some point in their life. Unlike that, this text allows for the government to selectively target people to ensure they can't be voted into office, this is a problem.

**Comment by terrorist96** [comment]
I guess the question we have to ask is what's worse? Someone legitimately under investigation prevented from running for office or the government falsely targeting someone for investigation to prevent them from running for office?

**Comment by Auahi** [comment]
I would say that the latter is worse, if someone is egitimately under investigation and wins office they can be impeached at a further date thus fixing the problem, you cannot fix the problem with the latter.

**Comment by KacperZajc** [comment]
Hahahha, I see Im not the only watching closely Hillary's scandals.
But here I have to side with @Auahi.
It would be to effectively overturn the presumption of innocence. 
And it would allow the executive (public prosecutor) to decide who will run for office (by merely opening investigation).
The risk is not worth it.
