### ISSUE TITLE
Granting immunity 

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#547]
In the US, you can lose your right to remain silent if you are bestowed with immunity from prosecution. So there would be no risk of incriminating yourself because would would be shielded from prosecution. Would this occur in Liberland? From my reading of the Constitution, it would seem that this would not be an option. Should it? Or should it not?

**Comment by terrorist96** [comment]
Actually, I just reread it and I have concerns now.

> §XI.9. All defendants in criminal proceedings shall have the right to be presumed innocent until proven guilty and to not be compelled to be a witness against himself or herself, or such other Persons as may be prescribed by law, without any negative inference;

It seems like the right to remain silent would not apply except in criminal proceedings. It would not apply to investigations, interrogations, etc. That's a problem.

**Comment by KacperZajc** [comment]
Good point.
I propose:

§XI.9. All defendants in criminal proceedings shall have the right to be presumed innocent until proven guilty; the Prosecution shall at all times carry the legal burden of proof, discharged beyond reasonable doubt, in relation to the defendant's guilt, including disproving any defence envisaged by the law which he or she might raise; nothing in this provision shall prevent the creation of defences which require the defendant to discharge the evidential burden of proof by raising the issue of defence available to him or her.

XI. ??. All defendants in criminal proceedings and all Persons testifying in criminal investigation or before the Assembly Committee or Judicial Appointment Commission shall have the right to not be compelled to be a witness against himself or herself, or such other Persons as may be prescribed by law, without any negative inference, unless where immunity has been granted to them by the Prosecutor or the Committee or Commission panel.

???

**Comment by terrorist96** [comment]
> XI. ??. All defendants in criminal proceedings and all Persons testifying in criminal ~~investigation~~ **investigations** or before the Assembly Committee or Judicial Appointment Commission shall have the right to not be compelled to be a witness against himself or herself, or such other Persons as may be prescribed by law, without any negative inference, unless where immunity **from prosecution** has been granted ~~to them~~ by the Prosecutor or the Committee or Commission panel.

**Comment by Auahi** [comment]
> XI. ??. All defendants in criminal proceedings and all Persons testifying in criminal investigations, testifying before the Assembly Committee and/or Judicial Appointment Commission **shall not be compelled to bear** witness against himself or herself, or **other such** Persons as may be prescribed by law, without any negative inference, unless where immunity from prosecution has been granted by the Prosecutor, the Committee, or Commission panel.

Some of this may just be dialectal differences.

**Comment by KacperZajc** [comment]
okk
