### ISSUE TITLE
defamation laws

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#548]
I think we need to clarify the issue of future defamation laws:

§VIII.2. No law shall abridge the freedom of thought and expression thereof; such free expression shall be allowed in all public areas within the Free Republic of Liberland.

VIII.??. No Person shall be convicted of any criminal offence for any statement of opinion, whether offensive or otherwise; nor shall any Person have a civil lawsuit brought against him or her for any statement of opinion or of facts unless such a statement of facts was made in public and it was not materially true.

???

**Comment by terrorist96** [comment]
> VIII.??. No Person shall be convicted of any criminal offence for any statement of opinion, whether offensive or otherwise; nor shall any Person have a civil lawsuit brought against him of her for any statement of opinion or of facts unless such a statement of facts was made ~~in public~~ **publicly** and it was ~~not~~ materially ~~true~~ **false**.

**Comment by KacperZajc** [comment]
what's the difference between 'materially false' and 'not materially true'?
does the former sets the bar higher?

**Comment by terrorist96** [comment]
I don't know if it would make a real difference, but I think you can find something as being not true even if the statement is true except for one part of it (maybe a slip of the tongue), but for something to be false, it would have to be shown to be outright false.

**Comment by KacperZajc** [comment]
Yeah this was my impression as well so it is a different standard.
Should be go for a higher standard then?

**Comment by terrorist96** [comment]
I think so, so as to avoid chilling free speech

**Comment by Auahi** [comment]
Yes you need a much higher standard. I'm against defamation laws to begin with, and if a Libertarian country were to have defamation laws, I think they shouldn't have any vagueness whatsoever.

**Comment by TWalls** [comment]
I think we would want to avoid situations where a business can sue a person
for merely leaving a negative online customer review - which has happened
in the U.S..

**Comment by terrorist96** [comment]
@TWalls see #531

**Comment by KacperZajc** [comment]
Ok then

VIII.??. No Person shall be convicted of any criminal offence for any statement of opinion, whether offensive or otherwise; nor shall any Person have a civil lawsuit brought against him of her for any statement of opinion or of facts unless such a statement of facts was made publicly and it was materially false.

it is.

**Comment by terrorist96** [comment]
him or her***

**Comment by KacperZajc** [comment]
okk

**Comment by terrorist96** [comment]
Maybe we should add "and with intent to defame"?
