### ISSUE TITLE
Grand Jury

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#549]
I've been thinking about the Grand Jury lately.
First of all, it would curb the powers of the public prosecutor where there is no victim (which was rightly a concern to the US Founding Fathers).
Secondly, it would curb the powers of private prosecutions against Agents and Members of the PA where no public prosecution has been brought (our 'Hillary Clinton clause'), that @Auahi worried so much.
It complicates the system a bit but I think it might be worth the hassle.
Im open to this idea, here is what I propose:

VI.??. Any criminal proceedings initiated by a Public Prosecutor, or by a Private Prosecutor against any Agent or Member of the Public Administration for his official conduct, shall be subject to approval by the Grand Jury before an indictment is brought.
VI.??(1) The Grand Jury shall be summoned by the Judge at a Preliminary Hearing. 
VI.??(2) The Grand Jury shall be composed of 18 Citizens randomly drawn from the Electoral Register.
VI.??(3) The Grand Jury shall determine whether there is a probable cause that the defendant has committed the alleged offence. 
VI.??(4) The Grand Jury shall find probable cause with no fewer than 12 votes.
VI.??(5) The Grand Jury may find probable cause only in relation to selected counts of the proposed indictment.
VI.??(6) Should the Grand Jury fail to find probable cause with 12 or more votes in relation to one or more counts, the defendant shall not be indicted on such counts.
VI.??(7) The Grand Jury shall have the right to refuse to find a probable cause in relation to the whole proposed indictment where it is satisfied with no fewer than 16 votes that the indictment would not be in the public interest.

§VI.13(3) All Public Prosecutions and Private Prosecutions against Agents and Members of the Public Administration for their official conduct shall be subject to approval by the Grand Jury at a Preliminary Hearing. 

§VI.15(6) The Judge at a Preliminary Hearing, where appropriate, shall summon the Grand Jury for the purpose of determining the existence of a probable cause.

**Comment by Auahi** [comment]
So someone indicted by the Grand Jury wouldn't be allowed to run for office during trial? This is a step better in the better direction, but is still not completely ideal. I'd be more comfortable if the Grand Jury was composed of 50+ members. I find 18 to be a bit small.

**Comment by KacperZajc** [comment]
There is nothing here that has any bearing on running for public office.
#545 has been resolved and closed.
Also, Grand Juries has 16 - 24 Members traditionally, so we shouldnt go higher than that.
I am, however, open to increasing the number up to 24 if there are good reasons for this.

**Comment by KacperZajc** [comment]
@terrorist96 ???

**Comment by terrorist96** [comment]
I went back and reread all the previous discussions about grand juries. Here is my previous thread regarding the issue: https://github.com/liberland/constitution/issues/502
Which then led to the preliminary hearing: https://github.com/liberland/constitution/issues/503

Some questions up front: why shield public officials with the additional step of a grand jury but not afford regular people that same level of due process?

> VI.??. Any criminal proceedings initiated by a Public Prosecutor, or by a Private Prosecutor against any Agent or Member of the Public Administration for his **or her** official conduct, shall be subject to approval by the Grand Jury before an indictment is brought.

To be clear, you're saying that all public prosecutions need to meet the grand jury requirement. And private prosecutions of public officials would need to meet the grand jury requirement. But private prosecution of non-public officials would be able to skip the grand jury requirement?

> VI.??(1) The Grand Jury shall be summoned by the Judge at a Preliminary Hearing.

The grand jury should occur before the preliminary hearing. Grand juries are usually secret, where only the prosecutor presents evidence, no defense. Once approved, then the preliminary hearing would be scheduled.

> VI.??(3) The Grand Jury shall determine ~~whether there is a~~ **the existence** of probable cause that the ~~defendant~~ **accused** has committed the alleged offence.

There is no defendant yet. They are determining on whether or not it should even proceed to that stage.

> VI.??(5) The Grand Jury may find probable cause only in relation to **the** selected counts of the proposed indictment.
VI.??(6) Should the Grand Jury fail to find probable cause ~~with 12 or more votes~~(redundant) in relation to one or more counts, the ~~defendant~~ **accused** shall not be indicted on such counts.
VI.??(7) The Grand Jury shall have the right to refuse to find ~~a~~ probable cause in relation to the whole proposed indictment where it is satisfied with no fewer than 16 votes that the indictment would not be in the public interest.
§VI.15(~~6~~ **5**) The Judge at a Preliminary Hearing, where appropriate, shall summon the Grand Jury for the purpose of determining the existence of ~~a~~ probable cause.


This is mostly good, but one thing missing is the issue where a public prosecutor will deliberately sabotage his own case before the grand jury so as to shield the accused from future prosecution.

Also, does summoning a grand jury count as prosecution? Or attempted prosecution? Meaning: would the accused have his right against double jeopardy violated if the public prosecution fails to secure an indictment, but a private prosecution succeeds thereafter?

**Comment by terrorist96** [comment]
Also, grand juries aren't used in all criminal proceedings. If you are caught in a criminal act and are arrested/ticketed by the police, there's no grand jury step. Grand juries are only used to indict someone for an alleged crime. Being arrested/ticketed is similar to already being indicted. At least that's how it works in the US, as far as I know.

**Comment by KacperZajc** [comment]
considering all issues, I think it is not worth the hassle after all 
it's too complicated and doesnt fit our system as it stands now
