### ISSUE TITLE
Flowchart update

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#550]
![](https://raw.githubusercontent.com/liberland/constitution/master/diagrams/elections-and-impeachment-flowchart.png)

This should be updated to include impeachment of Assembly Reps by the citizens as per IV.3(1)

**Comment by Auahi** [comment]
IV.3 is in the to be discussed later: #412 

It might be pointless to change it if it'll be change again in the coming months.

**Comment by KacperZajc** [comment]
I didnt make those charters, I dont change them.
