### ISSUE TITLE
Election validity - 3% within 7 days

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#551]
> §VII.5. The 3% of the overall number of Citizens registered to vote at the time of the last General Election shall have the right to, within seven days of the publication of the results, request the Supreme Court to review the validity of any election or referendum held in the Free Republic of Liberland

This is a monumental task to accomplish within 7 days. If there are 300,000 registered voters, for example, you have to obtain 9,000 signatures within 7 days.
Also, the `The` at the beginning seems outta place.

**Comment by Auahi** [comment]
I agree 20 - 30 seems better, but all in all I see 5 000 - 20 000 registered voters to be much more reasonable which would be 150 - 600 signatures, we might want to increase the threshold to 5%.

**Comment by KacperZajc** [comment]
I think 20 000 is much more plausible than 300 000 therefore 600 signatures within 7 days is totally doable.
I think it's a good balance.

**Comment by terrorist96** [comment]
@KacperZajc yeah but you can't predict what the future holds. In the future, we may have many citizens who don't physically preside in Liberland, but are registered to vote and can vote remotely via blockchain technology. Population will grow irrespective of the physical space available; think e-residents.

**Comment by KacperZajc** [comment]
if you think e-residents, it's even easier to get the signatures online
doesnt require canvassing just sending emails

**Comment by terrorist96** [comment]
Yeah, that's true.
