### ISSUE TITLE
appeals on the question of facts

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#552]
I think this is missing:

§VI.9(10) The Supreme Court shall hear appeals from the Criminal Court on the point of fact only upon conviction in that Court where materially new information has subsequently come to light which suggests that a miscarriage of justice took place.

???

**Comment by terrorist96** [comment]
I think this could be tacked on to the end of VI.9(1).

> §VI.9(10) The Supreme Court shall hear appeals from the Criminal Court on the point of fact only upon conviction in that Court where materially new information has subsequently come to light ~~which suggests that a miscarriage of justice took place.~~

I would remove the last part. It's so specific that a judgement call has to be made before the case has had a chance to be heard.

**Comment by KacperZajc** [comment]
I will put it as (2).
I think we need a high standard so there must be 'probable cause' that the new facts have any bearing on the conviction.
But I open to any alternative wording.

**Comment by terrorist96** [comment]
Using the word "material" fulfils that, doesn't it?

**Comment by KacperZajc** [comment]
okk
