### ISSUE TITLE
age of majority

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#555]
We make some rights available only for minors and most only for non-minors so I think we should make sure the Assembly doesn't abuse peoples' rights by setting an extraordinarily high (or low) age of majority:

§XVIII.5. The age of majority shall be universal for all Persons and in relation to all rights and duties and shall be regulated by law but it shall not be set before a Person reaches seventeen years of age and no later than upon reaching by such a Person twenty-one years of age.

Add this to §XVIII.4:

....the term “Minor” shall signify a Person who has not reached the age of majority as prescribed by law;...

**Comment by terrorist96** [comment]
Put a comma before `but`

**Comment by liberlandcitizen** [comment]
Ever consider defining the age right in the constitution? I would suggest
averaging the age used in all countries of Europe and going with that.

**Comment by KacperZajc** [comment]
I did consider that but I think leaving some leeway is a better solution.
There are good reasons for a lower and higher majority age and it should be resolved by the society through law rather than imposed by the Constitution IMO.
There is no harm done.

**Comment by terrorist96** [comment]
What if society wants to impose an age of majority of 18 for somethings (like buying cigarettes) but a higher age for other things (like buying guns or alcohol)? That won't be allowed with your current wording.

**Comment by KacperZajc** [comment]
this is exactly why I put 'universal' bit in this provision
one age - for all rights and duties

**Comment by terrorist96** [comment]
It could drive the legislature to set the maximum age because they want to prevent gun ownership until 21 and your other rights suffer due to the inflexibility. Just playing devil's advocate.

**Comment by KacperZajc** [comment]
It's a good point. 
But I think it's really unfair to require higher age for rights and lower for duties, it should be universal IMO.
