### ISSUE TITLE
statute of limitations?

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#556]
Im wondering whether we should include some sort of 'statute of limitations' in the Constitution.
This is mainly because I think alleging sexual assault after 30 years is bollocks and I really dont want to see that. It's a political tool used to destroy people.
Any opinions?

**Comment by terrorist96** [comment]
Don't we have the 1 year limit to prosecute?

**Comment by KacperZajc** [comment]
only where a person is in detained under a warrant and the prosecution is ongoing;
here Im talking about someone waking up one day and suddenly reminding themselves that they were raped 20 years ago

**Comment by terrorist96** [comment]
I think it would be better left to each law. You can have a low statute of limitations for a petty crime, and a high one for a serious crime and the Assembly can decide that.

**Comment by terrorist96** [comment]
But we could say that for a law to be valid, it needs to include a statute of limitations without defining the limit in the constitution.

**Comment by terrorist96** [comment]
§I.7 seems like an appropriate section to add this to.

**Comment by KacperZajc** [comment]
This is what I would propose for Fair Trial Right Article:

All criminal offences shall be divided into misdemeanours and felonies, according to the harm they inflict, and each category shall attract different nature and severity of punishment;
Criminal offences of both categories shall be subject to time limitation upon reaching which prosecution shall no longer be permitted;
All misdemeanours shall be subject to time limitation of no longer than 5 years;
All felonies, other than murder, shall be subject to time limitation of no longer than 10 years;
The criminal offence of murder shall not be subject to any time limitation;
Any such time limitation shall run from the date an act or omission giving rise to the prosecution took place or came to light or, in case of a continuous action, from the date the action ceased.

But Im not convinced this isnt too detailed for the Constitution???

**Comment by terrorist96** [comment]
I think it's too detailed. Just say that for a criminal statute to be valid, it must include a time limit.

**Comment by KacperZajc** [comment]
I think it would be better to create a separate provision in Fair Trial Article:

All criminal offences shall be classified either as misdemeanours or felonies, attracting different nature and severity of punishment, and shall be enumerated in a single Criminal Code; all such offences, other than homicide, shall have expiration date upon which they shall no longer be prosecuted.

**Comment by KacperZajc** [comment]
@terrorist96 ???

**Comment by terrorist96** [comment]
> all such offences, other than ~~homicide~~ **capital offences**, shall have **an** expiration date upon which they shall no longer be **prosecutable**

**Comment by KacperZajc** [comment]
okk
