### ISSUE TITLE
hearsay evidence rules

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#557]
I think we should make some things clearer:

§XI.8. All defendants in criminal proceedings shall have the right to attend Court proceedings, to be informed of criminal charges and of his or her rights, to compel witnesses to appear in Court for examination, to examine all evidence gathered against him or her and to cross-examine all witnesses giving testimony against him or her about any issue that might be of relevance to the outcome of the proceedings and no testimony shall be admitted as evidence against any defendant which is not verbally confirmed by the author in the presence of the jury unless he or she is deceased or incapacitated.

**Comment by terrorist96** [comment]
> §XI.8. All defendants in criminal proceedings shall have the right to attend Court proceedings, to be informed of criminal charges and of his or her rights, to compel witnesses to appear in Court for examination, to examine all evidence gathered against him or her and to cross-examine all witnesses giving testimony against him or her about any issue that might be of relevance to the outcome of the proceedings**; ~~and~~** no testimony shall be admitted as evidence against any defendant which is not verbally confirmed by the author in the presence of the jury unless he or she is deceased or incapacitated.

What if the person is a mute? Can't verbally confirm anything. Overall, I think this is kinda unnecessary. We can trust the judiciary to conduct a fair trial without having to spell out everything. They can come up with their own rules as long as it doesn't violate the constitution. If hearsay if admitted into court, then that can be challenged based on fair trial rights.

**Comment by KacperZajc** [comment]
Well I thought so but apparently not.
American and British judiciary and the European Court of Human Rights all interpreted 'confront the accuser' clause to allow for example for preventing a defendant from questioning an alleged a rape victim about her past sexual conduct etc
Since we dont trust the gov with anything, we should make the courts with this.
Not sure how to go around mute persons though xd

**Comment by KacperZajc** [comment]
§XI.8. All defendants in criminal proceedings shall have the right to attend Court proceedings, to be informed of criminal charges and of his or her rights, to compel witnesses to appear in Court for examination, to examine all evidence gathered against him or her and to cross-examine all witnesses giving testimony against him or her about any issue that might be of relevance to the outcome of the proceedings; no testimony shall be admitted as evidence against any defendant which is not confirmed by the author in person in the presence of the jury unless he or she is deceased or incapacitated.

**Comment by terrorist96** [comment]
Can't have confirmation via video chat? Requiring in-person feels inefficient and barbaric. :stuck_out_tongue_closed_eyes:

**Comment by KacperZajc** [comment]
....no testimony shall be admitted as evidence against any defendant which is not confirmed by the author himself or herself before the jury unless he or she is deceased or incapacitated.

**Comment by terrorist96** [comment]
:+1:
