### ISSUE TITLE
right to assemble 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#558]
§VIII.4. All Individuals shall have the right to assemble peaceably, including in all public areas of the Free Republic of Liberland, without having to obtain any permit for this purpose, so long as they do not obstruct the functioning of the Public Administration; no law shall interfere with any voluntary relations or cooperative ventures formed by Individuals exclusively.

**Comment by terrorist96** [comment]
> §VIII.4. All Individuals shall have the right to assemble peaceably, including in all public areas of the Free Republic of Liberland, without having to obtain any permit for ~~this~~ **such** purpose, so long as ~~they do not obstruct~~ the functioning of the Public Administration **is not obstructed**; no law shall interfere with any voluntary relations or cooperative ventures formed by Individuals exclusively.

What if people are blocking the street?

**Comment by KacperZajc** [comment]
then they're crybabies :D

**Comment by terrorist96** [comment]
Well it would violate people's right to free movement. And we only allow exercising constitutional rights up to the point that it interferes with others' rights via XVII.5 so it doesn't need to be explicitly addressed.

Speaking of which.. I went back and found when the text was changed.
It went from this:
> all Rights enumerated in this Constitution shall be exercisable only where no negative rights of others are infringed by force, fraud, of threat thereof, or unbeknownst to them.

to what we have currently:
> §XVII.5. No provision of this Constitution shall be construed as to prevent the Assembly from criminalising any act or omission which does not stem from the inherent right of self-defence but amounts to any (a) physical, or constitutionally recognised form of non-physical, violence towards any Person or animal capable of conscious behaviour, or threat thereof, (b) invasion of privacy, (c) fraud, (d) direct and grave interference with enjoyment of one’s property or (e) harm to environment beyond the boundaries of one’s property.

Does the current version actually encompass the meaning of the original? It mentions property rights, but what about other constitutional rights? I think the original version is more clear in that it says you can exercise your rights only up to the point that it interferes with others' rights. I'd like to see this clarified, if possible.

**Comment by KacperZajc** [comment]
could you give me an example of any breach of constitutional rights which would not involve direct contact (i.e. violence), interference with property or invasion of privacy?

**Comment by terrorist96** [comment]
Perfect example would be your right to travel.

> §XV.3. No Individual shall be prevented from residing in any part of the Free Republic of Liberland or **moving freely throughout its territory**.

People peacefully assembling to protest, but at the same time, impede traffic and hinder others' right to travel unmolested. No violence would be involved.

**Comment by KacperZajc** [comment]
But would that not in fact amount to physical violence?
Blocking the road will ultimately include physical contact when sb tries to get through and any physical contact (even touching) in malice amount to assaults in law.
This is assuming the road was public, if it was private then obviously it was an interference with private property.

**Comment by terrorist96** [comment]
> But would that not in fact amount to physical violence?

No? Where is the violence?

> Blocking the road will ultimately include physical contact when sb tries to get through and any physical contact (even touching) in malice amounts to assault in law.

Yeah, but even prior to that, their rights have been infringed. The violence only happens if someone in their car decides to plow over the people blocking the path. But the violation of the right to travel already occurred prior to that. And many people won't want to run over others with their car.

> This is assuming the road was public, if it was private then obviously it was an interference with private property.

Yes, this would be true. Let's assume the road is public. Doesn't even have to be a road. People could assemble in the forest, and someone trying to walk by could be prevented.

**Comment by KacperZajc** [comment]
But should blocking a road be a criminal offence?
I think it could be dealt with at civil law level.
It could easily be classified as interference with business etc
And since it is 'obstructing the functioning of the Public Administration' it would not be protected by the Constitution

**Comment by terrorist96** [comment]
I'm not saying what kind of offense it should be. I'm saying it shouldn't be protected activity under freedom to assemble, because you're encroaching on others' freedom (to travel). The rest can be dealt with via legislation.

**Comment by KacperZajc** [comment]
so it's not because it falls under the 'the functioning of the Public Administration is not obstructed' exception

**Comment by terrorist96** [comment]
Why should the PA be afforded that extra protection but regular citizens not? You could make the case that some action by someone infringes the rights of someone else without the PA being affected.

**Comment by KacperZajc** [comment]
§VIII.4. All Individuals shall have the right to assemble peaceably, including in all public areas of the Free Republic of Liberland, so long as neither the movement of Persons necessary for the minimal functioning of the society, nor constitutional functions of the Public Administration, are not obstructed; no law shall interfere with any voluntary relations or cooperative ventures formed by Individuals exclusively.

???

Im trying here to catch circumstances where protesters block the roads or border crossings, not just create an inconvenience or impede the passage of one or two people through one particular street.

**Comment by KacperZajc** [comment]
@terrorist96 ???

**Comment by terrorist96** [comment]
> §VIII.4. All Individuals shall have the right to assemble peaceably, including in all public areas of the Free Republic of Liberland, providing that neither the passageway of Persons through major communication infrastructure, nor constitutional functions of the Public Administration, are obstructed.

This is better, but I think a better solution is to simply say all constitutional rights are exercisable up until you encroach or threaten to encroach on someone else's constitutional right. This would cover the above scenario plus other scenarios we may not be able to envision.

**Comment by KacperZajc** [comment]
I think what you're proposing is too vague, that is why we moved from this concept in the past
