### ISSUE TITLE
licensing 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#559]
I want to make one umbrella provision for all licencing issues rather than put that in each separate provision:

§XVII.7. All rights enumerated in this Constitution, and others retained by any Person within the jurisdiction of the Free Republic of Liberland, shall be enjoyed directly, without any requirement of permit, licence or registration.

remove:

§VIII.1: ...no law shall introduce the requirement of licensing or registration in respect of any printed materials, radio stations, television channels, Internet websites or any other medium of information exchange...

§XIV.3.: ...no form of licensing and/or registration shall be used to infringe upon these rights...

§VIII.4. (as proposed): ...without having to obtain any permit for this purpose,...

also rephrase:

§XVII.6. The enumeration of certain rights in this Constitution shall not be construed as to deny or disparage others retained any Person within the jurisdiction of the Free Republic of Liberland.

**Comment by terrorist96** [comment]
:+1:
