### ISSUE TITLE
Free movement

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#560]
Should

> §XV.3. No Individual shall be prevented from residing in any part of the Free Republic of Liberland or moving freely throughout its territory.

be moved from
`Article XV: Cross-Border Rights`

to

`Article XII: Physical Liberty Rights`
`THE RIGHT TO PHYSICAL LIBERTY AND FREE MOVEMENT SHALL BE SECURED`

?

**Comment by KacperZajc** [comment]
Possibly but there is an imbalance when it comes to the number of provisions in each Article so it might as well be in XV.3. :)

**Comment by terrorist96** [comment]
But it doesn't really deal with cross-border rights, and is more related to free movement. Your call.

**Comment by KacperZajc** [comment]
I mean by implication it does because you have to cross the border and then decide where you wanna go - here the right kicks in by allowing you to go wherever you want

I know it's far-fetched, as I said, it's there to maintain the balance :)
