### ISSUE TITLE
Issue with residents crossing the border, and more

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#561]
In Liberland, we have two classes of people: Citizens and non-citizen residents. Citizens will have paperwork indicating their citizenship. Residents may not. 
We guarantee citizens the right of entry, but not for residents, even if they have a valid "leave to remain".

I thought the benefit of being a resident was that you didn't have to be registered with the government. 

> §XVIII.4. ...the term “Citizen” shall signify any Person holding citizenship of the Free Republic of Liberland; the term “Resident” shall signify any Person within the jurisdiction of the Free Republic of Liberland who is not a Citizen

So a resident also encompasses an illegal alien. We should distinguish between **citizens**, **residents** (with a valid leave to remain), **illegal aliens** (which are residents without a leave to remain), and **tourists/travelers/students studying abroad** (which are not citizens or residents, per se, though are within the jurisdiction of Liberland), .

And furthermore, legal residents should have their right of entry guaranteed just like citizens. Else it violates equality under the law. Example: some states in the US had reserved the right to keep/bear arms to citizens only, disenfranchising legal non-citizens. Those laws have been ruled unconstitutional in several courts. We should make sure that anyone who has a right to be in Liberland is guaranteed that right.

Look at all the different statuses in the US:
https://www.irs.gov/individuals/international-taxpayers/immigration-terms-and-definitions-involving-aliens

**Comment by KacperZajc** [comment]
I think you are misconstruing the system
We guarantee the rights to Persons and Individuals with no distinction between Citizens and Non-Citizens
the only exception being cross-border issues and voting rights
so in all other cases even illegal aliens enjoy constitutional rights (e.g. fair trial etc)
