### ISSUE TITLE
Article XVII: Due Process of Law

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#562]
I want to strengthen civil rights adjudication process, sort of like the Due Process Clause in the US Constitution.
Here is what I propose:

Article XVII: Due Process Rights

THE RIGHT TO DUE PROCESS OF LAW SHALL BE SECURED

XVII.1. Whenever any dispute arises between any Person and any body of the Public Administration as to the existence or scope of any right held by such a Person vis-a-vis that body, such a dispute shall be adjudicated before the Courts of Law once the Person in question has exhausted all administrative appeal measures. (§VI.11)

XVII.2. All Executive Measures issued by the Cabinet may be subject to challenge in the Civil Court, in the absence of any Person specifically affected by them, by any association composed of no fewer than thirty Citizens; without prejudice to the appeal procedures, such challenge shall be admissible once only unless the original challenge was not genuine but brought in order to shield the defendant from liability or where a new challenge raises a different point of law. (§VI.11)

XVII.3. Any law creating any obligation vis-a-vis any Person, shall contain a precise definition of such obligation and all of its elements, a general scope of its application, available defences and the nature and minimum (if any) and maximum extent of punishment that may be imposed for its breach; all criminal offences shall be enumerated in a single Criminal Code. (§I.7.)

XVII.4. No Person shall be threatened with, or subjected to, any punishment which has not been expressly provided for by an Act of the Assembly or the Constitution, nor shall any Person be punished for any act or omission which has not been expressly forbidden by an Act of the Assembly or the Constitution. (§II.3)

XVII.5. No ex post facto law retroactively changing the legal consequences and/or status of actions that have been already committed, or relationships that already existed, before the enactment of said law shall be passed; nor shall any Person be subjected to any punishment which was not available at the time an act or omission for which the punishment is to be imposed was committed. (§II.2.)

XVII.6. All parties to any proceedings before any Court of Law shall be given a fair hearing in accordance with the rules of natural justice, based on the adversarial process with full equality of arms, before any verdict is rendered by the Court and subsequently shall be served with legal reasons behind such a verdict. (§VI.19.)

XVII.7. Access to any Court of Law shall not be impeded by any excessive formal or financial requirements; nor shall any Person be prevented from acting in his or her case before the Civil Court or Criminal Court.

**Comment by KacperZajc** [comment]
@terrorist96 ???

**Comment by terrorist96** [comment]
> XVII.1. Whenever any dispute arises between any Person and any body of the Public Administration as to the existence or scope of any right held by such a Person vis-a-vis that body, such a dispute shall be adjudicated before the Courts of Law once the Person in question has exhausted all administrative appeal measures. (§VI.11)

Old: All administrative decisions of any branch of the Public Administration, and actions undertaken by its Agents, which are capable of directly affecting any Person...

The new version seems more narrow compared to the old version. The new version only deals with the rights of a person whereas the old version isn't limited to that.

> XVII.2. All Executive Measures issued by the Cabinet may be subject to challenge in the Civil Court, in the absence of any Person specifically affected by them, by any association composed of no fewer than thirty Citizens;

I prefer the old version:
All Executive Measures issued by the Cabinet may be subject to challenge in the Civil Court by a Person affected thereby or, in the absence of such a Person, by any association composed of no fewer than thirty Citizens

It's a little longer, but reads more clearly.

> based on the adversarial process with full equality of arms

I like this.

> XVII.7. Access to any Court of Law shall not be impeded by any excessive formal or financial requirements; nor shall any Person be prevented from appearing before the Civil Court or Criminal Court in his or her own case ~~due to the lack of relevant legal qualifications~~.

I say remove the qualifier. Guarantee that right regardless. That makes me think of trial by absentia. Should we allow it or forbid it? If we remove that qualifier, trial by absentia wouldn't be disallowed.

**Comment by KacperZajc** [comment]
XVII.1. seems border IMO
and it covers a bit of old XVII.2. hence the new one has a slightly different form

XVII.7. : OK

trial in absentia is already forbidden:
§XI.8. All defendants in criminal proceedings shall have the right to attend Court proceedings...
(but online trial is allowed)

so let's rephrase to be consistent: 

XVII.7. Access to any Court of Law shall not be impeded by any excessive formal or financial requirements; nor shall any Person be prevented from acting in his or her case before the Civil Court or Criminal Court.

**Comment by terrorist96** [comment]
> XVII.1. seems border IMO
and it covers a bit of old XVII.2. hence the new one has a slightly different form

If you say so.

> trial in absentia is already forbidden:
§XI.8. All defendants in criminal proceedings shall have the right to attend Court proceedings...
(but online trial is allowed)

Nothing here forbids it. It only guarantees the right. Doesn't mean the right can't be waived. Though a waiver should be allowed, so let's leave it.

> XVII.7. Access to any Court of Law shall not be impeded by any excessive formal or financial requirements; nor shall any Person be prevented from acting in his or her case before the Civil Court or Criminal Court.

:+1:
