### ISSUE TITLE
self-defence

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#563]
rephrase:

§XIV.1. All Persons shall have the right to use reasonable force in defence against any Person, including any Agent of the Public Administration acting unlawfully or in error, or animal, posing a direct and true threat to (a) themselves, (b) their property or animals, (c) their Constitutional Rights and/or (d) any other Person; should such a threat arise on the property a Person is in charge of, he or she shall have the right to use any force deemed fit. 

add:

§XIV.7. No Person acting within their right of self-defence as prescribed in the Constitution and any law passed in accordance therewith shall be convicted of any criminal offence or have any civil lawsuit brought against him or her by the Person initiating aggression in connection with any act or omission he or she might have committed in the course of exercising such a right.

**Comment by KacperZajc** [comment]
@terrorist96 ???

**Comment by terrorist96** [comment]
Wouldn't a person's animal/pet be considered property?
Otherwise, :+1:

**Comment by KacperZajc** [comment]
yeah this is not clear hence my proposal
no harm done here
