### ISSUE TITLE
Quantity of Legislators

### ISSUE THREAD

**Issue by grantmor** [liberland/constitution#569]
Great work so far on the Constitution; there's a lot to like.

I do, however, have concerns regarding the size of the legislature. An important factor here is the representative to citizen ratio. When it's small, campaigns become more expensive requiring legislators to sell out to special interest groups in order to have any chance of winning. Also, bribery becomes more and more practical as the number of legislators you need to bribe falls.

At the same time, the more constituents a legislator represents, the less responsive they become. It's much harder to genuinely listen to 150,000 people (e.g. House of Representatives in the U.S.) than 3,000 people (e.g. New Hampshire House of Representatives). Here in New Hampshire, House races can be won with a budget as low as $500, helping to discourage purchase of politicians.

Another interesting effect of limiting the Assembly to 20 members is that Constitutional Bills only require one additional Assemblyman to pass.

Ordinary Bill: ceiling(2/3 * 20)  = 14
Constitutional Bill: ceiling(3/4 * 20) = 15

I think a more appropriate way of determining the size of the Assembly would be, for example to require at least one Assemblyman for every 5,000 (just throwing a number out there; personally I'd like to see it as low as possible) citizens, and specifying a lower limit on its size.

The founders of the U.S. operated under the assumption that republican government would break down if this ratio increased beyond 30,000. It's unfortunate that early on we had the size of the House artificially capped at 435.

Just something to think about.

**Comment by terrorist96** [comment]
From what I know, 20 is the number that Vit wants. I also found this:
https://ballotpedia.org/Population_represented_by_state_legislators#Sortable_chart
NH has the least number of people represented by each representative and CA has the most.

**Comment by michalptacnik** [comment]
7 - 21. Initial number: 7. Closing the issue.
