### ISSUE TITLE
liberland.io is dead

### ISSUE THREAD

**Issue by qm3ster** [liberland/constitution#570]
[constitution.liberland.io](//constitution.liberland.io) is down, and [liberland.io](//liberland.io) redirects to [ca.linkedin.com/in/paul-peteranac-2542301a](//ca.linkedin.com/in/paul-peteranac-2542301a)
Probably should take that link down from this repo.

**Comment by terrorist96** [comment]
#442

**Comment by qm3ster** [comment]
Are you able to change it to let's say https://liberland.org/en/constitution/ ?

**Comment by terrorist96** [comment]
I would if I had the power to do so. The main person who was in charge of this repo deleted their account about a week ago.

**Comment by igronus** [comment]
I think we need country code Top-Level Domain. For example .liberland or .lbr

**Comment by terrorist96** [comment]
It's going to be .ll

**Comment by michalptacnik** [comment]
The new top level domain is indeed ll.land. Closing the issue.
