### ISSUE TITLE
Why the Liberland don't honor the constitution law, Article III, Section III.1?

### ISSUE THREAD

**Issue by yahoo5588** [liberland/constitution#572]
https://github.com/LiberlandProblems/LiberlandProblems/wiki/Transparency-Problem

**Comment by terrorist96** [comment]
The Constitution is still a draft and hasn't been ratified since no elections have occurred yet. So there's nothing to honor yet.

**Comment by michalptacnik** [comment]
We have a new draft of the constitution here: https://docs.google.com/document/d/1J2o5N9JDOzBXRkefe9Azm6P6vAwqCxw7B2jcKoHSjhg/edit

Closing issue.
