### ISSUE TITLE
Consequence of violating the constitution

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#575]
I think we should add something that says if the legislature violates the constitution, it shall immediately and automatically be dissolved and a new election held as soon as practicable. This would actually provide for consequences and an enforcement mechanism for ignoring the constitution.

**Comment by michalptacnik** [comment]
We have a new draft of the constitution here: https://docs.google.com/document/d/1J2o5N9JDOzBXRkefe9Azm6P6vAwqCxw7B2jcKoHSjhg/edit

This is a good point, we do have a similar mechanism in the Judiciary. Anything the Legislature does will be reviewable by the Courts. If issues with the Constitution are found, the legislative work will be removed from the books in full or in part. Where the Legislature does this repeatedly, the Congress will likely be voted out during the next elections (remember: election cycle is 3 months!).

Closing issue. Please reopen if there are any more questions.
