### ISSUE TITLE
Licensing of the constitution

### ISSUE THREAD

**Issue by Matr1x-101** [liberland/Constitution#588]
What is the license of the Liberland constitution? 

Is it CC0? Is it in the public domain? Or is it copyrighted? Or is it under another license?

**Comment by michalptacnik** [comment]
It is likely, like everything else, MIT license. Meaning that you could take it and use it freely, even brand a copy and market it, if you would find buyers. It is for sure free to use, though.

**Comment by michalptacnik** [comment]
As there were no longer any replies from the author, closing this issue.
