### ISSUE TITLE
How are representatives elected?

### ISSUE THREAD

**Issue by joshmh** [liberland/constitution#6]
Details of the elections are not provided. Perhaps citizens should be allowed to vote for an ordered list of any citizens, with the results determined by [Single Transferable Vote](https://en.wikipedia.org/wiki/Single_transferable_vote).

**Comment by cpacia** [comment]
I agree here. Duverger's law has poisoned most electoral systems. To the extend voting is used it should be a transferrable vote like instant runoff voting. 

It will have much less of a tendency to coalesce into a two party system.

**Comment by rossbd** [comment]
Approval voting works too.

In some places, an ordered list allows for election gaming. If the ordering is specified, it should be randomized.

**Comment by joshmh** [comment]
In my proposal, ordering would be done by each voter. Approval voting is for single winners, whereas here we'd want to choose all assembly members.

**Comment by rossbd** [comment]
Approval voting can be used for multiple winners: top vote getters win. Same process. When discussed (in the U.S., anyway) it's nearly always in the context of a single winner, because that's how the vote was "designed" long ago.

**Comment by cpacia** [comment]
I'm less familiar with other voting schemes but I'm pretty sure there isn't any voting strategy that can rig an instant runoff election. 

IRV would work for both elections where only a single candidate wins or multiple candidates win. 

video: https://www.youtube.com/watch?v=wqblOq8BmgM

**Comment by joshmh** [comment]
Looks like IRV is a special case of STV and they are equivalent in the case of single winners. It might be worth considering district voting, with one rep for each district, although the district doesn't have to be geographical. For instance, each citizen could be issued a random number token, and a district could be the token modulo the number of districts. A candidate would run in the district of his own token. This would allow a more intimate relationship between constituent and representative.

**Comment by cpacia** [comment]
Yeah actually I like the idea of voting for all reps (or at least all reps up for elections, assuming not all terms expire at once). 

If nothing else it should probably get large exposure for different ideas as people need to learn about more than just two candidates.

**Comment by tinkyholloway** [comment]
STV would be appropriate if the Assembly is formed from constituencies. Given the size of Liberland wouldn't it be suitable to present the voter with a list of all candidates standing and have them pick one? The Assembly is then filled with the top 20 candidates with the most votes. If fewer than 20 candidates receive votes then the election is invalid.

**Comment by joshmh** [comment]
That sounds like a simple special case of STV but there are some problems with it. Voting is a [complex problem](https://en.wikipedia.org/wiki/Voting_system#Evaluating_voting_systems_using_criteria), so I propose we go with a well-studied system that isn't susceptible to the most important failures.

**Comment by rossbd** [comment]
There is no perfect voting system, mathematically. No matter what you pick, voting is liable to sum level of gaming. The outside-the-box solution is to prevent what can be voted on at all.

**Comment by joshmh** [comment]
@rossbd +1

**Comment by KacperZajc** [comment]
this was left undecided on purpose, because I would be easier to qualify the rules though ordinary laws, I didnt know what kind of electoral system we wanted, it is open to debate.
