### ISSUE TITLE
Practice of Medicine

### ISSUE THREAD

**Issue by FellowTraveler** [liberland/constitution#65]
In the U.S. it's accepted that there is a right to practice medicine but that it's subject to licensing in order to prevent incompetents from practicing.

This licensing requirement has led to medical boards who rescind medical licenses. In the case of injury to a patient, this may seem reasonable. However, patients tend to be sick or injured, and many die even in the course of proper treatment. Medicine is a highly political field, and medical boards often act improperly and to political ends, for example, in order to railroad their competition out of town.

===> Therefore I strongly recommend a provision that explicitly protects the right to practice medicine except in the case where incompetence has been proven in a court of law.

If you are amenable to this, I will create a pull request.

**Comment by KacperZajc** [comment]
this is a highly political decision we cannot make ourselves, at this point it is unclear so it cannot make its way to the constitution now, Im closing

**Comment by joshmh** [comment]
If the government can constitutionally impose medical licensing, then I don't understand this constitution, especially:

> No law shall abridge the right of persons to the control of their own bodies and property, nor interfere with voluntary consensual or contractual relations among adult persons, nor impinge on the right to form cooperative ventures of any kind, so long as no negative rights of others are infringed by force or fraud, or threat thereof, or unbeknown to them.

If I go to someone and pay them to help me with my broken finger, and the government makes a law that abridges my ability to do that, how does that not violate that section? And, more significantly, how is Liberland any different than the US?
