### ISSUE TITLE
grand jury

### ISSUE THREAD

**Issue by FellowTraveler** [liberland/constitution#66]
One way to ensure equal protection under the law, is to allow anyone to present a case to the grand jury for an indictment, not just a district attorney.

For example, imagine that a certain law is only enforced against black people, but never enforced against white people. Or only enforced against Libertarians, but never enforced against Republicans/Democrats. Etc.

One protection is to allow any private investigation of a case to present its evidence before the grand jury and ask for an indictment, without needing the permission of the district attorney.

This may require to allow the private prosecutor to fund the expenses of the case, so as not to destroy the budgetary discretion of the public prosecutor. But it would help protect against selective enforcement of laws.

If you are amenable to this idea, I can submit a pull request.

**Comment by KacperZajc** [comment]
very interesting, let me think about that

**Comment by informed-juror** [comment]
I think its a great idea! 
I seem to recall its part of English Common Law (there continue to be private prosecutions in the U.K. from time-to-time) and the basis of U.S. law but in the past hundred years or so many states (and I think Congress) have enacted laws to prevent private prosecutions or make them very difficult. There were lots of reasons given by legislators when selling this to the public (when reasons were given at all) but the obvious one, that it would threaten the elites in a very real way, were never spoken.
As for restricting the financing to purely private means I think this should only be for the investigation and presentation portions before the grand jury. Once a GJ finds sufficient reason for an indictment the private prosecution parties should have some fair access to public funds as they are doing the public's bidding.

**Comment by KacperZajc** [comment]
My idea is:

All criminal offences are at the same time civil wrongs, but not all civil wrongs are criminal offences, so-

let's guarantee a right to initiate a private prosecution in the Criminal Court before an ordinary panel of Jury to every person whose claim against other person was successful in the Civil Court and there is a corresponding criminal offence to that civil wrong.

After the proceedings in the Civil Court, the claimant can take the defendant to the Criminal Court and prosecute for the same act/omission but now as a criminal offence. The standard of proof is higher in criminal cases so not all Civil Court successes will be able to be approved as criminal convictions but it guarantees a right to give it a shot.

Obviously this will be perused only if the Public Prosecutor fails to instigate normal prosecution. In such case, the claimant (private prosecutor) will have to provide all evidence and the Jury as directed by the Judge as to the law, will give a verdict.

What do you think guys?

**Comment by FellowTraveler** [comment]
This sounds good to me.

There are still cases I wonder about. For example, let's say that a government employee is guilty of bribery, but the public prosecutor declines to press charges. Can a private investigator then present his findings to the Grand Jury for an indictment?

Notice in that example there is not necessarily an "injured party" other than John Q. Public.

**Comment by KacperZajc** [comment]
OK we should include that if the accused is the agent of the Public Administration then any citizens has a right to instigate the prosecution provided the Public Prosecutor failed to do so. ???

**Comment by FellowTraveler** [comment]
Sounds good to me. Can we explicitly say that the citizen can present the evidence to the grand jury? From there it can take the normal legal process.

**Comment by KacperZajc** [comment]
Sure.
I'll close this issue, and you could propose a pull then we will work on wording there :)

**Comment by FellowTraveler** [comment]
What if we start with this wording: *"If a claim is won in Civil Court that has a corresponding criminal offense, the claimant shall have the right to place the evidence before the grand jury in pursuit of an indictment."*

I also want citizens to be able to place evidence before the grand jury against an agent of the Public Administration, but I'm not sure how to allow this without also allowing thousands of frivolous accusations. Perhaps the citizen should have to present the evidence before a judge first. But that makes it easy for the judge to kill the case before the grand jury gets a chance to see it.

Thoughts?

**Comment by informed-juror** [comment]
FT: The Civil --> Criminal case linkage must not force the defendant to reveal, under oath, testimony that could later incriminate.

**Comment by informed-juror** [comment]
https://en.wikipedia.org/wiki/Private_prosecution, esp. https://en.wikipedia.org/wiki/Private_prosecution#England_and_Wales
The U.S. Supreme Court, I think selfishly, decided that "... a private citizen lacks a judicially cognizable interest in the prosecution or non-prosecution of another." in 
https://en.wikipedia.org/wiki/Linda_R._S._v._Richard_D.
