### ISSUE TITLE
Taxing money

### ISSUE THREAD

**Issue by FellowTraveler** [liberland/constitution#68]
In the U.S.A. you can give someone dollars for euros, and it's not a taxable event.

But if you gave dollars for Bitcoins, or dollars for Gold, or Bitcoins for Gold, then it becomes a taxable event (capital gains taxes) and you are supposed to record the value of each at the time it was bought/sold. This, of course, makes it very difficult to use Gold or Bitcoin as a form of money.

Therefore I recommend adding a specific protection against the taxation of anything that is used as a currency.

Does the Constitution already cover this? Otherwise maybe I will create a pull request. Thank you.

**Comment by KacperZajc** [comment]
it's covered, Im closing

**Comment by joshmh** [comment]
Good question. There's no income tax, according to the constitution, but does mean there's no capital gains tax? If I have to ask the question, you can be sure a government court will eventually argue that capital gains tax isn't income tax.

**Comment by KacperZajc** [comment]
I have make an amendment recently making only tax on land and sales tax possible.
This was requested by the President's team.

**Comment by joshmh** [comment]
Ok, that's actually a huge step forward if it can be maintained, and if it really rules out all other forms of taxation. Land tax and poll taxes are probably the least obtrusive taxes, but sales tax is very different. This will require massive intrusion into private affairs and a huge bureaucracy. At what point does the government feel a right to extract money from two people engaging in a voluntary contract?

**Comment by KacperZajc** [comment]
probably as a last resort, I dont know. This is what was requested.

**Comment by tinkyholloway** [comment]
@KacperZajc would it be possible to list out somewhere the constitutional areas that the 'president's team' - who don't seem to participate here - decide on unilaterally.

I'd like to know what they are. Perhaps these 'do not touch' clauses can be decorated as such in the constitution draft.

I'm concerned that without their participation in this process, the resulting document will be warped and inconsistent as it tries to accommodate clauses that have been reached through reasoned discussion here with clauses that have been set in stone outside the working group. At least identifying these will make it obvious.

Perhaps, there is another way...

I would like to consider a fork of the constitution from the head branch where people like @joshmh @cpacia @FellowTraveler @fare and others can work with fewer restrictions. Too often I have seen these people's interesting ideas get cut short. The reason given is that someone distant to the discussion disagrees with them. I'd like to see where these people's ideas can go in forming a simple and consistent document without the outside limitations.

Please, I don't mean this to sound confrontational or dismissive of your nightmare job of keeping things together, only that it would allow for some experimentation of more non standard ideas, while the President can keep refering to the Statist-friendly document in the head branch for public relations reasons as he struggles to gain international support.

**Comment by cpacia** [comment]
I would be down for creating a fork. Maybe Kacper will let us put it up as an alternate branch?
