### ISSUE TITLE
removal of drug use protection 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#69]
President just asked me to remove the provision protecting the drug use due to PR reasons.
This is not my idea and I do not agree with it.

**Comment by joshmh** [comment]
I have no problem with removing it, it's probably a good idea. If that's not covered by section II.3, then I fail to see the point of this document.

> **§II.3.** No law shall abridge the right of persons to the control of their own bodies and property, nor interfere with voluntary consensual or contractual relations among adult persons, nor impinge on the right to form cooperative ventures of any kind, so long as no negative rights of others are infringed by force or fraud, or threat thereof, or unbeknown to them.

I'd love to hear a justification for a ban on marijuana that doesn't violate II.3.

**Comment by KacperZajc** [comment]
I agree.
Plus the ban on victimless crimes.
If we were to remove those two there would be nothing left.
