### ISSUE TITLE
Common Law

### ISSUE THREAD

**Issue by FellowTraveler** [liberland/constitution#75]
The legal tradition of English common law has a principle called *Stare Decisis* wherein once a certain precedent is set, the same precedent is applied to all similar cases. If the precedent is later found to be incorrect in a specific case, and overturned (at the Appeals Court or the Supreme Court) then it also impacts all similar cases.

This is in contrast to Roman Civil law, where the judge rules according to the legislation only, without being bound by precedent. As a result, apparently identical cases might have entirely different outcomes under Roman Civil law.

There are several great benefits to the English common law tradition:

1. Since the judge is bound by precedent, the outcomes of cases are much more predictable.

2. Since the judge is bound by precedent, it becomes much more difficult for bribery and corruption to enter the judicial system.

3. Due to (1) and (2), the nation ends up with a much wealthier economy. Those nations based on English common law tend to be the richest ones. For example, the United States, Australia, the U.K., Hong Kong, Mauritius, New Zealand, Canada, etc. (Contrast those economies with nations based on Roman Civil law, such as Spain, Portugal, Italy, and Greece.)

Since in English common law the jury has the ultimate power over the application of government force, and cannot be forced to violate their conscience, the primary law of the land (the common law) is formed by the conscience of juries. If the jury believes a certain decision is wrong, then they prevent it from going into the common law and becoming a precedent.

Common law actually predates legislative bodies in the English tradition, and legislation is viewed only as modifying the existing body of common law. Legislation can even be thrown out by courts if it violates established common law. (As opposed to Roman Civil law, where the legislation itself is the primary law.) The natural rights recognized in America, for example, were established legally in the common law tradition. The U.S. Constitution does not grant these rights, but assumes that they exist and that they predate the document, and merely prohibits the government from infringing upon those rights.

This brings us to the point of the hour. The current Liberland Constitution has juries for criminal trials, but not for civil trials. Does this mean the Liberland judicial system will not adhere to *Stare Decisis* ? (This would explain why there seems to be a push to de-fang juries.) Does this mean there will not be precedents set in Liberland courts?

**I should warn you that if this is the case, it is a recipe for poverty and corruption.**

**Comment by KacperZajc** [comment]
As long as I am responsible for the legal system, there will be precedents and stare decisis :)
There is no Jury in British civil courts and it is a common law jurisdiction. 
I really dont think Jury is necessary for adjudicating civil wrongs.
This has no place in the Constitution in any event.
