### ISSUE TITLE
Policy explanation 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#76]
Let me explain what seems to be a problem here.

We have several people here with different types of libertarian ideas. There is no one form of libertarianism and what is even worse, different forms often contradict each other. Consequently, you all have ideas which often do not match.

I am sorry I often sound authoritarian but I am trying to hold this document together. On the one hand I have all your ideas which are often inconsistent, on the other, there is the President's team which is not consistent with their suggestions either. On the top of that I have my own vision of this Constitution.

Unlike you I and the President's team are concerned with the international situation. Liberland is not recognised and will not be if its constitution looks unworkable or inevitably leads to anarchy. That is why there cannot be any 'experimental' ideas, at least not at this point.

What is more, I feel personally responsible for this Constitution in a sense that if it fails to work, if this state turns out to be impossible to govern, this will be on my conscience as I am the main author.

Finally, I dont want to sound condescending but apart from political involvement, I am also legally educated (perhaps I am not the only one here?) and sometimes I just know that some of the ideas 'won't do'.

The President put it clear - there would be no major changes to the Constitution. We can meddle with the Bill of Rights, polish wording, clarify various issues, but there will be no revolution here.
Therefore there will be no major changes to the Political Institutions part of the document.

These are to be considered:
- Grand Jury idea
- Entrapment idea
- Identification paper requirement 

These are to be left alone for now:
- electoral system
- taxes

Of course you can discuss any ideas you like but please try to understand that so long as there is no international support for the recognition of Liberalnd, there can be no provisions which clearly lead to permanent internal instability.

**Comment by FellowTraveler** [comment]
> this will be on my conscience

:-)

**Comment by Zephram-C** [comment]
I only hope that in the end President's team will be consistent with their suggestions and compatible with here-iterated vision of this Constitution.

**Comment by rafaelkaufmann** [comment]
I suggest that this explanation is moved to the README. It is urgent that the reader knows the context of the document.
