### ISSUE TITLE
Occupational licensing

### ISSUE THREAD

**Issue by liberty90** [liberland/constitution#79]
http://en.m.wikipedia.org/wiki/Occupational_licensing

Should constitution directlly prohibit such laws, or maybe current version protect against them sufficiently ?

**Comment by KacperZajc** [comment]
@joshmh pointed out that this:

No law shall abridge the right of persons to the control of their own bodies and property, nor interfere with voluntary consensual or contractual relations among adult persons, nor impinge on the right to form cooperative ventures of any kind, so long as no negative rights of others are infringed by force or fraud, or threat thereof, or unbeknown to them.

protects against licensing.

**Comment by FellowTraveler** [comment]
Looks good to me.

**Comment by liberty90** [comment]
It's possible that this will be sufficient, but keep in mind that it's easier to bypass one article than two. Social democratic states guarantee their tyranny with constitutions that have hundreds of pages (look, for example, at this socialist monstrosity: http://www.sejm.gov.pl/prawo/konst/angielski/kon1.htm ) ; we surely can afford to guarantee liberty two or even three times instead of once ; )

**Comment by KacperZajc** [comment]
Id rather keep it as short as possible.
If it's covered, it's covered.
