### ISSUE TITLE
Juries on civil trials

### ISSUE THREAD

**Issue by FellowTraveler** [liberland/constitution#84]
I was thinking about how there's no jury for civil trials, and I thought of a potential problem:

Wouldn't it be possible to prejudice the judge by presenting evidence to him that would not be considered admissible in front of a jury?

If there's a jury, the judge can decide which evidence the jury will actually see, and which evidence should be considered inadmissible. But if there's no jury, then the judge will have to see potentially bad evidence, and then decide whether or not he's supposed to "disregard it" (but of course he's already seen it by then.)

**Comment by KacperZajc** [comment]
There are 3 judges, only can 1 judge the admissibility of evidence if that seems to be a problem. The other 2 would be 'untainted' by what has been seen.

Jury in civil proceedings is a waste of time and effort. It hugely slows down the process and what might be even worse, is prone to manipulation. Undoubtedly we need Jury in criminal proceedings, but civil wrongs can be efficiently adjudicated by judges themselves.

**Comment by FellowTraveler** [comment]
> There are 3 judges, only can 1 judge the admissibility of evidence if that seems to be a problem. The other 2 would be 'untainted' by what has been seen.

Doesn't this mean, if the 2 'untainted' judges disagree on the verdict, that the prejudiced judge will be the tie-breaker?

**Comment by KacperZajc** [comment]
yes
I dont think it is a problem because judges are trained to properly disregard evidence they have seen - this is only a real problem with a jury because they are 'normal' people.
So I dont think this would be an issue if all 3 saw the evidence, not to mention only 1 out of 3.

**Comment by FellowTraveler** [comment]
@KacperZajc I want you to consider this scenario outlined by Spooner:

_ it would be absurd and inconsistent to make a jury paramount to legislation in criminal suits, and subordinate to it in civil suits; because an individual, by resisting the execution of a civil judgment, founded upon an unjust law, could give rise to a criminal suit, in which the jury would be bound to hold the same law invalid. So that, if an unjust law were binding upon a jury in civil suits, a defendant, by resisting the execution of the judgment, could, in effect, convert the civil action into a criminal one, in which the jury would be paramount to the same legislation, to which, in the civil suit, they were subordinate. In other words, in the criminal suit, the jury would be obliged to justify the defendant in resisting a law, which, in the civil suit, they had said he was bound to submit to._

How can we logically address this situation without having juries in civil cases?

A further question: The reason we have a Jury in the first place is to protect our liberty/property from court orders, unless the whole people agree with the order. So if a judge, in a criminal case, cannot make orders regarding my property without a jury's consent, then how can he make orders regarding my property in a civil case without a jury's consent? It enables the court to make orders infringing upon our liberty/property without first obtaining the consent of the whole people.

This jury/civil thing is a serious issue, as Spooner points out, and so far I have not heard any good response to this very real problem.
