### ISSUE TITLE
Self-ownership and bodily integrity

### ISSUE THREAD

**Issue by mtelka** [liberland/constitution#91]
I think we should have self-ownership noted in the Constitution as a basic principle of the bodily integrity.

**Comment by KacperZajc** [comment]
what do you mean?
we have an article saying that every person has a right to do whatever he or she wants with his or her body where no rights of others are infringed

**Comment by mtelka** [comment]
You probably mean §II.7.  That is okay.  But I still think that the self-ownership and the ownership in general should be listed as general principle, not only in the Legislative Restrictions.  If this is in the Legislative Restrictions only, then, obviously no law is permitted to violate the ownership, but, OTOH, there is no strong statement that the ownership (and the self-ownership as the first natural right ever) is the basic right.  This could (potentially) lead to a situation that you could lost your ownership (of your body, or other property) not by a law (remember we do have the Legislative Restrictions), but by some other act (let say some new kind of crime, not yet known, so we cannot protect against it explicitly in the Bill of Justice).

**Comment by Jean-LouisMesic** [comment]
+1 I agree with @mtelka mtelka.

The more redundancy, the better.
