### ISSUE TITLE
The power to initiate a legislative procedure shall lie with the Cabinet only 

### ISSUE THREAD

**Issue by saintego** [liberland/constitution#95]
I have two concerns here. 
1. What if there is some important need of changing law in short time period? For example new act is wrong and there is no chance to change it for next year. Or some crisis, war or something...What about initiate a legislative procedure between State of Republic speeches, but with sunset clause till next State of Republic speech? 
2. Why there is no chance to initiate legislative procedure by the Citizens with a majority of two-thirds votes in a referendum called by no less than 10% of population. This can be useful to cancel act even after 90 days period. Maybe it can be subject of veto of assembly after that.

**Comment by Jean-LouisMesic** [comment]
Enacting laws through referendum is a surefire way to introduce totalitarian practices.

Citizens already have a veto power, as well. If they fail to veto it, then it must not have been so catastrophic that it can't wait a year.

Finally, if it truly is catastrophic, then citizens can take the law to the Supreme Court to judge constitutionality.

**Comment by saintego** [comment]
OK, maybe you are right that promoting law through referendum is not good idea, but I still think that taking down act by referendum even after 90 days is good idea. If act is Constitutional,  not obsolete and government like it, there is no way to take it down by citizens. Same like there is no chance to promote emergency law. I know it can be highway to hell with emergency law, but if it'll be temporary and with full responsibility of government, it can make sense...

**Comment by mtelka** [comment]
@Jean-LouisMesic: What is the difference between "adopt a law through referendum" and "vote first for the parliament (the process is very similar to referendum), and then adopt a law through the representatives" in terms of totalitarian practices?  Why people think that the two-lever democracy is better than the one-level democracy?  With the referendum you know what you are voting for.  With the elections you are creating a blank cheque for _any_ law...

With the current forms of democracy around the globe the people have general elections every (usually) four years, so it cannot be so bad and the parliament cannot adopt _bad_ laws, so the current form of democracy is good, and we do not need to waste our time with some new constitutions... Oh, wait, ...

Yes, there is some difference: the speed of the degradation only, but the direction is always the same.

The only way how to prevent that is to make any kind of offensive violation prohibited by the Constitution (including non-voluntary taxation, for example).

**Comment by Jean-LouisMesic** [comment]
One-level democracy allows for a few thousand socialists to immigrate and fundamentally change our nation.

Two-level democracy, when properly restricted, allows for the legislative body to have tied-hands as to what they can and cannot ever put into law.

**Comment by mtelka** [comment]
@Jean-LouisMesic: If you are able to properly restrict the legislative body to have tied-hands as to what they can and cannot ever put into law in the two-level democracy, you could use the exactly same restriction in the one-level democracy to achieve the exactly same results.

IOW, two-level democracy allows for a few thousand socialists to immigrate, vote in elections, and fundamentally change our nation via the assembly.

Why do you think that people are stupid enough to vote for socialism in the one-level democracy, but wise enough to elect good assembly that won't adopt the socialist law in the two-level democracy?

**Comment by Jean-LouisMesic** [comment]
Because the Constitution prohibits the assembly from enacting such laws. It doesn't prohibit referendums from doing so, nor could it. If a referendum passed, but was not carried by the Constitution, than the Constitution would be burned.

If an assembly vote passes, but is not carried by the Constitution, than the impact of the failure to past is blunted through the assembly rather than directly on the people. The blame is distributed much more thinly, and the degree of separation between the people and the vote also serves as a pacifier. There is much less likelihood of widespread violent response if it is the assembly that fails rather than the people.

Spoken like a true statist. ^ Regardless, I believe it is better for the assembly, cabinet, and courts to deal with legislation. We are already in the midst of adding a provision where 5 assembly members can propose bills to the cabinet to be considered for proposal to the assembly; why not instead have the people use this medium?

**Comment by Jean-LouisMesic** [comment]
Since when have you seen a piece of paper that can bind 200,000 people?

It is easier to bind a small group of people to a Constitution than a large.

**Comment by KacperZajc** [comment]
see #118
