### ISSUE TITLE
The Cabinet shall consist... 

### ISSUE THREAD

**Issue by saintego** [liberland/constitution#96]
Why is it necessary to have structure of cabinet in Constitution? Maybe it will be easier to outsource some part of administrative, some departments will be not important and some other will appear. I think it'll be better if Chancellor will be able to build structure of his team in the way he will prefer and not to have some puppet department just to fulfil Constitution

**Comment by Jean-LouisMesic** [comment]
We are structuring the cabinet in our constitution because the alternative would be structuring a U.S. style executive, and we would rather have a group of people instead of a single person as our executive branch.

Allowing the Chancellor to fill the Cabinet allows him to stack the deck in his favor, and if the Cabinet is the only was to introduce and reintroduce laws, this is a quick way to totalitarianism.

**Comment by saintego** [comment]
I think to tell what should be structure of Cabinet is not solving anything. They can have virtual departments and actual power can be held by somebody else.

**Comment by mtelka** [comment]
@Jean-LouisMesic: That's not true.  There is a bunch of European countries without the U.S. style of executive, and without the cabinet structure listed in the Constitution.

@saintego: :+1:

**Comment by KacperZajc** [comment]
the list of cabinet departments is closed so that we wont see the government expanding endlessly

**Comment by Jean-LouisMesic** [comment]
Right. We don't need a George W. Bush coming in and establishing a whole new department of the Executive branch.

**Comment by saintego** [comment]
@KacperZajc I don't think this will help. Only difference between creating new executive branch  under new department or under existing one is that if you create new department than assembly can take down head of new department. Size of government, budged, expansion is the same. Just without new department structure is bit more messy and control of government is bit smaller. Even after taking down head of department he can still control department from some another position. 
I understand the idea of controlling size of government, but I don't think it will work with this.
