### ISSUE TITLE
Supreme court checking constitutionaity

### ISSUE THREAD

**Issue by cpacia** [liberland/constitution#98]
They posted the diagram of the legislative flow on the Liberland facebook page and the more I look at it, the more the part about the Supreme Court checking constitutionality gives me great concern. Here in the United States, the Supreme Court also has that power and it almost always rules that laws are Constitutional when in fact they are not. And doing so serves to legitimize the law in the minds of the public. "Why of course it's constitutional. The supreme court ruled it as such! Surely, you don't doubt the Supreme Court". 

Professor Michael Huemer has documented the problem of using a Supreme Court as the arbiter of the Constitution. 

> Perhaps one branch of the government can be tasked with enforcing the constitution against the other branches. The courts, for example, may invalidate a law when they find it to be unconstitutional. But what mechanism induces the courts to faithfully discharge this duty? What stops them from nullifying laws that are constitutional but that they simply disagree with or putting their imprimatur on laws that are in fact unconstitutional? As always, when we hire one group of people to watch over others, the question arises, ‘Who will watch the watchers?’

> Constitutional limits have in fact been tried. How well have they worked? I focus again on the experience of the United States. Some aspects of the U.S. Constitution have been followed closely, particularly those describing institutional structures. The government is divided into executive, legislative, and judicial branches, just as the Constitution prescribes; the legislature is divided into a Senate and a House of Representatives; and so on. However, with respect to the extent of government power, constitutional restrictions are routinely and unapologetically flouted. It is worth devoting a few pages to this case study.

[Huemer proceeds to list the powers of congress as stated in the US Constitution and just a few of the enormous number of laws that are outside the scope of that power.]

> Why has the Supreme Court not struck down all these laws? Here is the official story: appearances to the contrary notwithstanding, they are all really authorized by the Constitution. A typical illustration of the logic is provided by the case of Wickard v. Filburn, decided in 1942. The Roosevelt administration had successfully sponsored a law designed to increase the price of wheat by restricting the amount of wheat that farmers could grow. Roscoe Filburn was a farmer growing wheat entirely for use in feeding livestock on his own farm. Filburn exceeded the amount allowed by the law and was fined by the Department of Agriculture. Filburn then sued in federal court to prevent the enforcement of the law against him, arguing that there was no constitutional authority for the federal government to control how much wheat he grew on his farm. The Supreme Court unanimously upheld the law, claiming that it was authorized by the third clause in Article I, section 8, which grants Congress the power ‘To regulate Commerce with foreign Nations, and among the several States, and with the Indian Tribes.’ The court reasoned that because Filburn grew wheat to feed his livestock, he would therefore buy less wheat from other farmers. If many farmers were to do this, it would significantly lower the price of wheat. This, in turn, would have an effect on commerce in wheat, some of which crosses state borders. Therefore, by fining Filburn for growing too much wheat, the federal government was simply exercising its constitutional power to regulate interstate commerce.

> It is hard to believe that any unbiased observer competent in the English language would read the phrase ‘regulate commerce [ ... ] among the several states’ in this way. Here is the unofficial but more truthful account of events: At the beginning of his presidency in the early 1930s, Franklin Delano Roosevelt’s New Deal programs were repeatedly and decisively struck down for exceeding the powers granted by the Constitution. President Roosevelt sought to circumvent these decisions by proposing the Judicial Procedures Reform Bill of 1937, which would have given him the power to appoint six new justices to the Supreme Court, bringing the total to fifteen. Had the plan gone through, Roosevelt would have selected only candidates who would support the New Deal. However, shortly after Roosevelt proposed this plan, the court switched direction and began to approve of Roosevelt’s programs (though only by a narrow margin); FDR thus abandoned his ‘court-packing’ plan. Over the next few years, several judges retired and were replaced by Roosevelt appointees anyway, with the result that by the time of the Wickard case, eight of the nine Supreme Court justices owed their tenure to Franklin Roosevelt. These judges were determined to approve of Roosevelt’s agenda, no matter what the Constitution said. They therefore invented rationalizations for reversing earlier court opinions.

> On this account, the problem lay not in any ambiguity or unclarity in the Constitution, such as might have been remedied by a more judicious choice of words at the time the document was written. There was no misunderstanding; the judges simply chose not to enforce the Constitution. The particular content of the opinion penned by Justice Jackson in the Wickard case is essentially irrelevant. It functions as a very thin veil to disguise the intentional expunction of the constitutional limits on the power of Congress – but if that veil had not been available, there would have been another one. If the commerce clause did not exist, the court would have devised another rationalization. Perhaps they would have claimed that the New Deal law fell under the fifth clause, permitting Congress ‘To coin Money, regulate the Value thereof, and of foreign Coin, and fix the Standard of Weights and Measures.’ The restriction on wheat production had an effect on wheat prices; in that sense, it affected the value of money (the lower prices are, the more valuable a given quantity of money is). So perhaps Congress was only exercising its power to regulate the value of money.

> Many today might argue that it was a good thing that the Court chose to overrule the Constitution, because the document as written was overly restrictive. Think of how many wonderful federal programs would not exist today if we had to stick to a natural reading of the words in the Constitution! But regardless of what one thinks of these programs, the American experience should give pause to any democrat who would place his faith in the power of constitutions to limit governmental power. Even if the New Deal programs were good policy, they should still, in theory, have required a constitutional amendment before they could be enacted. The fact that they did not and that so many other clearly unconstitutional laws are routinely passed without apology bears witness to the fundamental problem facing a constitutional regime. The constitution is a law, and laws require enforcement. But once we establish a supreme authority, there is no one to enforce the law against that authority.

The question is what to do about this problem? We might say, well ultimately the voters have to veto unconstitutional laws. But what's their incentive to do so? If a majority stand to gain at the expense of a minority, the majority will usually vote with the government. 

When I drafted my original constitution I took pains to ensure the Supreme Court was not considered the final arbiter of the Constitution. 

> Failure of the Judiciary to strike down an Act of Government shall not be construed to legitimize the Act nor to affirm its constitutionality or lawfulness nor to prohibit the other parties from passing judgment on its Constitutionality.

One possible way around this problem is to allow lower subdivisons of government (the Cantons in my constitution) to nullify laws that conflict with the constitutions. This concept comes directly from Thomas Jefferson (who, reportedly, is one of Vit's inspirations). The context below is that US government passed laws that imprison people for free speech (despite being a blatant violation of the constitution... again unapologetic violations of the constitution started at the very beginning.) Jefferson, writing on behalf of the State of Kentucky wrote:

> Resolved... that this commonwealth is determined, as it doubts not its co-States are, to submit to undelegated, and consequently unlimited powers in no man, or body of men on earth: that in cases of an abuse of the delegated powers, the members of the general government, being chosen by the people, a change by the people would be the constitutional remedy; **but, where powers are assumed which have not been delegated, a nullification of the act is the rightful remedy**: that every State has a natural right in cases not within the compact, (casus non fœderis) to nullify of their own authority all assumptions of power by others within their limits: that without this right, they would be under the dominion, absolute and unlimited, of whosoever might exercise this right of judgment for them.

So nullification can be a powerful check on government and a counter to a Supreme Court run amok, but we have no such lower political divisions in Liberland. So the question is. How do we deal with a Supreme Court that affirms the constitutionality of unconstitutional laws and a majority of voters which supports it?

**Comment by saintego** [comment]
Maybe we can add possibility of adding virtual  lower political division just by respecting any political group gathering more than 1% of population. They will have some set of rules that their members need to respect, some inner police to enforce rules and possibility to disrespect acts that are against Constitution. So for example  majority of population without lower political institution and then some groups like north liberland, Hindus, Muslims, communist, Allianz insurance company, pastafarians..later Vojvodina

**Comment by liberlandcitizen** [comment]
The constitutionality of any law should be evident, otherwise it shouldn't be a law.  My concern is less about having a supreme court deciding the constitutionality of laws (especially since they can be impeached by 2/3 of citizen votes) and more that a law will be stamped as constitutional with just 60% of the judges agreeing that the law is constitutional.  

Why not require 5 out of 5?  Or at least 4 out of 5?

**Comment by cpacia** [comment]
@liberlandcitizen The underlying problem is the "who watches the watchers" problem. 

I completely agree with Huemer that:

> The constitution is a law, and laws require enforcement. But once we establish a supreme authority, there is no one to enforce the law against that authority.

Which is why I'm skeptical that this type of structure can really limit government long term. 

Things like having the constitution only binding on those who literally sign and assent to it, or requiring that laws be funded voluntarily would go a long way to preventing the type of abuses of power we see in the US.

**Comment by liberlandcitizen** [comment]
@cpacia I absolutely agree with you about funding.  We must honor Vit's pledge that all taxes be voluntary, as he stated to dozens of media reporters.

**Comment by Jean-LouisMesic** [comment]
I believe constitutionality should not require a scholarly experience in Constitution semantics to determine. If the jargon of a constitution is such that you must hire nine individuals for life to interpret and regurgitate said Constitution, then you are allowing those nine men to tell you what the Constitution says. This would be just like Jim Crow enthusiasts telling illiterate African American aspirant voters that the Bible says "The White Man shall Rule over the Black Man." Surely, those nine words appear in order in the 12,143 words of the King James Bible, but certainly that is not what they mean, nor do they appear in consequence.

The common citizen should be able to read the Constitution and understand immediately their own rights, the rights of their neighbor, the rights of their burglar, the rights of their government, and, arguably most importantly, exactly what the government can under no circumstances ever do. In the common understanding of the literate of the U.S. Constitution's Framers' era, this was precisely the case. Those who could read could easily understand the legal terminology of the document. Today, mannerisms of speech and text have changed, and it has become difficult for many to even stomach a reading of the Constitution.

What is the argument against appointing an impartial Layman jury to lock away for a day in a hot, slightly fanned room, deliberating on the constitutionality of a bill? Could they not then submit their verdict and rationale to a judge or panel of Justices to determine a final sentence (yea or nay.)?

Does anyone else see any inherent problems with my way of thinking?

**Comment by cpacia** [comment]
@Jean-LouisMesic My main concern there would be situation where the jury rules it to be constitutional and that forever changes public opinion about a laws constitutionality. 

I would not be opposed to a jury in a criminal case taking the constitutionality of a law into mind when determining guilt and innocence. As opposed to the jury blindly following the orders or a judge who assure them the law is constitutional. 

I'll have to re-read that section of this constitution, but if I remember right, the last time I brought that up, it got shot down in favor of the rather despotic current policy of the judge telling the jury what the law is.

**Comment by KacperZajc** [comment]
@cpacia the citizens watch the Supreme Court so there is someone who watches the watchers, this is precisely why I introduced the power to remove the Justices of the Supreme Court in a referendum.
Plus there is a possibility of veto by citizens in respect of each bill.
So we have double or even triple safeguard. 
Please dont ask we what happens if the majority of citizens dont want their liberty anymore because in that case there is nothing what can be done at all, regardless of the Constitution. 

If it is a serious concern we can require unanimity of the Supreme Court to declare constitutionality as @liberlandcitizen suggested.

**Comment by liberlandcitizen** [comment]
Well I hope others will chime in to agree that it's a serious concern :)

Remember - as of now it only takes 60% of the Supreme Court judges to declare a law constitution.  That's barely half of them saying it's constitutional, with nearly half saying it's not!  

How about 5 out of 5?

**Comment by Jean-LouisMesic** [comment]
I agree with unanimity. If it becomes a problem, we can always vote out the dissenters and elect new judges, should the new referendum justice election idea pass.

**Comment by KacperZajc** [comment]
done
